### PR TITLE
Fix to ignore zero amount change and add error for negative amount - Closes #6027

### LINKED ISSUE #6027: Report misbehavior fails when delegate has zero balance
### Expected behavior
when reward is zero, it should not try to change the balance.

### Actual behavior
When delegate has zero balance, reportMisbehavior reward will be 0.
it will try to deduct `0` which should have no effect. However, token has the check for the min balance requirement. Therefore, the transaction will be rejected

### Steps to reproduce
1. Start 2 nodes and enable plugin in one of the plugin (add reportMisbehavior config encrypted passphrase)
2. enable plugin with api client
3. wait till misbehavior happen
4. observe the error log

### Which version(s) does this affect? (Environment, OS, etc...)
5.0-

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #6027 

### How was it solved?

- Add check for debit and credit to throw error if amount is negative
- Add check for debit and credit to ignore when amount is zero

### How was it tested?

TBD

### CODE REVIEW

**Review by nazarhussain — APPROVED** [review]

File: framework/src/modules/token/token_module.ts [hunk 1]
```diff
@@ -51,6 +51,9 @@ export class TokenModule extends BaseModule {
 			if (typeof amount !== 'bigint') {
 				throw new Error('Amount must be a bigint');
 			}
+			if (amount <= BigInt(0)) {
+				throw new Error('Amount must be a positive bigint');
```
Comment (ManuGowda) [inline framework/src/modules/token/token_module.ts:55]:
```suggestion
				throw new Error('Amount must be a positive bigint.');
```

File: framework/src/modules/token/token_module.ts [hunk 2]
```diff
@@ -68,6 +71,9 @@ export class TokenModule extends BaseModule {
...
```
Comment (ManuGowda) [inline framework/src/modules/token/token_module.ts:75]:
```suggestion
				throw new Error('Amount must be a positive bigint.');
```

File: framework/test/unit/modules/token/token_module.spec.ts [hunk 3]
```diff
@@ -103,14 +103,36 @@ describe('token module', () => {
...
+
+		it('should throw error if amount is less than zero', async () => {
+			senderAccount.token.balance = BigInt(0);
+
+			return expect(
+				tokenModule.reducers.credit(
+					{ address: senderAccount.address, amount: BigInt(-10) },
+					stateStore,
+				),
+			).rejects.toThrow('Amount must be a positive bigint');
```
Comment (ManuGowda) [inline framework/test/unit/modules/token/token_module.spec.ts:125]:
```suggestion
			).rejects.toThrow('Amount must be a positive bigint.');
```

**Review by ManuGowda — APPROVED** [review]

File: framework/test/unit/modules/token/token_module.spec.ts [hunk 4]
```diff
@@ -103,14 +103,36 @@ describe('token module', () => {
...
-		it('should throw error if account does not have sufficient balance', async () => {
+		it('should throw error if amount is zero', async () => {
 			senderAccount.token.balance = BigInt(0);
 
 			return expect(
 				tokenModule.reducers.credit(
 					{ address: senderAccount.address, amount: BigInt('0') },
 					stateStore,
 				),
+			).rejects.toThrow('Amount must be a positive bigint');
```
Comment (shuse2) [inline framework/test/unit/modules/token/token_module.spec.ts:114]:
```suggestion
			).rejects.toThrow('Amount must be a positive bigint.');
```
