### PR TITLE
Fix transaction related dependency - Closes #3614

### LINKED ISSUE #3614: Combine all the transaction related logic into one module and expose used functionality
### Expected behavior
Within transactions module, it should not have any external dependency, and only exposing the used function from other module

- init_transaction.js
- process_transaction.js
- check_transaction_against_exceptions.js
- broadcaster.js
- transaction_pool.js
- transactions.js
- process_transactions.js
- multisignatures.js

### Actual behavior
Transaction logic spread across the chain module

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?
Transaction related logic had dependency everywhere and logic was scattered.

### How did I fix it?
- Transaction pool depends on blocks
- blocks still temporally depends on transaction pool
- removed proxy `transaction.js` and move API related logic to node status (only used for node status endpoint)
- Removed dependency of blocks (_getCurrentContext) from process_transactions
- Changed process transactions to function
- Directly expose transaction pool as module
- Skipped/replaced dapp related/using tests
- Removed all callbacks in transactions and transaction pool

### How to test it?
- Run the application
- Check the changed tests carefully
- Run the tests

### Review checklist

* The PR resolves #3614  
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/chain/transactions/votes.js [hunk 1]
```diff
@@ -89,7 +93,7 @@ const updateSenderRoundInformationWithAmountForTransaction = function(
 			.map(vote => vote.slice(1));
 
 		// Votes inside the transaction should not be incase it's an exception, but the existing votes should be updated
-		if (!exceptions.roundVotes.includes(transaction.id)) {
+		if (!(exceptions.roundVotes || []).includes(transaction.id)) {
```
Comment (SargeKhan) [inline framework/src/modules/chain/transactions/votes.js]: exceptions default configuration should set empty array for roundVotes property.

File: framework/src/modules/chain/loader.js [hunk 2]
```diff
@@ -570,13 +566,16 @@ __private.getTransactionsFromNetwork = async function() {
...
-				modules.transactions.processUnconfirmedTransaction(
-					transaction,
-					false,
-					addSequenceCb
-				);
+				try {
+					await modules.transactionPool.processUnconfirmedTransaction(
+						transaction
+					);
+					setImmediate(addSequenceCb);
```
[the remark this answers is not in the document]
Comment (shuse2) [reply framework/src/modules/chain/loader.js]: I think usage of balanceSequenceAdd is wrong, and it's from 2.0- 😢

File: framework/src/modules/chain/loader.js [hunk 3]
```diff
@@ -541,9 +537,9 @@ __private.getTransactionsFromNetwork = async function() {
 
 	const transactions = result.transactions;
 	try {
-		const {
-			transactionsResponses,
-		} = modules.processTransactions.validateTransactions(transactions);
+		const { transactionsResponses } = validateTransactions(exceptions)(
```
[the remark this answers is not in the document]
Comment (shuse2) [reply framework/src/modules/chain/loader.js]: in the process of validateTransactions, it calls the exception_handler functions, and it excepts to exists.
Maybe I should change the exceptions handler to accepts undefined keys?

[the remark this answers is not in the document]
Comment (SargeKhan) [reply framework/src/modules/chain/loader.js]: i was suggesting to pass an empty object here. It makes more sense because no transaction should be considered an exception when they are loaded from network.

File: framework/src/modules/chain/chain.js [hunk 4]
```diff
@@ -319,6 +307,53 @@ module.exports = class Chain {
 		this.logger.info('Cleaned up successfully');
 	}
 
+	async _initModules() {
```
Comment (lsilvs) [inline framework/src/modules/chain/chain.js]: Can't we move all this logic to `./init_steps/init_modules`?

File: framework/src/modules/chain/submodules/blocks/chain.js [hunk 5]
```diff
@@ -28,6 +32,7 @@ let modules;
 let library;
 let self;
 const __private = {};
+const exceptions = global.exceptions;
```
[the remark this answers is not in the document]
Comment (shuse2) [reply framework/src/modules/chain/submodules/blocks/chain.js]: we are going to remove them in the block PR

File: framework/src/modules/chain/init_steps/init_logic_structs.js [hunk 6]
```diff
@@ -33,27 +23,15 @@ module.exports = async ({
 			err ? reject(err) : resolve(object);
 		});
 	});
-	const initTransactionLogic = new InitTransaction({ registeredTransactions });
 
 	const blockLogic = await new Promise((resolve, reject) => {
-		new Block(ed, schema, initTransactionLogic, (err, object) => {
+		new Block(ed, schema, (err, object) => {
```
[the remark this answers is not in the document]
Comment (shuse2) [reply framework/src/modules/chain/init_steps/init_logic_structs.js]: we are going to remove them in the block PR

File: framework/src/modules/chain/chain.js (hunk 4 above)
Comment (shuse2) [reply framework/src/modules/chain/chain.js]: we can move to the init_modules file, but it will not be dynamic anymore.
so probably it's easier to access all the required parameters here

**Comment by shuse2** [comment]
I have separated `transaction_manager` to different folder and renamed it to `interface_adapters/transaction_interface_adapter.js` after discussion with @SargeKhan

File: framework/src/modules/chain/submodules/blocks/chain.js [hunk 7]
```diff
@@ -64,11 +69,13 @@ class Chain {
 			balancesSequence,
 			logic: {
 				block,
-				initTransaction,
 			},
 			channel,
 		};
 		self = this;
+		self.modules = {
```
Comment (SargeKhan) [inline framework/src/modules/chain/submodules/blocks/chain.js]: Can we assign interfaceAdapters to a different variable name. Lest we will have `self.modules` and `module` variables which have different values.

File: framework/src/modules/chain/transport.js [hunk 8]
```diff
@@ -77,7 +77,7 @@ class Transport {
 			scope.config.nonce,
 			scope.config.broadcasts,
 			scope.config.forging.force,
-			scope.logic.transactionPool,
+			scope.modules.transactionPool,
```
Comment (SargeKhan) [inline framework/src/modules/chain/transport.js]: Why do we bind transactionPool in the onBind function this file already receives it in the constructor?

File: framework/src/modules/chain/submodules/blocks/chain.js (hunk 7 above)
Comment (shuse2) [reply framework/src/modules/chain/submodules/blocks/chain.js]: true, but this will be changed in the coming block PR

File: framework/src/modules/chain/transport.js (hunk 8 above)
Comment (shuse2) [reply framework/src/modules/chain/transport.js]: This is because I didn't want to touch the bind method (since it will be removed), and it will break the test ='(
forgers, transport and loader needs to be refactored after the block PR
