### PR TITLE
Fix merging default options on entities - Closes #4532

### LINKED ISSUE #4532: BFT: Error occurred during synchronization
### Expected behavior
- Rename table `temp block` to `temp blocks`
- During synchronization the temp blocks deletion should be handled properly
### Actual behavior
```
09:14:10.237Z DEBUG lisk-framework: Received tip of the chain from peer (module=chain, peerId=134.209.166.150:5000, blockId=923313856981135964)
09:14:10.238Z DEBUG lisk-framework: Validating detached block (module=chain, id=923313856981135964, height=16038)
09:14:10.239Z DEBUG lisk-framework: Reverting chain to the last common block with peer (module=chain, peerId=134.209.166.150:5000)
09:14:10.239Z DEBUG lisk-framework: Requesting the last common block from peer (module=chain, peerId=134.209.166.150:5000)
09:14:10.320Z DEBUG lisk-framework: Found common block (module=chain, blockId=12727341266616364462)
09:14:10.321Z DEBUG lisk-framework: Deleting blocks after common block (module=chain, blockId=12727341266616364462, height=5454)
09:14:10.322Z DEBUG lisk-framework: Deleting last block (module=chain, id=14858750031150783735, height=5455)
09:14:10.351Z ERROR lisk-framework: Error occurred during synchronization. (module=chain, err.code=23505)
    error: duplicate key value violates unique constraint "temp_block_pkey"
        at Connection.parseE (/home/lisk/lisk-3.0.0-alpha.2-1ad1c681a-e62ccfa-Linux-x86_64/node_modules/pg/lib/connection.js:554:11)
        at Connection.parseMessage (/home/lisk/lisk-3.0.0-alpha.2-1ad1c681a-e62ccfa-Linux-x86_64/node_modules/pg/lib/connection.js:379:19)
        at Socket.<anonymous> (/home/lisk/lisk-3.0.0-alpha.2-1ad1c681a-e62ccfa-Linux-x86_64/node_modules/pg/lib/connection.js:119:22)
        at Socket.emit (events.js:210:5)
        at Socket.EventEmitter.emit (domain.js:476:20)
        at addChunk (_stream_readable.js:308:12)
        at readableAddChunk (_stream_readable.js:289:11)
        at Socket.Readable.push (_stream_readable.js:223:10)
        at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
```
### Steps to reproduce
Synchrinize to network from scratch http://byzantine-seed-01.liskdev.net:6040/
### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0-alpha.2

### PR DESCRIPTION
**Pull request by limiaspasdaniel**
### What was the problem?
Default filtering options were overriding custom ones
### How did I solve it?
By changing the order in the spread operator
### Review checklist

- [ ] The PR resolves #4532 
- [ ] All new code is covered with unit tests
- [ ] Relevant integration / functional tests are added
- [ ] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [ ] Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js [hunk 1]
```diff
@@ -351,6 +355,7 @@ class BlockSynchronizationMechanism extends BaseSynchronizer {
 		await deleteBlocksAfterHeight(
 			this.processorModule,
 			this.blocks,
+			this.logger,
```
Comment (yatki) [inline framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js]: would you like to keep the logger here? I thought it was for debugging reasons?

File: framework/src/modules/chain/synchronizer/utils.js [hunk 2]
```diff
@@ -109,13 +121,15 @@ const restoreBlocksUponStartup = async (
 	storageModule,
 ) => {
 	// Get all blocks and find lowest height (next one to be applied)
-	const tempBlocks = await storageModule.entities.TempBlock.get();
-	const blockHighestHeight = tempBlocks.reduce((prev, current) =>
-		prev.height > current.height ? prev : current,
-	);
-	const blockLowestHeight = tempBlocks.reduce((prev, current) =>
-		prev.height < current.height ? prev : current,
+	const tempBlocks = await storageModule.entities.TempBlock.get(
```
Comment (yatki) [inline framework/src/modules/chain/synchronizer/utils.js]: since we are getting the tempBlocks here, can't we just pass them to `restoreBlocks` function instead of `blocksModule` to avoid executing the same query again? Could you please take a look and refactor it if it's not too big?

File: framework/src/modules/chain/components/storage/entities/round_delegates.js [hunk 3]
```diff
@@ -193,8 +193,8 @@ class RoundDelegates extends BaseEntity {
 		const mergedFilters = this.mergeFilters(filters);
 		const parsedFilters = this.parseFilters(mergedFilters);
 		const { limit, offset, sort } = {
-			...options,
 			...this.defaultOptions,
+			...options,
```
Comment (yatki) [inline framework/src/modules/chain/components/storage/entities/round_delegates.js]: ❤️ 🙇

Comment (yatki) [reply framework/src/modules/chain/components/storage/entities/round_delegates.js]: why did prettier not move these to the same line tho :D

File: framework/src/modules/chain/synchronizer/utils.js [hunk 4]
```diff
@@ -75,11 +75,23 @@ const clearBlocksTempTable = storageModule =>
 const deleteBlocksAfterHeight = async (
 	processorModule,
 	blocksModule,
+	logger,
```
Comment (shuse2) [inline framework/src/modules/chain/synchronizer/utils.js]: it seems bit weird to have logger in the function

Comment (limiaspasdaniel) [reply framework/src/modules/chain/synchronizer/utils.js]: Agreed, we can refactor this functions and move them to base synchronizer in another issue to not delay this fix

File: framework/src/modules/chain/synchronizer/utils.js (hunk 2 above)
Comment (limiaspasdaniel) [reply framework/src/modules/chain/synchronizer/utils.js]: Let's do this in another issue once we move the logic to base synchronizer, this way we keep refactors isolated and we can review them further so this issue is fixed asap

File: framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js (hunk 1 above)
Comment (limiaspasdaniel) [reply framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js]: We needed logs inside this function to trace which blocks are being deleted. I will remove the need of passing dependencies as function aarguments as soon as I move the logic to Base Synchronizer (https://github.com/LiskHQ/lisk-sdk/pull/4537#discussion_r348986838)

File: framework/src/modules/chain/synchronizer/utils.js (hunk 4 above)
Comment (limiaspasdaniel) [reply framework/src/modules/chain/synchronizer/utils.js]: Issue: #4541

**Comment by limiaspasdaniel** [comment]
@yatki #4537

File: framework/src/modules/chain/synchronizer/utils.js (hunk 2 above)
Comment (yatki) [reply framework/src/modules/chain/synchronizer/utils.js]: @limiaspasdaniel #4541

File: framework/src/modules/chain/synchronizer/utils.js (hunk 4 above)
Comment (yatki) [reply framework/src/modules/chain/synchronizer/utils.js]: @limiaspasdaniel #4541
