### PR TITLE
SDK Link command does not work on bootstrapped application - Closes #6157

### LINKED ISSUE #6157: SDK Link command does not work on bootstrapped application
### Expected behavior

The command `./bin/run sdk:link` should link local sdk repo to the bootstrapped application. 

### Actual behavior

This command is linking it to wrong directory.

### Steps to reproduce

```
cd ~/my-app
./bin/run sdk:link /dev/lisk-sdk/sdk
Linked '/dev/lisk-sdk/sdk' to '/dev/lisk-sdk/commander/node_modules/lisk-sdk'.
```

It can be verified as well from directory listing; 

```
ls -lah node_modules/lisk-*
lrwxr-xr-x  1 nazar  staff    44B Feb 11 00:50 node_modules/lisk-commander -> ../../../../.config/yarn/link/lisk-commander
lrwxr-xr-x  1 nazar  staff    44B Feb 11 00:50 node_modules/lisk-framework -> ../../../../.config/yarn/link/lisk-framework

node_modules/lisk-sdk:
```

### Which version(s) does this affect? (Environment, OS, etc...)
5.0.0

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?

This PR resolves #6157

### How was it solved?

- Fix sdk link command

### How was it tested?

- Updated unit test
- Build, Run and create app from init, run link it should show the correct linking `Linked '../lisk-sdk/sdk' to '/Users/xxx/appName/node_modules/lisk-sdk'`

### CODE REVIEW

File: commander/src/bootstrapping/commands/sdk/link.ts [hunk 1]
```diff
@@ -37,7 +37,7 @@ export class LinkCommand extends Command {
 			throw new Error(`Path '${targetSDKFolder as string}' does not exist or access denied.`);
 		}
 
-		const sdkLocalPath = join(__dirname, '../../../../', 'node_modules', 'lisk-sdk');
+		const sdkLocalPath = join(process.cwd(), 'node_modules', 'lisk-sdk');
```
Comment (shuse2) [inline commander/src/bootstrapping/commands/sdk/link.ts:40]: this only works if it is run under `myApp`, while it was working regardless of the position

**Review by nazarhussain — APPROVED** [review]

**Review by nazarhussain — APPROVED** [review]

**Review by shuse2 — APPROVED** [review]
