### PR TITLE
Incorrect cleanup for validatorsHash

### LINKED ISSUE #8387: Incorrect clean up of validators hash
### Expected behavior

- Validators hash should be present in the available blockHeaders

### Actual behavior

- Validators hash is deleted incorrectly on cleanup

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-alpha.22`

### PR DESCRIPTION
**Pull request by ishantiw**
### What was the problem?

This PR resolves #8387 

### How was it solved?

- Incorrect cleanup for validatorsHash
- Incorrect cleanup for aggregateCommit
- Assign old certificateThreshold instead of zero when certificateThreshold is unchanged as compared to last Certificate

### How was it tested?

Run interops setup and run two sidechains along with mainchain nodes and observe CCUs

### CODE REVIEW

File: framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts [hunk 1]
```diff
@@ -628,10 +622,18 @@ export class ChainConnectorPlugin extends BasePlugin<ChainConnectorPluginConfig>
...
 
-		const newBlockHeader = chain.BlockHeader.fromJSON(receivedBlock).toObject();
+		const deletedBlockHeader = chain.BlockHeader.fromJSON(receivedBlock).toObject();
+
+		// Delete ccmEvents for the height of blockHeader
+		const crossChainMessages = await this._chainConnectorStore.getCrossChainMessages();
+		const indexForCCMEvents = crossChainMessages.findIndex(
+			ccm => ccm.height >= deletedBlockHeader.height,
+		);
+		crossChainMessages.splice(indexForCCMEvents, 1);
```
Comment (shuse2) [inline framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:632]: if we have multiple ccm at the same height, some of the ccm wont get removed? maybe `filter` would be better in this case

File: framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts [hunk 2]
```diff
@@ -640,21 +642,35 @@ export class ChainConnectorPlugin extends BasePlugin<ChainConnectorPluginConfig>
...
+		for (const validatorHash of activeValidatorsHashes) {
+			const doesValidatorsHashExist = blockHeaders.some(b =>
+				validatorHash.equals(b.validatorsHash),
+			);
+			if (!doesValidatorsHashExist) {
+				const indexOfValidatorHash = validatorsHashPreimage.findIndex(vHash =>
+					vHash.validatorsHash.equals(validatorHash),
+				);
+				validatorsHashPreimage.splice(indexOfValidatorHash, 1);
+			}
```
Comment (shuse2) [inline framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:670]: creating validatorsHash map from `blockHeaders` and filtering if it doesn't exist might be more simpler here.
ex)
```
const validatorsHashMap = blockHeaders.reduce((prev, curr) => prev[curr.validatorsHash.toString('hex')], {});
const updatedValidatorsHashPreimages = validatorsHashPreimage.filter(vhp => validatorsHashMap[vhp.validatorsHash.toString('hex')]);
if (updatedValidatorsHashPreimages.length !== validatorsHashPreimage.length) {
  await this._chainConnectorStore.setValidatorsHashPreimage(updatedValidatorsHashPreimages);
}

File: framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts [hunk 3]
```diff
@@ -684,12 +701,20 @@ export class ChainConnectorPlugin extends BasePlugin<ChainConnectorPluginConfig>
 		// Delete validatorsHashPreimage
 		const validatorsHashPreimage = await this._chainConnectorStore.getValidatorsHashPreimage();
 
-		await this._chainConnectorStore.setValidatorsHashPreimage(
-			validatorsHashPreimage.filter(
-				validatorsData =>
-					validatorsData.certificateThreshold >= BigInt(this._lastCertificate.height),
-			),
-		);
+		const activeValidatorsHashes = validatorsHashPreimage.map(b => b.validatorsHash);
```
Comment (shuse2) [inline framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:704]: same as above

File: framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts [hunk 4]
```diff
@@ -669,9 +685,10 @@ export class ChainConnectorPlugin extends BasePlugin<ChainConnectorPluginConfig>
 		// Delete blockHeaders
 		const blockHeaders = await this._chainConnectorStore.getBlockHeaders();
 
-		await this._chainConnectorStore.setBlockHeaders(
-			blockHeaders.filter(blockHeader => blockHeader.height >= this._lastCertificate.height),
+		const updatedBlockHeaders = blockHeaders.filter(
+			blockHeader => blockHeader.height >= this._lastCertificate.height,
```
Comment (ricott1) [inline framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:689]: why can't we filter with strict inequality `blockHeader.height > this._lastCertificate.height`?

File: framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts (hunk 1 above)
Comment (ricott1) [inline framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:632]: A clarification: here we are removing one element at index `indexForCCMEvents`? Why not all elements from that index on?

**Review by ricott1 — COMMENTED** [review]
A couple points I'd like to clarify

File: framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts (hunk 4 above)
Comment (ishantiw) [reply framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:689]: we need blockHeader at last certificate height for certificate generation

**Review by ricott1 — APPROVED** [review]

File: framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts (hunk 1 above)
Comment (ishantiw) [reply framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:632]: we want to delete only the element which was corresponding to the deleted block height

**Review by shuse2 — APPROVED** [review]

**Review by shuse2 — APPROVED** [review]

**Review by ricott1 — APPROVED** [review]
