### PR TITLE
Fix genesis account sorting - Closes #5768

### LINKED ISSUE #5768: chain library should sort the genesis account considering the length
### Expected behavior
While checking the order of the account, accounts which has shorter address should come in front

### Actual behavior
Currently the genesis block account is validated for order regardless of the account length

### Steps to reproduce
Add uninitialized account in genesis block account and validate

### Which version(s) does this affect? (Environment, OS, etc...)
5.0-

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #5768 

### How was it solved?

Sort with address length also when validating the genesis block account order

### How was it tested?

- Add unit test

### CODE REVIEW

File: elements/lisk-chain/src/validate.ts [hunk 1]
```diff
@@ -186,10 +186,20 @@ export const validateGenesisBlockHeader = (block: GenesisBlock, accountSchema: S
...
+		if (a.length < b.length) {
+			return -1;
+		}
+		return a.compare(b);
+	});
+
+	if (!objects.bufferArrayEqual(accountAddresses, copiedAddresses)) {
 		errors.push({
-			message: 'should be lexicographically ordered',
+			message: 'should be length and lexicographically ordered',
```
Comment (ManuGowda) [inline elements/lisk-chain/src/validate.ts:202]:
```suggestion
			message: 'should be ordered lexicographically and by length',
```

**Review by ManuGowda — APPROVED** [review]

File: elements/lisk-chain/src/validate.ts (hunk 1 above)
Comment (shuse2) [reply elements/lisk-chain/src/validate.ts:202]: I put length first because length takes priority

Comment (nazarhussain) [reply elements/lisk-chain/src/validate.ts:202]: Then it should be 

> should be ordered by length and lexicographically

**Review by nazarhussain — APPROVED** [review]
