### PR TITLE
CCU creation fails sometimes when the node fails to save data on start of node

### LINKED ISSUE #8288: CCU fails when node syncs from another node
### Expected behavior

- A node which is running Chain Connector plugin should be able to sync blocks from another node and at the same time save crucial information for CCU creation and creates/submits a valid CCU 

### Actual behavior

- When a node with Chain Connector plugin syncs with another node and when it tries to create a CCU, it fails to find certain information like BlockHeader or Validators Data. 

### Steps to reproduce

`Sync a node with Chain Connector plugin with another node in the network and observe CCU creation`

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-alpha.16`

### LINKED ISSUE #8316: verifyCertificateSignature is taking certificateThreshold from params instead of state
### Expected behavior

`verifyCertificateSignature` should take `certificateThreshold` from state

### Actual behavior

`verifyCertificateSignature` is taking `certificateThreshold` from transaction `params` instead of state

### Steps to reproduce

N/A

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-alpha.16`

### PR DESCRIPTION
**Pull request by ishantiw**
### What was the problem?

This PR resolves #8288 

### How was it solved?

- [♻️ Remove receivingChainAPIClient initialization from load](https://github.com/LiskHQ/lisk-sdk/commit/f22690107d7c5c4b1951d4678a9dd17a6d87379b)
- [♻️ Manage CCU save limit](https://github.com/LiskHQ/lisk-sdk/commit/8a80413f148702bcc34cfebb3ed6d68c09bbaf76)
- [🐛 Use certificateThreshold from state instead of params](https://github.com/LiskHQ/lisk-sdk/pull/8315/commits/491ed324ad7a33f65cbf569a66a59de9714c49fe) - Closes #8316

### How was it tested?

Run interop examples with Chain connector plugin and see if they are able to successfully send the CCU transaction to each other

### CODE REVIEW

**Review by ricott1 — APPROVED** [review]
This looks good.

File: framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts [hunk 1]
```diff
@@ -682,6 +680,16 @@ export class ChainConnectorPlugin extends BasePlugin<ChainConnectorPluginConfig>
 					validatorsData.certificateThreshold >= BigInt(this._lastCertificate.height),
 			),
 		);
+		// Delete CCUs
+		// When given -1 then there is no limit
+		if (this._ccuSaveLimit !== -1) {
```
Comment (Phanco) [inline framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:685]: Just curious, if `minimum` of `ccuSaveLimit` is set to 0, is it possible to be -1?

Comment (Phanco) [reply framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:685]: I think it is safe to use `0` as no-limit? Since there should be at least 1 ccu to be saved?

**Comment by Phanco** [comment]
Apart from the comment stated above, other parts are okay :D

File: framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts (hunk 1 above)
Comment (ishantiw) [reply framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:685]: good point, minimum should be -1

Comment (ishantiw) [reply framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:685]: if someone doesn't want to save any CCU then there will be no option if we use `0` as no limit

**Review by mitsuaki-u — APPROVED** [review]

File: framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts (hunk 1 above)
Comment (ishantiw) [reply framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:685]: I think this option is similar to how many events we store, so somewhere it is consistent with that

File: framework-plugins/lisk-framework-chain-connector-plugin/src/schemas.ts [hunk 2]
```diff
@@ -57,6 +62,11 @@ export const configSchema = {
 			minimum: 1,
 			maximum: CCU_TOTAL_CCM_SIZE,
 		},
+		ccuSaveLimit: {
+			type: 'integer',
+			description: 'Number of CCUs to save.',
```
[the remark this answers is not in the document]
Comment (ishantiw) [reply framework-plugins/lisk-framework-chain-connector-plugin/src/schemas.ts:67]: Lets do that in the coming PRs around Chain connector plugin
