### PR TITLE
CCM validation fails due incorrect params

### LINKED ISSUE #8660: CCM validation fails on apply
### Expected behavior

In apply function, the ccm params should validated against the decoded params.

### Actual behavior

Currently in apply function, the ccm params are validated against the encoded params.

### Steps to reproduce

Send any cross chain message and it will fail on the receiving chain where its executed.

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-beta.3`

### PR DESCRIPTION
**Pull request by ishantiw**
### What was the problem?

This PR resolves #8660

### How was it solved?

- Remove the CCM validation which was using encodedParams instead of decoded

### How was it tested?

- `npm t`
- Manual testing: Run a mainchain and a sidechain using interop examples and observe if the registration CCM is executed when we register chains and start sending CCUs through chain connector plugin

### CODE REVIEW

File: examples/interop/pos-mainchain-fast/src/commands/start.ts [hunk 1]
```diff
@@ -134,7 +134,7 @@ export class StartCommand extends BaseStartCommand {
 			app.registerPlugin(new DashboardPlugin(), { loadAsChildProcess: true });
 		}
 		if (flags['enable-chain-connector-plugin']) {
-			app.registerPlugin(new ChainConnectorPlugin(), { loadAsChildProcess: true });
+			app.registerPlugin(new ChainConnectorPlugin(), { loadAsChildProcess: false });
```
Comment (shuse2) [inline examples/interop/pos-mainchain-fast/src/commands/start.ts:137]: why loading it in memory?

**Review by shuse2 — APPROVED** [review]

File: examples/interop/pos-mainchain-fast/src/commands/start.ts (hunk 1 above)
Comment (ishantiw) [reply examples/interop/pos-mainchain-fast/src/commands/start.ts:137]: ah i did that due to this issue https://github.com/LiskHQ/lisk-sdk/issues/8629 locally but maybe we can leave it inMemory here and later we can change it if we want when the issue is fixed

**Review by mitsuaki-u — APPROVED** [review]
