### PR TITLE
P2P avoid fixedPeer eviction - Closes #4581

### LINKED ISSUE #4581: fixedPeers still being evicted
### Expected behavior
Expect `fixedPeers` to not be evicted

### Actual behavior
It does

### Steps to reproduce
- Create a 2 node network and add each one in the `fixedPeers` network config.
- Start both nodes.
- Wait until one of the connection is closed with the message:
```
EVENT_CLOSE_INBOUND: Close inbound peer connection (module=network, ipAddress=104.248.90.241, wsPort=8001, code=4418, reason="Evicted outbound peer 167.71.12.55:8001")
```
### Which version(s) does this affect? (Environment, OS, etc...)
`3.0.0-alpha.2`

### PR DESCRIPTION
**Pull request by valamidev**
### What was the problem?
- After restarting a Node PeerKind `fixedPeers` could be overwritten from perviousPeers to PeerKind `None`.

### How did I solve it?
- Change the loading order in `P2P._initializePeerBook()`

### How to manually test it?
- `npm run test:unit`

### Review checklist

- [x] The PR resolves #4581
- [x] All new code is covered with unit tests
- [x] Relevant integration / functional tests are added
- [x] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [x] Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-p2p/test/unit/p2p.ts [hunk 1]
```diff
@@ -50,6 +57,18 @@ describe('p2p', () => {
 				.and.be.instanceof(P2P);
 		});
 
+		it('should load PeerBook with correct fixedPeer hierarchy', async () => {
+			const expectedFixedPeers = generatedPeers
+				.slice(0, 6)
+				.map(peer => `${peer.ipAddress}:${peer.wsPort}`);
```
Comment (diego-G) [inline elements/lisk-p2p/test/unit/p2p.ts]: Use `constructPeerId` method.
