### PR TITLE
Provide default application parameters - Closes #3660

### LINKED ISSUE #3660: Provide default application parameters
### Expected behavior
In the config, the following parameters should have the default values, so that the sample app starts without the need of specifying them.
```
app.label
app.version
app.minVersion
app.protocolVersion
```

### Actual behavior
There is a need for specifying the mentioned parameters.
### Steps to reproduce
Run the sample application described in README.md
### Which version(s) does this affect? (Environment, OS, etc...)
`2.1.0`

### PR DESCRIPTION
**Pull request by MaciejBaj**
### What was the problem?
A need for specifying the label and versions parameters while running an Alpha SDK application doesn't follow the documented example.

### How did I fix it?
There are defaults for application parameters. 

Also, the schema validation errors were not shown, so I populated them in the error's message.
### Review checklist

* The PR resolves #3660 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/src/controller/schema/application_config_schema.js [hunk 1]
```diff
@@ -206,6 +206,10 @@ module.exports = {
 	additionalProperties: false,
 	default: {
 		app: {
+			label: 'alpha-sdk-app',
+			version: '0.0.0',
+			minVersion: '0.0.0',
+			protocolVersion: '0.0',
```
Comment (nazarhussain) [inline framework/src/controller/schema/application_config_schema.js]: It should be the protocol version which SDK development branch is implementing.

Comment (nazarhussain) [inline framework/src/controller/schema/application_config_schema.js]:
```suggestion
			protocolVersion: '1.5',
```

File: framework/src/errors.js [hunk 2]
```diff
@@ -37,6 +37,7 @@ class SchemaValidationError extends FrameworkError {
 	 */
 	constructor(errors) {
 		super('Schema validation error');
+		this.message = JSON.stringify(errors, null, 2);
```
Comment (shuse2) [inline framework/src/errors.js]: This is overwriting the `super('Schema validation error');`
