### PR TITLE
Reorganise p2p library - Closes #3678

### LINKED ISSUE #3678: Reorganise P2P library folders and files
### Expected behavior

- [x] Use `index.ts` as the top-level export.
- [x] Add `event.ts` file and put all event string constants inside.
- [x] Rename `errors.ts` to `exceptions.ts` for clarity (to make the distinction between errors and exceptions).
- [x] Create `constants.ts`
- [x] Create utils folder for pure functions that shared between the classes
- [x] Move all the different share utils to the new folder and rename them appropriately
- [x] Create `utils/index.ts` as the top-level export

Moving files around while they are being worked on can create complex conflicts in the code so these changes should be made at once. The time to introduce this change should be chosen carefully to reduce the possibility of conflicts (e.g. start of a sprint).

### Actual behavior

All source files for the P2P library are currently in the main `src` directory.
As we will likely be adding more files, it is time to organize those files into logical directories and improve naming where possible.
Also, all the integration tests are currently in a single file.

### PR DESCRIPTION
**Pull request by diego-G**
### Review checklist

- [x] The PR resolves #3678
- [x] All new code is covered with unit tests
- [x] Relevant integration / functional tests are added
- [x] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [x] Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-p2p/src/index.ts [hunk 1]
```diff
@@ -12,6 +12,9 @@
  * Removal or modification of this copyright notice is prohibited.
  *
  */
-export * from './disconnect_status_codes';
-export * from './errors';
+export * from './constants';
+export * from './exceptions';
```
Comment (shuse2) [inline elements/lisk-p2p/src/index.ts]: do we need to export these for external users?

File: elements/lisk-p2p/src/p2p.ts [hunk 2]
```diff
@@ -663,7 +617,10 @@ export class P2P extends EventEmitter {
 					return;
 				}
 
-				const wsPort: number = parseInt(queryObject.wsPort, BASE_10_RADIX);
+				const wsPort: number = parseInt(
+					queryObject.wsPort,
+					DEFAULT_BASE_10_RADIX,
```
Comment (shuse2) [inline elements/lisk-p2p/src/p2p.ts]: not sure about changing the name to DEFAULT_BASE_10_RADIX because there is only base 10 radix

File: elements/lisk-p2p/src/index.ts (hunk 1 above)
Comment (diego-G) [reply elements/lisk-p2p/src/index.ts]: Not for now I guess. @jondubois?

File: elements/lisk-p2p/src/peer/base.ts [hunk 3]
```diff
@@ -30,16 +51,26 @@ import {
...
 	validatePeersInfoList,
 	validateProtocolMessage,
 	validateRPCRequest,
-} from '../validation';
+} from '../utils';
+
+type SCClientSocket = socketClusterClient.SCClientSocket;
+
+// Can be used to convert a rate which is based on the rateCalculationInterval into a per-second rate.
+const RATE_NORMALIZATION_FACTOR = 1000;
```
Comment (mitsujutsu) [inline elements/lisk-p2p/src/peer/base.ts]: should this also be in `constants`?

File: elements/lisk-p2p/src/utils/index.ts [hunk 4]
```diff
@@ -0,0 +1,18 @@
...
+ *
+ * Unless otherwise agreed in a custom licensing agreement with the Lisk Foundation,
+ * no part of this software, including this file, may be copied, modified,
+ * propagated, or distributed except according to the terms contained in the
+ * LICENSE file.
+ *
+ * Removal or modification of this copyright notice is prohibited.
+ *
+ */
+export * from './miscellaneous';
```
Comment (mitsujutsu) [inline elements/lisk-p2p/src/utils/index.ts]: if you look at this file, it is all related to IP address related functionality and not really miscellaneous. perhaps we can name it `net` or something of the sort

File: elements/lisk-p2p/src/utils/miscellaneous.ts [hunk 5]
```diff
@@ -14,26 +14,21 @@
...
 import { hash } from '@liskhq/lisk-cryptography';
 import { isIPv4 } from 'net';
-import { P2PPeerInfo } from './p2p_types';
+import { P2PDiscoveredPeerInfo, P2PPeerInfo } from '../p2p_types';
 
 const SECRET_BUFFER_LENGTH = 4;
 const NETWORK_BUFFER_LENGTH = 1;
-const PREFIX_BUFFER_LENGTH = 1;
 const BYTES_4 = 4;
+const PREFIX_BUFFER_LENGTH = 1;
```
Comment (mitsujutsu) [inline elements/lisk-p2p/src/utils/miscellaneous.ts]: why move this one?

File: elements/lisk-p2p/src/peer/base.ts (hunk 3 above)
Comment (diego-G) [reply elements/lisk-p2p/src/peer/base.ts]: I've kept some local constants in their files depending on the scope. For example this one wasn't being exported, so for now we should keep it in its enclosed scope. Do you foresee any use in another scope?

File: elements/lisk-p2p/src/utils/index.ts (hunk 4 above)
Comment (diego-G) [reply elements/lisk-p2p/src/utils/index.ts]: There is also `getNetwork` , `getBucket`, `getByteSize`... I thought `miscellaneous` can englobe any case.

File: elements/lisk-p2p/src/utils/miscellaneous.ts (hunk 5 above)
Comment (diego-G) [reply elements/lisk-p2p/src/utils/miscellaneous.ts]: Move from where? It is related to `getIPBytes()`.

File: elements/lisk-p2p/src/utils/index.ts (hunk 4 above)
Comment (mitsujutsu) [reply elements/lisk-p2p/src/utils/index.ts]: all of those you mentioned are related to or only used in the other ip address related functions.

File: elements/lisk-p2p/src/utils/miscellaneous.ts (hunk 5 above)
Comment (mitsujutsu) [reply elements/lisk-p2p/src/utils/miscellaneous.ts]: from before BYTES_4 to after it. `LENGTH` ones group together and `BYTES` ones group together.

File: elements/lisk-p2p/src/utils/index.ts (hunk 4 above)
Comment (diego-G) [reply elements/lisk-p2p/src/utils/index.ts]: We don't `network` anything in those methods. What we do is more `get`, `compute` or `calculate`. Therefore, I prefer to keep `misc` since I don't find a proper verb to follow the pattern.

Comment (ishantiw) [reply elements/lisk-p2p/src/utils/index.ts]: Can we use `helpers` maybe?

Comment (diego-G) [reply elements/lisk-p2p/src/utils/index.ts]: It looks a bit redundant `utils/helpers.ts`.

File: elements/lisk-p2p/src/index.ts (hunk 1 above)
Comment (shuse2) [reply elements/lisk-p2p/src/index.ts]: Please check what exactly we were exposing and let's minimize the exporting value.
After being 1.0, removing the exported function/value will be breaking change and we want to avoid that

File: elements/lisk-p2p/src/exceptions.ts [hunk 6]
```diff
@@ -13,8 +13,7 @@
  *
  */
 /* tslint:disable: max-classes-per-file */
-
-export class PeerInboundHandshakeError extends Error {
+export class PeerInboundHandshakeException extends Error {
```
[the remark this answers is not in the document]
Comment (diego-G) [reply elements/lisk-p2p/src/exceptions.ts]: We didn't have a strong opinion on this. I'll revert back to the previous state.
