### PR TITLE
Fix Dropdown selection and JSON validation for dashboard - Closes #6423

### LINKED ISSUE #6423: Transaction type changes to the first transaction type in the dropdown list on adding any text to asset field
### Expected behavior

When we select a certain transaction type on send transaction widget from the drop down and then add asset in the asset text area, on submit the transaction type should be the same as selected.

### Actual behavior

Transaction type changes to the first transaction type in the drop down on adding some text to asset text area

### Steps to reproduce

Start dashboard plugin and try sending transaction using post transaction widget.

### Which version(s) does this affect? (Environment, OS, etc...)

`5.1.0`

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #6423

### How was it solved?

- Fix the usage of `useEffect`
- Add `disabled` for button
- Add json validation and call `disabled`

### How was it tested?

- Add invalid JSON and check if button is disabled
- Try to send different transactions and see they can be sent

### CODE REVIEW

**Review by Incede — APPROVED** [review]

File: framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/widgets/CallActionWidget.tsx [hunk 1]
```diff
@@ -29,24 +29,17 @@ const CallActionWidget: React.FC<WidgetProps> = props => {
 	const actions = props.actions.map(action => ({ label: action, value: action })).flat();
 	const [selectedAction, setSelectedAction] = React.useState<SelectInputOptionType>();
 	const [keyValue, setKeyValue] = React.useState('{}');
+	const [valueValid, setValidValid] = React.useState(true);
```
Comment (Incede) [inline framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/widgets/CallActionWidget.tsx:32]:
```suggestion
	const [validValue, setValidValue] = React.useState(true);
```

File: framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/widgets/CallActionWidget.tsx [hunk 2]
```diff
@@ -71,12 +64,20 @@ const CallActionWidget: React.FC<WidgetProps> = props => {
 						placeholder={'Params'}
 						size={'l'}
 						value={keyValue}
-						onChange={val => setKeyValue(val)}
+						onChange={val => {
+							try {
+								JSON.parse(val ?? '');
+								setValidValid(true);
+							} catch (error) {
+								setValidValid(false);
```
Comment (Incede) [inline framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/widgets/CallActionWidget.tsx:72]:
```suggestion
								setValidValue(true);
							} catch (error) {
								setValidValue(false);
```

File: framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/widgets/CallActionWidget.tsx [hunk 3]
```diff
@@ -71,12 +64,20 @@ const CallActionWidget: React.FC<WidgetProps> = props => {
...
+							}
+							setKeyValue(val);
+						}}
 					></TextAreaInput>
 				</Box>
 
 				<Box textAlign={'center'}>
-					<Button size={'m'} onClick={handleSubmit}>
+					<Button size={'m'} onClick={handleSubmit} disabled={!valueValid}>
```
Comment (Incede) [inline framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/widgets/CallActionWidget.tsx:80]:
```suggestion
					<Button size={'m'} onClick={handleSubmit} disabled={!validValue}>
```

**Review by Incede — CHANGES_REQUESTED** [review]

**Review by Incede — APPROVED** [review]

**Review by ishantiw — APPROVED** [review]
