### PR TITLE
Sequence should not be used in Loader - Closes #3977

### LINKED ISSUE #3977: Sequence should not be used in Loader
### Expected behavior

sequence is a property of loader

### Actual behavior

sequence is not a property of loader causing an error on startup

```[2019-07-17T15:03:36.259Z] ERROR: lisk-framework/69100 on Pablos-MacBook-Pro.local (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/loader.js:99 in async.retry.err):
    Unconfirmed transactions loader Error: [object Object]
        at /Users/pablo/Documents/LISK/Repos/lisk-sdk/node_modules/async/dist/async.js:205:62
        at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-07-17T15:03:36.259Z]  INFO: lisk-framework/69100 on Pablos-MacBook-Pro.local (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/loader.js:178 in _getSignaturesFromNetwork): Loading signatures from the network
[2019-07-17T15:03:36.260Z] DEBUG: lisk-framework/69100 on Pablos-MacBook-Pro.local (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/rounds/delegates.js:230 in updateDelegateListCache): Updating delegate list cache for round 1
[2019-07-17T15:03:36.262Z]  INFO: lisk-framework/69100 on Pablos-MacBook-Pro.local (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/loader.js:178 in _getSignaturesFromNetwork): Loading signatures from the network
[2019-07-17T15:03:36.264Z]  INFO: lisk-framework/69100 on Pablos-MacBook-Pro.local (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/loader.js:178 in _getSignaturesFromNetwork): Loading signatures from the network
[2019-07-17T15:03:36.264Z] DEBUG: lisk-framework/69100 on Pablos-MacBook-Pro.local (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/rounds/rounds.js:208 in Tick): Performing forward tick
[2019-07-17T15:03:36.268Z]  INFO: lisk-framework/69100 on Pablos-MacBook-Pro.local (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/loader.js:178 in _getSignaturesFromNetwork): Loading signatures from the network
[2019-07-17T15:03:36.269Z]  INFO: lisk-framework/69100 on Pablos-MacBook-Pro.local (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/loader.js:178 in _getSignaturesFromNetwork): Loading signatures from the network
[2019-07-17T15:03:36.270Z] ERROR: lisk-framework/69100 on Pablos-MacBook-Pro.local (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/loader.js:111 in async.retry.err):
    Signatures loader TypeError: Cannot read property 'add' of undefined
        at Loader._getSignaturesFromNetwork (/Users/pablo/Documents/LISK/Repos/lisk-sdk/framework/src/modules/chain/loader.js:192:23)
        at process._tickCallback (internal/process/next_tick.js:68:7)```

### Steps to reproduce

### Which version(s) does this affect? (Environment, OS, etc...)

2.2.*

### PR DESCRIPTION
**Pull request by pablitovicente**
### What was the problem?

Sequence was removed in 2.2.* but one call was still present in Loader

### How did I fix it?

By removing the call to sequence.add() from Loader

### How to test it?

Build should be green

### Review checklist

* The PR resolves #3977
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/chain/loader.js [hunk 1]
```diff
@@ -189,22 +189,20 @@ class Loader {
...
+			const signaturePacket = signatures[i];
+			const subSignatureCount = signaturePacket.signatures.length;
+			for (let j = 0; j < subSignatureCount; j++) {
+				const signature = signaturePacket.signatures[j];
+
+				// eslint-disable-next-line no-await-in-loop
+				await this.transactionPoolModule.getTransactionAndProcessSignature({
+					signature,
+					transactionId: signature.transactionId,
+				});
```
Comment (limiaspasdaniel) [inline framework/src/modules/chain/loader.js]: Will using `await Promise.all` instead, improve in performance?

Comment (pablitovicente) [reply framework/src/modules/chain/loader.js]: @limiaspasdaniel I only fixed the bug for this issue. Please create an issue for the investigation about your comment.
