### PR TITLE
Uncaught TypeError in checkProtocolVersionCompatibility P2P validation method - Closes #3923

### LINKED ISSUE #3923: Uncaught TypeError in checkProtocolVersionCompatibility P2P validation method
# Actual behavior

```
  1) Integration tests for P2P library
       Partially connected network which becomes fully connected: All nodes launch at the same time. The seedPeers list of each node contains the next node in the sequence. Discovery interval runs multiple times.
         P2P.send
           P2P.send when peers are at different heights
             should send messages to peers within the network with updated heights; should reach multiple peers with even distribution:
     Uncaught TypeError: Cannot read property 'split' of undefined
      at Object.exports.checkProtocolVersionCompatibility (src/validation.ts:1:25373)
      at P2P.exports.checkPeerCompatibility [as _peerHandshakeCheck] (src/validation.ts:1:25910)
      at SCServer._scServer.on.socket (src/p2p.ts:1:65590)
      at /Users/diego-g/git/lisk-sdk/elements/lisk-p2p/node_modules/socketcluster-server/scserver.js:578:14
      at /Users/diego-g/git/lisk-sdk/elements/lisk-p2p/node_modules/socketcluster-server/scserver.js:378:7
      at Object.module.exports [as verify] (node_modules/jsonwebtoken/verify.js:43:12)
      at AuthEngine.verifyToken (node_modules/sc-auth/index.js:15:11)
      at SCServer._processAuthToken (node_modules/socketcluster-server/scserver.js:334:13)
      at /Users/diego-g/git/lisk-sdk/elements/lisk-p2p/node_modules/socketcluster-server/scserver.js:536:12
      at /Users/diego-g/git/lisk-sdk/elements/lisk-p2p/node_modules/socketcluster-server/scserver.js:889:9
      at /Users/diego-g/git/lisk-sdk/elements/lisk-p2p/node_modules/async/dist/async.js:1110:9
      at /Users/diego-g/git/lisk-sdk/elements/lisk-p2p/node_modules/async/dist/async.js:460:16
      at replenish (node_modules/async/dist/async.js:977:25)
      at /Users/diego-g/git/lisk-sdk/elements/lisk-p2p/node_modules/async/dist/async.js:986:9
      at _asyncMap (node_modules/async/dist/async.js:1103:5)
      at /Users/diego-g/git/lisk-sdk/elements/lisk-p2p/node_modules/async/dist/async.js:1189:16
      at /Users/diego-g/git/lisk-sdk/elements/lisk-p2p/node_modules/async/dist/async.js:1016:16
      at Object.<anonymous> (node_modules/async/dist/async.js:227:20)
      at Object.<anonymous> (node_modules/async/dist/async.js:89:12)
      at apply (node_modules/async/dist/async.js:20:25)
      at Object.<anonymous> (node_modules/async/dist/async.js:56:12)
      at Object.<anonymous> (node_modules/async/dist/async.js:232:23)
      at apply (node_modules/async/dist/async.js:21:25)
      at Object.applyEachSeries (node_modules/async/dist/async.js:56:12)
      at SCServer._passThroughHandshakeSCMiddleware (node_modules/socketcluster-server/scserver.js:867:9)
      at SCServerSocket.<anonymous> (node_modules/socketcluster-server/scserver.js:525:10)
      at SCServerSocket.on (node_modules/component-emitter/index.js:65:8)
      at SCServerSocket.Emitter.emit (node_modules/component-emitter/index.js:133:20)
      at /Users/diego-g/git/lisk-sdk/elements/lisk-p2p/node_modules/socketcluster-server/scserversocket.js:165:38
      at SCServer._passThroughMiddleware (node_modules/socketcluster-server/scserver.js:801:7)
      at SCServer.verifyInboundEvent (node_modules/socketcluster-server/scserver.js:695:8)
      at SCServerSocket._handleEventObject (node_modules/socketcluster-server/scserversocket.js:149:19)
      at WebSocket.<anonymous> (node_modules/socketcluster-server/scserversocket.js:118:14)
      at Receiver.receiverOnMessage (node_modules/socketcluster-server/node_modules/ws/lib/websocket.js:741:20)
      at Receiver.dataMessage (node_modules/socketcluster-server/node_modules/ws/lib/receiver.js:417:14)
      at Receiver.getData (node_modules/socketcluster-server/node_modules/ws/lib/receiver.js:347:17)
      at Receiver.startLoop (node_modules/socketcluster-server/node_modules/ws/lib/receiver.js:133:22)
      at Receiver._write (node_modules/socketcluster-server/node_modules/ws/lib/receiver.js:69:10)
      at doWrite (_stream_writable.js:410:12)
      at writeOrBuffer (_stream_writable.js:394:5)
      at Receiver.Writable.write (_stream_writable.js:294:11)
      at Socket.socketOnData (node_modules/socketcluster-server/node_modules/ws/lib/websocket.js:816:35)
      at addChunk (_stream_readable.js:284:12)
      at readableAddChunk (_stream_readable.js:265:11)
      at Socket.Readable.push (_stream_readable.js:220:10)
      at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

### Steps to reproduce

`npm run test:integration`

### Which version(s) does this affect? (Environment, OS, etc...)
`2.0.0`

### PR DESCRIPTION
**Pull request by jondubois**
### What was the problem?

- There were validation issues which would cause an error to be thrown and crash the node in some situations.

### How did I fix it?

- Perform additional checks on data from peers to prevent invalid method calls.

### Review checklist

* The PR resolves #3923
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-p2p/src/validation.ts [hunk 1]
```diff
@@ -159,13 +159,20 @@ export const checkProtocolVersionCompatibility = (
 	peerInfo: P2PDiscoveredPeerInfo,
 	nodeInfo: P2PNodeInfo,
 ): boolean => {
+	if (typeof nodeInfo.protocolVersion !== 'string') {
```
Comment (shuse2) [inline elements/lisk-p2p/src/validation.ts]: in 1.4, protocolVersion will be `undefined`, so it will return here, but that should not happen

File: elements/lisk-p2p/src/p2p.ts [hunk 2]
```diff
@@ -445,7 +445,8 @@ export class P2P extends EventEmitter {
 				if (
 					typeof queryObject.wsPort !== 'string' ||
 					typeof queryObject.version !== 'string' ||
-					typeof queryObject.nethash !== 'string'
+					typeof queryObject.nethash !== 'string' ||
+					typeof queryObject.protocolVersion !== 'string'
```
Comment (shuse2) [inline elements/lisk-p2p/src/p2p.ts]: same as below

File: elements/lisk-p2p/src/validation.ts (hunk 1 above)
Comment (jondubois) [reply elements/lisk-p2p/src/validation.ts]: Ah yep. I was meant to move it down but duplicated the whole if block instead :(

Comment (jondubois) [reply elements/lisk-p2p/src/validation.ts]: This is checking `nodeInfo. protocolVersion` (our own node's protocolVersion). We only check `peerInfo.protocolVersion` below the other `if (!peerInfo.protocolVersion) {` block. So it should be OK.

Comment (jondubois) [reply elements/lisk-p2p/src/validation.ts]: I will add a comment because it looks like accidentally duplicated code at a glance.
