### PR TITLE
Start command network flag shows invalid error message - Closes #6408, #6409

### LINKED ISSUE #6408: Start command network flag shows invalid error message
### Expected behavior

It should should the comma separated list of supported network names.

### Actual behavior

```
./bin/run start --network=manu
Starting Lisk my_chain at /Users/manu/.lisk/my_chain.
 ›   Error: Network must be one of default but received manu.
```

### Steps to reproduce

`./bin/run start --network=manu`

### Which version(s) does this affect? (Environment, OS, etc...)
5.1.0

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?

This PR resolves #6408, #6409

### How was it solved?

- Updated description, env and error message

### How was it tested?

- `./bin/run init ./sample_lisk_app --registry https://npm.lisk.io`
- `./bin/run start --network=testme`

### CODE REVIEW

**Review by shuse2 — APPROVED** [review]

File: commander/src/bootstrapping/commands/start.ts [hunk 1]
```diff
@@ -33,7 +33,7 @@ import {
 
 const LOG_OPTIONS = ['trace', 'debug', 'info', 'warn', 'error', 'fatal'];
 export abstract class StartCommand extends Command {
-	static description = 'Start Lisk Core Node.';
+	static description = 'Start Blockchain Client.';
```
Comment (ishantiw) [inline commander/src/bootstrapping/commands/start.ts:36]: Is it a client or it starts a node?

Comment (ManuGowda) [reply commander/src/bootstrapping/commands/start.ts:36]: I think its a blockchain client application similar to geth?
