### PR TITLE
Redefine p2p communication and update nodeInfo - Closes #5419 & #5472

### LINKED ISSUE #5419: Redefine P2P communication and message formats after using lisk-codec
### Description
Update the content of each endpoints to
#### getPeers
```
{
  peers: {
     ipAddress: string;
     port: uint32;
  }[]
}
```
#### getNodeInfo
```
{
  advertiseAddress: boolean;
  networkID: string;
  protocolVersion: string;
  nonce: string;
  // custom field injected from outside
  options: {
    height: uint32;
    maxHeightPrevoted: uint32;
    blockVersion: uint32;
  },
}
```
#### updateNodeInfo
```
// Only accept custom field
{
  height: uint32;
  maxHeightPrevoted: uint32;
  blockVersion: uint32;
}
```
#### Handshake
It should only require below information
```
{
  advertiseAddress: boolean;
  port: uint32;
  networkId: string;
  protocolVersion: string;
  nonce: string;
}
```

### Expected behavior

- P2P layer should communicate messages en/decoded using lisk-codec
- Should allow custom fields for custom modules by accepting schema from the user - Solved in https://github.com/LiskHQ/lisk-sdk/pull/5434

### Actual behavior

- Some messages are not well defined for p2p communicated and we need to finalize which fields will be required in the schema for encoding.

### Steps to reproduce

N/A

### Which version(s) does this affect? (Environment, OS, etc...)

`5.0`

### PR DESCRIPTION
**Pull request by ishantiw**
### What was the problem?

This PR resolves #5419 and #5472

### How was it solved?

- Update node Info to have these properties,
```typescript
 {
	readonly networkId: string,
	readonly networkVersion: string,
	readonly nonce: string,
        readonly advertiseAddress: boolean,
        options?: [key: string]: unknown,
}
```
- Apply nodeInfo to only update `options` field 
- Prepare query object handling clientSocketOptions to have limited fields from above `NodeInfo`
- Only allow sharing of `ipAddress` and `port` of a peer when sharing `peerList`
- Update network_setup and utils for tests
- Update all the tests
- Make setup for custom schema for custom nodeInfo related tests

### How was it tested?
Run following tests under elements/lisk-p2p,

`npm run test:unit`
`npm run test:integration`
`npm run test:functional`

### CODE REVIEW

File: framework/src/application/network/network.ts [hunk 1]
```diff
@@ -139,7 +142,28 @@ export class Network {
...
+				advertiseAddress,
+				os,
+				version,
+				wsPort,
+				...options
+			} = state;
+
+			const nodeInfo = {
+				networkId,
+				networkVersion: protocolVersion,
```
Comment (shuse2) [inline framework/src/application/network/network.ts:160]: lets create another issue to address the change in the `state`

File: framework/src/application/network/network.ts [hunk 2]
```diff
@@ -158,27 +183,28 @@ export class Network {
...
+			port: this._options.wsPort,
 			nodeInfo: initialNodeInfo,
 			hostIp: this._options.hostIp,
 			blacklistedIPs,
 			fixedPeers,
 			whitelistedPeers,
 			seedPeers: seedPeers.map(peer => ({
 				ipAddress: peer.ip,
-				wsPort: peer.wsPort,
+				port: peer.wsPort,
```
Comment (shuse2) [inline framework/src/application/network/network.ts:207]: Lets add another issue to change wsPort => port in config

File: framework/src/application/network/schema.ts [hunk 3]
```diff
@@ -31,13 +39,21 @@ export const customPeerInfoSchema = {
 	$id: '/peerInfo/custom',
 	type: 'object',
 	properties: {
+		height: {
```
Comment (shuse2) [inline framework/src/application/network/schema.ts:42]: I think this can be removed

Comment (ishantiw) [reply framework/src/application/network/schema.ts:42]: do we allow users to send custom properties to each other along with ipAddress and port? in that case we can remove peerInfo and only use one customSchema that will be used for `nodeInfo`

Comment (shuse2) [reply framework/src/application/network/schema.ts:42]: I think it shouldnt return anything other than the ip/port for the `getPeers` endpoint because it will be untrusted/outdated information

File: elements/lisk-p2p/src/peer_server/peer_server.ts [hunk 4]
```diff
@@ -301,35 +301,30 @@ export class PeerServer extends EventEmitter {
...
 					sharedState: {
 						...peerInPeerBook.sharedState,
-						...restOfQueryObject,
-						...queryOptions,
-						height: queryObject.height ? +queryObject.height : 0, // TODO: Remove the usage of height for choosing among peers having same ipAddress, instead use productivity and reputation
-						protocolVersion: queryObject.protocolVersion,
+						nonce: nonce as string,
+						networkVersion: networkVersion as string,
+						networkId: networkId as string,
+						options: queryOptions as UnknownKVPair,
```
[the remark this answers is not in the document]
Comment (ishantiw) [reply elements/lisk-p2p/src/peer_server/peer_server.ts:327]: if don't allow options then handshake logic cannot be extended( to use custom fields for exclusive handshakes, like a plugin owner only wants to accept connection from another plugin owner)

File: elements/lisk-p2p/src/p2p.ts [hunk 5]
```diff
@@ -110,14 +110,21 @@ import {
 } from './schema';
 
 const createRPCSchemas = (customRPCSchemas: RPCSchemas): RPCSchemas => ({
-	peerInfo: mergeCustomSchema(peerInfoSchema, customRPCSchemas.peerInfo),
-	nodeInfo: mergeCustomSchema(nodeInfoSchema, customRPCSchemas.nodeInfo),
+	peerInfo: mergeCustomSchema(
```
[the remark this answers is not in the document]
Comment (ishantiw) [reply elements/lisk-p2p/src/p2p.ts:113]: yeah I was thinking about it but I thought getPeers can also be modified to share custom properties. If its only ipAddress and port then we don't need custom schema peerInfo

File: elements/lisk-p2p/src/peer/outbound.ts [hunk 6]
```diff
@@ -116,15 +117,23 @@ export class OutboundPeer extends Peer {
 		const ackTimeout = this._peerConfig.ackTimeout
 			? this._peerConfig.ackTimeout
 			: DEFAULT_ACK_TIMEOUT;
+		const { options, ...nodeInfo } = this._serverNodeInfo as P2PNodeInfo;
+		const queryObject = options
+			? {
+					...nodeInfo,
+					port: this._peerConfig.hostPort,
+					options: JSON.stringify(options),
```
[the remark this answers is not in the document]
Comment (ishantiw) [reply elements/lisk-p2p/src/peer/outbound.ts:125]: for the reason discussed below, https://github.com/LiskHQ/lisk-sdk/pull/5514#discussion_r450245495

File: elements/lisk-p2p/src/peer_server/peer_server.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (mitsuaki-u) [reply elements/lisk-p2p/src/peer_server/peer_server.ts:327]: > like a plugin owner only wants to accept connection from another plugin owner)

Maybe we can discuss whether we are going forward with this feature

File: elements/lisk-p2p/src/utils/validate.ts [hunk 7]
```diff
@@ -95,7 +95,7 @@ export const validatePeerCompatibility = (
 		};
 	}
 
-	if (!validateProtocolVersionCompatibility(peerInfo, nodeInfo)) {
+	if (!validatenetworkVersionCompatibility(peerInfo, nodeInfo)) {
```
Comment (mitsuaki-u) [inline elements/lisk-p2p/src/utils/validate.ts:98]: prefer camel case for network

File: elements/lisk-p2p/src/peer_server/peer_server.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (ishantiw) [reply elements/lisk-p2p/src/peer_server/peer_server.ts:327]: @mitsuaki-u Related to this, we are not allowing custom fields in peerInfo and during handshake due to potential split in the network

File: elements/lisk-p2p/src/p2p.ts [hunk 8]
```diff
@@ -829,11 +839,21 @@ export class P2P extends EventEmitter {
 			.filter(
 				peer => !(peer.internalState && !peer.internalState.advertiseAddress),
 			)
-			.map(peer => ({
-				ipAddress: peer.ipAddress,
-				wsPort: peer.wsPort,
-				...peer.sharedState,
-			}));
+			.map(peer => {
+				// If custom fields are available then share them
```
[the remark this answers is not in the document]
Comment (ishantiw) [reply elements/lisk-p2p/src/p2p.ts]: https://github.com/LiskHQ/lisk-sdk/pull/5514#discussion_r450900846

File: elements/lisk-p2p/src/peer_server/peer_server.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (mitsuaki-u) [reply elements/lisk-p2p/src/peer_server/peer_server.ts:327]: Yes that was my understanding as well 👍

File: framework/src/application/network/network.ts (hunk 2 above)
Comment (ishantiw) [reply framework/src/application/network/network.ts:207]: created https://github.com/LiskHQ/lisk-sdk/issues/5527

File: framework/src/application/network/network.ts (hunk 1 above)
Comment (ishantiw) [reply framework/src/application/network/network.ts:160]: created https://github.com/LiskHQ/lisk-sdk/issues/5528
