### PR TITLE
Logging does not work for storage component - Closes #3455

### LINKED ISSUE #3455: Logging does not work for storage component
### Expected behavior

If we set some events for storage component `"logEvents": ["query"]` to `components.storage` and start the application, it must show db queries. 

### Actual behavior

There is no database logging shown. 

### Steps to reproduce
As specified in description.

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

### PR DESCRIPTION
**Pull request by nazarhussain**
### What was the problem?

Database logging was not working correctly as the pg monitor was not looking up to the right instance of library. 

### How did I fix it?

used the private object to cache the instance. 

### How to test it?

Add `"logEvents": ["query"] to components.storage` and run the application.

### Review checklist

* The PR resolves #3455
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/src/components/storage/adapters/pgp_adapter.js [hunk 1]
```diff
@@ -58,7 +59,9 @@ class PgpAdapter extends BaseAdapter {
 			},
 		};
 
-		this.pgp = pgpLib(this.pgpOptions);
+		_private.pgp = _private.pgp ? _private.pgp : pgpLib(this.pgpOptions);
```
Comment (pablitovicente) [inline framework/src/components/storage/adapters/pgp_adapter.js]: Could you add a comment about what does this achieves?
