### PR TITLE
Catch error on decode error and apply penalty - Closes #5699

### LINKED ISSUE #5699: P2P throws unhandled error with invalid data
### Expected behavior
Error should be handled and not shutdown the application. Also, if invalid data is received, it should ban the peer immediately 

### Actual behavior
with below error, node restarts.
```
0|alphanet  | 12:16:23 ERROR lisk-framework: EVENT_FAILED_PEER_INFO_UPDATE: Failed peer update (module=lisk:app)
0|alphanet  | Message: Invalid buffer length
0|alphanet  |  Trace: Error: Invalid buffer length
0|alphanet  |     at Object.exports.readUInt32 (/node/v12.18.3/lib/node_modules/lisk-core/node_modules/@liskhq/lisk-codec/dist-node/varint.js:44:19)
0|alphanet  |     at Object.exports.readObject (/node/v12.18.3/lib/node_modules/lisk-core/node_modules/@liskhq/lisk-codec/dist-node/collection.js:84:46)
0|alphanet  |     at Codec.decode (/node/v12.18.3/lib/node_modules/lisk-core/node_modules/@liskhq/lisk-codec/dist-node/codec.js:50:36)
0|alphanet  |     at InboundPeer._handleUpdateNodeInfo (/node/v12.18.3/lib/node_modules/lisk-core/node_modules/@liskhq/lisk-p2p/dist-node/peer/base.js:283:56)
0|alphanet  |     at SCServerSocket.Peer._handleRawMessage (/node/v12.18.3/lib/node_modules/lisk-core/node_modules/@liskhq/lisk-p2p/dist-node/peer/base.js:90:22)
0|alphanet  |     at SCServerSocket.Emitter.emit (/node/v12.18.3/lib/node_modules/lisk-core/node_modules/component-emitter/index.js:133:20)
0|alphanet  |     at /node/v12.18.3/lib/node_modules/lisk-core/node_modules/socketcluster-server/scserversocket.js:182:38
0|alphanet  |     at /node/v12.18.3/lib/node_modules/lisk-core/node_modules/socketcluster-server/scserver.js:821:11
0|alphanet  |     at /node/v12.18.3/lib/node_modules/lisk-core/node_modules/async/dist/async.js:248:13
0|alphanet  |     at wrapper (/node/v12.18.3/lib/node_modules/lisk-core/node_modules/async/dist/async.js:268:20)
0|alphanet  | 12:16:23 ERROR lisk-framework: System error: uncaughtException (module=lisk:app)
0|alphanet  | Message: Invalid buffer length
0|alphanet  |  Trace: Error: Invalid buffer length
0|alphanet  |     at Object.exports.readUInt32 (/node/v12.18.3/lib/node_modules/lisk-core/node_modules/@liskhq/lisk-codec/dist-node/varint.js:44:19)
0|alphanet  |     at Object.exports.readObject (/node/v12.18.3/lib/node_modules/lisk-core/node_modules/@liskhq/lisk-codec/dist-node/collection.js:84:46)
0|alphanet  |     at Codec.decode (/node/v12.18.3/lib/node_modules/lisk-core/node_modules/@liskhq/lisk-codec/dist-node/codec.js:50:36)
0|alphanet  |     at PeerPool.P2P._handlePeerPoolMessage (/node/v12.18.3/lib/node_modules/lisk-core/node_modules/@liskhq/lisk-p2p/dist-node/p2p.js:122:60)
0|alphanet  |     at PeerPool.emit (events.js:315:20)
0|alphanet  |     at InboundPeer.PeerPool._handlePeerMessage (/node/v12.18.3/lib/node_modules/lisk-core/node_modules/@liskhq/lisk-p2p/dist-node/peer_pool.js:70:18)
0|alphanet  |     at InboundPeer.emit (events.js:315:20)
0|alphanet  |     at SCServerSocket.Peer._handleRawMessage (/node/v12.18.3/lib/node_modules/lisk-core/node_modules/@liskhq/lisk-p2p/dist-node/peer/base.js:92:18)
0|alphanet  |     at SCServerSocket.Emitter.emit (/node/v12.18.3/lib/node_modules/lisk-core/node_modules/component-emitter/index.js:133:20)
0|alphanet  |     at /node/v12.18.3/lib/node_modules/lisk-core/node_modules/socketcluster-server/scserversocket.js:182:38
```

### Steps to reproduce
Connect with P2P client without setting the custom schema, which in result send nodeInfo which cannot be decoded

### Which version(s) does this affect? (Environment, OS, etc...)
5.0

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #5699 

### How was it solved?

- Add try-catch when decoding and apply penalty

### How was it tested?

- Update unit test to check the invalid value case

### CODE REVIEW

File: elements/lisk-p2p/src/peer/base.ts [hunk 1]
```diff
@@ -587,4 +579,26 @@ export class Peer extends EventEmitter {
...
+
+	private _decodePeerInfo(data: unknown): P2PPeerInfo {
+		try {
+			if (typeof data !== 'string' || !isHexString(data)) {
+				throw new Error('Invalid encoded data');
+			}
+			return codec.decode<P2PPeerInfo>(this._rpcSchemas.peerInfo, Buffer.from(data, 'hex'));
+		} catch (error) {
+			throw new InvalidPeerInfoError((error as Error).message);
+		}
```
Comment (ishantiw) [inline elements/lisk-p2p/src/peer/base.ts:602]: Maybe we can move these functions to utils?
`decodePeerInfo(data: unknown, schema: peerInfo): P2PPeerInfo`

Also, we can use encoding peer/nodeInfo functions that encode and return encoded strings. But we can do it in some other issue

**Review by ishantiw — COMMENTED** [review]
Just a comment

**Review by mitsuaki-u — APPROVED** [review]

**Review by ishantiw — APPROVED** [review]
