### PR TITLE
Unstable broadhash due to stale info about peers in `getNetworkStatus()`

### LINKED ISSUE #3574: Unstable broadhash consensus
### Expected behavior
Broadhash consensus should be stable.
### Actual behavior
Broadhash consensus is unstable which leads to missed blocks.
### Steps to reproduce
Tested on network with 10 peers, observe logs.
### Which version(s) does this affect? (Environment, OS, etc...)
`2.0.0-alpha.0`

### PR DESCRIPTION
**Pull request by ishantiw**
### What was the problem?

Broadhash consensus is unstable which leads to missed blocks. #3574 

`networkHeight` is incorrect (for about 1 second) when API called just after forging a block. #3533 

### How did I fix it?

- Assigning correct `state` information (`0` for `disconnected` and `2` for `connected`) for `connectedPeers` and `triedPeers` which are not connected.
- Update `triedPeers` info on update status event on p2p-lib
- Don't let the node to add itself in its `newPeers` list

### How to test it?

Test on network with 10 peers, observe logs.

### Review checklist

* The PR resolves #3574 #3533
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-p2p/src/p2p.ts [hunk 1]
```diff
@@ -433,7 +445,15 @@ export class P2P extends EventEmitter {
 					this.emit(EVENT_NEW_PEER, incomingPeerInfo);
 				}
 
-				if (!this._newPeers.has(peerId) && !this._triedPeers.has(peerId)) {
+				if (
+					!this._newPeers.has(peerId) &&
+					!this._triedPeers.has(peerId) &&
+					!(
+						['127.0.0.1', '0.0.0.0', 'localhost'].includes(
```
Comment (shuse2) [inline elements/lisk-p2p/src/p2p.ts]: maybe set this as constants?
```
const LOCAL_ADDRESSES = ['127.0.0.1', '0.0.0.0', 'localhost'];
```

Comment (ishantiw) [reply elements/lisk-p2p/src/p2p.ts]: Done

File: elements/lisk-p2p/src/p2p.ts [hunk 2]
```diff
@@ -103,6 +103,7 @@ export const EVENT_FAILED_TO_ADD_INBOUND_PEER = 'failedToAddInboundPeer';
 export const EVENT_NEW_PEER = 'newPeer';
 
 export const NODE_HOST_IP = '0.0.0.0';
```
Comment (diego-G) [inline elements/lisk-p2p/src/p2p.ts]: This is redundant after introducing `NODE_HOST_IP_LIST.

File: framework/src/modules/network/filter_peers.js [hunk 3]
```diff
@@ -168,18 +168,22 @@ const getCountByFilter = (peers, filter) => {
...
-		);
-
-		if (!found) {
+	// Assign state 2 to the connected peers
+	const connectedList = connectedPeers.map(peer => {
+		const { ipAddress, options, minVersion, nethash, ...peerWithoutIp } = peer;
+
+		return { ip: ipAddress, ...peerWithoutIp, state: 2 };
+	});
+	// For the peers that are not present in connectedList should be assigned state 0
```
Comment (diego-G) [inline framework/src/modules/network/filter_peers.js]: Shouldn't it be 1 as in previous versions? https://github.com/LiskHQ/lisk-sdk/blob/40e2e86021ad14661dea78932d638a2a5bb53835/framework/src/modules/chain/logic/peer.js#L197

File: elements/lisk-p2p/src/p2p.ts (hunk 2 above)
Comment (ishantiw) [reply elements/lisk-p2p/src/p2p.ts]: We are using `NODE_HOST_IP` only for http server that requires only one ip, if we remove it then it will look something like `this._httpServer.listen(this._nodeInfo.wsPort, NODE_HOST_IP_LIST[1])`
which doesn't look so nice. 

How about we rename them like below?,
`NODE_HOST_IP` => `NODE_HTTP_HOST_IP`
`NODE_HOST_IP_LIST` => `NODE_VALID_HOST_IP_LIST`

File: framework/src/modules/network/filter_peers.js (hunk 3 above)
Comment (ishantiw) [reply framework/src/modules/network/filter_peers.js]: Oh yeah need to change disconnected peer's state to `1` 👍

File: elements/lisk-p2p/src/p2p.ts [hunk 4]
```diff
@@ -433,7 +446,14 @@ export class P2P extends EventEmitter {
 					this.emit(EVENT_NEW_PEER, incomingPeerInfo);
 				}
 
-				if (!this._newPeers.has(peerId) && !this._triedPeers.has(peerId)) {
+				if (
+					!this._newPeers.has(peerId) &&
+					!this._triedPeers.has(peerId) &&
+					!(
```
Comment (jondubois) [inline elements/lisk-p2p/src/p2p.ts]: Is this new condition needed?
If the node tries to connect to itself, it should be rejected on line `365` and it should never reach this code.

File: elements/lisk-p2p/src/p2p.ts [hunk 5]
```diff
@@ -497,7 +517,14 @@ export class P2P extends EventEmitter {
 
 		discoveredPeers.forEach((peerInfo: P2PDiscoveredPeerInfo) => {
 			const peerId = constructPeerIdFromPeerInfo(peerInfo);
-			if (!this._triedPeers.has(peerId) && !this._newPeers.has(peerId)) {
+			if (
+				!this._triedPeers.has(peerId) &&
+				!this._newPeers.has(peerId) &&
+				!(
+					NODE_HOST_IP_LIST.includes(peerInfo.ipAddress) &&
+					peerInfo.wsPort === this.nodeInfo.wsPort
```
Comment (jondubois) [inline elements/lisk-p2p/src/p2p.ts]: This condition wouldn't work in a production environment. The node's own IP will not be `127.0.0.1` (nor `localhost`), it will look like a regular IP address. The only way to know which IP is our own is during the handshake when we get the nonce.

To make it work properly, we would need to add separate logic for self-discovery and the node would store its own IP address somewhere.

Given the amount of complexity involved, I think it would be simpler to just allow the node to add itself as a peer.

File: elements/lisk-p2p/src/p2p.ts (hunk 4 above)
Comment (ishantiw) [reply elements/lisk-p2p/src/p2p.ts]: That's true but somehow it's still being added to `newPeers` list reported by @shuse2 so at some point the nonce is different for the same IP, is it because we are having two nonces (network and config)?

File: elements/lisk-p2p/src/p2p.ts (hunk 5 above)
Comment (ishantiw) [reply elements/lisk-p2p/src/p2p.ts]: It's just an extra check to avoid adding these IPs in `newPeers` list which are showing up sometimes, if it adds itself with its public IP then it's fine

File: elements/lisk-p2p/src/p2p.ts (hunk 4 above)
Comment (ishantiw) [reply elements/lisk-p2p/src/p2p.ts]: Removed this condition as discussed, as it will be covered by nonce condition already

File: elements/lisk-p2p/src/p2p.ts (hunk 5 above)
Comment (ishantiw) [reply elements/lisk-p2p/src/p2p.ts]: same as above

File: elements/lisk-p2p/src/p2p.ts (hunk 2 above)
Comment (ishantiw) [reply elements/lisk-p2p/src/p2p.ts]: removed this condition as discussed, so it isn't relevant anymore
