### PR TITLE
Modify boolean validation logic env - Closes #3495

### LINKED ISSUE #3495: Improve handling boolean ENV var passed via CLI
### Expected behavior
For type boolean, we check if the variable is equal to `"true"`. If yes, we return `true`, else `false`. This implies that `this-is-wrong` renders `false`.

We want to change the behavior to throw a meaningful error.

### Steps to reproduce
Start app with `LISK_API_PUBLIC=invalid-param`.

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

### PR DESCRIPTION
**Pull request by michielmulders**
### How did I fix it?
Return error if value for type boolean is not equal to `"true"` or `"false"`.
Added test, and updated others accordingly.

### How to test it?
Start app with `LISK_API_PUBLIC=truuuee TS_NODE_PROJECT=./tsconfig.json ts-node src/index.ts | bunyan`

### Review checklist

* The PR resolves #3495 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/src/controller/validator/keywords/env/index.js [hunk 1]
```diff
@@ -45,7 +45,17 @@ const compile = (schema, parentSchema) => {
...
+						variableValue = true;
+					} else if (variableValue.toLowerCase() === 'false') {
+						variableValue = false;
+					} else {
+						throw new Error(
+							`Failed to apply value for option ${
+								envVariable.name
+							}, use "true" or "false"`
+						);
+					}
```
Comment (yatki) [inline framework/src/controller/validator/keywords/env/index.js]:
```js
if (variableValue.toLowerCase() !== 'true' && variableValue.toLowerCase() !== 'false') {
   throw new Error(`Failed to apply value for option ${envVariable.name}, use "true" or "false"`);
} 
          
variableValue = variableValue.toLowerCase() === 'true';
break;
```
how about this ? :D

Comment (michielmulders) [reply framework/src/controller/validator/keywords/env/index.js]: Shorter!

Comment (shuse2) [reply framework/src/controller/validator/keywords/env/index.js]: `['true', 'false'].includes(variableValue.toLowerCase())`?
