### PR TITLE
Solve JavaScript heap out of memory - Closes #4183

### LINKED ISSUE #4183: JavaScript heap out of memory error
### Expected behavior
Expect to sync with mainnet

### Actual behavior
It crashes with the following error:

> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### Steps to reproduce
Using `feature/introduce_bft_consensus` branch in Lisk SDK and `release/2.1.0` branch in Lisk Core.
Link SDK in Core: `npm link lisk-sdk`
Start core on mainnet: `LISK_CONSOLE_LOG_LEVEL=debug node dist/index.js -n mainnet | npx bunyan -o short`

### Which version(s) does this affect? (Environment, OS, etc...)
`feature/introduce_bft_consensus`

### PR DESCRIPTION
**Pull request by michielmulders**
### What was the problem?
It crashes with the following error:

> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### How did I solve it?
Separate both prepare statements, use `for ... of`, and skip caching for genesis block (preventing 8k DB calls -> causing the issue previously).

### How to manually test it?
Start application and see if it runs correctly.

### Review checklist

- [x] The PR resolves #4183 
- [ ] All new code is covered with unit tests
- [ ] Relevant integration / functional tests are added
- [ ] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [ ] Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/chain/transactions/votes_weight.js [hunk 1]
```diff
@@ -224,9 +224,13 @@ const prepare = async (stateStore, transaction) => {
 	];
 
 	const cacheFilter = senderRecipientVotedPublicKeys.map(publicKey => ({
-		address: getAddressFromPublicKey(publicKey),
+		publicKey,
```
Comment (shuse2) [inline framework/src/modules/chain/transactions/votes_weight.js]: I think we should use consistently primary key search otherwise we will always need more index

File: framework/src/modules/chain/transactions/votes_weight.js [hunk 2]
```diff
@@ -224,9 +224,13 @@ const prepare = async (stateStore, transaction) => {
...
 	}));
 
+	if (cacheFilter.length === 0) {
```
Comment (shuse2) [inline framework/src/modules/chain/transactions/votes_weight.js]: shouldn't this check goes before creating filter?

Comment (limiaspasdaniel) [reply framework/src/modules/chain/transactions/votes_weight.js]: @shuse2 what do you mean?

Comment (shuse2) [reply framework/src/modules/chain/transactions/votes_weight.js]: I mean maybe we can just check the length of `senderRecipientVotedPublicKeys`?

Comment (limiaspasdaniel) [reply framework/src/modules/chain/transactions/votes_weight.js]: True @michielmulders

Comment (michielmulders) [reply framework/src/modules/chain/transactions/votes_weight.js]: Yes we can do this as well so we don't have to loop the empty array

File: framework/src/modules/chain/transactions/transactions_handlers.js [hunk 3]
```diff
@@ -115,8 +115,17 @@ const applyGenesisTransactions = storage => async (
 		tx,
 	});
 
-	await Promise.all(transactions.map(t => t.prepare(stateStore)));
-	await Promise.all(transactions.map(t => votesWeight.prepare(stateStore, t)));
+	// eslint-disable-next-line no-restricted-syntax
```
Comment (lsilvs) [inline framework/src/modules/chain/transactions/transactions_handlers.js]: It would be good to have a comment explaining why we can't run in parallel and why we need two for loops here. (`to avoid someone merging this into one for loop in the future`)
