### PR TITLE
Fix length requirement and dataType on getChainAccountRequestSchema

### LINKED ISSUE #8604: Chain ID length not validated in interoperability endpoints
### Description

The [BaseInteroperabilityEndpoint](https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/framework/src/modules/interoperability/base_interoperability_endpoint.ts) and [MainchainInteroperabilityEndpoint](https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/framework/src/modules/interoperability/mainchain/endpoint.ts) classes provide several methods that take a hex-formatted chain ID as a parameter. These methods validate the chain ID using different schemas that are all aliases for `getChainAccountRequestSchema`

https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/framework/src/modules/interoperability/schemas.ts#L561-L571

The `chainID` property in the above schema lacks the `minLength` and `maxLength` fields. As a result, arbitrary-length chain ID strings may be passed to internal functions that assume a correct length.

### Affected version

`v6.0.0-beta.2`

### PR DESCRIPTION
**Pull request by Phanco**
### What was the problem?

This PR resolves #8604

### CODE REVIEW

File: framework/src/modules/interoperability/schemas.ts [hunk 1]
```diff
@@ -564,8 +564,10 @@ export const getChainAccountRequestSchema = {
 	required: ['chainID'],
 	properties: {
 		chainID: {
-			type: 'string',
-			format: 'hex',
+			dataType: 'bytes',
+			fieldNumber: 1,
+			minLength: CHAIN_ID_LENGTH,
+			maxLength: CHAIN_ID_LENGTH,
```
Comment (ishantiw) [inline framework/src/modules/interoperability/schemas.ts:570]: Would be nice if we can have a unit test for this

**Review by ishantiw — APPROVED** [review]
