### PR TITLE
Ban peers after failed block verification

### LINKED ISSUE #8433: Peer should be banned when block fail on verification
### Expected behavior
Peer should be banned if the block failed before execution up to this [line](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/engine/consensus/consensus.ts#L574).

### Actual behavior
It has the handling of banning the peer [here](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/engine/consensus/consensus.ts#L329-L341). However, the execution code is not throwing this particular error

### Steps to reproduce
Try to send invalid block

### Which version(s) does this affect? (Environment, OS, etc...)
6.0.0-beta.0

### PR DESCRIPTION
**Pull request by bobanm**
### What was the problem?

This PR resolves #8433

### How was it solved?

- Private methods `_execute()` and `_executeValidated()` now throw `ApplyPenaltyError` when block verification fails
- Removed redundant code comments
- Bonus: renamed `_verifyAssetsHeight()` and `_verifyAssetsSignature()` into `_verifyBlockHeight()` and `_verifyBlockSignature()` 😎 

### How was it tested?

Added 2 new unit tests which validate that `Consensus._execute()` and `Consensus._executeValidated()` throw `ApplyPenaltyError`

### CODE REVIEW

File: framework/src/engine/consensus/consensus.ts [hunk 1]
```diff
@@ -514,14 +518,19 @@ export class Consensus {
...
+					});
+				} catch (error) {
+					throw new ApplyPenaltyError(error);
+				}
+
 				await this._deleteBlock(lastBlock);
 				try {
 					await this._executeValidated(block);
 				} catch (err) {
+					const previousLastBlock = objects.cloneDeep(lastBlock);
```
Comment (shuse2) [inline framework/src/engine/consensus/consensus.ts:533]: `cloneDeep` was meant to be executed before deleting the block to avoid possibility of mutating the last block. (lastBlock is reference)

**Review by shuse2 — CHANGES_REQUESTED** [review]

**Review by shuse2 — APPROVED** [review]
