### PR TITLE
Use nodejs crypto library for checksum verification - Closes #3872

### LINKED ISSUE #3872: Use nodejs crypto library for checksum verification
### Expected behavior
To avoid inconsistent behaviors it's better to use Nodejs `crypto` module which provides a way to verify the checksum  
### Actual behavior
`shasum` is used for verifying the checksum of the Lisk core binary, this results in inconsistent behavior in the ubunut instance. 
### Steps to reproduce
- Use a bare Linux machine or Install Docker on your machine and run `docker run -it ubuntu:18.04 /bin/bash`
- Create lisk user and install commander `2.2.0`
- Extract and install Lisk core `./lisk core:install --network=testnet testnet-01`
- You will receive an error `→ /bin/sh: 1: shasum: not found`
### Which version(s) does this affect? (Environment, OS, etc...)
Lisk Commander 2.2.0

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?
`shasum` was incompatible with `linux` when the machine had bare minimum installation.
### How did I fix it?
Using Nodejs `crypto` library to verify the checksum to support all OS.
### How to test it?
- Use a bare Linux machine or Install Docker on your machine and run docker run -it ubuntu:18.04 /bin/bash
- Create lisk user and install commander 2.2.0
- Extract and install Lisk core ./lisk core:install --network=testnet testnet-01
- The installation should succeed

### Review checklist

* The PR resolves #3872 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Comment by fchavant** [comment]
@ManuGowda 
1. shouldn't there be a system test for that?
2. how can this be tested before the PR is merged? (`oclif-dev pack` seems to always pull the published version)

File: commander/src/utils/download.ts [hunk 1]
```diff
@@ -88,5 +72,13 @@ export const extract = async (
 export const downloadAndValidate = async (url: string, cacheDir: string) => {
 	await download(url, cacheDir);
 	await download(`${url}.SHA256`, cacheDir);
-	await validateChecksum(`${url}.SHA256`, cacheDir);
+
+	const { fileName, fileDir } = getDownloadedFileInfo(url, cacheDir);
+	const dataBuffer = fs.readFileSync(`${fileDir}/${fileName}`);
```
Comment (fchavant) [inline commander/src/utils/download.ts]: It looks like the whole file would be read into RAM. Since it is pretty large already wouldn't it be nicer to read it as a stream instead?

File: elements/lisk-cryptography/src/hash.ts [hunk 2]
```diff
@@ -43,3 +43,13 @@ export const hash = (data: Buffer | string, format?: string): Buffer => {
 		'Unsupported data format. Currently only Buffers or `hex` and `utf8` strings are supported.',
 	);
 };
+
+export const verifyChecksum = (
+	data: Buffer | string,
+	checksum: string,
+): boolean => {
+	const dataHash = hash(data);
+	const hex = bufferToHex(dataHash);
```
Comment (fchavant) [inline elements/lisk-cryptography/src/hash.ts]: How does this work? The output of `sha256sum` looks like `48be5c5bff9fbf6077844165242856b9db6cdbf44e10cd9aeb8ae18f46acbac2  lisk-2.0.0-rc.0-Linux-x86_64.tar.gz` (notice the `\t<file name>`)

Comment (ManuGowda) [reply elements/lisk-cryptography/src/hash.ts]: when u generate the hex from buffer of tar file it will be just the hex `48be5c5bff9fbf6077844165242856b9db6cdbf44e10cd9aeb8ae18f46acbac2`, so it should be fine.
on the other hand, what you might be referring to `SHA256` file which has the format you mentioned, in that case i am already doing 
```
const content = fs.readFileSync(`${fileDir}/${fileName}.SHA256`, 'utf8');
const checksum = content.split(' ')[0];
```

File: elements/lisk-cryptography/src/hash.ts [hunk 3]
```diff
@@ -43,3 +43,13 @@ export const hash = (data: Buffer | string, format?: string): Buffer => {
 		'Unsupported data format. Currently only Buffers or `hex` and `utf8` strings are supported.',
 	);
 };
+
+export const verifyChecksum = (
```
Comment (shuse2) [inline elements/lisk-cryptography/src/hash.ts]: maybe if it's this simple, then probably we don't need to add this function.
This is not really specific to checksum either

Comment (ManuGowda) [reply elements/lisk-cryptography/src/hash.ts]: ok then I will not add the changes in cryptography 👍 
it will not be useful in general so

File: commander/package.json [hunk 4]
```diff
@@ -119,6 +119,7 @@
 		"pm2": "3.5.0",
 		"semver": "5.6.0",
 		"strip-ansi": "4.0.0",
+		"tar": "^4.4.10",
```
Comment (shuse2) [inline commander/package.json]: please use exact version

File: commander/package.json [hunk 5]
```diff
@@ -139,6 +140,7 @@
 		"@types/sinon": "7.0.5",
 		"@types/sinon-chai": "3.2.2",
 		"@types/strip-ansi": "3.0.0",
+		"@types/tar": "^4.0.1",
```
Comment (shuse2) [inline commander/package.json]: same as above

File: commander/src/commands/core/install.ts [hunk 6]
```diff
@@ -255,7 +256,11 @@ export default class InstallCommand extends BaseCommand {
 								);
 
 								createDirectory(installDir);
-								await extract(fileDir, fileName, installDir);
+								await tar.x({
```
Comment (fchavant) [inline commander/src/commands/core/install.ts]: This is not really related, is it?

File: commander/package-lock.json [hunk 7]
```diff
@@ -119,6 +119,95 @@
...
+			},
+			"dependencies": {
+				"@types/node": {
+					"version": "11.11.2",
+					"resolved": "https://registry.npmjs.org/@types/node/-/node-11.11.2.tgz",
+					"integrity": "sha512-iEaHiDNkHv4Jrm9O5T37OYEUwjJesiyt6ZlhLFK0sbo4CLD0jyCOB4Pc2F9iD3MbW2397SLNxZKdDGntGaBjQQ=="
+				}
+			}
+		},
+		"@liskhq/lisk-api-client": {
```
Comment (shuse2) [inline commander/package-lock.json]: siblings package shouldn't be in the `package-lock`.
Please use 
`npx lerna boostrap` in the root level to update the `package-lock`

File: commander/src/utils/download.ts [hunk 8]
```diff
@@ -14,9 +14,34 @@
...
 import fs from 'fs-extra';
+import * as tar from 'tar';
 import { dateDiff, getDownloadedFileInfo } from './core/commons';
-import { exec, ExecResult } from './worker-process';
+
+export const verifyChecksum = async (
+	filePath: string,
+	expectedChecksum: string,
+): Promise<boolean> => {
+	const shasum = crypto.createHash('sha256');
```
Comment (shuse2) [inline commander/src/utils/download.ts]: prefer to use `hash` and `bufferToHex` from `lisk-cryptography`
We shouldn't try not to use `crypto` directly

File: commander/src/commands/core/install.ts (hunk 6 above)
Comment (ManuGowda) [reply commander/src/commands/core/install.ts]: i just removed the old function and now we can use the npm package for the extract. so all good

File: commander/src/commands/core/upgrade.ts [hunk 9]
```diff
@@ -174,7 +175,11 @@ export default class UpgradeCommand extends BaseCommand {
 									cacheDir,
 								);
 
-								await extract(fileDir, fileName, installationPath);
+								await tar.x({
```
Comment (shuse2) [inline commander/src/commands/core/upgrade.ts]: why not using `extract` now?

File: commander/src/commands/core/install.ts (hunk 6 above)
Comment (shuse2) [inline commander/src/commands/core/install.ts]: same as below, why not use `extract`?

File: commander/src/utils/download.ts (hunk 8 above)
Comment (ManuGowda) [reply commander/src/utils/download.ts]: the problem with using the `hash` function was that its not a buffer.. its stream here.. so

File: commander/src/commands/core/upgrade.ts (hunk 9 above)
Comment (ManuGowda) [reply commander/src/commands/core/upgrade.ts]: tar has the extract function directly.. we dont need an extra wrapper just for calling it

File: commander/src/utils/download.ts (hunk 8 above)
Comment (shuse2) [reply commander/src/utils/download.ts]: we can read the file and then create the hash. we don't need to do it while streaming i think

File: commander/src/commands/core/upgrade.ts (hunk 9 above)
Comment (shuse2) [reply commander/src/commands/core/upgrade.ts]: I think you already defined the extra wrapper, and probably it would be easier if we need to change library (like this case) if we keep the wrapper

File: commander/package-lock.json (hunk 7 above)
Comment (ManuGowda) [reply commander/package-lock.json]: @shuse2 i tried the `npx lerna boostrap` in the root and it dint resolve the package lock issue

File: commander/src/commands/core/upgrade.ts (hunk 9 above)
Comment (ManuGowda) [reply commander/src/commands/core/upgrade.ts]: ok ll move it back.
