### PR TITLE
Request and apply blocks of new chain [BSM] - Closes #3771

### LINKED ISSUE #3771: Implement request and apply blocks of new chain step for Block Sync Mechanism
### Expected behavior
Implement request and apply blocks of new chain step for Block Sync Mechanism

We request blocks from `P` and apply them according to the section "Processing Blocks" of the LIP until we have block `B` at tip of the chain.

In order to do this we need to issue a network call `blocks` which returns 34 blocks. This is pretty old code and maybe we can update it to rename the endpoint to `getBlocks` and rethink how many blocks to return.

a) If all blocks up to `B` are successfully applied, the block synchronization mechanism terminates.

b) If the node is not able to obtain all blocks up to block `B` from `P`, but synchronization stops at a block `T` (i.e., `T` is the tip of the current chain), then the node checks whether `T` has priority over `A` (where A is tip of our original chain)  in terms of the fork choice rule (condition at the beginning of the section):

`(A.heightPrevoted<T.heightPrevoted) || A.height<T.height && A.heightPrevoted==T.heightPrevoted)`

If the check fails, `P` is banned, the chain with tip `A` is restored and block synchronization is restarted from Step 1. If the check passes, block synchronization is also restarted from Step 1.

### Which version(s) does this affect? (Environment, OS, etc...)
`feature/BFT`

### PR DESCRIPTION
**Pull request by limiaspasdaniel**
### What was the problem?
Refer to #3771 
### How did I solve it?
Refer to #3771 
### How to manually test it?
Test will be implemented on #4375 
### Review checklist
- [ ] The PR resolves #3771 
- [ ] All new code is covered with unit tests
- [ ] Relevant integration / functional tests are added
- [ ] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [ ] Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/chain/processor/processor.js [hunk 1]
```diff
@@ -158,9 +158,8 @@ class Processor {
 		});
 	}
 
-	async forkStatus(receivedBlock) {
+	async forkStatus(receivedBlock, lastBlock = this.blocksModule.lastBlock) {
```
Comment (michielmulders) [inline framework/src/modules/chain/processor/processor.js]: I don't like this to have this static getter being used as default value directly in the parameter definition (personal opinion).

File: framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js [hunk 2]
```diff
@@ -91,6 +227,8 @@ class BlockSynchronizationMechanism {
 	/**
 	 * Reverts the current chain so the new tip of the chain corresponds to the
 	 * last common block.
+	 *
+	 * Returns the last common block
```
Comment (michielmulders) [inline framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js]: Minor: Add this return message behind `@return {Promise<object>}`

File: framework/src/modules/chain/synchronizer/utils.js [hunk 3]
```diff
@@ -51,10 +51,15 @@ const restoreBlocks = async (blocksModule, processorModule, tx) => {
...
 const deleteBlocksAfterHeightAndBackup = async (
+	logger,
 	processorModule,
 	blocksModule,
 	desiredHeight,
 ) => {
+	logger.debug(
+		{ height: desiredHeight },
+		'Deleting blocks after target height',
+	);
```
Comment (michielmulders) [inline framework/src/modules/chain/synchronizer/utils.js]: would it make sense to add another logger.debug message after the while loop telling something like `blocks deleted successfully`?

File: framework/src/modules/chain/transport/transport.js [hunk 4]
```diff
@@ -215,37 +215,32 @@ class Transport {
...
 	/**
-	 * Description of blocks.
-	 *
-	 * @todo Add @param tags
-	 * @todo Add description of the function
+	 * Returns a set of full blocks starting from the ID defined in the payload up to
+	 * the current tip of the chain.
+	 * @param {object} payload
+	 * @param {string} payload.blockId - The ID of the starting block
+	 * @return {Promise<*|Promise<*>>}
```
Comment (michielmulders) [inline framework/src/modules/chain/transport/transport.js]: What are the possible returns? `this.blocksModule.loadBlocksFromLastBlockId(payload.blockId, 34);` ?

File: framework/src/modules/chain/transport/transport.js [hunk 5]
```diff
@@ -215,37 +215,32 @@ class Transport {
...
+			payload,
+		);
 
-		try {
-			const data = await this.blocksModule.loadBlocksFromLastBlockId(
-				query.lastBlockId,
-				34, // 1977100 bytes
+		if (validationResult.length) {
+			const err = validationResult;
+			const error = `${err[0].message}: ${err[0].path}`;
```
Comment (michielmulders) [inline framework/src/modules/chain/transport/transport.js]: Manu is trying to make strict usage of only `err` throughout the code.
Can we do:
```
const error = `${validationResult[0].message}: ${validationResult[0].path}`;
```

or 

```
const errList = validationResult;
const err = `${errList[0].message}: ${errList[0].path}`;
```

Comment (michielmulders) [reply framework/src/modules/chain/transport/transport.js]: then you can do below

```
this.logger.debug(
	{
		err,
		req: payload,
	},
        ...
);

throw new Error(err);
```

File: framework/test/mocha/functional/ws/transport/transport.js [hunk 6]
```diff
@@ -127,27 +127,23 @@ describe('WS transport', () => {
...
+					data: { blockId },
 				});
-				expect(data)
-					.to.have.property('blocks')
-					.to.be.an('array');
+				expect(data).to.be.an('array');
 			});
 
-			it('using valid headers should be ok', async () => {
+			it('using a valid payload should be ok', async () => {
```
Comment (michielmulders) [inline framework/test/mocha/functional/ws/transport/transport.js]: I see it was using this `it using a valid ...` format but would be nice if we could refactor to: `it( 'should use a valid payload')`

File: framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js [hunk 7]
```diff
@@ -60,12 +63,142 @@ class BlockSynchronizationMechanism {
...
+	 * @return {Promise<void | boolean>}
+	 * @private
+	 */
+	async _requestAndApplyBlocksToCurrentChain(
+		receivedBlock,
+		lastCommonBlock,
+		peer,
+	) {
+		this.logger.debug(
+			{ peer, fromID: lastCommonBlock.id, toID: receivedBlock.id },
```
Comment (ManuGowda) [inline framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js]: whole peer object would be too much info.. only peer id?

File: framework/src/modules/chain/processor/processor.js (hunk 1 above)
Comment (limiaspasdaniel) [reply framework/src/modules/chain/processor/processor.js]: Sometimes we want to pass an optional lastBlock to statically compare two blocks (BSM)

File: framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js [hunk 8]
```diff
@@ -60,12 +63,142 @@ class BlockSynchronizationMechanism {
...
+			lastCommonBlock.id,
+			receivedBlock.id,
+		);
+		const tipBeforeApplying = cloneDeep(this.blocks.lastBlock);
+
+		if (!listOfFullBlocks.length) {
+			return this._applyPenaltyAndRestartSync(
+				peer,
+				receivedBlock,
+				new Error("Peer didn't return any block after calling getBlocksFromId"),
```
Comment (ManuGowda) [inline framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js]: Instead of an error object, how about defining error codes for the penalty?
example: PEER_PENALTY_EMPTY_BLOCKS = `code here`

File: framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js [hunk 9]
```diff
@@ -60,12 +63,142 @@ class BlockSynchronizationMechanism {
...
+			);
+		}
+
+		try {
+			await this._applyBlocksToCurrentChain(listOfFullBlocks);
+		} catch (e) {
```
Comment (ManuGowda) [inline framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js]: how about `err` instead of `e`? that way you can use { err } below in logger

File: framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js [hunk 10]
```diff
@@ -60,12 +63,142 @@ class BlockSynchronizationMechanism {
...
+			this.logger.debug(
+				{ err: e },
+				'Applying obtained blocks to the current chain failed',
```
Comment (ManuGowda) [inline framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js]: `Failed to apply blocks obtained to current chain`?

File: framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js [hunk 11]
```diff
@@ -60,12 +63,142 @@ class BlockSynchronizationMechanism {
...
+			const forkStatus = await this.processorModule.forkStatus(
+				this.blocks.lastBlock, // New tip of the chain
+				tipBeforeApplying, // Previous tip of the chain
+			);
+
+			if (!forkStatus === FORK_STATUS_DIFFERENT_CHAIN) {
+				return this._applyPenaltyAndRestartSync(
+					peer,
+					receivedBlock,
+					new Error(
```
Comment (ManuGowda) [inline framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js]: same here, using the error code?

File: framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js [hunk 12]
```diff
@@ -60,12 +63,142 @@ class BlockSynchronizationMechanism {
...
+						'New tip of the chain has no preference over the previous tip before synchronizing',
+					),
+				);
+			}
+
+			this.logger.debug('Restarting block synchronization');
```
Comment (ManuGowda) [inline framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js]: info maybe?

File: framework/src/modules/chain/synchronizer/utils.js (hunk 3 above)
Comment (limiaspasdaniel) [reply framework/src/modules/chain/synchronizer/utils.js]: Agreed

File: framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js [hunk 13]
```diff
@@ -78,6 +211,10 @@ class BlockSynchronizationMechanism {
 	 * @private
 	 */
 	async _applyPenaltyAndRestartSync(peer, receivedBlock, error) {
+		this.logger.debug(
```
Comment (ManuGowda) [inline framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js]: info?

File: framework/src/modules/chain/blocks/fork_choice_rule.js [hunk 14]
```diff
@@ -142,12 +142,17 @@ const isTieBreak = ({ slots, lastAppliedBlock, receivedBlock }) =>
...
  */
 // eslint-disable-next-line class-methods-use-this
-const isDifferentChain = (lastBlock, currentBlock) =>
-	lastBlock.prevotedConfirmedUptoHeight <
-		currentBlock.prevotedConfirmedUptoHeight ||
-	(lastBlock.height < currentBlock.height &&
-		lastBlock.prevotedConfirmedUptoHeight ===
-			currentBlock.prevotedConfirmedUptoHeight);
+const isDifferentChain = (lastBlock, currentBlock) => {
+	if (lastBlock.height === 1) return true;
```
Comment (michielmulders) [inline framework/src/modules/chain/blocks/fork_choice_rule.js]: nice one!

File: framework/src/modules/chain/blocks/schema.js [hunk 15]
```diff
@@ -54,15 +54,15 @@ const baseBlockSchema = {
 			type: 'integer',
 		},
 		totalAmount: {
-			type: 'object',
+			type: ['string', 'object'],
```
Comment (michielmulders) [inline framework/src/modules/chain/blocks/schema.js]: NOt sure why we expect or string or object? Is it not just a string?

File: framework/src/modules/chain/processor/processor.js (hunk 1 above)
Comment (michielmulders) [reply framework/src/modules/chain/processor/processor.js]: I agree on the use, but I don't like to have like business logic tied to our input parameters, feels bit odd?
this default value is more meant to be like object = {} or string = '' but`this.blocksModule.lastBlock` is really business logic and the function depends on it

Comment (limiaspasdaniel) [reply framework/src/modules/chain/processor/processor.js]: It is meant to set default values, and in this case, the last block has default value the real last block of the chain. I get your point but I don't think it is misleading.

File: framework/src/modules/chain/blocks/schema.js (hunk 15 above)
Comment (limiaspasdaniel) [reply framework/src/modules/chain/blocks/schema.js]: This is due to the fact that the function responsible to validate `amount` format accepts both object or string, therefore if only setting the type of `totalAmount` to object, when passing a `string` it was failing, so now it is actually correct and compliant with the format definition.

File: framework/src/modules/chain/block_processor_v2.js [hunk 16]
```diff
@@ -95,22 +95,14 @@ const getBytes = block => {
...
 		SIZE_INT64,
 		LITTLE_ENDIAN,
 	);
 
-	const totalFeeBuffer = intToBuffer(
-		block.totalFee.toString(),
-		SIZE_INT64,
-		LITTLE_ENDIAN,
-	);
+	const totalFeeBuffer = intToBuffer(block.totalFee, SIZE_INT64, LITTLE_ENDIAN);
```
Comment (shuse2) [inline framework/src/modules/chain/block_processor_v2.js]: I think this error was due to the deserialization timing.
All the processor logic assumes block to be deserialized, so i think this is also should be the case

File: framework/src/modules/chain/blocks/fork_choice_rule.js (hunk 14 above)
Comment (shuse2) [inline framework/src/modules/chain/blocks/fork_choice_rule.js]: As coding standard, it should be
```
if (lastBlock.height === 1) {
  return true;
}
```
Also, why if the last block height is 1, then it's different chain?

File: framework/src/modules/chain/blocks/schema.js (hunk 15 above)
Comment (shuse2) [reply framework/src/modules/chain/blocks/schema.js]: As mentioned above

File: framework/src/modules/chain/processor/processor.js (hunk 1 above)
Comment (shuse2) [reply framework/src/modules/chain/processor/processor.js]: I also agree with @michielmulders 
Default input should be static to be able to test easier.
It could be optional and assigned if not exist?

File: framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js [hunk 17]
```diff
@@ -248,7 +421,7 @@ class BlockSynchronizationMechanism {
 	async isValidFor(receivedBlock) {
 		// 2. Step: Check whether current chain justifies triggering the block synchronization mechanism
 		const finalizedBlock = await this.storage.entities.Block.getOne({
-			height_eq: this.bft.finalizedHeight,
+			height_eql: this.bft.finalizedHeight,
```
Comment (shuse2) [inline framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js]: I think we can do this?
```suggestion
			height: this.bft.finalizedHeight,
```

File: framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js [hunk 18]
```diff
@@ -60,12 +63,142 @@ class BlockSynchronizationMechanism {
...
+		this.logger.debug(
+			{
+				peerId: peer.id,
+				fromBlockId: lastCommonBlock.id,
+				toBlockId: receivedBlock.id,
+			},
+			'Requesting blocks within ID range from peer',
+		);
+
+		const listOfFullBlocks = await this._requestBlocksWithinIDs(
```
Comment (shuse2) [inline framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js]: shouldn't this loop through until we get to the last block?

File: framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js [hunk 19]
```diff
@@ -60,12 +60,140 @@ class BlockSynchronizationMechanism {
...
+		return blocks;
+	}
+
+	/**
+	 * Applies a set of blocks on top of the current chain
+	 * @param {Array<object>} blocks - An array of full blocks
+	 * @return {Promise<void>}
+	 * @private
+	 */
+	async _applyBlocksToCurrentChain(blocks) {
```
[the remark this answers is not in the document]
Comment (limiaspasdaniel) [reply framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js]: @shuse2 it is removed, Idk why Github still shows it as present

File: framework/src/modules/chain/synchronizer/errors.js [hunk 20]
```diff
@@ -0,0 +1,41 @@
+/*
+ * Copyright © 2018 Lisk Foundation
```
Comment (michielmulders) [inline framework/src/modules/chain/synchronizer/errors.js]: 2019 copyright?

File: framework/src/modules/chain/block_processor_v2.js [hunk 21]
```diff
@@ -113,7 +113,7 @@ const getBytes = block => {
 	);
 
 	const payloadLengthBuffer = intToBuffer(
-		block.payloadLength,
+		block.payloadLength.toString(),
```
Comment (shuse2) [inline framework/src/modules/chain/block_processor_v2.js]: This is number 😉
