### PR TITLE
_verifyTerminatedStateAccountsCommon doesn't need to be inside loop

### LINKED ISSUE #8998: `verifyTerminatedStateAccountsCommon` is called inside loop
### Expected behavior
- This seems to be a bug & we can take it outside of loop, i.e., 
```
for (const chainInfo of chainInfos) {
	// For each entry chainInfo in chainInfos, chainInfo.chainData.status == CHAIN_STATUS_TERMINATED
	// if and only if a corresponding entry (i.e., with chainID == chainInfo.chainID) exists in terminatedStateAccounts.
	if (chainInfo.chainData.status === ChainStatus.TERMINATED) {
		const correspondingTerminatedAccount = terminatedStateAccounts.find(
			terminatedStateAccount => terminatedStateAccount.chainID.equals(chainInfo.chainID),
		);
		if (!correspondingTerminatedAccount) {
			throw new Error(
				'For each chainInfo with status terminated there should be a corresponding entry in terminatedStateAccounts.',
			);
		}
	}
}
this._verifyTerminatedStateAccountsCommon(terminatedStateAccounts, mainchainID); // *** 
```

### Actual behavior
In current code, `_verifyTerminatedStateAccountsCommon` is called inside loop
```
for (const chainInfo of chainInfos) {
	// For each entry chainInfo in chainInfos, chainInfo.chainData.status == CHAIN_STATUS_TERMINATED
	// if and only if a corresponding entry (i.e., with chainID == chainInfo.chainID) exists in terminatedStateAccounts.
	if (chainInfo.chainData.status === ChainStatus.TERMINATED) {
		const terminatedAccount = terminatedStateAccounts.find(tAccount =>
			tAccount.chainID.equals(chainInfo.chainID),
		);
		if (!terminatedAccount) {
			throw new Error(
				'For each chainInfo with status terminated there should be a corresponding entry in terminatedStateAccounts.',
			);
		}

		this._verifyTerminatedStateAccountsCommon(terminatedStateAccounts, mainchainID); // ***
```
- Another small point
` const mainchainID = getMainchainID(mainchainInfo.chainID);` 
=> 
`const mainchainID = getMainchainID(ctx.chainID);`

### Steps to reproduce
https://github.com/LiskHQ/lips/blob/main/proposals/lip-0045.md#mainchain
> Each entry stateAccount in terminatedStateAccounts has a unique stateAccount.chainID and terminatedStateAccounts is ordered lexicographically by stateAccount.chainID. Furthermore for each entry it holds stateAccount.chainID != getMainchainID() and stateAccount.chainId[0] == getMainchainID()[0].

### Which version(s) does this affect? (Environment, OS, etc...)
git branch `release/6.0.0`

### PR DESCRIPTION
**Pull request by sitetester**
### What was the problem?

This PR resolves #8998 

### How was it solved?
Bug fixed & genesis block updated

Steps to update genesis block:
- cd lisk-sdk/examples/interop/pos-mainchain-fast
- ./bin/run genesis-block:create --output config/default/ --assets-file config/default/genesis_assets.json
- ./bin/run start --api-ipc --api-http --port 9001

Debugging tips:
- To remove existing app `rm -rf ~/.lisk/pos-mainchain-fast`
- To allow HTTP communication (via, e.g., postman)
```
nano ~/.lisk/pos-mainchain-fast/config/config.json
"rpc": {
        "modes": ["ipc", "ws", "http"],
        "allowedMethods": ["*"]
},
```
 
### How was it tested?

Relevant test added

### CODE REVIEW

**Review by ishantiw — CHANGES_REQUESTED** [review]
Looks good, 
- I think we need to pass ownChainID i.e., 

`const mainchainID = getMainchainID(ctx.chainID); `

https://github.com/LiskHQ/lisk-sdk/blob/c9c1ecc7f71b41edabb2919ced2c7c51f3192a04/framework/src/modules/interoperability/sidechain/module.ts#L293

Another small change,
- https://github.com/LiskHQ/lisk-sdk/blob/c9c1ecc7f71b41edabb2919ced2c7c51f3192a04/framework/src/modules/interoperability/base_interoperability_module.ts#L149-L152 use `BigInt(0)` for comparison 

Please include it in the same PR

File: framework/src/modules/interoperability/mainchain/module.ts [hunk 1]
```diff
@@ -367,32 +367,44 @@ export class MainchainInteroperabilityModule extends BaseInteroperabilityModule
 						'For each chainInfo with status terminated there should be a corresponding entry in terminatedStateAccounts.',
 					);
 				}
+			}
+		}
```
Comment (gkoumout) [inline framework/src/modules/interoperability/mainchain/module.ts:372]: I think current implementation is correct and according to the LIP.

However, I think that in terms of performance, we are introducing way many un-necessary loops. 

Perhaps it would have been better if we just move the call to `				this._verifyTerminatedStateAccountsCommon(terminatedStateAccounts, mainchainID);` in between the first two loops (e.g., line 357) and then leave the second for loop as it was before. 

The reason is that in the second for-loop (line 358 onwards) we loop through chainInfos and find the corresponding terminated state account, so all checks can be done at this step. 

By closing the loop and starting a new loop in line 381 all those pairs of entries in chainInfos and terminated state accounts have to be found again, which is a bit wasteful.

Comment (gkoumout) [reply framework/src/modules/interoperability/mainchain/module.ts:372]: In fact even calling the `verifyTerminatedStateAccountsCommon` is not that efficient since it introduces an un-necessary loop, but we did it for avoiding repetition and errors, so it is fine to keep it I guess..

**Review by gkoumout — CHANGES_REQUESTED** [review]

File: framework/src/modules/interoperability/mainchain/module.ts (hunk 1 above)
Comment (gkoumout) [reply framework/src/modules/interoperability/mainchain/module.ts:372]: In fact I think here is the most efficient way to do this, minimizing the number of for-loops (@ishantiw we can discuss this all together to see if we proceed):

- Remove the for-loop of lines 358-371 and perform this check in `verifyChainData`, which runs inside a loop across `chainInfos` anyways. In other words, move lines 361-370 after line 334 (with appropriate modification of variable names). This way we check the one direction of "if-and-only-if", i.e, that each chain with status terminated should have a corresponding terminated account.
- Then, during `verifyTerminatedStateAccounts`, loop *only once* through the `terminatedStateAccounts` array, as follows:  

1.  Check uniqueness of `chainID` and sorting in lexicographic order (now lines 196-211 in `_verifyTerminatedStateAccountsCommon`).
2. Loop through elements `stateAccount` of `terminatedStateAccounts` and check:2a) that there exists a corresponding entry in `chainInfo`, otherwise throw (lines 345-355 now) 2b) `verifyChainID(stateAccount.chainID)`, (now line 213 of `_verifyTerminatedStateAccountsCommon`) and then 2c) verify the validity of `stateAccount.terminatedStateAccount` as in lines 388-408.

Note this would have the exact same result, and replaces 4 loops by just 1. The only refactoring is that we don't need anymore `_verifyTerminatedStateAccountsCommon`, so we need to adjust the sidechain check as well.

**Review by ishantiw — CHANGES_REQUESTED** [review]
Overall looks fine to me, 
One issue, the comparison should be `ownChainNonce <= BigInt(0)`
https://github.com/LiskHQ/lisk-sdk/blob/24cdc25d44b35c9c406079c7c8d795bb571bd5e6/framework/src/modules/interoperability/mainchain/module.ts#L268C41-L268C54

File: framework/src/modules/interoperability/base_interoperability_module.ts [hunk 2]
```diff
@@ -189,28 +181,19 @@ export abstract class BaseInteroperabilityModule extends BaseInteroperableModule
...
-			const stateAccountWithChainID = terminatedStateAccounts[i];
-			if (!stateAccountWithChainID.chainID.equals(sortedByChainID[i].chainID)) {
-				throw new Error('terminatedStateAccounts must be ordered lexicographically by chainID.');
-			}
+		if (!objectUtils.isBufferArrayOrdered(chainIDs)) {
+			throw new Error('terminatedStateAccounts must be ordered lexicographically by chainID.');
+		}
 
-			this._verifyChainID(stateAccountWithChainID.chainID, mainchainID, 'stateAccount.');
+		for (const chainID of chainIDs) {
```
Comment (gkoumout) [inline framework/src/modules/interoperability/base_interoperability_module.ts:195]: Minor improvement comment: This could also be removed from here and call `this._verifyChainID(chainID, mainchainID, 'stateAccount.')` inside the loop of `verifyTerminatedStateAccounts` (e.g., line 366 in mainchain/module.ts and line 329 in sidechain/module.ts), since we are already running for-loops there..

**Review by gkoumout — APPROVED** [review]
Very nice, good job! Approved, with an optional small improvement suggestion.

**Review by ishantiw — APPROVED** [review]
Good work @sitetester 👏
