### PR TITLE
Stopping application shows error - Closes #5830

### LINKED ISSUE #5830: Stopping application shows error
### Expected behavior
Child process should gracefully shutdown without error

### Actual behavior
```
12:35:37 INFO lisk-framework: Controller cleanup started (module=lisk:app)
12:35:37 ERROR lisk-framework: System error: uncaughtException (module=lisk:app)
Message: Cannot read property 'writable' of undefined
 Trace: TypeError: Cannot read property 'writable' of undefined
    at PubSocket.send (/Users/lisk/.nvm/versions/node/v12.18.3/lib/node_modules/lisk-core/node_modules/pm2-axon/lib/sockets/pub.js:47:14)
    at Bus.publish (/Users/lisk/.nvm/versions/node/v12.18.3/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/controller/bus.js:115:29)
    at PullSocket.<anonymous> (/Users/lisk/.nvm/versions/node/v12.18.3/lib/node_modules/lisk-core/node_modules/lisk-framework/dist-node/controller/bus.js:51:18)
    at PullSocket.emit (events.js:315:20)
    at Parser.<anonymous> (/Users/lisk/.nvm/versions/node/v12.18.3/lib/node_modules/lisk-core/node_modules/pm2-axon/lib/sockets/sock.js:224:15)
    at Parser.emit (events.js:315:20)
    at Parser._write (/Users/lisk/.nvm/versions/node/v12.18.3/lib/node_modules/lisk-core/node_modules/amp/lib/stream.js:91:16)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Parser.Writable.write (_stream_writable.js:318:11)
12:35:37 INFO lisk-framework: Application shutdown started (module=lisk:app)
{
 "errorCode": 1,
 "message": "Cannot read property 'writable' of undefined"
}
```

### Steps to reproduce
Run plugins with child process and start and stop the application multiple times

### Which version(s) does this affect? (Environment, OS, etc...)
5.0.0-alpha.1

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?

This PR resolves #5830 

### How was it solved?

- change the order of cleanup
- add missing await

### How was it tested?

- Updated unit test

### CODE REVIEW

**Review by pablitovicente — APPROVED** [review]

File: framework/src/node/node.ts [hunk 1]
```diff
@@ -626,8 +626,7 @@ export class Node {
 			this._logger.error({ err: err as Error }, 'Failed to load delegates for forging');
 		}
 		this._forgingJob = new jobHandlers.Scheduler(async () => this._forgingTask(), forgeInterval);
-		// eslint-disable-next-line @typescript-eslint/no-floating-promises
-		this._forgingJob.start();
+		await this._forgingJob.start();
```
Comment (pablitovicente) [inline framework/src/node/node.ts:629]: This await might have been left out to avoid blocking here; maybe check with original author. Rest of PR looks good.

**Review by pablitovicente — CHANGES_REQUESTED** [review]
Still failing. So needs more research.

**Review by shuse2 — APPROVED** [review]

**Comment by shuse2** [comment]
Although this is not fixing the root problem, it is not affecting the application behavior so let's merge this PR but keep the issue open in the backlog

**Review by pablitovicente — APPROVED** [review]
