### PR TITLE
Too many self connect errors from P2P

### LINKED ISSUE #3651: P2P errors while syncing with testnet
### Expected behavior
While syncing with testnet or mainnet, the node shouldn't make too many disconnects or the other errors mentioned below.
### Actual behavior
Too many P2P errors while syncing with test network.

`14:46:17.406Z ERROR lisk-framework: Event 'rpc-request' was aborted due to a bad connection`
`14:46:13.092Z ERROR lisk-framework: Unable to match an address to the peer`
`14:46:13.073Z ERROR lisk-framework: Connection id does not match with corresponding peer`
### Steps to reproduce
Start `2.0.0-alpha.4` node with test network.
### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

### PR DESCRIPTION
**Pull request by ishantiw**
### What was the problem?

Too many self connect errors

```
09:30:35.899Z DEBUG lisk-framework: Peer disconnect event: Outbound connection of peer 134.209.90.103:5000 was closed with code 4101 and reason: Peer cannot connect to itself
09:30:35.900Z ERROR lisk-framework: Event 'rpc-request' was aborted due to a bad connection
09:30:35.900Z DEBUG lisk-framework: Socket connection closed with status code 4101 and reason: Peer cannot connect to itself
```

### How did I fix it?

Since a node is finding itself during discovery from other peers so we add it to the blacklist the first time we see it.

### How to test it?

`npm run test:integration`

### Review checklist

* The PR resolves #3651
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-p2p/src/p2p.ts [hunk 1]
```diff
@@ -406,6 +412,29 @@ export class P2P extends EventEmitter {
 						INVALID_CONNECTION_SELF_REASON,
 					);
 
+					// Ignore these steps for local network tests since all the IPs will be localhost
+					if (socket.remoteAddress !== '127.0.0.1') {
```
Comment (shuse2) [inline elements/lisk-p2p/src/p2p.ts]: Probably this is only helpful in the case of local?
maybe instead, when you check the nonce and found out it's urself, just add the the blacklist?

File: elements/lisk-p2p/src/p2p_types.ts [hunk 2]
```diff
@@ -72,7 +72,8 @@ export interface P2PClosePacket {
 }
 
 export interface P2PConfig {
-	readonly blacklistedPeers?: ReadonlyArray<P2PPeerInfo>;
+	// tslint:disable-next-line:readonly-keyword
+	blacklistedPeers: P2PPeerInfo[];
```
Comment (shuse2) [inline elements/lisk-p2p/src/p2p_types.ts]: do we need to change it here?
maybe holding instance type should be changed but not the P2P config?

File: elements/lisk-p2p/src/p2p.ts [hunk 3]
```diff
@@ -406,6 +412,29 @@ export class P2P extends EventEmitter {
...
+						const selfWSPort = queryObject.wsPort
+							? +queryObject.wsPort
+							: this._nodeInfo.wsPort;
+						const selfP2PInfo = {
+							ipAddress: socket.remoteAddress,
+							wsPort: selfWSPort,
+						};
+						// When a node tries to connect itself then add it to blacklist so that it doesn't connect itself.
+						this._config.blacklistedPeers = this._config.blacklistedPeers
```
Comment (jondubois) [inline elements/lisk-p2p/src/p2p.ts]: Maybe `blacklistedPeers` should be stored as a private property on the `P2P` class (and always use that one instead of the one on the config)? That way we don't need to mutate the config object.

**Comment by ishantiw** [comment]
As per discussion, I have added conditions after discovery and on incoming connections to avoid adding a node to itself in `newPeer` or `triedPeer` list, if exist then delete it. Adding an integration test scenario, to check whether the `peerInfo` update is applied properly in all the other nodes and update their `newPeer`, `triedPeer` or `connectedPeer` list if exist.

**Comment by ishantiw** [comment]
Added scenario to check itself in both p2p-lib and functional test of the framework
