### PR TITLE
Spellcheck and fix the grammatical errors - Closes #5746

### LINKED ISSUE #5746: Spellcheck and fix the grammatical errors
### Expected behavior

For better readability and clean code, majority of the grammatical errors must be addressed.

### Actual behavior

There are multiple files with grammatical errors

### Steps to reproduce

Go through each file or use any tool to list down all errors.

### Which version(s) does this affect? (Environment, OS, etc...)
5.0

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?

This PR resolves #5746 

### How was it solved?

Update variable naming and comments to fix typo

### How was it tested?

NA

### CODE REVIEW

File: elements/lisk-chain/src/state_store/account_store.ts [hunk 1]
```diff
@@ -126,7 +126,7 @@ export class AccountStore {
 	}
 
 	public async del(address: Buffer): Promise<void> {
-		// If account is nither in memory or DB, it should not be able to delete
+		// If account is either in memory or DB, it should not be able to delete
```
Comment (shuse2) [inline elements/lisk-chain/src/state_store/account_store.ts:129]:
```suggestion
		// If account is neither in memory nor DB, it should not be able to delete
```

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: elements/lisk-chain/test/unit/chain.spec.ts [hunk 2]
```diff
@@ -409,12 +409,12 @@ describe('chain', () => {
 				.mockResolvedValue(validatorBuffer as never);
 		});
 
-		it('should return current a validator based on the timestamp and round robin from genesis timestap', async () => {
+		it('should return current a validator based on the timestamp and round robin from genesis timestamp', async () => {
```
Comment (pablitovicente) [inline elements/lisk-chain/test/unit/chain.spec.ts:412]:
```suggestion
		it('should return current validator based on the timestamp and round robin from genesis timestamp', async () => {
```

File: elements/lisk-chain/test/unit/chain.spec.ts [hunk 3]
```diff
@@ -409,12 +409,12 @@ describe('chain', () => {
...
 			const validator = await chainInstance.getValidator(genesisBlock.header.timestamp);
 			expect(validator.address).toEqual(validators[0].address);
 		});
 
-		it('should return current a validator based on the timestamp and round robin from genesis timestap with offset 5', async () => {
+		it('should return current a validator based on the timestamp and round robin from genesis timestamp with offset 5', async () => {
```
Comment (pablitovicente) [inline elements/lisk-chain/test/unit/chain.spec.ts:417]:
```suggestion
		it('should return current validator based on the timestamp and round robin from genesis timestamp with offset 5', async () => {
```

**Review by shuse2 — APPROVED** [review]

**Review by pablitovicente — APPROVED** [review]
