### PR TITLE
No call to token.mint when reward is zero - Closes #7388

### LINKED ISSUE #7388: Node crashes when running dpos-mainchain example
### Expected behavior

The node should run without crash and should be able to forge blocks if enabled.

### Actual behavior

Currently when we run a node (example/dpos-mainchain)
The node crashes with following error,
```ts
15:34:30 ERROR lisk-framework: Fail to respond (module=lisk:app)
Message: Amount 0 does not satisfy min balance requirement.
 Trace: Error: Amount 0 does not satisfy min balance requirement.
    at TokenAPI.mint (/Users/ishantiwari/lisk-repos/sdk/node2/lisk-sdk/framework/src/modules/token/api.ts:222:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RewardModule.afterTransactionsExecute (/Users/ishantiwari/lisk-repos/sdk/node2/lisk-sdk/framework/src/modules/reward/module.ts:102:3)
    at StateMachine.afterExecuteBlock (/Users/ishantiwari/lisk-repos/sdk/node2/lisk-sdk/framework/src/state_machine/state_machine.ts:254:5)
    at ABIHandler.afterTransactionsExecute (/Users/ishantiwari/lisk-repos/sdk/node2/lisk-sdk/framework/src/abi_handler/abi_handler.ts:387:3)
    at ABIServer._listenToRequest (/Users/ishantiwari/lisk-repos/sdk/node2/lisk-sdk/framework/src/abi_handler/abi_server.ts:198:18)
{
 "method": "afterTransactionsExecute"
}
/Users/ishantiwari/lisk-repos/sdk/node2/lisk-sdk/framework/dist-node/abi_handler/abi_client.js:141
                deferred.reject(new Error(response.error.message));
                                ^

Error: Amount 0 does not satisfy min balance requirement.
    at ABIClient._listenToRPCResponse (/Users/ishantiwari/lisk-repos/sdk/node2/lisk-sdk/framework/dist-node/abi_handler/abi_client.js:141:33)
15:34:30 ERROR lisk-framework: Engine exited unexpectedly (module=lisk:app)
{
 "code": 1,
 "signal": ""
}
15:34:30 INFO lisk-framework: Application shutdown started (module=lisk:app)
{
 "errorCode": 1,
 "message": "process.exit"
}
```

### Steps to reproduce

`examples/dpos-mainchain/bin/run start --api-ipc --port 5002`

### Which version(s) does this affect? (Environment, OS, etc...)

`development`

### PR DESCRIPTION
**Pull request by ishantiw**
- When reward is zero we should not call token.mint API, we only call it when reward is > 0

### What was the problem?

This PR resolves #7388

### How was it solved?

[🐛 No call to token.mint when reward is zero](https://github.com/LiskHQ/lisk-sdk/commit/18efd13f447252315acdd071b5a7cb9a5eac7ef5)

### How was it tested?

- Run `examples/dpos-mainchain/bin/run start --api-ipc --port 5002`
- Test should pass under `framework/test/unit/modules/reward/reward_module.spec.ts`

### CODE REVIEW

File: framework/src/modules/reward/module.ts [hunk 1]
```diff
@@ -99,12 +99,14 @@ export class RewardModule extends BaseModule {
...
-			blockReward,
-		);
+		if (blockReward !== BigInt(0)) {
+			await this._tokenAPI.mint(
+				context.getAPIContext(),
+				context.header.generatorAddress,
+				this._tokenID,
+				blockReward,
+			);
+		}
```
Comment (shuse2) [inline framework/src/modules/reward/module.ts:109]: I think if the reward is not minted, event also doesn't make much sense?

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: framework/src/modules/reward/module.ts (hunk 1 above)
Comment (ishantiw) [reply framework/src/modules/reward/module.ts:109]: hmm I think event data will never contain, for ex, `REWARD_REDUCTION_SEED_REVEAL` as the reward can be zero and will never emit an event?

**Review by shuse2 — APPROVED** [review]

**Review by mitsuaki-u — APPROVED** [review]
