### PR TITLE
Fix maxHeightPrevoted to be initialized with the genesis height - Closes #5893

### LINKED ISSUE #5893: BFT should initialize maxHeightPrevoted to genesis block height
### Expected behavior
`maxHeightPrevoted` should be initialized with genesis block height, which might not be 0

### Actual behavior
Currently it is initializing with `0`

### Which version(s) does this affect? (Environment, OS, etc...)
5.0.0-alpha.2

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #5893 

### How was it solved?

- Update to use finzlied height when prevote does not exist. When prevote does not exist, finalizedHeight should be the height at the genesis block. Therefore, indirectly it is setting to the genesis block height

### How was it tested?

- Add unit test to see if it will be initialized

### CODE REVIEW

File: elements/lisk-bft/src/finality_manager.ts [hunk 1]
```diff
@@ -411,27 +411,17 @@ export class FinalityManager extends EventEmitter {
...
-		const preVoted = highestHeightPreVoted ? parseInt(highestHeightPreVoted, 10) : 0;
-
-		const highestHeightPreCommitted = Object.keys(ledger)
-			.reverse()
-			.find(key => ledger[key].preCommits >= this.preCommitThreshold);
-
-		const preCommitted = highestHeightPreCommitted ? parseInt(highestHeightPreCommitted, 10) : 0;
-
-		return { preVoted, preCommitted };
+		return highestHeightPreVoted ? parseInt(highestHeightPreVoted, 10) : this.finalizedHeight;
```
Comment (ManuGowda) [inline elements/lisk-bft/src/finality_manager.ts:424]:
```suggestion
		return chainMaxHeightPreVoted ? parseInt(chainMaxHeightPreVoted, 10) : this.finalizedHeight;
```

File: elements/lisk-bft/src/finality_manager.ts [hunk 2]
```diff
@@ -411,27 +411,17 @@ export class FinalityManager extends EventEmitter {
...
-
-		return preVoted;
+		return this._calculateMaxHeightPrevoted(ledger);
 	}
 
-	private _getChainMaxHeightStatus(ledger: LedgerMap): { preVoted: number; preCommitted: number } {
+	private _calculateMaxHeightPrevoted(ledger: LedgerMap): number {
 		debug('updatePreVotedAndFinalizedHeight invoked');
 
 		const highestHeightPreVoted = Object.keys(ledger)
```
Comment (ManuGowda) [inline elements/lisk-bft/src/finality_manager.ts:420]:
```suggestion
		const chainMaxHeightPreVoted = Object.keys(ledger)
```

File: elements/lisk-bft/src/finality_manager.ts (hunk 1 above)
Comment (shuse2) [reply elements/lisk-bft/src/finality_manager.ts]: Updated to `maxHeightPrevoted` since thats the name we use everywhere else

File: elements/lisk-bft/src/finality_manager.ts [hunk 3]
```diff
@@ -411,27 +411,17 @@ export class FinalityManager extends EventEmitter {
...
-		const preVoted = highestHeightPreVoted ? parseInt(highestHeightPreVoted, 10) : 0;
-
-		const highestHeightPreCommitted = Object.keys(ledger)
-			.reverse()
-			.find(key => ledger[key].preCommits >= this.preCommitThreshold);
-
-		const preCommitted = highestHeightPreCommitted ? parseInt(highestHeightPreCommitted, 10) : 0;
-
-		return { preVoted, preCommitted };
+		return maxHeightPreVoted ? parseInt(maxHeightPreVoted, 10) : this.finalizedHeight;
```
Comment (janhack) [inline elements/lisk-bft/src/finality_manager.ts:424]: I don't fully understand the code:
- Why is `maxHeightPreVoted` a string and needs to be pared and not a number?
- Do I return this.finalizedHeight if maxHeightPreVoted is undefined?
- The `finalizedHeight` is part of the state and initialized with the height of the genesis block, right? The `maxHeightPrevoted` is not part of the state and always computed from scratch?
- In the prototype implementation `maxHeightPrevoted` together with `finalizedHeight` is maintained as part of the state. The update works as follows: Go over the last 303 block headers and checking and if for any of them the prevotes/precommits and update if the height is larger. If you only store the `finalizedHeight` explicitly, you will have to go over all block headers from `finalizedHeight` onwards (this number can be arbitrarily large, e.g., 10,000). Does this happen here? 
-

Comment (janhack) [reply elements/lisk-bft/src/finality_manager.ts:424]: Cosmetic remark: The camelCase is a bit inconsistent, sometimes prevote and sometimes preVote. Note that the LIP uses prevote and precommit as one work in lower case.

Comment (janhack) [reply elements/lisk-bft/src/finality_manager.ts:424]: Another remark: Why are there two methods `getMaxHeightPrevoted` and `_calculateMaxHeightPrevoted`? The second method is called directly as well, but before the call it seems the same things happens as in  `getMaxHeightPrevoted`.

Comment (shuse2) [reply elements/lisk-bft/src/finality_manager.ts:424]: > Why is maxHeightPreVoted a string and needs to be parsed and not a number?

Node.js object key is always a string even though we assign a number. Therefore, it needs to be parsed.

> Do I return this.finalizedHeight only if maxHeightPreVoted is undefined? Does this happen only if there is no block which reaches the prevoteThreshold?

yes. maxHeightPrevoted is undefined only if there is no block height which is above prevoteThreshold.

> The finalizedHeight is part of the state and initialized with the height of the genesis block, right? The maxHeightPrevoted is not part of the state and always computed from scratch?

> In the prototype implementation maxHeightPrevoted together with finalizedHeight is maintained as part of the state. The update works as follows: Go over the last 303 block headers, check if for any of them the prevotes/precommits threshold is reach and update if the height is larger. If you only store the finalizedHeight explicitly, you will have to go over all block headers from finalizedHeight onwards (this number can be arbitrarily large, e.g., 10,000). Does this happen here?

prevotes/precommits are also stored as state until finalized height. it's called `ledger` in the code. the structure is like
```
{
  ${height}: {
    preVotes: number,
    preCommits: number,
  }
}
```
so moving back and forward is managed along with account state.

Comment (shuse2) [reply elements/lisk-bft/src/finality_manager.ts:424]: `_calculateMaxHeightPrevoted` is used in 2 different places, so that's why it is extracted to private method

**Review by janhack — APPROVED** [review]
Looks good.

**Review by ManuGowda — APPROVED** [review]
