### PR TITLE
Wrong attribute description in app config schema #4167

### LINKED ISSUE #4167: Wrong attribute description in app config schema
### Expected behavior
I expect the description of attributes in app config schema to be correct

### Actual behavior
The attribute `app.genesisConfig.REWARDS.OFFSET: 2160` says `Start rewards at first block of the second round` but it actually represents the 39th block of the 22nd round in a network with 101 active delegates.

### Steps to reproduce
https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/controller/schema/application_config_schema.js#L197

### Which version(s) does this affect? (Environment, OS, etc...)
`development`

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?
Application config rewards description was incorrect
### How did I solve it?
```
Rewards starts at 2160-(101*21)=39

Where 2160 is the reward offset, 101 delegates, 21st round
```
Updated the description
### Review checklist

- [ ] The PR resolves #4167 
- [ ] All new code is covered with unit tests
- [ ] Relevant integration / functional tests are added
- [ ] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [ ] Documentation has been added/updated

### CODE REVIEW

File: framework/src/controller/schema/application_config_schema.js [hunk 1]
```diff
@@ -202,7 +202,7 @@ module.exports = {
 						'200000000', // Milestone 3
 						'100000000', // Milestone 4
 					],
-					OFFSET: 2160, // Start rewards at first block of the second round
+					OFFSET: 2160, // Start rewards at 39th block of 21st round
```
Comment (lsilvs) [inline framework/src/controller/schema/application_config_schema.js]:
```suggestion
					OFFSET: 2160, // Start rewards at 39th block of 22nd round
```
