### PR TITLE
Fix transaction create logic to resolve name properly - Closes #6006

### LINKED ISSUE #6006: lisk-api-client does not resolve asset name
### Expected behavior
APIClient should be able to create transaction from the asset name

### Actual behavior
API client cannot create transaction from asset name

### Steps to reproduce
```
const fundTx = await client.transaction.create({
			moduleName: 'token',
			assetName: 'transfer',
			nonce: genesisNonce,
			fee,
			asset: {
				amount: BigInt(200000000),
				recipientAddress: sender.address,
				data: '',
			},
		}, genesisPassphrase);
console.log(fundTx);
```

### Which version(s) does this affect? (Environment, OS, etc...)
5.0-

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #6006 

### How was it solved?

- Fix the logic to properly use the correct value

### How was it tested?

- Added test
- Execute the sample in #6006 and see if the result has assetID

### CODE REVIEW

**Review by Incede — COMMENTED** [review]
LGTM

**Review by Incede — APPROVED** [review]

File: elements/lisk-api-client/src/transaction.ts [hunk 1]
```diff
@@ -83,16 +83,28 @@ export class Transaction {
 			const registeredModule = this._nodeInfo.registeredModules.find(
 				module => module.name === input.moduleName,
 			);
-			txInput.moduleID = registeredModule?.id ? registeredModule.id : txInput.moduleID;
+			if (!registeredModule) {
+				throw new Error(`Module corresponding to name ${txInput.moduleName} not found.`);
```
Comment (ManuGowda) [inline elements/lisk-api-client/src/transaction.ts:87]:
```suggestion
				throw new Error(`Module corresponding to name ${txInput.moduleName} not registered.`);
```

File: elements/lisk-api-client/src/transaction.ts [hunk 2]
```diff
@@ -83,16 +83,28 @@ export class Transaction {
...
 				throw new Error('Missing assetID and assetName');
 			}
-			const registeredAsset = this._nodeInfo.registeredModules.find(
-				asset => asset.name === input.assetName,
+			const registeredModule = this._nodeInfo.registeredModules.find(
+				m => m.id === txInput.moduleID,
 			);
-			txInput.assetID = registeredAsset?.id ? registeredAsset.id : txInput.assetID;
+			if (!registeredModule) {
+				throw new Error(`Module corresponding to id ${txInput.moduleID} not found.`);
```
Comment (ManuGowda) [inline elements/lisk-api-client/src/transaction.ts:99]:
```suggestion
				throw new Error(`Module corresponding to id ${txInput.moduleID} not registered.`);
```

File: elements/lisk-api-client/src/transaction.ts [hunk 3]
```diff
@@ -83,16 +83,28 @@ export class Transaction {
...
+			}
+			const registeredAsset = registeredModule.transactionAssets.find(
+				asset => asset.name === txInput.assetName,
+			);
+			if (!registeredAsset) {
+				throw new Error(`Asset corresponding to name ${txInput.assetName} not found.`);
```
Comment (ManuGowda) [inline elements/lisk-api-client/src/transaction.ts:105]:
```suggestion
				throw new Error(`Asset corresponding to name ${txInput.assetName} not registered.`);
```

File: elements/lisk-api-client/test/unit/transaction.spec.ts [hunk 4]
```diff
@@ -121,6 +121,28 @@ describe('transaction', () => {
...
 			});
 
+			describe('when called with module name which does not exist', () => {
+				it('should throw error', async () => {
+					await expect(
+						transaction.create(
+							{ ...validTransaction, moduleID: undefined, moduleName: 'newModule' },
+							passphrase1,
+						),
+					).rejects.toThrow('Module corresponding to name newModule not found.');
```
Comment (ManuGowda) [inline elements/lisk-api-client/test/unit/transaction.spec.ts:131]:
```suggestion
					).rejects.toThrow('Module corresponding to name newModule not registered.');
```

File: elements/lisk-api-client/test/unit/transaction.spec.ts [hunk 5]
```diff
@@ -121,6 +121,28 @@ describe('transaction', () => {
...
+			});
+
+			describe('when called with asset name which does not exist', () => {
+				it('should throw error', async () => {
+					await expect(
+						transaction.create(
+							{ ...validTransaction, assetID: undefined, assetName: 'newAsset' },
+							passphrase1,
+						),
+					).rejects.toThrow('Asset corresponding to name newAsset not found.');
```
Comment (ManuGowda) [inline elements/lisk-api-client/test/unit/transaction.spec.ts:142]:
```suggestion
					).rejects.toThrow('Asset corresponding to name newAsset not registered.');
```

**Review by ManuGowda — APPROVED** [review]
