### PR TITLE
Resolve relative root path - Closes #6035

### LINKED ISSUE #6035: Relative rootPath keeps node from booting
### Expected behavior
When configuring a node with rootPath: './store' the node data should store in the project root/store folder and run.

### Actual behavior
When configuring a node with rootPath: './store' the node will hang on the loading controller step. It creates the store folder but the node won't start.

### Steps to reproduce
Configure an application with configuration argument rootPath: './store'

### Which version(s) does this affect? (Environment, OS, etc...)
SDK V5, experienced on Mac and Debian

### PR DESCRIPTION
**Pull request by Incede**
### What was the problem?

This PR resolves #6035 

### How was it solved?

* Add logic to resolve root path while creating system directories

### How was it tested?

* Updated unit tests
* Tested manually 
```
config.rootPath = './store';
app = Application.defaultApplication(genesisBlock, config);
app.run();
```

### CODE REVIEW

File: framework/src/system_dirs.ts [hunk 1]
```diff
@@ -16,10 +16,10 @@ import * as path from 'path';
...
-	tmp: path.join(rootPath, appLabel, 'tmp'),
-	logs: path.join(rootPath, appLabel, 'logs'),
-	sockets: path.join(rootPath, appLabel, 'tmp', 'sockets'),
-	pids: path.join(rootPath, appLabel, 'tmp', 'pids'),
+	dataPath: path.resolve(rootPath, appLabel),
+	data: path.resolve(rootPath, appLabel, 'data'),
+	tmp: path.resolve(rootPath, appLabel, 'tmp'),
+	logs: path.resolve(rootPath, appLabel, 'logs'),
+	sockets: path.resolve(rootPath, appLabel, 'tmp', 'sockets'),
+	pids: path.resolve(rootPath, appLabel, 'tmp', 'pids'),
```
Comment (nazarhussain) [inline framework/src/system_dirs.ts:24]: Problem using this approach is that if ever `appLabel` got `/` in start it will skip the `rootPath` completely. e.g. 

```
path.resolve('/root/path', 'data', 'second/dir', '/third/dir`) 
```

The above will not result `/root/path/data/second/dir/third/dir` instead it will just return `/third/dir`.

So I would suggest to use `path.join` first and then use single value for `path.resolve` to get absolute path.

File: framework/test/unit/application.spec.ts [hunk 2]
```diff
@@ -668,6 +668,7 @@ describe('Application', () => {
 		let _nodeDBSpy: jest.SpyInstance<any, unknown[]>;
 
 		beforeEach(async () => {
+			config.rootPath = '/lisk';
```
Comment (nazarhussain) [inline framework/test/unit/application.spec.ts:671]: May be instead of changing current ones, we should add a new tests case particularly for absolute root path.

File: framework/test/unit/controller/controller.spec.ts [hunk 3]
```diff
@@ -74,7 +74,7 @@ describe('Controller Class', () => {
 		publish: jest.fn(),
 	};
 	const config = {
-		rootPath: '~/.lisk',
+		rootPath: '/lisk',
```
Comment (nazarhussain) [inline framework/test/unit/controller/controller.spec.ts:77]: Same here.

**Review by nazarhussain — CHANGES_REQUESTED** [review]

File: framework/src/system_dirs.ts (hunk 1 above)
Comment (Incede) [reply framework/src/system_dirs.ts:24]: @shuse2 any suggestions ?

Comment (shuse2) [reply framework/src/system_dirs.ts:24]: ah i also see the problem
i think we can do like
```
dataPath: path.resolve(path.join(rootPath, appLabel)),
```

File: framework/src/application.ts [hunk 4]
```diff
@@ -140,7 +139,6 @@ export class Application {
 			config.label ?? `lisk-${config.genesisConfig?.communityIdentifier}`;
 
 		const mergedConfig = objects.mergeDeep({}, appConfig, config) as ApplicationConfig;
```
Comment (shuse2) [inline framework/src/application.ts:141]: i think in this file there are place that uses `rootPath` directly

Comment (nazarhussain) [reply framework/src/application.ts:141]: I believe whenever rootPath is directly passed the inner function either logger or controller uses the system dir to get the correct path. So that will work.

**Review by nazarhussain — DISMISSED** [review]

**Review by shuse2 — APPROVED** [review]

**Review by shuse2 — APPROVED** [review]

**Review by shuse2 — APPROVED** [review]

**Review by nazarhussain — APPROVED** [review]
