### PR TITLE
Remove internal peer info from API get peers' output - Closes #4508

### LINKED ISSUE #4508: API peers should hide internal state information
### Expected behavior
API get peers endpoint should not show internal fields (`nonce`, `blockVersion`, `maxHeightPrevoted`, `lastBlockId`).
### Actual behavior
```
{
"ip": "82.196.5.152",
"height": 475,
"os": "linux4.15.0-70-generic",
"version": "3.0.0-alpha.1",
"httpPort": 4000,
"protocolVersion": "2.0",
"blockVersion": 2,
"maxHeightPrevoted": 407,
"lastBlockId": "6569507740839559794",
"state": 2,
"nonce": "9e7fb782da3019c5",
"wsPort": 5000
}
```
### Steps to reproduce
http://devnet-seed-01.liskdev.net:4000/api/peers
### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0-alpha.1

### PR DESCRIPTION
**Pull request by diego-G**
### What was the problem?
Endpoint `/api/peers` reveals internal peer information

### How did I solve it?
By filtering the internal peer information

### How to manually test it?
- Start two nodes, add seed peer info to discover
- Check endpoint `/api/peers` and validate the internal peer information is not exposed
### Review checklist

- [x] The PR resolves #4508
- [x] All new code is covered with unit tests
- [x] Relevant integration / functional tests are added
- [x] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [x] Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/http_api/helpers/utils.js [hunk 1]
```diff
@@ -139,12 +139,32 @@ const filterByParams = (peers, filters) => {
...
+		const {
+			ipAddress,
+			options,
+			minVersion,
+			nethash,
+			nonce,
+			blockVersion,
+			maxHeightPrevoted,
+			lastBlockId,
+			...peerWithoutIp
```
Comment (lsilvs) [inline framework/src/modules/http_api/helpers/utils.js]: Does this var name still name sense? It will be the peer object without all the above properties and not only `ip`
