### PR TITLE
wait_for helper not updated when changing status endpoint - Closes #4553

### LINKED ISSUE #4553: wait_for helper not updated when changing status endpoint
### Expected behavior

wait_for works correctly for tests

### Actual behavior

wait_for is using the property `res.data.loaded` from calling `/api/node/status` but that property was removed by #4544 

### Steps to reproduce

try to run `npm run mocha:functional:post test/mocha/functional/http/post/0.transfer.js` locally

### PR DESCRIPTION
**Pull request by pablitovicente**
### What was the problem?

`wait_for` not updated when removing properties from `/api/node/status`

### How did I solve it?

by using a different property in `wait_for` to check for the HTTP API

### Review checklist

- [ ] The PR resolves #4553
- [ ] All new code is covered with unit tests
- [ ] Relevant integration / functional tests are added
- [ ] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [ ] Documentation has been added/updated

### CODE REVIEW

File: framework/test/mocha/common/utils/wait_for.js [hunk 1]
```diff
@@ -58,7 +58,7 @@ function blockchainReady(retries, timeout, baseUrl, doNotLogRetries, cb) {
 			.then(res => {
 				retries -= 1;
 				res = JSON.parse(res.body);
-				if (!res.data.loaded && retries >= 0) {
+				if (res.data.syncing && retries >= 0) {
```
Comment (shuse2) [inline framework/test/mocha/common/utils/wait_for.js]: i think it should check like `res.data.syncing === undefined || res.data.syncing === null`?

Comment (pablitovicente) [reply framework/test/mocha/common/utils/wait_for.js]: I think this value in the context of tests is always false and never undefined or null
