### PR TITLE
Fix chain connector failing unit test

### LINKED ISSUE #8213: Fix chain connector plugin failing unit test
### Expected behavior
All unit tests should pass

### Actual behavior
The `should throw error when no validators data is found for the new certificate height` is failing

### Steps to reproduce
`yarn test` on the dev branch with sha 27ac3c3ce8c0c08b5bff7c24a562640341729261

### PR DESCRIPTION
**Pull request by mosmartin**
### What was the problem?

This PR resolves #8213

### How was it solved?

- Refactored the `inbox_update` test
- Refactored the `chain_connector_plugin`

### How was it tested?

Existing tests are passing ✅

### CODE REVIEW

File: framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts [hunk 1]
```diff
@@ -282,7 +282,7 @@ export class ChainConnectorPlugin extends BasePlugin<ChainConnectorPluginConfig>
 		 */
 		const lastSentCCM = (await this._chainConnectorStore.getLastSentCCM()) ?? {
 			nonce: BigInt(0),
-			height: this._lastCertificate.height,
+			height: this._lastCertificate?.height,
```
Comment (ishantiw) [inline framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:285]: is this really throwing the error? coz at this point in the code lastCertificate should exist

Comment (ishantiw) [reply framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:285]: we check for lastCertificate on L209 :) but I think we can still keep this change if its throwing warning or something

**Review by ishantiw — APPROVED** [review]

File: framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts (hunk 1 above)
Comment (shuse2) [reply framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:285]: i think it shouldn't throw error or warning because it's defined as
```
private _lastCertificate!: LastCertificate;
```
the code wise it looks strange to allow `height: undefined`

File: framework-plugins/lisk-framework-chain-connector-plugin/test/unit/inbox_update.spec.ts [hunk 2]
```diff
@@ -86,6 +86,7 @@ describe('inboxUpdate', () => {
 			},
 			messageFeeTokenID: Buffer.from('04000001', 'hex'),
 			partnerChainOutboxRoot: Buffer.alloc(2),
+			minReturnFeePerByte: BigInt(0),
```
Comment (shuse2) [inline framework-plugins/lisk-framework-chain-connector-plugin/test/unit/inbox_update.spec.ts:89]: this seems to be required change, but im not sure why it was not caught in the test run or in action

File: framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts (hunk 1 above)
Comment (mosmartin) [reply framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:285]: image


error on this line

Comment (mosmartin) [reply framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:285]: Ahh even better solution 🙂

File: framework-plugins/lisk-framework-chain-connector-plugin/test/unit/inbox_update.spec.ts (hunk 2 above)
Comment (mosmartin) [reply framework-plugins/lisk-framework-chain-connector-plugin/test/unit/inbox_update.spec.ts:89]: Baffled me as well especially since `minReturnFeePerByte` is not an optional property in the interface.

File: framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts (hunk 1 above)
Comment (mosmartin) [reply framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:285]: Hi @shuse2 , I've updated the package.json scripts but getting the same failed message. Is there any other test setup that's off that I should have a look at? The `height` is still coming in as `undefined`.

Comment (shuse2) [reply framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:285]: not only the package.json, but you need to fix the test. (I think in this case, test setup is wrong)

**Review by shuse2 — APPROVED** [review]
