### PR TITLE
Remove interoperability_getInteroperabilityStore endpoint

### LINKED ISSUE #7466: Remove interoperability_getInteroperabilityStore endpoint
### Expected behavior

We should not expose protected or private functions from endpoints

### Actual behavior

We expose protected function `getInteroperabilityStore` in the interoperability endpoint which we should modify to be private function

### Steps to reproduce

Run `examples/dpos-mainchain` and see logs for exposed endpoints

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-alpha`

### PR DESCRIPTION
**Pull request by sitetester**
### What was the problem?

This PR resolves #7466

### How was it solved?
`getInteroperabilityStore` method from concrete & abstract class is replaced with a private method in `abstract` class

### How was it tested?
- `cd /lisk-sdk/examples/dpos-mainchain/`
-  `./bin/run start --api-ipc` (it shouldn't show registered endpoints in logs like this)

```bash
18:00:20 INFO lisk-framework: Starting controller (module=lisk:app)
18:00:20 INFO lisk-framework: [
  'app_getRegisteredActions',
  'app_getRegisteredEvents',
  'auth_getAuthAccount',
  'auth_isValidSignature',
  'auth_isValidNonce',
  'validators_validateBLSKey',
  'validators_getValidator',
  'token_getBalances',
  'token_getBalance',
  'token_getTotalSupply',
  'token_getSupportedTokens',
  'token_getEscrowedAmounts',
  'reward_getDefaultRewardAtHeight',
  'random_isSeedRevealValid',
  'dpos_getVoter',
  'dpos_getDelegate',
  'dpos_getAllDelegates',
  'dpos_getConstants'
] Application ready for endpoints (module=lisk:app)
```

### CODE REVIEW

File: framework/src/modules/interoperability/base_interoperability_endpoint.ts [hunk 1]
```diff
@@ -31,19 +31,22 @@ import { TerminatedOutboxAccountJSON } from './stores/terminated_outbox';
 import { BaseInteroperabilityStore } from './base_interoperability_store';
 import { chainAccountToJSON } from './utils';
 import { ImmutableStoreGetter, StoreGetter } from '../base_store';
+import { MainchainInteroperabilityStore } from './mainchain/store';
+import { SidechainInteroperabilityStore } from './sidechain/store';
```
Comment (ishantiw) [inline framework/src/modules/interoperability/base_interoperability_endpoint.ts:35]: hmm its better if we don't reference to Mainchain or sidechain as they are derived from these base classes, else the base class will depend on these classes that derived.
Maybe we can switch to instance member property instead of member?
Something like,
```ts
protected abstract getInteroperabilityStore: (context: StoreGetter | ImmutableStoreGetter) => T;
```

**Review by ishantiw — CHANGES_REQUESTED** [review]
Make sure base classes don't depend on mainchain/sidechain classes

**Review by ishantiw — APPROVED** [review]

**Review by mitsuaki-u — APPROVED** [review]
