### PR TITLE
Fixes NFTEndpoint.getNFT for  escrowed NFTs

### LINKED ISSUE #8714: NFTEndpoint.getNFT endpoint fails if NFT is escrowed
### Expected behavior
NFTEndpoint.getNFT should return NFT details without the `lockingModule` field if NFT is escrowed else it should return `lockingModule` from `UserStore`. 

### Actual behavior
NFTEndpoint.getNFT fails if the provided NFT is escrowed.

### Steps to reproduce
Call nft_getNFT endpoint for an escrowed NFT.

### Which version(s) does this affect? (Environment, OS, etc...)
`feature/6917-implement-nft-module` branch.

### PR DESCRIPTION
**Pull request by has5aan**
### What was the problem?

This PR resolves #8714 

### How was it solved?

Modifies `NFT` type to have a nullable `lockingModule` field and updates `NFTEndpoint.getNFT` to return NFT details for escrowed NFT.

Calls `NFTEndpoint.addDependencies` from `NFTModule.addDependencies`.

### How was it tested?

Implemented unit tests.

### CODE REVIEW

File: framework/src/modules/nft/endpoint.ts [hunk 1]
```diff
@@ -111,18 +111,28 @@ export class NFTEndpoint extends BaseEndpoint {
...
 
 		return {
 			owner: nftData.owner.toString('hex'),
 			attributesArray: nftData.attributesArray.map(attribute => ({
 				module: attribute.module,
 				attributes: attribute.attributes.toString('hex'),
 			})),
-			lockingModule: userData.lockingModule,
 		};
 	}
```
Comment (mjerkov) [inline framework/src/modules/nft/endpoint.ts:137]: Is it possible to optimize this code and do the check `if (nftData.owner.length === LENGTH_ADDRESS)` immediately before returning the `lockingModule`? As it is now, it looks a bit duplicated. Just a minor comment

**Review by mjerkov — APPROVED** [review]
Looks good to me, just one minor comment

**Review by Incede — APPROVED** [review]
