### PR TITLE
Remove caching for max height prevoted - Closes #5506

### LINKED ISSUE #5506: While syncing it fails to process block because of maxHeightPrevoted
### Expected behavior
With 2 local nodes without malicious code, it should successfully sync to each other

### Actual behavior
```
18:37:05 ERROR lisk-framework: Block processing failed (module=lisk:app)
Message: Wrong maxHeightPrevoted in blockHeader. maxHeightPrevoted: 344, : 447
 Trace: Error: Wrong maxHeightPrevoted in blockHeader. maxHeightPrevoted: 344, : 447
    at FinalityManager.verifyBlockHeaders (/lisk-sdk/elements/lisk-bft/src/finality_manager.ts:388:10)
    at BFT.verifyNewBlock (/lisk-sdk/elements/lisk-bft/src/bft.ts:116:31)
    at BlockProcessorV2.verify.pipe.async.block.block (/lisk-sdk/framework/src/application/node/block_processor_v2.ts:172:20)
    at Pipeline.run (/lisk-sdk/framework/src/application/node/processor/pipeline.ts:64:25)
    at Processor._processValidated (/lisk-sdk/framework/src/application/node/processor/processor.ts:348:3)
    at Sequence._tick (/lisk-sdk/framework/src/application/node/utils/sequence.ts:98:19)
    at Timeout.nextSequence [as _onTimeout] (/lisk-sdk/framework/src/application/node/utils/sequence.ts:63:4)
```

### Steps to reproduce
- Run a forging node and let it forge more than 1000 blocks
- From another node, Sync to the node from scratch 
- After a while it fails with above error

### Which version(s) does this affect? (Environment, OS, etc...)
5.0-

### LINKED ISSUE #5507: Fail to reload temp blocks because of maxPrevoteHeight
### Expected behavior
Once syncing fails, it should successfully reload from the temp blocks saved.
This issue could be related to #5506 

### Actual behavior
```
18:37:06 DEBUG lisk-framework: Restoring blocks from temporary table (module=lisk:app)
18:37:06 DEBUG lisk-framework: Processing validated block (module=lisk:app)
{
 "id": "eZ0wOFv+LzXc5cFXCGnxjXtuQK0PQtpS1t/qqKZqMEM=",
 "height": 515
}
18:37:06 ERROR lisk-framework: Failed to restore blocks from blocks temp table (module=lisk:app)
Message: Wrong maxHeightPrevoted in blockHeader. maxHeightPrevoted: 446, : 447
 Trace: Error: Wrong maxHeightPrevoted in blockHeader. maxHeightPrevoted: 446, : 447
    at FinalityManager.verifyBlockHeaders (/lisk-sdk/elements/lisk-bft/src/finality_manager.ts:388:10)
    at BFT.verifyNewBlock (/lisk-sdk/elements/lisk-bft/src/bft.ts:116:31)
    at BlockProcessorV2.verify.pipe.async.block.block (/lisk-sdk/framework/src/application/node/block_processor_v2.ts:172:20)
    at Pipeline.run (/lisk-sdk/framework/src/application/node/processor/pipeline.ts:64:25)
    at Processor._processValidated (/lisk-sdk/framework/src/application/node/processor/processor.ts:348:3)
    at Sequence._tick (/lisk-sdk/framework/src/application/node/utils/sequence.ts:98:19)
    at Timeout.nextSequence [as _onTimeout] (/lisk-sdk/framework/src/application/node/utils/sequence.ts:63:4)
```

### Steps to reproduce
Same as #5506 , and it happens after failing on the #5506 

### Which version(s) does this affect? (Environment, OS, etc...)
5.0-

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #5506 

### How was it solved?

- Remove memory cache for the maxHeightPrevoted, and calculate on demand

### How was it tested?

- Update all the tests
- Prepare 2 nodes, and make syncing node fail manually by mutating the code
- It should revert blocks and resync again. It should not fail to resync.

### CODE REVIEW

File: elements/lisk-bft/src/finality_manager.ts [hunk 1]
```diff
@@ -446,6 +431,39 @@ export class FinalityManager extends EventEmitter {
...
 	}
 
+	public getMaxHeightPrevoted(
+		bftVotingLedgerBuffer: Buffer | undefined,
+	): number {
+		const { ledger } = this._decodeVotingLedger(bftVotingLedgerBuffer);
+		const { preVoted } = this._getChainMaxHeightStatus(ledger);
+
+		return preVoted;
+	}
```
Comment (nazarhussain) [inline elements/lisk-bft/src/finality_manager.ts:441]: This method is used only once in the `BFT`, where its parameter are fetched from the `_chain` module. Since `finalyManager` itself have the access to `_chain`, why not just remove the parameter and use `_chain` directly here.

File: elements/lisk-bft/src/finality_manager.ts [hunk 2]
```diff
@@ -368,25 +352,26 @@ export class FinalityManager extends EventEmitter {
...
+		stateStore: StateStore,
+	): Promise<boolean> {
 		debug('verifyBlockHeaders invoked');
 		debug(blockHeader);
 
+		const bftBlockHeaders = stateStore.consensus.lastBlockHeaders;
+		const { ledger } = await this._getVotingLedger(stateStore);
+		const { preVoted: chainMaxHeightPrevoted } = this._getChainMaxHeightStatus(
+			ledger,
+		);
```
Comment (nazarhussain) [inline elements/lisk-bft/src/finality_manager.ts:366]: Since we already have `getMaxHeightPrevoted`, should not we use it to instead?

File: elements/lisk-bft/src/bft.ts [hunk 3]
```diff
@@ -195,25 +193,25 @@ export class BFT extends EventEmitter {
...
-		return this.finalityManager.finalizedHeight;
-	}
-
-	public get maxHeightPrevoted(): number {
-		return this.finalityManager.chainMaxHeightPrevoted;
+	public async getMaxHeightPrevoted(): Promise<number> {
+		const bftState = await this._chain.dataAccess.getConsensusState(
+			CONSENSUS_STATE_DELEGATE_LEDGER_KEY,
+		);
+		return this.finalityManager.getMaxHeightPrevoted(bftState);
```
Comment (nazarhussain) [inline elements/lisk-bft/src/bft.ts:210]: Related to earlier comment, we can move this `this._chain.dataAccess.getConsensusState` directly in the `finalityManager.getMaxHeightPrevoted`

File: elements/lisk-bft/src/finality_manager.ts (hunk 2 above)
Comment (shuse2) [reply elements/lisk-bft/src/finality_manager.ts]: It is not using because getMaxHeightPrevoted is not using the state store, and during the processing of block, it should use state store consistently
