### PR TITLE
Fix BFT delete blocks logic - Closes #4800

### LINKED ISSUE #4800: BFT deletion logic throws error which is not error
### Expected behavior
* It should not fail to delete blocks more than 197 blocks.
* It should recompute after filling the cache
* Update `prevotedConfirmedHeight` to `chainMaxHeightFinalized` in order to be compatible with LIP
* Include `height`, `heightPrevoted` and `maxHeightPreviouslyForged` in the forgers list

### Actual behavior
When deleting blocks which makes the block header cache to go below, it fails to refill the cache because of the `chainMaxHeightFinalized` validation.

### Steps to reproduce
Delete more than 197 blocks when it has 500 blocks cache

### Which version(s) does this affect? (Environment, OS, etc...)
3.0-

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?
This PR resolves #4800 

### How was it solved?
- Update the saved forger info to be consistent with LIP
- Update variable name to be consistent with LIP
- delete block, but only populate the cache first and recompute without validation

### How was it tested?
- Added test case to check the recompute
- Check database to contain correct forger info

### CODE REVIEW

File: framework/src/modules/chain/bft/bft.js [hunk 1]
```diff
@@ -334,13 +325,64 @@ class BFT extends EventEmitter {
...
+				height => height >= minimumPossibleActiveHeight,
+			);
+
+			const blockHeader = {
+				...blockJSON,
+				delegateMinHeightActive,
+			};
+			this.finalityManager.headers.add(
+				extractBFTBlockHeaderFromBlock(blockHeader),
+			);
```
Comment (ManuGowda) [inline framework/src/modules/chain/bft/bft.js]: can we abstract this in a function and reuse in `_loadBlocksFromStorage` as well?

File: framework/src/modules/chain/bft/finality_manager.js [hunk 2]
```diff
@@ -58,7 +58,7 @@ class FinalityManager extends EventEmitter {
 		this.finalizedHeight = finalizedHeight;
 
 		// Height up to which blocks have pre-voted
-		this.prevotedConfirmedHeight = 0;
+		this.chainMaxHeightFinalized = 0;
```
Comment (nazarhussain) [inline framework/src/modules/chain/bft/finality_manager.js]: `this.prevotedConfirmedHeight` are different than `this.chainMaxHeightFinalized`

File: framework/src/modules/chain/bft/finality_manager.js [hunk 3]
```diff
@@ -88,7 +88,7 @@ class FinalityManager extends EventEmitter {
 
 		debug('after adding block header', {
 			finalizedHeight: this.finalizedHeight,
-			prevotedConfirmedHeight: this.prevotedConfirmedHeight,
+			chainMaxHeightFinalized: this.chainMaxHeightFinalized,
```
Comment (nazarhussain) [inline framework/src/modules/chain/bft/finality_manager.js]: Its duplicate information both `finalizedHeight` and `chainMaxHeightFinalized` are the same attribute.

File: framework/src/modules/chain/bft/finality_manager.js [hunk 4]
```diff
@@ -191,9 +191,9 @@ class FinalityManager extends EventEmitter {
 			.reverse()
 			.find(key => this.preVotes[key] >= this.preVoteThreshold);
 
-		this.prevotedConfirmedHeight = highestHeightPreVoted
+		this.chainMaxHeightFinalized = highestHeightPreVoted
 			? parseInt(highestHeightPreVoted, 10)
-			: this.prevotedConfirmedHeight;
+			: this.chainMaxHeightFinalized;
```
Comment (nazarhussain) [inline framework/src/modules/chain/bft/finality_manager.js]: Block with highest prevotes is not the finalized height.

File: framework/src/modules/chain/block_processor_v2.js [hunk 5]
```diff
@@ -27,8 +27,7 @@ const {
 const { baseBlockSchema } = require('./blocks');
 const { BaseBlockProcessor } = require('./processor');
 
-const FORGER_INFO_KEY_MAX_HEIGHT_PREVIOUSLY_FORGED =
-	'maxHeightPreviouslyForged';
+const FORGER_INFO_KEY_MAX_HEIGHT_PREVIOUSLY_FORGED = 'previouslyForged';
```
Comment (ManuGowda) [inline framework/src/modules/chain/block_processor_v2.js]: can you update the variable to the corresponding key

File: framework/src/modules/chain/bft/finality_manager.js (hunk 2 above)
Comment (shuse2) [reply framework/src/modules/chain/bft/finality_manager.js]: It was meant to be `chainMaxHeightPrevoted`, will update.
This was because when we were discussing the bug, it was hard to communicate/reference the LIP

File: framework/src/modules/chain/bft/bft.js (hunk 1 above)
Comment (shuse2) [reply framework/src/modules/chain/bft/bft.js]: it's slightly different functionality, and for the patch, i don't want to clean up and change so much.
On my other PR, it will be cleaned up

File: framework/src/modules/chain/bft/bft.js [hunk 6]
```diff
@@ -124,17 +124,8 @@ class BFT extends EventEmitter {
 			this.finalityManager.maxHeight - this.finalityManager.minHeight <
 			this.constants.activeDelegates * BFT_ROUND_THRESHOLD
 		) {
-			const tillHeight = this.finalityManager.minHeight - 1;
-			const fromHeight =
-				this.finalityManager.maxHeight -
-				// Search is inclusive, therefore, it should start from one above (ex: 288 - 500, which results total 303)
-				this.constants.activeDelegates * BFT_ROUND_THRESHOLD +
-				1;
-			await this._loadBlocksFromStorage({
```
Comment (nazarhussain) [inline framework/src/modules/chain/bft/bft.js]: Why we need to keep this function still int he file? actually that function should have been renamed to `fillCache`

Comment (shuse2) [reply framework/src/modules/chain/bft/bft.js]: @ManuGowda Also mentioned this, but this logic is slightly different than fill cache because it fills to the top, and this is patch so i didn't want to clean up. This will be changed in my BFT PR #4737
