### PR TITLE
P2P message formats are inconsistent - Closes #6193

### LINKED ISSUE #6193: P2P message formats are inconsistent
### Expected behavior
P2P message should follow consistent message structures

```
export interface P2PRequestPacket {
	readonly data?: unknown; // This should be internally check if it's buffer, and if not converted to buffer
	readonly procedure: string;
}

export interface P2PResponsePacket {
	readonly peerId?: string;
	readonly data: unknown; // This should be internally check if it's buffer, and if not converted to buffer
}

export interface P2PMessagePacket {
	readonly peerId?: string;
	readonly data?: unknown; // This should be internally check if it's buffer, and if not converted to buffer
	readonly event: string;
}
```
- The buffer needs to be encoded into `binary` before sending to the network.
- Framework code where it uses request/response or event from the P2P needs to updated.
- All Request/response must be encoded using codec
- Interface should not change for p2p library

### Actual behavior
For example, 
- postNodeInfo (event)
```
{
  event: 'postNodeInfo',
  data: 'hex string encoded by lisk-codec'
}
```
- getPeers (req/res)
```
Req: undefined
---
Res:
procedure: 'getPeers',
data: {
    success: true,
    peers: [
      'hex string encoded by lisk-codec',
    ]
  }
```
- getBlockFromId
```
Req:
{
    blockId: 'hex string id'
}
---
Res:
 data: [
   'hex string encoded by lisk-codec',
 ]
```

### Steps to reproduce
Observe the raw data of the communication

### Which version(s) does this affect? (Environment, OS, etc...)
5.0.3-

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?

This PR resolves #6193 

### How was it solved?

- Update p2p socket level message communication format to binary
- Update p2p, peer pool and network layer to use buffer
- Update event handlers, RPC handlers to encode and decode buffer data

### How was it tested?

- Updated all the tests

### CODE REVIEW

File: elements/lisk-p2p/src/utils/validate.ts [hunk 1]
```diff
@@ -161,9 +164,11 @@ export const validatePeerInfoList = (
 			throw new InvalidPeerInfoListError(PEER_INFO_LIST_TOO_LONG_REASON);
 		}
 
-		const sanitizedPeerList = peers.map<P2PPeerInfo>(peerInfo =>
-			validatePeerInfo(sanitizeIncomingPeerInfo(peerInfo), maxPeerInfoByteSize),
-		);
+		const sanitizedPeerList = peers.map<P2PPeerInfo>((peerInfoBuffer: Buffer) => {
+			const peerInfo = codec.decode<P2PPeerInfo>(peerInfoSchema, peerInfoBuffer);
```
Comment (shuse2) [inline elements/lisk-p2p/src/utils/validate.ts:168]: I think decoding should happen before the validation

File: elements/lisk-p2p/src/utils/validate.ts [hunk 2]
```diff
@@ -180,20 +185,25 @@ export const validateRPCRequest = (request: unknown): P2PRequestPacket => {
...
 
+	if (rpcRequest.data !== undefined && typeof rpcRequest.data !== 'string') {
+		throw new InvalidRPCRequestError('Request data is not a string or undefined');
+	}
+
 	return rpcRequest;
 };
 
-export const validateProtocolMessage = (message: unknown): P2PMessagePacket => {
+export const validateProtocolMessage = (message: P2PMessagePacket): void => {
```
Comment (shuse2) [inline elements/lisk-p2p/src/utils/validate.ts:195]: message comes from the network and in order to avoid assuming any type, the type was set to `unknown`, so i think we should keep it `unknown`

File: framework-plugins/lisk-framework-monitor-plugin/src/monitor_plugin.ts [hunk 3]
```diff
@@ -217,8 +217,7 @@ export class MonitorPlugin extends BasePlugin {
 	}
 
 	private _handlePostBlock(data: EventPostBlockData) {
-		const blockBytes = Buffer.from(data.block, 'hex');
-		const decodedBlock = codec.decode<RawBlock>(this.schemas.block, blockBytes);
+		const decodedBlock = codec.decode<RawBlock>(this.schemas.block, Buffer.from(data.block, 'hex'));
```
Comment (shuse2) [inline framework-plugins/lisk-framework-monitor-plugin/src/monitor_plugin.ts:220]: data.block is Buffer?

File: elements/lisk-validator/src/validation.ts [hunk 4]
```diff
@@ -38,15 +38,57 @@ export const isNumberString = (num: unknown): boolean => {
...
-	if (typeof data !== 'string') {
+	if (!isString(data)) {
 		return false;
 	}
 
-	return data === '' || /^[a-f0-9]+$/i.test(data);
+	return data === '' || /^[a-f0-9]+$/i.test(data as string);
+};
+
+export const isBinaryString = (data: unknown): boolean => {
```
Comment (shuse2) [inline elements/lisk-validator/src/validation.ts:80]: do we still need these changes?

File: framework/src/node/network/network.ts [hunk 5]
```diff
@@ -363,6 +363,7 @@ export class Network {
 					},
 					'EVENT_MESSAGE_RECEIVED: Received inbound message',
 				);
+				// TODO: Fix packet data buffer to hex conversion
```
Comment (shuse2) [inline framework/src/node/network/network.ts:366]: this needs special handling to keep the current events in format

File: framework/src/node/network/network.ts [hunk 6]
```diff
@@ -409,15 +410,13 @@ export class Network {
 		requestPacket: liskP2P.p2pTypes.P2PRequestPacket,
 	): Promise<liskP2P.p2pTypes.P2PResponsePacket> {
 		return this._p2p.request({
-			procedure: requestPacket.procedure,
-			data: requestPacket.data,
+			...requestPacket,
```
Comment (shuse2) [inline framework/src/node/network/network.ts:413]: do we need to change here?

File: elements/lisk-p2p/src/utils/codec.ts [hunk 7]
```diff
@@ -14,27 +14,27 @@
  */
 
 import { codec, Schema } from '@liskhq/lisk-codec';
-import { isHexString } from '@liskhq/lisk-validator';
+
 import { P2PPeerInfo, P2PNodeInfo, ProtocolPeerInfo } from '../types';
 import { InvalidPeerInfoError, InvalidNodeInfoError } from '../errors';
 
-export const decodePeerInfo = (peerInfoSchema: Schema, data: unknown): P2PPeerInfo => {
+export const decodePeerInfo = (peerInfoSchema: Schema, data?: Buffer): P2PPeerInfo => {
```
Comment (shuse2) [inline elements/lisk-p2p/src/utils/codec.ts:21]: probably keeping data type `unknown` make more sense?

File: elements/lisk-p2p/src/utils/validate.ts [hunk 8]
```diff
@@ -133,10 +133,12 @@ export const validatePeerInfo = (
 	return peerInfo;
 };
 
-export const validateNodeInfo = (nodeInfo: Buffer, maxByteSize: number): void => {
-	const byteSize = getByteSize(nodeInfo);
+export const validatePayloadSize = (nodeInfo: Buffer | undefined, maxByteSize: number): void => {
+	if (nodeInfo) {
```
Comment (shuse2) [inline elements/lisk-p2p/src/utils/validate.ts:137]: opposite logic?

File: framework/src/node/transport/transport.ts [hunk 9]
```diff
@@ -287,9 +300,10 @@ export class Transport {
 		// eslint-disable-next-line @typescript-eslint/default-param-last
 		data: unknown = { transactionIds: [] },
 		peerId: string,
-	): Promise<HandleRPCGetTransactionsReturn> {
+	): Promise<Buffer> {
 		this._addRateLimit('getTransactions', peerId, DEFAULT_RATE_LIMIT_FREQUENCY);
-		const errors = validator.validate(schemas.getTransactionsRequest, data as object);
+		const decodedData = codec.decode(transactionIdsSchema, data as never);
```
Comment (shuse2) [inline framework/src/node/transport/transport.ts:305]: why `never` here?

File: elements/lisk-p2p/src/p2p_request.ts [hunk 10]
```diff
@@ -102,4 +104,17 @@ export class P2PRequest {
 	public error(responseError: Error): void {
 		this._respondCallback(responseError);
 	}
+
+	// eslint-disable-next-line class-methods-use-this
+	private _getBinaryData(data: unknown): string | undefined {
```
Comment (ishantiw) [inline elements/lisk-p2p/src/p2p_request.ts:109]: maybe have more specific name, like `getBinaryBufferData` as in `base.ts` we have the same func but returning string

File: elements/lisk-p2p/src/p2p.ts [hunk 11]
```diff
@@ -647,28 +656,33 @@ export class P2P extends EventEmitter {
 	}
 
 	public async request(packet: P2PRequestPacket): Promise<P2PResponsePacket> {
-		const response = await this._peerPool.request(packet);
+		const bufferData = this._getBufferData(packet.data);
+		const response = await this._peerPool.request({ ...packet, data: bufferData });
```
Comment (ishantiw) [inline elements/lisk-p2p/src/p2p.ts:660]: maybe its better to be specific in order to avoid any extra property, 
```suggestion
		const response = await this._peerPool.request({ procedure: packet.procedure, data: bufferData });
```

File: framework/src/node/network/network.ts (hunk 6 above)
Comment (ishantiw) [reply framework/src/node/network/network.ts:413]: yeah maybe keep it as before to avoid passing any unnecessary props to p2p.request

File: framework/src/node/transport/schemas.ts [hunk 12]
```diff
@@ -12,72 +12,113 @@
...
+	title: 'Broadcast Transactions',
+	type: 'object',
+	required: ['transactionIds'],
+	properties: {
+		transactionIds: {
+			type: 'array',
+			fieldNumber: 1,
+			items: {
+				dataType: 'bytes',
 			},
```
Comment (ishantiw) [inline framework/src/node/transport/schemas.ts:91]: isn't this the same as `postTransactionsAnnouncementEventSchema`

File: elements/lisk-p2p/src/p2p.ts [hunk 13]
```diff
@@ -647,28 +653,35 @@ export class P2P extends EventEmitter {
...
+			data: bufferData,
+		});
 		return response;
 	}
 
-	public send(message: P2PMessagePacket): void {
-		this._peerPool.send(message);
+	public send(packet: P2PMessagePacket): void {
+		const bufferData = this._getBufferData(packet.data);
+		this._peerPool.send({ ...packet, data: bufferData });
```
Comment (ishantiw) [inline elements/lisk-p2p/src/p2p.ts:666]:
```suggestion
		this._peerPool.send({ event: packet.event, data: bufferData });
```

File: elements/lisk-p2p/src/p2p.ts [hunk 14]
```diff
@@ -647,28 +653,35 @@ export class P2P extends EventEmitter {
...
-		return this._peerPool.requestFromPeer(packet, peerId);
+		const bufferData = this._getBufferData(packet.data);
+		return this._peerPool.requestFromPeer({ ...packet, data: bufferData }, peerId);
 	}
 
-	public sendToPeer(message: P2PMessagePacket, peerId: string): void {
-		this._peerPool.sendToPeer(message, peerId);
+	public sendToPeer(packet: P2PMessagePacket, peerId: string): void {
+		const bufferData = this._getBufferData(packet.data);
+		this._peerPool.sendToPeer({ ...packet, data: bufferData }, peerId);
```
Comment (ishantiw) [inline elements/lisk-p2p/src/p2p.ts:684]:
```suggestion
		this._peerPool.sendToPeer({ procedure: packet.procedure, data: bufferData }, peerId);
```

File: elements/lisk-p2p/src/peer/base.ts [hunk 15]
```diff
@@ -245,9 +242,9 @@ export class Peer extends EventEmitter {
 
 		// This needs to be an arrow function so that it can be used as a listener.
 		this._handleRawMessage = (packet: unknown): void => {
-			let message;
+			const message = packet as P2PMessagePacket;
```
Comment (shuse2) [inline elements/lisk-p2p/src/peer/base.ts:245]: `_handleRawRPC` has similar pattern, so it should be the same.
I think it would be better if the `packet` is unknown and after the validation the type is changed. ie)
```
this._handleRawMessage = (packet: unknown): void => {
    try {
		validateProtocolMessage(packet);
	} catch (error) {
		this.emit(EVENT_INVALID_MESSAGE_RECEIVED, {
			packet,
		.......................			
const message = packet as P2PMessagePacket;
...

```

File: elements/lisk-validator/src/validation.ts [hunk 16]
```diff
@@ -38,15 +38,43 @@ export const isNumberString = (num: unknown): boolean => {
...
+	typeof data === 'bigint' ? data <= MAX_UINT64 && data >= BigInt(0) : false;
+
+export const isBytes = (data: unknown): boolean => Buffer.isBuffer(data);
+
 export const isValidInteger = (num: unknown): boolean =>
 	typeof num === 'number' ? Math.floor(num) === num : false;
 
 export const isHexString = (data: unknown): boolean => {
-	if (typeof data !== 'string') {
+	if (!isString(data)) {
```
Comment (shuse2) [inline elements/lisk-validator/src/validation.ts:73]: unrelated change?

File: framework/src/node/network/network.ts [hunk 17]
```diff
@@ -203,7 +207,7 @@ export class Network {
 		// ---- START: Bind event handlers ----
 		this._p2p.on(EVENT_NETWORK_READY, () => {
 			this._logger.debug('Node connected to the network');
-			this._channel.publish(APP_EVENT_NETWORK_READY);
+			this.events.emit(APP_EVENT_NETWORK_READY);
```
Comment (shuse2) [inline framework/src/node/network/network.ts:210]: this event must be emitted through channel also

File: elements/lisk-p2p/src/peer/base.ts [hunk 18]
```diff
@@ -259,19 +256,24 @@ export class Peer extends EventEmitter {
...
 			this._updateMessageCounter(message);
 			const rate = this._getMessageRate(message);
-			const messageWithRateInfo = {
-				...message,
-				peerId: this._peerInfo.peerId,
-				rate,
-			};
+			let messageBufferData: Buffer | undefined;
+			if (typeof message.data === 'string') {
+				messageBufferData = Buffer.from(message.data, 'binary');
```
Comment (ishantiw) [inline elements/lisk-p2p/src/peer/base.ts:261]: use getBufferData kind of func similar to what we are doing at other places?

File: framework/src/node/network/network.ts [hunk 19]
```diff
@@ -363,7 +371,10 @@ export class Network {
 					},
 					'EVENT_MESSAGE_RECEIVED: Received inbound message',
 				);
-				this._channel.publish('app:network:event', packet);
+				this.events.emit(APP_EVENT_NETWORK_EVENT, packet);
+				const data =
+					packet.data && Buffer.isBuffer(packet.data) ? packet.data.toString('hex') : packet.data;
+				this._channel.publish('app:network:event', { ...packet, data });
```
Comment (ishantiw) [inline framework/src/node/network/network.ts:377]:
```suggestion
				this._channel.publish(APP_EVENT_NETWORK_EVENT
, { ...packet, data });
```

File: elements/lisk-p2p/src/peer/base.ts [hunk 20]
```diff
@@ -342,38 +343,48 @@ export class Peer extends EventEmitter {
...
+				const data = this._getBinaryData(packet.data);
 				this._socket.emit(
 					REMOTE_SC_EVENT_RPC_REQUEST,
 					{
 						procedure: packet.procedure,
-						data: packet.data,
+						data,
 					},
-					(error: Error | undefined, responseData: unknown) => {
+					(error: Error | undefined, responseData: BaseRequestResponsePacket | undefined) => {
```
Comment (shuse2) [inline elements/lisk-p2p/src/peer/base.ts:375]: this should also be unknown since it comes from network

File: elements/lisk-p2p/src/utils/validate.ts [hunk 21]
```diff
@@ -133,93 +122,47 @@ export const validatePeerInfo = (
...
-		},
-		data: {
-			type: ['object', 'string'],
-		},
-	},
 };
 
 export const validatePacket = (packet: unknown): void => {
-	const errors = validator.validate(packetSchema, packet as P2PMessagePacket | P2PRequestPacket);
+	const errors = validator.validate(PacketSchema, packet as P2PMessagePacket | P2PRequestPacket);
```
Comment (shuse2) [inline elements/lisk-p2p/src/utils/validate.ts:165]: it should be lower camel case

File: elements/lisk-p2p/src/utils/validate.ts [hunk 22]
```diff
@@ -37,12 +30,8 @@ import {
...
 
 // eslint-disable-next-line import/no-cycle
-import { getByteSize, sanitizeIncomingPeerInfo } from '.';
-
-interface RPCPeerListResponse {
-	readonly peers: ReadonlyArray<object>;
-	readonly success?: boolean; // Could be used in future
-}
+import { getByteSize } from '.';
+import { PacketSchema, RPCRequestSchema, ProtocolMessageSchema } from './schemas';
```
Comment (shuse2) [inline elements/lisk-p2p/src/utils/validate.ts:34]: schemas should be lower camel case

**Review by shuse2 — CHANGES_REQUESTED** [review]

**Review by ishantiw — COMMENTED** [review]
Apart from @shuse2 's comments LGTM

**Review by ishantiw — APPROVED** [review]

File: elements/lisk-p2p/src/peer/base.ts [hunk 23]
```diff
@@ -177,107 +171,19 @@ export class Peer extends EventEmitter {
...
-					id: this.peerInfo.peerId,
-					rate,
-					productivity: this.internalState.productivity,
-				},
-				respond,
-			);
-
-			this.emit(EVENT_REQUEST_RECEIVED, request);
-		};
+		): void => this._handleRawRPCFunc(packet, respond);
```
Comment (shuse2) [inline elements/lisk-p2p/src/peer/base.ts:176]: prefer to keep it as it was

File: elements/lisk-p2p/src/peer/base.ts [hunk 24]
```diff
@@ -111,33 +113,24 @@ export enum ConnectionState {
...
 export class Peer extends EventEmitter {
+	// protected handlers
 	protected readonly _handleRawRPC: (
 		packet: P2PRawRequestPacket,
 		respond: (responseError?: Error, responseData?: unknown) => void,
 	) => void;
 	protected readonly _handleWSMessage: (message: string) => void;
 	protected readonly _handleRawMessage: (packet: unknown) => void;
+
+	// protected variables
```
Comment (shuse2) [inline elements/lisk-p2p/src/peer/base.ts:126]: it's already commented above

File: elements/lisk-p2p/src/peer/base.ts [hunk 25]
```diff
@@ -111,33 +113,24 @@ export enum ConnectionState {
 export interface ConnectedPeerInfo extends P2PPeerInfo {
 	internalState: P2PInternalState;
 }
-export interface PeerConfig {
```
Comment (shuse2) [inline elements/lisk-p2p/src/peer/base.ts:107]: why move this to another place?

File: elements/lisk-p2p/src/peer_pool.ts [hunk 26]
```diff
@@ -116,34 +117,6 @@ export enum PROTECTION_CATEGORY {
 	CONNECT_TIME = 'connectTime',
 }
 
-export interface PeerPoolConfig {
```
Comment (shuse2) [inline elements/lisk-p2p/src/peer_pool.ts:118]: this should be here as it is the config for the peer pool

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: framework/src/node/transport/schemas.ts [hunk 27]
```diff
@@ -12,72 +12,97 @@
...
+export const getHighestCommonBlockRequestSchema = {
+	$id: 'lisk/getHighestCommonBlockRequest',
+	title: 'Get Highest Common Block Request',
+	type: 'object',
+	required: ['ids'],
+	properties: {
+		ids: {
+			type: 'array',
+			fieldNumber: 1,
+			uniqueItems: true,
```
Comment (shuse2) [inline framework/src/node/transport/schemas.ts:53]: I think `uniqueItems` will not work for buffers, it would be nice to make sure

**Review by shuse2 — APPROVED** [review]

**Review by ishantiw — APPROVED** [review]
