### PR TITLE
Confirmations value in block is NaN - Close #3688

### LINKED ISSUE #3688: Confirmations value in block is NaN
### Expected behavior
`confirmations` value should be valid and an integer and also the 
### Actual behavior
There are two issues here one is `undefined` value `MONITOR: undefined` 
and another is `confirmations` value is `undefined`
```
MONITOR: undefined -> chain:blocks:change { id: '10705954266938328476',
      version: 1,
      timestamp: 94239710,
      height: 8305141,
      previousBlock: '9592550440812684133',
      numberOfTransactions: 0,
      totalAmount: 0,
      totalFee: 0,
      reward: 300000000,
      payloadLength: 0,
      payloadHash:
       'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      generatorPublicKey:
       'a6b504812068c9a1186034966868118e1d98e88bc60835a81252f51136c3cddd',
      generatorId: '11027108891413363651L',
      blockSignature:
       'fccdec62363f37456174362d6857075209ea9bc2d1d50d30d6fff59771ac9c84cb86f3b032e0ac3bc9f26c67d47480a75019f712b1ff5834371eb794fb94d70f',
      confirmations: NaN,
      totalForged: '300000000',
      transactions: [] }
```
### Steps to reproduce
Sync `2.0.0-alpha.9` node with testnet
### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

### PR DESCRIPTION
**Pull request by pablitovicente**
### What was the problem?

- confirmations was showing NAN

### How did I fix it?

- By setting a default when the property `confirmations` is not present in the blocks when calling `dbRead` or `storageRead` when receiving blocks

### How to test it?

- Build should be green
- Run two nodes, one forging, one not
- Look for the message `chain:blocks:change` confirmations should not be `NaN`

### Review checklist

* The PR resolves #3688
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/chain/logic/block.js [hunk 1]
```diff
@@ -518,7 +518,7 @@ Block.prototype.dbRead = function(raw) {
 		generatorPublicKey: raw.b_generatorPublicKey,
 		generatorId: __private.getAddressByPublicKey(raw.b_generatorPublicKey),
 		blockSignature: raw.b_blockSignature,
-		confirmations: parseInt(raw.b_confirmations),
+		confirmations: raw.b_confirmations ? parseInt(raw.b_confirmations) : 0,
```
Comment (lsilvs) [inline framework/src/modules/chain/logic/block.js]:
```suggestion
		confirmations: parseInt(raw.b_confirmations) ? parseInt(raw.b_confirmations) : 0,
```

File: framework/src/modules/chain/logic/block.js [hunk 2]
```diff
@@ -550,7 +550,7 @@ Block.prototype.storageRead = function(raw) {
 		generatorPublicKey: raw.generatorPublicKey,
 		generatorId: __private.getAddressByPublicKey(raw.generatorPublicKey),
 		blockSignature: raw.blockSignature,
-		confirmations: parseInt(raw.confirmations),
+		confirmations: raw.confirmations ? parseInt(raw.confirmations) : 0,
```
Comment (lsilvs) [inline framework/src/modules/chain/logic/block.js]:
```suggestion
		confirmations: parseInt(raw.confirmations) ? parseInt(raw.confirmations) : 0,
```

File: framework/src/modules/chain/logic/block.js [hunk 3]
```diff
@@ -518,7 +518,7 @@ Block.prototype.dbRead = function(raw) {
 		generatorPublicKey: raw.b_generatorPublicKey,
 		generatorId: __private.getAddressByPublicKey(raw.b_generatorPublicKey),
 		blockSignature: raw.b_blockSignature,
-		confirmations: parseInt(raw.b_confirmations),
+		confirmations: parseInt(raw.b_confirmations) ? parseInt(raw.b_confirmations) : 0,
```
Comment (shuse2) [inline framework/src/modules/chain/logic/block.js]: can we do `parseInt` above once?
```
const confirmations = parseInt(raw.b_confirmations);
...
confirmations: confirmations !== NaN ? confirmations : 0,
```

Comment (pablitovicente) [reply framework/src/modules/chain/logic/block.js]: Changed.
