### PR TITLE
Handle block data to log properly and fix event log - Closes #4998

### LINKED ISSUE #4998: TypeError: Do not know how to serialize a BigInt
### Expected behavior

The logger should be able to log all the messages without error

### Actual behavior

```
Message: Do not know how to serialize a BigInt 
 Trace: TypeError: Do not know how to serialize a BigInt
```

also, we see `TRACE undefined: Monitor Bus Channel (module=unknown)` frequently
### Steps to reproduce

`LISK_CONSOLE_LOG_LEVEL=trace node test/test_app`

### Which version(s) does this affect? (Environment, OS, etc...)

`4.0.0-alpha.0`

### PR DESCRIPTION
**Pull request by ishantiw**
### What was the problem?

This PR resolves #4998 

### How was it solved?

- [x] Logging only `previousBlockId` instead of all the `previousBlock` data
- [x] Event is a string so logging it as a string Monitor Bus Channel logging

### How was it tested?

`LISK_CONSOLE_LOG_LEVEL=trace node test/test_app` and check the logs

### CODE REVIEW

File: framework/src/application/node/processor/processor.js [hunk 1]
```diff
@@ -187,7 +187,11 @@ class Processor {
 	}
 
 	async create(values) {
-		this.logger.trace({ data: values }, 'Creating block');
+		const { previousBlock, ...restOFValues } = values;
+		this.logger.trace('Creating block', {
```
Comment (ManuGowda) [inline framework/src/application/node/processor/processor.js]: the data should come first know? and then the message?

Comment (ishantiw) [reply framework/src/application/node/processor/processor.js]: somehow it doesn't log if I give it as the second argument, for that, I have to stringify which can be done when using it as the second argument
