### PR TITLE
Fix to start/stop transaction pool in application/node - Closes #4978

### LINKED ISSUE #4978: Transaction pool should be started in the application
### Expected behavior
`transactionPool.start` and `transactionPool.stop` should be called in the application start and end

### Actual behavior
transaction pool is not started nor stopped

### Which version(s) does this affect? (Environment, OS, etc...)
4.0-

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #4978 

### How was it solved?

Call `transaction.start` and `transaction.stop` when bootstrapping or cleaning.

### How was it tested?

- Added test
- Add log and see reorganize job is running

### CODE REVIEW

File: framework/src/application/node/node.js [hunk 1]
```diff
@@ -330,6 +331,7 @@ module.exports = class Node {
 	}
 
 	async cleanup(error) {
+		await this.transactionPool.stop();
```
Comment (nazarhussain) [inline framework/src/application/node/node.js]: We do have a convention of `bootstrap`  and `cleanup` method in every module? Should not we follow same here instead of `start/stop`?

Comment (shuse2) [reply framework/src/application/node/node.js]: I think for p2p, it's start and stop. Also, for p2p and transaction pool, it's running the interval and not just bootstrapping, so it's better to call start than bootstrap IMO
