### PR TITLE
Increase unit test coverage across P2P peer book - Closes #4227

### LINKED ISSUE #4227: Add unit test coverage for P2P peer directory folder
### Expected behavior

Every file from `lisk-p2p` library is well covered with unit test. The minimum must be 80% at least to achieve green reports.  

### Actual behavior

`peer_directory/` counts with only 75% coverage.

### Steps to reproduce

`npm t`

### Which version(s) does this affect? (Environment, OS, etc...)

`+2.3`

### PR DESCRIPTION
**Pull request by diego-G**
### How to manually test it?
`npm t`
`npm run test:unit`

### Review checklist
- [x] The PR resolves #4227
- [x] All new code is covered with unit tests
- [x] Relevant integration / functional tests are added
- [x] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [x] Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-p2p/src/peer_book/base_list.ts [hunk 1]
```diff
@@ -121,66 +128,25 @@ export class PeerList {
...
-				isAdded: false,
-				evictedPeer: undefined,
-			};
-		}
-
-		const newPeer = this.initPeerInfo(peerInfo);
-
-		if (bucket.size < this.peerListConfig.peerBucketSize) {
-			bucket.set(incomingPeerId, newPeer);
+	public makeSpace(ipAddress: string): CustomPeerInfo | undefined {
```
Comment (shuse2) [inline elements/lisk-p2p/src/peer_book/base_list.ts]: why it's not `addPeer` anymore? if the space is empty and just simply adding peer, would it use this function?

File: elements/lisk-p2p/test/unit/peer/base.ts [hunk 2]
```diff
@@ -399,24 +391,17 @@ describe('peer/base', () => {
...
 
-			it('should throw an error', async () => {
-				try {
-					await defaultPeer.fetchPeers();
-				} catch (e) {
-					expect(e).to.be.an.instanceOf(RPCResponseError);
-					expect(e.message).to.be.eql('Failed to fetch peer list of peer');
-					expect(e.peerId).to.be.eql(defaultPeerInfo.ipAddress);
-				}
+			it('should throw an error', () => {
```
[the remark this answers is not in the document]
Comment (diego-G) [reply elements/lisk-p2p/test/unit/peer/base.ts]: Thank you for pointing out. I found out we need `return` when using `.to.be.rejectedWith`, otherwise if it fails we have an unhandled rejection. However, I don't see the need of `async`.

File: elements/lisk-p2p/src/peer_book/base_list.ts (hunk 1 above)
Comment (diego-G) [reply elements/lisk-p2p/src/peer_book/base_list.ts]: `makeSpace()` checks if the bucket is full and only in that case removes a peer using eviction strategies and returns that evicted peer. If the bucket is not full, it just returns undefined without removing any peer. After that, `addPeer()` is executed.

File: elements/lisk-p2p/src/peer_book/utils.ts [hunk 3]
```diff
@@ -0,0 +1,135 @@
...
+						targetBBytes,
+					]),
+			  ).readUInt32BE(0) % firstMod
+			: hash(
+					Buffer.concat([secretBytes, networkBytes, addressBytes]),
+			  ).readUInt32BE(0) % firstMod;
+
+	kBytes.writeUInt32BE(k, 0);
+
+	// New peers: b = Hash(random_secret, source_group, k) % 128
```
Comment (ishantiw) [inline elements/lisk-p2p/src/peer_book/utils.ts]: These comments are out of place

File: elements/lisk-p2p/src/peer_book/base_list.ts [hunk 4]
```diff
@@ -75,22 +70,35 @@ export class PeerList {
...
+		const peer = bucket.get(incomingPeerId);
 
-		if (!bucket) {
-			return false;
+		return peer ? peer.peerInfo : undefined;
+	}
+
+	public addPeer(peerInfo: P2PPeerInfo): CustomPeerInfo | undefined {
+		if (this.getPeer(peerInfo)) {
+			throw new Error('Peer already exists');
```
[the remark this answers is not in the document]
Comment (diego-G) [reply elements/lisk-p2p/src/peer_book/base_list.ts]: The bucket must always exist. When you add a peer the only exception that might arise is the peer already exists.

File: elements/lisk-p2p/src/peer_book/utils.ts (hunk 3 above)
Comment (diego-G) [reply elements/lisk-p2p/src/peer_book/utils.ts]: Where would you place them?

File: elements/lisk-p2p/src/peer_book/base_list.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (mitsujutsu) [reply elements/lisk-p2p/src/peer_book/base_list.ts]: Currently it looks like whereever `addPeer` is called there is a check to see if it already exists using `getPeer`

File: elements/lisk-p2p/src/peer_book/base_list.ts (hunk 1 above)
Comment (mitsujutsu) [reply elements/lisk-p2p/src/peer_book/base_list.ts]: I am not sure about the naming. maybe `checkBucket`

File: elements/lisk-p2p/src/peer_book/utils.ts [hunk 5]
```diff
@@ -0,0 +1,135 @@
...
+	const bucketPeerIds = Array.from(bucket.keys());
+	const randomPeerIndex = Math.floor(Math.random() * bucketPeerIds.length);
+	const randomPeerId = bucketPeerIds[randomPeerIndex];
+	const evictedPeer = bucket.get(randomPeerId);
+	bucket.delete(randomPeerId);
+
+	return evictedPeer;
+};
+
+export const evictAnOldPeerFromBucket = (
```
Comment (mitsujutsu) [inline elements/lisk-p2p/src/peer_book/utils.ts]: prefer `expirePeerFromBucket`

File: elements/lisk-p2p/src/utils/misc.ts [hunk 6]
```diff
@@ -119,82 +117,6 @@ export const getNetgroup = (address: string, secret: number): number => {
 	return hash(netgroupBytes).readUInt32BE(0);
 };
```
Comment (mitsujutsu) [inline elements/lisk-p2p/src/utils/misc.ts]: These functions can remain here and the new `util` functions can also move here, instead of having `util` files on different levels.

File: elements/lisk-p2p/src/peer_book/utils.ts [hunk 7]
```diff
@@ -0,0 +1,135 @@
+/*
```
[the remark this answers is not in the document]
Comment (mitsujutsu) [reply elements/lisk-p2p/src/peer_book/utils.ts]: prefer to keep it where the `getBucketId` function is.

[the remark this answers is not in the document]
Comment (diego-G) [reply elements/lisk-p2p/src/peer_book/utils.ts]: I've moved `getBucketId()` util as well. Before it was placed into `utils/misc`. I don't see a big issue having these utils separated under `peer_book/`.  They are very specific and I don't foresee them used in another place.

[the remark this answers is not in the document]
Comment (mitsujutsu) [reply elements/lisk-p2p/src/peer_book/utils.ts]: I think they can all be in the `utils/misc` file in the base level where it was previously. imo there is no need for two levels of `utils` files.

File: elements/lisk-p2p/src/peer_book/base_list.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (diego-G) [reply elements/lisk-p2p/src/peer_book/base_list.ts]: I've added this commit https://github.com/LiskHQ/lisk-sdk/pull/4377/commits/ba6b41de56528d91685c08aab46c31525da88bba .

File: elements/lisk-p2p/src/peer_book/base_list.ts (hunk 1 above)
Comment (diego-G) [reply elements/lisk-p2p/src/peer_book/base_list.ts]: At the end, all of them are incomplete. MakeSpace is simply and we just need to write in the header that it does it if there is not space.

Comment (ishantiw) [reply elements/lisk-p2p/src/peer_book/base_list.ts]: Yes, let's keep it simple as of now
