### PR TITLE
Delegate without valid hash onion is unable to forge - Closes #5793

### LINKED ISSUE #5793: Delegate without valid hash onion is unable to forge
### Expected behavior
Delegate without a valid hash onion or seed reveal CAN forge but is not rewarded if it does not miss last 2 rounds (current round+last round)

### Actual behavior
Delegate without any hash onion or seed reveal FAILS to forge
Delegate with a invalid(whose pre-image does not match the last used) hash onion FAILS to forge

```
ERROR lisk-framework: Invalid block reward: 0 expected: 500000000 (module=lisk:app)
Message: Invalid block reward: 0 expected: 500000000 
 Trace: Error: Invalid block reward: 0 expected: 500000000
    at BFT.verifyBlockHeader (~/lisk-sdk/elements/lisk-bft/src/bft.ts:102:10)
    at Processor._processValidated (~/lisk-sdk/framework/src/node/processor/processor.ts:347:3)
    at Object.worker (~/lisk-sdk/framework/src/node/processor/processor.ts:225:4)
    at JobQueue._tick (~/lisk-sdk/elements/lisk-utils/src/job_handlers/job_queue.ts:109:19)
    at Timeout.nextJobQueue [as _onTimeout] (~/lisk-sdk/elements/lisk-utils/src/job_handlers/job_queue.ts:62:4)
```

### Steps to reproduce

1. Change the config.json to alter the hash onions of a "particular delegate" to empty or random values
2. Run a node including the above config with forging disabled intially
3. Enable the "particular delegate" and optionally a few others to forge
4. Wait for atleast 2 rounds and check the console log

### Which version(s) does this affect? (Environment, OS, etc...)
5.0

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #5793 

### How was it solved?

- Expose a function to return expected reward which also take seed reveal in consideration
- Use expected reward to calculate quarter fee

### How was it tested?

- Add integration test
- Run a node from scratch and wait for 1 round, and change seed reveal of on one of the delegate, and check if the delegate creates a block with 0 reward and being accepted

### CODE REVIEW

File: framework/src/node/forger/forger.ts [hunk 1]
```diff
@@ -580,11 +580,21 @@ export class Forger {
 		// Reduce reward based on BFT rules
 		if (!isBFTProtocolCompliant) {
 			header.reward /= BigInt(4);
+			this._logger.warn(
+				{ originalReward: reward.toString(), deducted: header.reward.toString() },
```
Comment (ManuGowda) [inline framework/src/node/forger/forger.ts:584]:
```suggestion
				{ originalReward: reward.toString(), deductedReward: header.reward.toString() },
```

File: framework/src/node/forger/forger.ts [hunk 2]
```diff
@@ -580,11 +580,21 @@ export class Forger {
...
+				'Deducting reward due to BFT violation',
+			);
+		}
+		// Reduce reward based on SeedReveal rules
+		const validSeedReveal = this._chainModule.isValidSeedReveal(header as BlockHeader, stateStore);
+		if (!validSeedReveal) {
+			const originalReward = header.reward.toString();
+			header.reward = BigInt(0);
+			this._logger.warn(
+				{ originalReward, deducted: header.reward.toString() },
```
Comment (ManuGowda) [inline framework/src/node/forger/forger.ts:594]:
```suggestion
				{ originalReward, deductedReward: header.reward.toString() },
```

**Review by ManuGowda — APPROVED** [review]

**Review by Incede — APPROVED** [review]
