### PR TITLE
Dpos.getRoundDelegates returns outdated list - Closes #4147

### LINKED ISSUE #4147: Dpos.getRoundDelegates returns outdated list
### Expected behavior
I expect to get the correct list of delegates when calling `Dpos.getRoundDelegates` after a new round is reverted and previous round changes the delegate list.

### Actual behavior
It always uses the cached list ignoring possible changes on the list when a block is reverted.

### Steps to reproduce

1. Call `Dpos.getRoundDelegates(R2)` where `R2` is the beginning of a new round
2. Revert the last blocks so that we return to the previous round (`R1`)
3. Unvote an active delegate and vote for a new one during the previous round (`R1`)
4. Call `Dpos.getRoundDelegates(R2)` again in the beginning of the next round (`R2`)

Because `Dpos.getRoundDelegates` caches every new list and never clears it, it returns an outdated list ignoring the changes made after the last block of the round is reverted.

Step 4 should return a new delegate list including the new voted delegate and excluding the unvoted delegate.

### Which version(s) does this affect? (Environment, OS, etc...)
`feature/introduce_bft_consensus`

### PR DESCRIPTION
**Pull request by yatki**
### What was the problem?
Dpos.getRoundDelegates was returning an outdated delegate list after reverting the last block of previous round.
### How did I solve it?
I made sure on undo operations we are invalidating the cache for upcoming rounds.
### Review checklist

- [x] The PR resolves #4147 
- [x] All new code is covered with unit tests
- [x] Relevant integration / functional tests are added - Will be done in https://github.com/LiskHQ/lisk-sdk/issues/4192
- [x] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [x] Documentation has been added/updated

### CODE REVIEW

**Comment by lsilvs** [comment]
`Dpos.getRoundDelegates` unit tests are missing. Can you add them, bitte?

File: framework/src/modules/chain/dpos/delegates_list.js [hunk 1]
```diff
@@ -48,6 +48,12 @@ class DelegatesList extends EventEmitter {
 		this.exceptions = exceptions;
 	}
 
+	deleteDelegateListFromCache(round) {
+		if (this.delegateListCache[round]) {
+			delete this.delegateListCache[round];
```
Comment (lsilvs) [inline framework/src/modules/chain/dpos/delegates_list.js]: I reckon it would be safer to clear everything after `round`

Comment (lsilvs) [reply framework/src/modules/chain/dpos/delegates_list.js]: Also I think we need to clear `RoundDelegates` entry in the database?

File: framework/src/modules/chain/components/storage/entities/round_delegates.js [hunk 2]
```diff
@@ -71,6 +71,10 @@ class RoundDelegates extends BaseEntity {
 		this.SQLs = this.loadSQLFiles('dpos', sqlFiles, this.sqlDirectory);
 	}
 
+	/**
+	 * @returns {string[]} delegatePublicKeys
+	 */
+
```
Comment (michielmulders) [inline framework/src/modules/chain/components/storage/entities/round_delegates.js]: Minor thingy:
- Remove empty line between description and function declaration
- This code has been there, but it is very hard to know for someone reading the code what `result[0]` means? Please add some clarification if possible.

File: framework/src/modules/chain/dpos/delegates_info.js [hunk 3]
```diff
@@ -85,6 +85,16 @@ class DelegatesInfo {
 
 		// Perform updates that only happens in the end of the round
 		if (this._isLastBlockOfTheRound(block)) {
+			if (undo) {
```
Comment (michielmulders) [inline framework/src/modules/chain/dpos/delegates_info.js]: Can you also remove the `@todo` mention and add a small description for the `_update` function as it's a generic name. (out of scope+-)

File: framework/src/modules/chain/dpos/delegates_list.js [hunk 4]
```diff
@@ -88,11 +88,30 @@ class DelegatesList extends EventEmitter {
 	}
 
 	async deleteDelegateListUntilRound(round) {
+		this.deleteDelegateListsFromCache(r => r < round);
```
Comment (michielmulders) [inline framework/src/modules/chain/dpos/delegates_list.js]: Can you pick a more meaningful name for `r`? :)
Something like `roundFromCache`?

File: framework/src/modules/chain/dpos/delegates_list.js [hunk 5]
```diff
@@ -88,11 +88,30 @@ class DelegatesList extends EventEmitter {
...
 		await this.storage.entities.RoundDelegates.delete({
 			round_lt: round,
 		});
 	}
 
+	async deleteDelegateListAfterRound(round, tx) {
+		this.deleteDelegateListsFromCache(r => r > round);
```
Comment (michielmulders) [inline framework/src/modules/chain/dpos/delegates_list.js]: Same here, would prefer a more descriptive name

File: framework/src/modules/chain/dpos/delegates_list.js [hunk 6]
```diff
@@ -88,11 +88,30 @@ class DelegatesList extends EventEmitter {
...
+			{
+				round_gt: round,
+			},
+			tx,
+		);
+	}
+
+	deleteDelegateListsFromCache(filterCb) {
+		Object.keys(this.delegateListCache)
+			.filter(filterCb)
```
Comment (michielmulders) [inline framework/src/modules/chain/dpos/delegates_list.js]: Is this a filter function? Mabye `filterFn`?

File: framework/src/modules/chain/dpos/dpos.js [hunk 7]
```diff
@@ -24,7 +24,7 @@ module.exports = class Dpos {
 		this.delegatesList = new DelegatesList({
 			storage,
 			logger,
-			slots,
+      slots,
```
Comment (michielmulders) [inline framework/src/modules/chain/dpos/dpos.js]: formatting issue

Comment (michielmulders) [reply framework/src/modules/chain/dpos/dpos.js]: Fixed!

File: framework/src/modules/chain/dpos/delegates_list.js (hunk 6 above)
Comment (yatki) [reply framework/src/modules/chain/dpos/delegates_list.js]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter#Syntax in the api description they called it callback so did i :D

Comment (michielmulders) [reply framework/src/modules/chain/dpos/delegates_list.js]: I hate any reference to the callback era :D I saw some other implementations where they call it `lambdaFn` `fn` `filterFn`, feel free to pick what feels appropriate or use the standard by Mozilla :)

File: framework/src/modules/chain/processor/processor.js [hunk 8]
```diff
@@ -157,8 +157,8 @@ class Processor {
 
 	async create(values) {
 		this.logger.debug({ data: values }, 'creating block');
-		const heghestVersion = Math.max.apply(null, Object.keys(this.processors));
-		const processor = this.processors[heghestVersion];
+		const highestVersion = Math.max.apply(null, Object.keys(this.processors));
```
Comment (shuse2) [inline framework/src/modules/chain/processor/processor.js]: 🙇

File: framework/test/jest/unit/specs/modules/chain/dpos/getRoundDelegates/utils.js [hunk 9]
```diff
@@ -0,0 +1,24 @@
+const { hash } = require('@liskhq/lisk-cryptography');
```
Comment (shuse2) [inline framework/test/jest/unit/specs/modules/chain/dpos/getRoundDelegates/utils.js]: please add the license header

File: framework/test/jest/unit/specs/modules/chain/dpos/getRoundDelegates/getRoundDelegates.spec.js [hunk 10]
```diff
@@ -0,0 +1,128 @@
+const { when } = require('jest-when');
```
Comment (shuse2) [inline framework/test/jest/unit/specs/modules/chain/dpos/getRoundDelegates/getRoundDelegates.spec.js]: please add the license header

File: framework/src/modules/chain/components/storage/entities/round_delegates.js [hunk 11]
```diff
@@ -120,7 +128,7 @@ class RoundDelegates extends BaseEntity {
 	 * @param {Object} [tx]
 	 * @returns {Promise.<boolean, Error>}
 	 */
-	delete(filters, _options, tx = null) {
+	delete(filters, tx = null) {
```
Comment (SargeKhan) [inline framework/src/modules/chain/components/storage/entities/round_delegates.js]: Why we remove the options parameter? Maybe it makes sense to follow the consistent interface for the entities.

File: framework/src/modules/chain/dpos/delegates_info.js [hunk 12]
```diff
@@ -76,7 +76,11 @@ class DelegatesInfo {
...
 	 */
 	async _update(block, undo, tx) {
-		// @todo add proper description
+		/**
+		 * If the block height is 1, that means the block is
+		 * the genesis block, in that case we don't have to
+		 * update anything in the accounts.
+		 */
 		if (block.height === 1) {
 			return false;
```
Comment (SargeKhan) [inline framework/src/modules/chain/dpos/delegates_info.js]: what does returning false/true signify here? Also, out of scope, but don't we need to update the `_updateVotedDelegatesVoteWeight` for geneisBlock?

File: framework/src/modules/chain/dpos/delegates_list.js [hunk 13]
```diff
@@ -88,11 +88,30 @@ class DelegatesList extends EventEmitter {
...
+		await this.storage.entities.RoundDelegates.delete(
+			{
+				round_gt: round,
+			},
+			tx,
+		);
+	}
+
+	deleteDelegateListsFromCache(filterFn) {
+		Object.keys(this.delegateListCache)
```
Comment (SargeKhan) [inline framework/src/modules/chain/dpos/delegates_list.js]: Probably makes more sense to do to more functionaly. Something like:
```
this.delegateListCache = Object.keys(this.delegateListCache).filter(filterFn)
    .reduce((newDelegateListCache, roundFromCacheToKeep) => { 
        newDelegateListCache[roundFromCacheToKeep] = this.delegateListCahe[roundFromCacheToKeep];
       return newDelegateListCache;
    }, {})

File: framework/src/modules/chain/dpos/delegates_info.js [hunk 14]
```diff
@@ -85,6 +89,16 @@ class DelegatesInfo {
 
 		// Perform updates that only happens in the end of the round
 		if (this._isLastBlockOfTheRound(block)) {
+			if (undo) {
```
Comment (SargeKhan) [inline framework/src/modules/chain/dpos/delegates_info.js]: Does it maybe make more sense to have another function. Something like: `updateDelegateListAtTheEndOfRound`. This function, when called with undo can delete the delegate list, otherwise, in case of apply, it will create the delegate list for the new round.

File: framework/test/jest/unit/specs/modules/chain/dpos/getRoundDelegates/getRoundDelegates.spec.js [hunk 15]
```diff
@@ -0,0 +1,128 @@
...
+				.calledWith(roundNo)
+				.mockResolvedValue([]);
+			stubs.storage.entities.Account.get.mockResolvedValue(delegateAccounts);
+			shuffledList = shuffleDelegateListForRound(roundNo, delegatePublicKeys);
+
+			// Act
+			list = await dpos.getRoundDelegates(roundNo);
+		});
+
+		it('should return shuffled delegate list by using delegate accounts', () => {
```
Comment (SargeKhan) [inline framework/test/jest/unit/specs/modules/chain/dpos/getRoundDelegates/getRoundDelegates.spec.js]: Imagine the current round is 2 and we have the entry for the current round in the round_delegates table. If getRoundDelegates function is called with round number 4 or 5, what will happen? Will it throw an error or will be generate invalid delegateList for the round in the future?

File: framework/test/jest/unit/specs/modules/chain/dpos/getRoundDelegates/utils.js [hunk 16]
```diff
@@ -0,0 +1,24 @@
...
+
+const shuffleDelegateListForRound = (round, list) => {
```
Comment (lsilvs) [inline framework/test/jest/unit/specs/modules/chain/dpos/getRoundDelegates/utils.js]: Shouldn't we avoid having implementation to test implementation? Maybe here we should use a known list instead of re-implementing the `shuffleDelegateListForRound`

File: framework/src/modules/chain/components/storage/entities/round_delegates.js (hunk 11 above)
Comment (yatki) [reply framework/src/modules/chain/components/storage/entities/round_delegates.js]: But it's not used anywhere in the method? :D

File: framework/src/modules/chain/dpos/delegates_info.js (hunk 12 above)
Comment (yatki) [reply framework/src/modules/chain/dpos/delegates_info.js]: Nothing actually. It's just the termination of the method. 

Based on the previous rounds implementation it seems we were not doing it. But if there is a case that genesisBlock can contain vote transactions from a delegate to someone else maybe we should do it? @shuse2 ?

File: framework/src/modules/chain/dpos/delegates_list.js (hunk 13 above)
Comment (yatki) [reply framework/src/modules/chain/dpos/delegates_list.js]: But here, the filtered rounds have to be deleted. This function is keeping everything. Also, we'll get rid of cache mechanism #4217. So this code gonna be removed very very soon :D

File: framework/test/jest/unit/specs/modules/chain/dpos/getRoundDelegates/utils.js (hunk 16 above)
Comment (yatki) [reply framework/test/jest/unit/specs/modules/chain/dpos/getRoundDelegates/utils.js]: delegateList changes by roundNumber and to sake of avoiding having hardcoded values in tests I'm generating round number randomly. Thus, I wanted to have the shuffle logic as utils. Also I wanted to avoid using original implementation just in case something breaks there. 

I think this is a better way to go and maybe mowing shuffle logic to elements is the way to go?

File: framework/src/modules/chain/components/storage/entities/round_delegates.js (hunk 11 above)
[the remark this answers is not in the document]
Comment (yatki) [reply framework/src/modules/chain/components/storage/entities/round_delegates.js]: As i said earlier, it wasn't being used. If you and @SargeKhan didn't like this, I can revert it instead of modifying other functions in this pr.

File: framework/src/modules/chain/dpos/delegates_info.js (hunk 14 above)
Comment (yatki) [reply framework/src/modules/chain/dpos/delegates_info.js]: I agree with this also your other concern if we provide a future round number to getRoundDelegates method make sense. I'll create a separate issue to tackle that.https://github.com/LiskHQ/lisk-sdk/issues/4218

File: framework/test/jest/unit/specs/modules/chain/dpos/getRoundDelegates/getRoundDelegates.spec.js (hunk 15 above)
Comment (yatki) [reply framework/test/jest/unit/specs/modules/chain/dpos/getRoundDelegates/getRoundDelegates.spec.js]: https://github.com/LiskHQ/lisk-sdk/issues/4218

File: framework/src/modules/chain/dpos/delegates_list.js (hunk 13 above)
Comment (SargeKhan) [reply framework/src/modules/chain/dpos/delegates_list.js]: We are reassigning the variable: `this.delegateListCache` in the code I shared above. The value of this object will not contain the delegateList for rounds which fail the filter condition. So, it's irrelevant if we delete keys from the old delegateListCache object. Right? 
Also, this is not refactoring of some old code. I am suggesting changes in the code which was added as part of this PR. So, doesn't it make sense to add code which is cleaner?

File: framework/src/modules/chain/dpos/delegates_info.js (hunk 12 above)
Comment (SargeKhan) [reply framework/src/modules/chain/dpos/delegates_info.js]: GenesisBlock contains delegate registeration as well as vote transactions. I wonder how it was syncing with the testnet. @lsilvs what do you think?

File: framework/src/modules/chain/dpos/delegates_list.js (hunk 13 above)
Comment (yatki) [reply framework/src/modules/chain/dpos/delegates_list.js]: @SargeKhan filter conditions that were used in the other functions were returning only the rounds to be deleted. That's what i meant so reduce only iterates on the rounds to be deleted in that case. But we can negate those conditions. That's not a problem.

What I mean is, the whole caching logic will be deleted, so this function will be deleted completely. So there is no need to refactor it to be functional.

File: framework/src/modules/chain/dpos/delegates_info.js (hunk 12 above)
Comment (shuse2) [reply framework/src/modules/chain/dpos/delegates_info.js]: dpos module only do the apply for `reward` and `fee`, which does not exists on the genesis block now.
Therefore, in our case it should work now.

File: framework/test/jest/unit/specs/modules/chain/dpos/getRoundDelegates/utils.js (hunk 16 above)
Comment (shuse2) [reply framework/test/jest/unit/specs/modules/chain/dpos/getRoundDelegates/utils.js]: This shuffle logic is essential part of the DPOS module. I don't think it make sense to move to any other parts.
I also think instead of generating the implementation by implementation, it's better to use fixture in this case
Since it's very hard to test, we should add specific test for this function (although it's not public function) with fixture.

File: framework/test/jest/unit/specs/modules/chain/dpos/getRoundDelegates/getRoundDelegates.spec.js [hunk 17]
```diff
@@ -0,0 +1,144 @@
...
+			},
+		};
+
+		dpos = new Dpos({
+			...stubs,
+			activeDelegates: constants.ACTIVE_DELEGATES,
+		});
+	});
+
+	describe('When non-shuffled delegate public keys for the round IS in the cache', () => {
```
Comment (shuse2) [inline framework/test/jest/unit/specs/modules/chain/dpos/getRoundDelegates/getRoundDelegates.spec.js]: Probably it's better to add a case where it should fail if table and cache doesn't exist but in the middle of the round?

File: framework/src/modules/chain/dpos/delegates_info.js (hunk 12 above)
Comment (lsilvs) [reply framework/src/modules/chain/dpos/delegates_info.js]: Among all updates performed during `Dpos.apply`, only `_updateProducedBlocks` would be relevant for genesis block because genesis block is not the last block of the round. As the genesis block forger is not even a delegate account, we don't update its `producedBlocks` column.

PS: Note that `_updateVotedDelegatesVoteWeight` is not related to vote transactions included in the block. It's related to the accounts that the block forger voted for.

File: framework/test/jest/unit/specs/modules/chain/dpos/getRoundDelegates/getRoundDelegates.spec.js (hunk 17 above)
Comment (shuse2) [reply framework/test/jest/unit/specs/modules/chain/dpos/getRoundDelegates/getRoundDelegates.spec.js]: Since the implementation is changed, agreed to test it on the coming PR

File: framework/test/jest/unit/specs/modules/chain/dpos/undo.spec.js [hunk 18]
```diff
@@ -95,6 +96,22 @@ describe('dpos.undo()', () => {
 	});
 
 	describe('Given block is NOT the last block of the round', () => {
+		it('should delete delegate list for rounds which are after the current round', async () => {
```
Comment (lsilvs) [inline framework/test/jest/unit/specs/modules/chain/dpos/undo.spec.js]:
```suggestion
		it('should NOT delete delegate list for rounds which are after the current round', async () => {
```
