### PR TITLE
Resolve tilde - Closes #6017

### LINKED ISSUE #6017: Update createIPCClient to allow "~"
### Expected behavior
createIPCClient should accept relative path, absolute path and path with `~`

### Actual behavior
`~` cannot be used for the input.

### Steps to reproduce
Create IPCClient with `~/.lisk/lisk-core`

### Which version(s) does this affect? (Environment, OS, etc...)
5.0-

### PR DESCRIPTION
**Pull request by Incede**
### What was the problem?

This PR resolves #6017 

### How was it solved?

* Resolve tilde before setting up socket directories

### How was it tested?

Tested manually by linking to the local `lisk-api-client` and `createIPCClient('~/.lisk/lisk-core')`

### CODE REVIEW

File: elements/lisk-api-client/src/ipc_channel.ts [hunk 1]
```diff
@@ -34,7 +35,8 @@ import { convertRPCError } from './utils';
 const CONNECTION_TIME_OUT = 2000;
 
 const getSocketsPath = (dataPath: string) => {
-	const socketDir = path.join(path.resolve(dataPath), 'tmp', 'sockets');
+	const dataPathWithoutTilde = dataPath.replace('~', homedir());
+	const socketDir = path.join(path.resolve(dataPathWithoutTilde), 'tmp', 'sockets');
```
Comment (ManuGowda) [inline elements/lisk-api-client/src/ipc_channel.ts:39]:
```suggestion
	const socketDir = path.join(dataPath.replace('~', homedir()), 'tmp', 'sockets');
```

Comment (Incede) [reply elements/lisk-api-client/src/ipc_channel.ts:39]: I think this will not work for relative data paths like `./myDir`.
Although can be reformatted as 
`const socketDir = path.join(path.resolve(dataPath.replace('~', homedir())), 'tmp', 'sockets');`

**Review by ManuGowda — APPROVED** [review]

**Review by mitsuaki-u — APPROVED** [review]
LGTM but jenkins still failling
