### PR TITLE
Chai-as-promised assertions are giving false positives - Closes #3956

### LINKED ISSUE #3956: Chai-as-promised assertions are giving false positives
### Expected behavior
assertions that use `eventually` matcher should be awaited/returned. Otherwise they are giving false positives.

Example: 
```js
// file: framework/test/mocha/unit/modules/chain/submodules/blocks/verify.js
// Correct
it('should throw error when transaction is already confirmed', async () => {
  await expect(
    __private.checkTransactions(dummyBlock, true)
  ).to.eventually.be.rejectedWith('memo');
});
```

The test above will fail because ıt's not being rejected with `memo`.
### Actual behavior

We are not awaiting/returning the async assertions. So tests are giving false positives.

Example:

```js
// Wrong
it('should throw error when transaction is already confirmed', async () => {
  await expect(
    __private.checkTransactions(dummyBlock, true)
  ).to.eventually.be.rejectedWith('memo');
});
```

The test above will **PASS** even though it's not being rejected with `memo`. But it shouldn't pass.

### Which version(s) does this affect? (Environment, OS, etc...)
I suggest to solve this in 2.0

### PR DESCRIPTION
**Pull request by yatki**
### What was the problem?
Async assertions were not awaited or returned thus giving false possitive in mocha tests.
### How did I fix it?
I returned the async assertions
### Review checklist

* The PR resolves #3956 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/test/mocha/integration/state_store/round_store.js [hunk 1]
```diff
@@ -63,7 +63,7 @@ describe('system test - round store', () => {
 
 	describe('cache', () => {
 		it('should throw ', async () => {
-			expect(roundStore.cache()).to.eventually.throw(
+			return expect(roundStore.cache()).to.eventually.throw(
```
Comment (lsilvs) [inline framework/test/mocha/integration/state_store/round_store.js]: Tests failing for this one. Changing to the following should fix it:

```suggestion
			return expect(roundStore.cache()).to.be.rejectedWith(
```

Comment (yatki) [reply framework/test/mocha/integration/state_store/round_store.js]: @lsilvs cache is an async function right? So I think eventually should stay there.

Comment (lsilvs) [reply framework/test/mocha/integration/state_store/round_store.js]: When you use `rejected` or `fulfilled` the `eventually` is implicit, I guess. But should work with it as well.

File: framework/test/mocha/unit/modules/chain/submodules/blocks/verify.js [hunk 2]
```diff
@@ -1794,8 +1794,8 @@ describe('blocks/verify', () => {
 					});
 
 					it('should throw error when transaction is already confirmed', async () => {
-						expect(__private.checkTransactions(dummyBlock, true)).to.eventually
-							.rejected;
+						return expect(__private.checkTransactions(dummyBlock, true)).to
+							.eventually.rejected;
```
Comment (lsilvs) [inline framework/test/mocha/unit/modules/chain/submodules/blocks/verify.js]: Would be nice to be explicit here and add the expected message using `rejectedWith` instead of `rejected` only

File: framework/test/mocha/unit/modules/chain/submodules/blocks/verify.js [hunk 3]
```diff
@@ -1835,8 +1835,8 @@ describe('blocks/verify', () => {
 						modules.processTransactions.verifyTransactions.resolves(
 							invalidTransactionsResponse
 						);
-						expect(__private.checkTransactions(dummyBlock, true)).to.eventually
-							.throw;
+						return expect(__private.checkTransactions(dummyBlock, true)).to
+							.eventually.throw;
```
Comment (lsilvs) [inline framework/test/mocha/unit/modules/chain/submodules/blocks/verify.js]: Same as above

File: framework/test/mocha/unit/modules/chain/submodules/blocks/verify.js [hunk 4]
```diff
@@ -1859,8 +1859,8 @@ describe('blocks/verify', () => {
 					],
 				});
 
-				expect(__private.checkTransactions(dummyBlock, false)).to.eventually.be
-					.rejected;
+				return expect(__private.checkTransactions(dummyBlock, false)).to
+					.eventually.be.rejected;
```
Comment (lsilvs) [inline framework/test/mocha/unit/modules/chain/submodules/blocks/verify.js]: Same as above

File: framework/test/mocha/unit/modules/chain/logic/broadcaster.js [hunk 5]
```diff
@@ -483,7 +483,9 @@ describe('Broadcaster', () => {
 				.rejects(new Error('failed to broadcast'));
 			broadcaster.filterQueue = filterQueueStub;
 			broadcaster.enqueue(params, options);
-			expect(broadcaster.releaseQueue()).rejectedWith('failed to broadcast');
+			return expect(broadcaster.releaseQueue()).to.eventually.be.rejectedWith(
+				'failed to broadcast2'
```
Comment (lsilvs) [inline framework/test/mocha/unit/modules/chain/logic/broadcaster.js]:
```suggestion
				'failed to broadcast'
```

File: framework/test/mocha/unit/modules/chain/components/storage/entities/account.js [hunk 6]
```diff
@@ -219,9 +224,11 @@ describe('ChainAccount', () => {
 				new accountFixtures.Account(),
 			];
 
-			expect(AccountEntity.create(accounts)).to.be.fulfilled;
+			await expect(
+				AccountEntity.create(accounts)
+			).to.eventually.be.fulfilled.and.deep.equal([]);
 
-			accounts.forEach(async account => {
+			return accounts.map(async account => {
```
Comment (lsilvs) [inline framework/test/mocha/unit/modules/chain/components/storage/entities/account.js]: I think we need a `Promise.all` here
