### PR TITLE
Fix the cache loading to be consistent - Closes #4776

### LINKED ISSUE #4776: BFT header cache is not working properly
### Expected behavior
* BFT header cache should at least save last 303 blocks
* BFT header should search through last 303 blocks

### Actual behavior
In the start up, it only holds cache up to 202 blocks.
In case the cache is requested with more length than the holding size, it returns incorrect value

### Steps to reproduce
* request cache with higher value than the actual contents
* Check the length of cache after initialization

### Which version(s) does this affect? (Environment, OS, etc...)
3.0-

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?
The PR resolves #4776 

### How did I solve it?
Update the parameter to be 3 rounds in stead of 2.
Fix the cache `top` mechanism to return value

### How to manually test it?
- Start double forging using 2 nodes, and on the second round, restart one of the nodes, and check the validation is correct

### CODE REVIEW

File: framework/src/modules/chain/bft/bft.js [hunk 1]
```diff
@@ -197,7 +199,8 @@ class BFT extends EventEmitter {
 		// Check BFT migration height
 		// https://github.com/LiskHQ/lips/blob/master/proposals/lip-0014.md#backwards-compatibility
 		const bftMigrationHeight =
-			this.constants.startingHeight - this.constants.activeDelegates * 2;
+			this.constants.startingHeight -
+			this.constants.activeDelegates * BFT_ROUND_THRESHOLD;
```
Comment (nazarhussain) [inline framework/src/modules/chain/bft/bft.js]: This variable `bftMigrationHeight ` is used to initialize the `finalizedHeight `. This value is clearly documented in LIP to be 202 blocks from the height of migraiton. Can we discuss with science team before making this change. 

> we propose that chainMaxHeightFinalized is initialized with the value l-202

https://github.com/LiskHQ/lips/blob/master/proposals/lip-0014.md#backwards-compatibility

File: framework/src/modules/chain/bft/bft.js [hunk 2]
```diff
@@ -72,7 +73,7 @@ class BFT extends EventEmitter {
 
 		const loadFromHeight = Math.max(
 			finalizedHeight,
-			lastBlockHeight - this.constants.activeDelegates * 2,
+			lastBlockHeight - this.constants.activeDelegates * BFT_ROUND_THRESHOLD,
```
Comment (nazarhussain) [inline framework/src/modules/chain/bft/bft.js]: Can we make it more readable, may be assign this value in initialiser. 

```js
this.constants = {
   activeDelegates, 
   startingHeight,
   twoRounds: activeDelegates * 2,
   threeRounds: activeDelegates * 3,
}
```

And then use it here...

```js
lastBlockHeight - this.constants.threeRounds,
```

This looks more clear while reading the code logic.

File: framework/src/modules/chain/bft/bft.js [hunk 3]
```diff
@@ -112,14 +113,15 @@ class BFT extends EventEmitter {
...
 		if (
 			this.finalityManager.maxHeight - this.finalityManager.minHeight <
-			this.constants.activeDelegates * 2
+			this.constants.activeDelegates * BFT_ROUND_THRESHOLD
 		) {
 			const tillHeight = this.finalityManager.minHeight - 1;
 			const fromHeight =
-				this.finalityManager.maxHeight - this.constants.activeDelegates * 2;
+				this.finalityManager.maxHeight -
+				this.constants.activeDelegates * BFT_ROUND_THRESHOLD;
```
Comment (nazarhussain) [inline framework/src/modules/chain/bft/bft.js]: The LIP defined 

> we need to ensure that the block headers of the blocks at heights A.height-302 up to height A.height are contained in memory

https://github.com/LiskHQ/lips/blob/master/proposals/lip-0014.md#reverting-blocks

This becomes having exactly 303 blocks in headers. Above logic will lead to 304 Blocks instead. Remember this `tillHeight` and `fromHeight` are inclusive. If we already have headers from `451-590`, above calculation will make sure to have `287-590`, this range when inclusive become 304 blocks.

File: framework/src/modules/chain/bft/bft.js (hunk 2 above)
Comment (nazarhussain) [inline framework/src/modules/chain/bft/bft.js]: This calculation also end up loading 304 blocks.

Comment (shuse2) [reply framework/src/modules/chain/bft/bft.js]: Instead of having 2 rounds, 3 rounds, I would prefer to have the 2 different constants and used accordingly

File: framework/src/modules/chain/bft/headers_list.js [hunk 4]
```diff
@@ -112,6 +112,10 @@ class HeadersList {
 	top(size) {
 		assert(size, 'Please provide the size');
 
+		if (this.length <= size) {
+			return [...this._items];
+		}
+
```
Comment (nazarhussain) [inline framework/src/modules/chain/bft/headers_list.js]: It was a very minor logical error, should have been catched in development/review cycle.  🤦‍♂
