### PR TITLE
Replace asset.moduleID with asset.module

### LINKED ISSUE #7465: Lisk API client fails on getting blocks
### Expected behavior

Lisk API Client should be able to get blocks and transactions

### Actual behavior

When we get block by ID then it throws error because getAssetSchema is getting schema using `moduleID` instead of `module`
https://github.com/LiskHQ/lisk-sdk/blob/c7d572296ccb9f89f8bf21af64230ecaaedf8a84/elements/lisk-api-client/src/codec.ts#L58

### Steps to reproduce

- Run `/examples/dpos-mainchain/bin/run start --api-ipc`
- In another terminal run `/examples/dpos-mainchain/bin/run block:get ba690c03d637b20a309d0d80281b3dbda5b55680e95894d72c59eb0f3e899d60`

### Which version(s) does this affect? (Environment, OS, etc...)

`6.0.0-alpha`

### PR DESCRIPTION
**Pull request by sitetester**
### What was the problem?

This PR resolves #7465 

### How was it solved?

asset.moduleID replaced with asset.module

### How was it tested?
- `cd /lisk-sdk/examples/dpos-mainchain`
-  `nano ~/.lisk/dpos-mainchain/config/default/config.json`
- change to `ipc` like this 
```
"rpc": {
                "modes": ["ipc"]
        },
```
- `./bin/run start`
- `./bin/run block:get bef09f78d1c7e14780046762b630431759919f5255866fae418cea14b9c962d3 --pretty` (in separate terminal)

### CODE REVIEW

**Review by ishantiw — COMMENTED** [review]
Looks good, Maybe also rename these error messages `moduleID`->`module`

https://github.com/LiskHQ/lisk-sdk/blob/c7d572296ccb9f89f8bf21af64230ecaaedf8a84/elements/lisk-api-client/src/codec.ts#L45

https://github.com/LiskHQ/lisk-sdk/blob/c7d572296ccb9f89f8bf21af64230ecaaedf8a84/elements/lisk-api-client/src/codec.ts#L52

**Review by Phanco — APPROVED** [review]

File: elements/lisk-api-client/src/codec.ts [hunk 1]
```diff
@@ -189,7 +189,7 @@ export const decodeAssets = (
 	for (const asset of assets) {
 		const assetSchema = getAssetDataSchema(
 			blockVersion,
-			{ moduleID: asset.moduleID.toString('hex') },
+			{ module: asset.module.toString('hex') },
```
Comment (shuse2) [inline elements/lisk-api-client/src/codec.ts:192]: `asset.module` is string, so it shouldnt need `toString`

Comment (ishantiw) [reply elements/lisk-api-client/src/codec.ts:192]: @sitetester You need to update BlockAsset and Event interfaces in `lisk-api-client` (module type from Buffer to string)

**Review by ishantiw — APPROVED** [review]

**Review by shuse2 — APPROVED** [review]
