### PR TITLE
Some transaction events are not being broadcasted - Closes #3962

### LINKED ISSUE #3962: Some transaction events are not being broadcasted
### Expected behavior

When sending Transactions, Signatures to a node they are broadcasted to the network

### Actual behavior

Transactions and Signatures are not being broadcasted to other nodes

### Steps to reproduce

Create a network with three nodes send a transaction to any of the nodes and check how that transaction is not broadcasted

### Which version(s) does this affect? (Environment, OS, etc...)

2.2.*

### PR DESCRIPTION
**Pull request by pablitovicente**
### What was the problem?

- Transaction were not being broadcasted by node
- Signatures were not being broadcasted by node
- Transactions were not being removed from the transaction pool when receiving block
- Broadcaster had a bug making the application crash when trying to broadcast

### How did I fix it?

- By adding missing code for broadcasting transactions
- By adding missing code for broadcasting signatures
- By clearing transactions from the transaction pool when receiving block
- Fixing the bug in Broadcaster
- Add tests

### How to test it?

- Build should be green
- Bring up a network and send transactions and signatures and they should be broadcasted

### Review checklist

* The PR resolves #3962
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/chain/chain.js [hunk 1]
```diff
@@ -505,9 +509,19 @@ module.exports = class Chain {
 			this.channel.publish('chain:blocks:change', block);
 		});
 
+		this.transactionPool.on(EVENT_UNCONFIRMED_TRANSACTION, transaction => {
+			this.logger.debug(`Broadcasting transaction ${transaction.id}`);
```
Comment (shuse2) [inline framework/src/modules/chain/chain.js]: Let's make the message more clear.

File: framework/src/modules/chain/chain.js [hunk 2]
```diff
@@ -505,9 +509,19 @@ module.exports = class Chain {
...
+			this.transport.onUnconfirmedTransaction(transaction, true);
+		});
+
 		this.blocks.on(EVENT_NEW_BROADHASH, ({ broadhash, height }) => {
 			this.channel.invoke('app:updateApplicationState', { broadhash, height });
 		});
+
+		this.transactionPool.on(EVENT_MULTISIGNATURE_SIGNATURE, signature => {
+			this.logger.debug('Broadcasting signature ', signature);
```
Comment (shuse2) [inline framework/src/modules/chain/chain.js]: same as above

File: framework/src/modules/chain/transaction_pool/transaction_pool.js [hunk 3]
```diff
@@ -160,7 +160,10 @@ class TransactionPool extends EventEmitter {
 		this.pool.on(pool.EVENT_VERIFIED_TRANSACTION_ONCE, ({ payload }) => {
 			if (payload.length > 0) {
 				payload.forEach(aTransaction =>
-					this.emit('unconfirmedTransaction', aTransaction)
+					this.emit(
+						transactionsModule.EVENT_UNCONFIRMED_TRANSACTION,
```
Comment (shuse2) [inline framework/src/modules/chain/transaction_pool/transaction_pool.js]: it should probably emit it's own event (ie defined in transaction pool)

File: framework/src/modules/chain/transaction_pool/transaction_pool.js [hunk 4]
```diff
@@ -224,6 +227,8 @@ class TransactionPool extends EventEmitter {
 			this.logger.error(message, { signature });
 			throw transactionResponse.errors;
 		}
+
+		this.emit(transactionsModule.EVENT_MULTISIGNATURE_SIGNATURE, signature);
```
Comment (shuse2) [inline framework/src/modules/chain/transaction_pool/transaction_pool.js]: same as above

File: framework/src/modules/chain/transactions/index.js [hunk 5]
```diff
@@ -27,6 +27,9 @@ const {
 	applyGenesisTransactions,
 } = require('./transactions_handlers');
 
+const EVENT_UNCONFIRMED_TRANSACTION = 'unconfirmedTransaction';
```
Comment (shuse2) [inline framework/src/modules/chain/transactions/index.js]:
```suggestion
const EVENT_UNCONFIRMED_TRANSACTION = 'EVENT_UNCONFIRMED_TRANSACTION';
```

File: framework/src/modules/chain/transactions/index.js [hunk 6]
```diff
@@ -27,6 +27,9 @@ const {
...
+const EVENT_MULTISIGNATURE_SIGNATURE = 'multisignature';
```
Comment (shuse2) [inline framework/src/modules/chain/transactions/index.js]: same as above

File: framework/src/modules/chain/chain.js (hunk 1 above)
Comment (limiaspasdaniel) [reply framework/src/modules/chain/chain.js]: Maybe we could use Bunyan's metadata handling such as:
`this.logger.debug({transactionId: 'theTrsId'}, 'Broadcasting transaction'}`
This will print the logs in a parseable JSON-structured format

File: framework/src/modules/chain/chain.js (hunk 2 above)
Comment (limiaspasdaniel) [reply framework/src/modules/chain/chain.js]: > Maybe we could use Bunyan's metadata handling such as:
> `this.logger.debug({transactionId: 'theTrsId'}, 'Broadcasting transaction'}`
> This will print the logs in a parseable JSON-structured format

We could apply this here too

File: framework/src/modules/chain/chain.js (hunk 1 above)
Comment (pablitovicente) [reply framework/src/modules/chain/chain.js]: Done

File: framework/src/modules/chain/chain.js (hunk 2 above)
Comment (pablitovicente) [reply framework/src/modules/chain/chain.js]: Done

File: framework/src/modules/chain/transaction_pool/transaction_pool.js (hunk 4 above)
Comment (pablitovicente) [reply framework/src/modules/chain/transaction_pool/transaction_pool.js]: Done

File: framework/src/modules/chain/transactions/index.js (hunk 6 above)
Comment (pablitovicente) [reply framework/src/modules/chain/transactions/index.js]: Done

File: framework/src/modules/chain/transaction_pool/transaction_pool.js (hunk 3 above)
Comment (pablitovicente) [reply framework/src/modules/chain/transaction_pool/transaction_pool.js]: Done

**Comment by pablitovicente** [comment]
> It should be broadcasted here too
> https://github.com/LiskHQ/lisk-sdk/pull/3965/files#diff-d7f87dc39c3d198a2e9b82d6b88dc4ffR420

Done and test added.
