### PR TITLE
Transaction create command failed on empty data attribute - Closes #6158

### LINKED ISSUE #6158: Transaction create command failed on empty data attribute
### Expected behavior

Transaction create command should work fine with an empty data field. 

### Actual behavior

For an empty data field the transaction creation failed. 

```
> ./bin/run transaction:create 2 0 1000000
? Please enter passphrase:  [hidden]
? Please re-enter passphrase:  [hidden]
? Please enter: amount:  10
? Please enter: recipientAddress:  7294d56fa05293e11086a86f0c1c42e5a9dce21e
? Please enter: data:  
 ›   Error: Lisk validator found 1 error[s]:
 ›   Property '.data' should pass "dataType" keyword validation
```

### Which version(s) does this affect? (Environment, OS, etc...)

5.0.x

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?

This PR resolves #6158 

### How was it solved?

- Fix transaction create asset 

### How was it tested?

- Updated unit test

### CODE REVIEW

File: commander/src/utils/reader.ts [hunk 1]
```diff
@@ -236,14 +236,20 @@ const getNestedPropertyTemplate = (schema: Schema): NestedPropertyTemplate => {
...
 	if (schemaType === 'object') {
 		// eslint-disable-next-line @typescript-eslint/no-unsafe-return
-		return JSON.parse(strVal);
+		return JSON.parse(val);
 	}
-	return Number.isInteger(Number(strVal)) ? Number(strVal) : strVal;
+	if (schemaType === 'array') {
+		return val.split(',');
+	}
+	if (Number.isInteger(Number(val))) {
```
Comment (nazarhussain) [inline commander/src/utils/reader.ts:249]: What if the `val` here is a an integer string but schemaType suggest that dataType should be string? I suggest to check `schemaType` not that value is integer or not.

**Review by nazarhussain — CHANGES_REQUESTED** [review]

File: commander/src/utils/reader.ts [hunk 2]
```diff
@@ -236,14 +236,25 @@ const getNestedPropertyTemplate = (schema: Schema): NestedPropertyTemplate => {
...
+	}
+	if (
+		schemaType === 'uint64' ||
+		schemaType === 'sint64' ||
+		schemaType === 'uint32' ||
+		schemaType === 'sint32'
+	) {
+		return schemaType === 'uint64' ? BigInt(val) : Number(val);
+	}
+	return val;
```
Comment (nazarhussain) [inline commander/src/utils/reader.ts:257]: This missed the condition for `sint64` type. Would be nice to split this condition to two for for bigint and number.

**Review by nazarhussain — CHANGES_REQUESTED** [review]

**Review by nazarhussain — APPROVED** [review]

**Review by shuse2 — APPROVED** [review]
