### PR TITLE
Fix handling of genesis block - Closes #6573

### LINKED ISSUE #6573: Handling of genesis block takes too much time
### Expected behavior

Even with a large genesis block file, it should be able to sync the nodes properly.

### Actual behavior

- Procedure `getHighestCommonBlock` for given block ids returns the whole common block header, in case of testnet or mainnet genesis block header the size of genesis block header is too big (20-200MB).
- When getting the block, it tries to decode the asset which takes long.
- Genesis block are kept in memory

### Steps to reproduce

- Migrate 2.1.6 and generate genesis block (which is around 200MB)
- Run `lisk-core start -n mainnet` with the new genesis block
- Connect to running node as seed peer
- Observer the syncing node fails to request block during synchronisation

### Which version(s) does this affect? (Environment, OS, etc...)
5.1.1, 3.0.0

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #6573 

### How was it solved?

- Update not to hold genesis block in memory
- Update getHighestCommonBlock to getHighestCommonBlockID

### How was it tested?

Run 2 nodes with heavy genesis block (modified mainnet snapshot etc)
- Check 2 nodes will sync even after 500 blocks. (after 500 blocks, genesis block will not be on cache)
- Restart one of the node and check the starting time is significantly faster than 1st time

### CODE REVIEW

File: elements/lisk-chain/src/data_access/storage.ts [hunk 1]
```diff
@@ -292,6 +292,12 @@ export class Storage {
 		}
 	}
 
+	// Warning: This function should never be used. This exist only for migration purpose.
```
Comment (ManuGowda) [inline elements/lisk-chain/src/data_access/storage.ts:295]: Also add a TODO? to be removed in 6.0.0

File: elements/lisk-chain/src/types.ts [hunk 2]
```diff
@@ -107,3 +107,9 @@ export interface Validator {
 	minActiveHeight: number;
 	isConsensusParticipant: boolean;
 }
+
+export interface GenesisInfo {
+	height: number;
+	timestamp: number;
```
Comment (ManuGowda) [inline elements/lisk-chain/src/types.ts:113]: are we using timestamp somewhere? i only saw height and initRounds usage, if not used maybe remove?

File: framework/src/node/transport/transport.ts [hunk 3]
```diff
@@ -196,10 +197,7 @@ export class Transport {
 		return codec.encode(getBlocksFromIdResponseSchema, { blocks: encodedBlocks });
 	}
 
-	public async handleRPCGetHighestCommonBlock(
-		data: unknown,
-		peerId: string,
-	): Promise<Buffer | undefined> {
+	public async handleRPCGetHighestCommonBlock(data: unknown, peerId: string): Promise<Buffer> {
```
Comment (ManuGowda) [inline framework/src/node/transport/transport.ts:200]:
```suggestion
	public async handleRPCGetHighestCommonBlockID(data: unknown, peerId: string): Promise<Buffer> {
```

**Review by ManuGowda — APPROVED** [review]

**Review by ishantiw — APPROVED** [review]
