### PR TITLE
 txpool_getTransactionsFromPool endpoint to return JSON

### LINKED ISSUE #7956: Fix `getTransactionsFromPool` to return JSON transaction format
### Expected behavior
`txpool_getTransactionsFromPool` endpoint should return transaction in JSON format

### Actual behavior
`txpool_getTransactionsFromPool` endpoint is returning the transactions in hex string

### Steps to reproduce
call `txpool_getTransactionsFromPool` endpoint

### Which version(s) does this affect? (Environment, OS, etc...)
6.0.0-alpha.10

### PR DESCRIPTION
**Pull request by has5aan**
### What was the problem?

This PR resolves #7956 

### How was it solved?

Modified `framework/src/engine/endpoint/txpool.ts` to return `JSONObject<TransactionObject>`.

### How was it tested?
Implemented unit tests.

### CODE REVIEW

File: framework/src/engine/endpoint/txpool.ts [hunk 1]
```diff
@@ -96,8 +97,17 @@ export class TxpoolEndpoint {
 	}
 
 	// eslint-disable-next-line @typescript-eslint/require-await
-	public async getTransactionsFromPool(_context: RequestContext): Promise<string[]> {
-		return this._pool.getAll().map(tx => tx.getBytes().toString('hex'));
+	public async getTransactionsFromPool(
+		_context: RequestContext,
+	): Promise<JSONObject<TransactionObject>[]> {
+		return this._pool.getAll().map(transaction => ({
```
Comment (shuse2) [inline framework/src/engine/endpoint/txpool.ts:103]: I think we can simply return `TransactionJSON[]` here, and you can just switch to `tx.getJSON()`

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: framework/src/engine/endpoint/txpool.ts (hunk 1 above)
Comment (shuse2) [reply framework/src/engine/endpoint/txpool.ts:103]: ah yes...
we can for now dow `(this._pool.getAll() as Transaction[]).map(tx => tx.toJSON())` or add `toJSON` in the interface in the pool

**Review by shuse2 — APPROVED** [review]

**Review by Incede — APPROVED** [review]
