### PR TITLE
Codec validateSchema should check for the field number existence - Closes #6191

### LINKED ISSUE #6191: Codec validateSchema should check for the field number existence
### Expected behavior
Schema which do not have field number should fail to add and compile

### Actual behavior
Related to #6190 , field number existence should be checked before adding schema and compiling the schema.

### Steps to reproduce
Try to compile schema without field number

### Which version(s) does this affect? (Environment, OS, etc...)
5.0.3-

### PR DESCRIPTION
**Pull request by Incede**
### What was the problem?

This PR resolves #6191 

### How was it solved?

* Check properties in schema to include `fieldNumber`

### How was it tested?

* Tested manually using custom schema in test cases

### CODE REVIEW

File: elements/lisk-codec/src/codec.ts [hunk 1]
```diff
@@ -67,6 +67,15 @@ export const validateSchema = (schema: {
 		throw new LiskValidationError([...errors]);
 	}
 
+	const { properties } = schemaToValidate as ValidatedSchema;
+	if (properties) {
+		Object.values(properties).forEach(property => {
```
Comment (shuse2) [inline elements/lisk-codec/src/codec.ts:72]: Prefer to use `for...of` as it is slow although this only runs once so it would not make big difference

File: elements/lisk-codec/src/codec.ts [hunk 2]
```diff
@@ -67,6 +67,15 @@ export const validateSchema = (schema: {
...
+			if (!('fieldNumber' in property)) {
```
Comment (shuse2) [inline elements/lisk-codec/src/codec.ts:73]: field number can exist in the nested properties, too. 
Did you consider updating `elements/lisk-validator/src/lisk_meta_schema.ts` which is executed in above L63?

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: elements/lisk-codec/src/codec.ts [hunk 3]
```diff
@@ -163,13 +163,21 @@ export class Codec {
 			if (properties === undefined) {
 				throw new Error('Invalid schema. Missing "properties" property');
 			}
+			for (const property of Object.values(properties)) {
+				if (!('fieldNumber' in property)) {
```
Comment (shuse2) [inline elements/lisk-codec/src/codec.ts:167]: I think we want to check `fieldNumber` exists and the value in the range 1 to 18’999. (https://github.com/LiskHQ/lips/blob/master/proposals/lip-0027.md#field-name-and-field-number)

**Review by shuse2 — CHANGES_REQUESTED** [review]
Please add unit tests to check if the root and nested field number check is done correctly

**Review by ishantiw — APPROVED** [review]

File: elements/lisk-codec/package.json [hunk 4]
```diff
@@ -54,6 +54,7 @@
 		"jest": "26.4.2",
 		"jest-extended": "0.11.5",
 		"jest-when": "2.7.2",
+		"lodash.clonedeep": "4.5.0",
```
Comment (shuse2) [inline elements/lisk-codec/package.json:57]: Please use cloneDeep from `@liskhq/lisk-utils`

**Review by shuse2 — CHANGES_REQUESTED** [review]
other than the dependency usage LGTM

**Review by shuse2 — APPROVED** [review]
