### PR TITLE
Consumes iterations when encrypting with passphrase

### LINKED ISSUE #8943: EncryptMessageWithPassword ignores iterations passed from options
### Expected behavior
- It should use the iteration value passed from options to getKey

### Actual behavior
- Still uses the default iteration value

### Steps to reproduce
- Pass an option to the kdfParams to replace the iteration value with a different one
- Notice the generated result, iteration is still 1

### Which version(s) does this affect? (Environment, OS, etc...)
- v6.0.0-rc.0

### PR DESCRIPTION
**Pull request by has5aan**
### What was the problem?

This PR resolves #8943 

### How was it solved?

If provided, passes `options.kdfparams.iterations` to `options.getKey`.

### How was it tested?

Updated unit tests.

### CODE REVIEW

File: elements/lisk-cryptography/src/encrypt.ts [hunk 1]
```diff
@@ -100,13 +101,13 @@ export const encryptAES128GCMWithPassword = async (
 	const SALT_BUFFER_SIZE = 8;
 	const salt = crypto.randomBytes(SALT_BUFFER_SIZE);
 	const iv = crypto.randomBytes(IV_BUFFER_SIZE);
-	const iterations =
-		kdf === KDF.ARGON2 ? ARGON2_ITERATIONS : options?.kdfparams?.iterations ?? PBKDF2_ITERATIONS;
```
Comment (shuse2) [inline elements/lisk-cryptography/src/encrypt.ts:104]: I think the issue was when setting the iteration, it was not taking the iteration. otherwise it should use the default for each kdf, so intended condition was something like this?
```
const iterations = options?.kdfparams?.iterations ?? kdf === KDF.ARGON2 ? ARGON2_ITERATIONS : PBKDF2_ITERATIONS;
```

**Review by shuse2 — CHANGES_REQUESTED** [review]

**Review by shuse2 — APPROVED** [review]
