### PR TITLE
Ban peer if block processing fails on FCS - Closes #4474

### LINKED ISSUE #4474: Ban peer if applying a block fails on FCS (_switchChain method)
### Description

The peer that triggered the mechanisms needs to be banned if applying any of the requested blocks on `_switchChain` method fails.
### Motivation

Described here: https://github.com/LiskHQ/lips/pull/34

### PR DESCRIPTION
**Pull request by limiaspasdaniel**
### What was the problem?
Refer to #4474 
### How did I solve it?
By banning the peer and restarting the mechanism if block processing fails
### How to manually test it?
Run `fast_chain_switching_mechanism.spec.js`
### Review checklist
- [ ] The PR resolves #4474 
- [ ] All new code is covered with unit tests
- [ ] Relevant integration / functional tests are added
- [ ] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [ ] Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/chain/synchronizer/fast_chain_switching_mechanism.js [hunk 1]
```diff
@@ -325,18 +344,26 @@ class FastChainSwitchingMechanism extends BaseSynchronizer {
...
-				'Deleting blocks after height',
-			);
-			await deleteBlocksAfterHeight(
-				this.processor,
-				this.blocks,
-				highestCommonBlock.height,
-			);
-			this.logger.debug('Restoring blocks from temporary table');
-			await restoreBlocks(this.blocks, this.processor);
+			if (err instanceof BlockProcessingError) {
```
Comment (ManuGowda) [inline framework/src/modules/chain/synchronizer/fast_chain_switching_mechanism.js]: can you extract the error handling to private function?

Comment (limiaspasdaniel) [reply framework/src/modules/chain/synchronizer/fast_chain_switching_mechanism.js]: Done :)
