### PR TITLE
Snapshotting and syncing fails on 2.2 - Closes #4003

### LINKED ISSUE #4003: Snapshotting and syncing fails on 2.2
### Expected behavior
Expect to successfully finish snapshotting and syncing when executed on testnet

### Actual behavior
It fails with the following message:
```
07:36:45.518Z DEBUG lisk-framework: Using delegate list from the cache for round 5320
07:36:45.519Z  INFO lisk-framework:
    Fork { delegate:
       '410ebf1736f1e7f8c5a3ce5364626e62731b105943ed94d2294d33304a496fd3',
      block:
       { id: '5010245806505876363',
         timestamp: 8719180,
         height: 537249,
         previousBlock: '14954058649670137792' },
      cause: 3 }
```

### Steps to reproduce
Start snapshotting or syncing on testnet

### Which version(s) does this affect? (Environment, OS, etc...)
`2.2`

### PR DESCRIPTION
**Pull request by lsilvs**
### What was the problem?
Exceptions was not being passed causing syncing and snapshotting to fails

### How did I fix it?
Added the `exceptions` object to `votes.apply` inside `applyTransactions`

### How to test it?
Perform syncing and snapshotting on testnet.

### Review checklist

* The PR resolves #4003 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/test/mocha/integration/process_transactions.js [hunk 1]
```diff
@@ -346,6 +347,16 @@ describe('processTransactions', () => {
 						);
 					});
 				});
+
+				it('should call votes.apply with correct params', async () => {
```
Comment (SargeKhan) [inline framework/test/mocha/integration/process_transactions.js]: Tests which spy or stub should be unit tests. No?

Comment (SargeKhan) [reply framework/test/mocha/integration/process_transactions.js]: Here we can test that stateStore value is updated as expected if we want this to be an integration test

Comment (lsilvs) [reply framework/test/mocha/integration/process_transactions.js]: I added this test here because the unit test for this method was skipped as reported in the issue https://github.com/LiskHQ/lisk-sdk/issues/3987

Comment (shuse2) [reply framework/test/mocha/integration/process_transactions.js]: I think spy is fine for integration test
