### PR TITLE
Fix the offline transaction creation command

### LINKED ISSUE #8277: Offline transaction creation is not working
### Expected behavior

When we create a transaction offline with `transaction:create --offline `command then it should create a transaction successfully.

### Actual behavior

When we run `transaction:create` command with `--offline` flag, it throws error 
```
LiskValidationError: Lisk validator found 1 error[s]:
Missing property, must have required property 'chainID'
```

#### Findings while debugging:

In the transaction:create command when we [getApplication](https://github.com/LiskHQ/lisk-sdk/blob/48b698dc63c44890bf384883cbc2a2e570f7a60c/commander/src/bootstrapping/commands/transaction/create.ts#L299) we need to pass `getApplication({ genesis: chainID })` as the config in order to get a valid application.

### Steps to reproduce

`./bin/run transaction:create token transfer 0 --nonce 600 --chain-id 04000001 --offline` and observe result

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-alpha.16`

### PR DESCRIPTION
**Pull request by mosmartin**
### What was the problem?

This PR resolves #8277

### How was it solved?

By creating an application object with the chainID specified in the flags.

### How was it tested?

Existing tests pass

### CODE REVIEW

File: commander/src/bootstrapping/commands/transaction/create.ts [hunk 1]
```diff
@@ -296,7 +296,12 @@ export abstract class CreateCommand extends Command {
 		this._dataPath = flags['data-path'] ?? getDefaultPath(this.config.pjson.name);
 
 		if (flags.offline) {
-			const app = this.getApplication({});
+			const app = this.getApplication({
```
Comment (shuse2) [inline commander/src/bootstrapping/commands/transaction/create.ts:299]: can we add test to support this change?

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: commander/src/bootstrapping/commands/transaction/create.ts (hunk 1 above)
Comment (mosmartin) [reply commander/src/bootstrapping/commands/transaction/create.ts:299]: ✅

**Review by shuse2 — APPROVED** [review]

**Review by ishantiw — APPROVED** [review]
