### PR TITLE
Fix framework reference - Closes #3366

### LINKED ISSUE #3366: Framework is referencing the framework keyword itself
### Expected behavior
Framework should not reference itself as framework

### Actual behavior
It's using framework in the path

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?
Framework itself was referencing it's own

### How did I fix it?
Change to relative path

### How to test it?
try to run the `lisk` app

### Review checklist

* The PR resolves #3366
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/chain/submodules/blocks.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ const { BLOCK_RECEIPT_TIMEOUT, EPOCH_TIME } = global.constants;
 const {
 	CACHE_KEYS_BLOCKS,
 	CACHE_KEYS_TRANSACTIONS,
-} = require('../../../../../framework/src/components/cache');
+} = require('../../../components/cache');
```
Comment (nazarhussain) [inline framework/src/modules/chain/submodules/blocks.js]: I am not sure if we keep these or not, as its easily accessible by `scope.components.cache.CACHE_KEYS_BLOCKS`. But probably refactor this separately.
