### PR TITLE
Fix duplicate schema $id and add github action check

### LINKED ISSUE #8473: Schemas with repeated ids
### Expected behavior
Each schema $id should corresponds to a unique schema

### Actual behavior
There are multiple duplicate `$id` property used

- $id: '/block/header/3' in lisk-sdk/elements/lisk-chain/src/schema.ts#L102-L104 and lisk-sdk/elements/lisk-chain/src/schema.ts#L112-L114
- $id: '/jsonRPCRequestSchema' in lisk-sdk/framework/src/controller/jsonrpc/utils.ts#L27-L28 and lisk-sdk/framework/src/controller/jsonrpc/utils.ts#L49-L50
- $id: '/modules/random/endpoint/isSeedRevealRequest' in lisk-sdk/framework/src/modules/random/schemas.ts#L308-L309 and lisk-sdk/framework/src/modules/random/schemas.ts#L324-L325
- $id: '/token/endpoint/getBalance' in lisk-sdk/framework/src/modules/token/schemas.ts#L494-L495 and lisk-sdk/framework/src/modules/token/schemas.ts#L448-L449
- $id: '/auth/account' in lisk-sdk/framework/src/modules/auth/schemas.ts#L22-L23 and lisk-sdk/framework/src/modules/auth/stores/auth_account.ts#L25-L26
- $id: '/block/event' in lisk-sdk/framework/src/abi/schema.ts#L30-L31 and lisk-sdk/elements/lisk-chain/src/schema.ts#L187-L188
- $id: '/commander/plainGeneratorKeys' in isk-sdk/commander/src/bootstrapping/commands/keys/encrypt.ts#L37-L38 and lisk-sdk/commander/src/bootstrapping/commands/keys/create.ts#L24-L25
- $id: '/modules/random/seedReveal' in lisk-sdk/framework/src/modules/random/stores/validator_reveals.ts#L29-L30 and lisk-sdk/framework/src/modules/random/schemas.ts#L196-L197
- $id: '/token/store/escrow' in lisk-sdk/framework/src/modules/token/schemas.ts#L109-L110 and lisk-sdk/framework/src/modules/token/stores/escrow.ts#L23-L24
- $id: '/token/store/supply' in lisk-sdk/framework/src/modules/token/schemas.ts#L77-L78 and lisk-sdk/framework/src/modules/token/stores/supply.ts#L21-L22
- $id: '/node/forger/usedHashOnion' in lisk-sdk/framework/src/modules/random/stores/used_hash_onions.ts#L30-L32 and lisk-sdk/framework/src/modules/random/schemas.ts#L276-L278
- $id: '/token/store/user' in lisk-sdk/framework/src/modules/token/stores/user.ts#L27-L28 and lisk-sdk/examples/interop/pos-mainchain-fast/config/scripts/recover_lsk_plugin.ts#L 68-L69 and lisk-sdk/framework/src/modules/token/schemas.ts#L52-L53

### Steps to reproduce
Check the list above. Also, check all $id with grep and verify the source code again

### Which version(s) does this affect? (Environment, OS, etc...)
6.0.0-beta.2

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #8473 

### How was it solved?

- Add script to check duplicate $id on source code (ignoring test/node_modules etc)
- Add check to Github action PR check
- Fix duplicate $id

### How was it tested?

N/A

### CODE REVIEW

File: scripts/duplicate_schema_id.js [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+		for (const { id, occurrences } of duplicateIds) {
+			console.log(`$id: ${id}`);
+			for (const { file, line } of occurrences) {
+				console.log(`  File: ${file}:${line}`);
+			}
+		}
+		process.exit(1);
+	}
+	console.log('No duplicate schema ids found');
+	process.exit(0);
```
Comment (bobanm) [inline scripts/duplicate_schema_id.js:67]: I know this script is of very low importance, but to achieve separation of concerns and make the code cleaner, you could change this function from `checkDuplicateIds()` into `getDuplicateIds()`, which only returns an array of duplicates.

Then this highlighted error handling and result logging logic would move to the the main script outside of `getDuplicateIds()`.

**Review by bobanm — APPROVED** [review]
Approved, with a minor improvement suggestion.

File: scripts/duplicate_schema_id.js [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+	let match;
+	const ids = [];
+	while ((match = schemaIdRegex.exec(content)) !== null) {
+		const line = content.substring(0, match.index).split('\n').length;
+		ids.push({ id: match[1], file: filePath, line: line });
+	}
+	return ids;
+}
+
+function checkDuplicateIds(directoryPath) {
```
Comment (bobanm) [inline scripts/duplicate_schema_id.js:18]: I thought that the convention we use in the codebase is to use `const` instead of `function`?

I personally find `function` to be cleaner, but then it is inconsistent with the rest of the codebase.

**Review by mosmartin — APPROVED** [review]
