### PR TITLE
On update root is saved twice on sparse merkle tree - Closes #6655

### LINKED ISSUE #6655: On update root is saved twice on sparse merkle tree
### Expected behavior
Root should be only saved once.

### Actual behavior
Root is always saved twice

### Steps to reproduce
Call `update` on sparse merkle tree and add the log for db save

### PR DESCRIPTION
**Pull request by nazarhussain**
### What was the problem?

This PR resolves #6655

### How was it solved?

- Removed the code line which endup calling `db.set` twice. 

### How was it tested?

- Run unit tests

### CODE REVIEW

**Review by shuse2 — APPROVED** [review]

File: elements/lisk-tree/src/sparse_merkle_tree/sparse_merkle_tree.ts [hunk 1]
```diff
@@ -165,7 +165,6 @@ export class SparseMerkleTree {
 		}
 		rootNode = bottomNode;
 		this._rootHash = rootNode.hash;
```
Comment (Incede) [inline elements/lisk-tree/src/sparse_merkle_tree/sparse_merkle_tree.ts:167]:
```suggestion
		this._rootHash = bottomNode.hash;
```

File: elements/lisk-tree/src/sparse_merkle_tree/sparse_merkle_tree.ts [hunk 2]
```diff
@@ -165,7 +165,6 @@ export class SparseMerkleTree {
...
-		await this._db.set(rootNode.hash, (rootNode as Branch).data);
 
 		return rootNode;
```
Comment (Incede) [inline elements/lisk-tree/src/sparse_merkle_tree/sparse_merkle_tree.ts:169]:
```suggestion
		return bottomNode;
```

**Review by Incede — APPROVED** [review]
LGTM.
Left one minor comment to match the `update` & `remove` functions and possibly achieve minor optimization.
