### PR TITLE
Fix IPC communication through plugins loaded as child process - Closes #3674, #3118

### LINKED ISSUE #3674: ChildProcessChannel can not subscribe
### Expected behavior

ChildProcessChannel should be able to listen events coming from other childProcessChannels.

### Actual behavior

ChildProcessChannels can not subscribe events that coming from other child process channels.

Blocking #3118 

### Which version(s) does this affect? (Environment, OS, etc...)

v.2.2.0

### PR DESCRIPTION
**Pull request by nazarhussain**
### What was the problem?

This PR resolves #3674, #3118

### How was it solved?

Restructured the IPC communication from the ground up and added the integration tests. 

### How was it tested?

Run all integration tests

### CODE REVIEW

File: framework/src/controller/ipc/ipc_socket.ts [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+		this.rpcServer.sock.close();
+	}
+
+	public async start(): Promise<void> {
+		await new Promise((resolve, reject) => {
+			this.rpcServer.sock.on('bind', resolve);
+			this.rpcServer.sock.on('error', reject);
+
+			this.rpcServer.sock.bind(this._actionRpcSeverSocketPath);
+		}).finally(() => {
```
Comment (shuse2) [inline framework/src/controller/ipc/ipc_socket.ts:74]: why removing all listener here? isn't it suppose to be done in the `stop`?

File: framework/src/controller/ipc/ipc_server.ts [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+
+	public async start(): Promise<void> {
+		await super.start();
+
+		await new Promise((resolve, reject) => {
+			this.pubSocket.on('bind', resolve);
+			this.pubSocket.on('error', reject);
+
+			this.pubSocket.bind(this._eventPubSocketPath);
+		}).finally(() => {
```
Comment (shuse2) [inline framework/src/controller/ipc/ipc_server.ts:40]: why removing all listener here? isn't it suppose to be done in the stop?

File: framework/src/controller/channels/child_process_channel.ts [hunk 3]
```diff
@@ -46,62 +42,86 @@ export const rejectWhenTimeout = async (timeInMillis: number): Promise<void> =>
...
 		super(moduleAlias, events, actions, options);
-		this.localBus = new EventEmitter2();
+
+		this._ipcClient = new IPCClient({
+			socketsDir: options.socketsPath.root,
+			name: moduleAlias,
+			rpcServerSocketPath: `unix://${options.socketsPath.root}/bus_rpc_socket.sock`,
+		});
+
+		this._emitter = new EventEmitter2({
```
Comment (shuse2) [inline framework/src/controller/channels/child_process_channel.ts:60]: do we still need to use EventEmitter2?

File: framework/src/controller/bus.ts [hunk 4]
```diff
@@ -112,24 +116,28 @@ export class Bus extends EventEmitter2 {
...
+				.then(data => {
+					cb(null, data);
+				})
+				.catch(error => {
+					cb(error);
+				});
 		});
 
-		this.rpcServer.expose('invokePublic', (action, cb: NodeCallback) => {
+		this._rpcServer.expose('invokePublic', (action, cb: NodeCallback) => {
```
Comment (shuse2) [inline framework/src/controller/bus.ts:129]: This can be removed as no longer used

File: framework/src/controller/bus.ts [hunk 5]
```diff
@@ -231,30 +262,24 @@ export class Bus extends EventEmitter2 {
...
 		// Communicate through event emitter
-		this.on(eventName, cb);
+		this._emitter.on(eventName, cb);
 
-		// Communicate through unix socket
-		if (this.config.ipc.enabled) {
-			this.subSocket?.on(eventName, cb);
-		}
+		// // Communicate through unix socket
+		// if (this.config.ipc.enabled) {
```
Comment (shuse2) [inline framework/src/controller/bus.ts:268]: Originally there was option to allow communication directly through socket or not, but that's not the case anymore?

File: framework/test/integration/setup.js [hunk 6]
```diff
@@ -1,16 +0,0 @@
-/*
- * Copyright © 2019 Lisk Foundation
```
Comment (shuse2) [inline framework/test/integration/setup.js:2]: why removing setup?

File: framework/test/integration/specs/controller/ipc/ipc_client.spec.ts [hunk 7]
```diff
@@ -0,0 +1,182 @@
...
+				await new Promise(resolve => {
+					client2.subSocket.on('message', data => {
+						expect(data).toEqual('myData');
+						resolve();
+					});
+				}),
+			]);
+
+			// Cleanup
+			client2.stop();
```
Comment (shuse2) [inline framework/test/integration/specs/controller/ipc/ipc_client.spec.ts:111]: if test fails, it wont get cleaned up? same for others

File: framework/src/controller/ipc/ipc_socket.ts (hunk 1 above)
Comment (nazarhussain) [reply framework/src/controller/ipc/ipc_socket.ts:74]: No these are listeners just for the confirmation if server bound or started. Once it started we can remove the listeners. Ongoing we have `message` listener which is removed in `stop` .

File: framework/src/controller/ipc/ipc_server.ts (hunk 2 above)
Comment (nazarhussain) [reply framework/src/controller/ipc/ipc_server.ts:40]: Same as above.

File: framework/src/controller/bus.ts (hunk 4 above)
Comment (nazarhussain) [reply framework/src/controller/bus.ts:129]: Not sure if is used or not, but it was there and have the test coverage as well. Maybe we can remove it afterward and clean all references of `isPublic`

File: framework/src/controller/bus.ts (hunk 5 above)
Comment (nazarhussain) [reply framework/src/controller/bus.ts]: Now this check is only in one place inside `setup`, rest is handled through local emitter.

File: framework/test/integration/specs/controller/ipc/ipc_client.spec.ts (hunk 7 above)
Comment (nazarhussain) [reply framework/test/integration/specs/controller/ipc/ipc_client.spec.ts:111]: But if the test fails we fix those... 😄

Comment (shuse2) [reply framework/test/integration/specs/controller/ipc/ipc_client.spec.ts:111]: but that will make the test hangs or put it in unstable situation?
I think it's better to put it in after/All?

File: framework/src/controller/bus.ts (hunk 4 above)
Comment (shuse2) [reply framework/src/controller/bus.ts:129]: Please create an issue for this

File: framework/src/controller/channels/child_process_channel.ts (hunk 3 above)
Comment (nazarhussain) [reply framework/src/controller/channels/child_process_channel.ts:60]: Yes, we need a local emitter. We can use native `EventEmitter` but it does not support wildcard. If one wants to listen `channel.subscribe('ap:*')` it can't be done with native `EventEmitter`. If we don't want that support anymore then we can remove `EventEmitter2`

File: framework/src/controller/bus.ts (hunk 4 above)
Comment (nazarhussain) [reply framework/src/controller/bus.ts:129]: https://github.com/LiskHQ/lisk-sdk/issues/5509

File: framework/src/controller/channels/child_process_channel.ts (hunk 3 above)
Comment (shuse2) [reply framework/src/controller/channels/child_process_channel.ts:60]: Change to push/pull will not affect the wildcard feature, then no need to remove them

File: framework/src/controller/ipc/ipc_server.ts [hunk 8]
```diff
@@ -0,0 +1,57 @@
...
+export class IPCServer extends IPCSocket {
+	public constructor(options: { socketsDir: string; name: string }) {
+		super(options);
+
+		this.pubSocket = axon.socket('pub', {}) as PubSocket;
+		this.subSocket = axon.socket('pull', {}) as PullSocket;
+	}
+
+	public async start(): Promise<void> {
+		await super.start();
```
Comment (ishantiw) [inline framework/src/controller/ipc/ipc_server.ts:33]: I'm not sure but if this server is running, should we handle errors or listen to error event on the server and handle or log it?

Comment (nazarhussain) [reply framework/src/controller/ipc/ipc_server.ts:33]: I agree that we should add more logging into it at the debug level. I will create another issue an refer it here.

Comment (nazarhussain) [reply framework/src/controller/ipc/ipc_server.ts:33]: @ishantiw I had set `CONNECTION_TIME_OUT=2000` which is the total time for connection including all tries. Each try time out default is 100ms and max try timeout is `5000`, but with our enforcement, it will reject in 2000. 

This connection timeout is for the clients when trying to connect to the server. But for server, its feasible as server don't need to connect to any. If it faces any issues opening the port or the socket, it will fail immediately. Suggest if we need to improve it further.

Comment (ishantiw) [reply framework/src/controller/ipc/ipc_server.ts:33]: okay, I think as of now `CONNECTION_TIME_OUT=2000` is good enough including total tries, I thought the socket only has a chance within 100ms to connect which can fail sometimes on Jenkins that's why I thought it should be increased. If there will be some failing tests later then we can rethink to change `2000` but at the moment it's good 👍
