### PR TITLE
Provide a default database name of the Storage component

### LINKED ISSUE #3385: Provide a default database name of the Storage component
### Expected behavior
For the ease of starting the development, it's nice to have a default database that the storage component connects to, without specifying the configuration parameter for Devnet network - `components.storage.database: "lisk_dev"`.

### Actual behavior
When not providing a `components.storage.database` parameter, the app exits with the error:
```
[ERR] 2019-04-17 08:22:49 | error: database "{$components.storage.user}" does not exist
    at Connection.parseE (/Users/macio/projects/liskHQ/lisk-update/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/Users/macio/projects/liskHQ/lisk-update/node_modules/pg/lib/connection.js:379:19)
    at Socket.<anonymous> (/Users/macio/projects/liskHQ/lisk-update/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```
### Steps to reproduce
Run the app without providing the `components.storage.database` parameter.

### Which version(s) does this affect? (Environment, OS, etc...)
`*`

### PR DESCRIPTION
**Pull request by MaciejBaj**
### What was the problem?
It's necessary to specify a database name which makes the basic application configuration more complicated.
### How did I fix it?
Provided a default database name and included a not about this in README.md
### How to test it?
Run a node without specifying a database name in config or as env variable. The data should be stored in `lisk-dev`.
### Review checklist

* The PR resolves #3385
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/src/components/storage/defaults/config.js [hunk 1]
```diff
@@ -61,7 +61,7 @@ const defaultConfig = {
 	default: {
 		host: 'localhost',
 		port: 5432,
-		database: '',
+		database: 'lisk_dev',
```
Comment (nazarhussain) [inline framework/src/components/storage/defaults/config.js]: If you set this default then you can remove this value from tenet. 

https://github.com/LiskHQ/lisk-sdk/blob/4e65ecbd6a5752750ee19f36126b025f84d088be/lisk/config/devnet/config.json#L14
