### PR TITLE
Fix dashboard styles - Closes #6365

### LINKED ISSUE #6365: Dashboard styles is not matching the design
### Description 
- Scrollbar should not be shown on text
- Scrollbar should not be shown on Grid
- Dialog should be render above all the backgrounds
- Dialog should have minimum width
- On click copy icon, it should not open the dialog

### Steps to reproduce
As shown in image
Screenshot 2021-04-30 at 18 38 36
Screenshot 2021-04-30 at 18 38 55

### Which version(s) does this affect? (Environment, OS, etc...)
develop-

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #6365 

### How was it solved?

Fix the styling mentioned in the issues

### How was it tested?

```
npm run start:web
```
and check the problem does not exist and other styles are not affected

### CODE REVIEW

File: framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Grid/index.tsx [hunk 1]
```diff
@@ -117,6 +117,7 @@ const Grid: React.FC<GridProps> = props => {
 	const colSpacing = props.colSpacing ?? props.spacing;
 
 	const classes = [
+		styles.root,
```
Comment (nazarhussain) [inline framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/Grid/index.tsx:120]:
```suggestion
```

There is no `.root` style for the grid.

**Review by nazarhussain — CHANGES_REQUESTED** [review]

**Review by nazarhussain — APPROVED** [review]

**Review by ManuGowda — APPROVED** [review]
