### PR TITLE
Fix config on application bootstrap

### LINKED ISSUE #9151: Add allowedMethods in the config on bootstrap and fix dataPath
### Description

- When we bootstrap an application using `lisk init` command, currently by default it doesn't have `allowedMethods` in the `rpc` configuration. We can add `allowedMethods: []`  to config on bootstrap
- Also dataPath in config file is currently absolute path which can be replaced with `homedir`->`~`. Ex, `dataPath : "~/.lisk/test-app"`

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0`

### PR DESCRIPTION
**Pull request by ishantiw**
### What was the problem?

This PR resolves #9151 

### How was it solved?

- Update `config.json` to have `allowedMethods` in `rpc`
- Update `dataPath` to have a format `~/.lisk/<app_name>`

### How was it tested?

In order to test locally, 
1. build `commander`
2. `yarn link`
3. `npm i -g`
4. `./bin/run init ~/Desktop/testapp`
5. `cd ~/Desktop/testapp`
6. `yarn link lisk-commander`
7. `./bin/run config:create --chain-id 02000001 --label 'testapp'`
8. check the `config.json` file for `dataPath` and `rpc` values

### CODE REVIEW

File: commander/src/bootstrapping/commands/config/create.ts [hunk 1]
```diff
@@ -68,7 +67,7 @@ export class CreateCommand extends Command {
 		const configPath = resolve(output);
 		const filePath = join(configPath, 'config');
 
-		defaultConfig.system.dataPath = join(homedir(), '.lisk', label);
+		defaultConfig.system.dataPath = join('~', '.lisk', label);
```
Comment (shuse2) [inline commander/src/bootstrapping/commands/config/create.ts:70]: why do we change from `homedir`?

**Review by mitsuaki-u — APPROVED** [review]
LGTM apart from comment

File: commander/src/bootstrapping/commands/config/create.ts (hunk 1 above)
Comment (ishantiw) [reply commander/src/bootstrapping/commands/config/create.ts]: Reverted this change

**Review by shuse2 — APPROVED** [review]
