### PR TITLE
Unreacheable peers are kept as connected for too long - Close #3917

### LINKED ISSUE #3917: Unreacheable peers are kept as connected for too long
### Expected behavior
When peer for some reason stops being reachable, for example, because of:
- lost internet connection
- crashed Lisk Core instance
- destroyed VM

It should be marked as disconnected in less time, for example 30 seconds would be acceptable.
### Actual behavior
Peers are marked as disconnected after 15 minutes, until then they stays as connected with all peer info preserved. This can affect broadcasts, consensus calculation, `networkHeight`, etc. `1.6.0` is marking peers as disconnected properly.
### Steps to reproduce
Have a network with `X` peers, destroy `Y` VM instances or kill `Y` Lisk Core clients. After this query `api/peers` endpoint of some node, check amount of peers with `state: 2` (it will report `X` connected`).
### Which version(s) does this affect? (Environment, OS, etc...)
`release/2.0.0`

### PR DESCRIPTION
**Pull request by jondubois**
### What was the problem?

Peers where not marked as disconnected after they were shut down.
Because the pingTimeout (heartbeat) was disabled, the low level WebSocket was not detecting the disconnection for several minutes.

### How did I fix it?

Removed the `pingTimeoutDisabled` option so that it uses the default ping behaviour.

### How to test it?

Run a network, shutdown some nodes (not gracefully).

### Review checklist

* The PR resolves #3917
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-p2p/src/peer.ts [hunk 1]
```diff
@@ -670,7 +657,7 @@ export const connectAndRequest = async (
 				procedure,
 			};
 			// Ideally, we should JSON-serialize the whole NodeInfo object but this cannot be done for compatibility reasons, so instead we put it inside an options property.
-			const clientOptions: ClientOptionsUpdated = {
+			const clientOptions: ClientOptions = {
 				hostname: basicPeerInfo.ipAddress,
```
Comment (diego-G) [inline elements/lisk-p2p/src/peer.ts]: Why don't we use `pingTimeoutDisabled: false, pingTimeout: 20000,` as suggested in the commit 6e0a8543f0b10733489b55951aba407935632443 ?

Comment (4miners) [reply elements/lisk-p2p/src/peer.ts]: @diego-G `pingTimeoutDisabled: false` is the default, so we don't need to set it explicitly.

Comment (jondubois) [reply elements/lisk-p2p/src/peer.ts]: @diego-G as Marius mentioned, it's safer and more compatible to stick to the defaults in SC.

Comment (diego-G) [reply elements/lisk-p2p/src/peer.ts]: The timeout too? What about adding a simple scenario checking the behaviour?
