### PR TITLE
Register all the events and add tests

### LINKED ISSUE #8818: TerminatedStateCreatedEvent class is not registered on sidechain
### Expected behavior

`TerminatedStateCreatedEvent` class should be registered on `sidechain` module.

### Actual behavior

`TerminatedStateCreatedEvent` class is not registered on `sidechain` module

### Steps to reproduce

Check https://github.com/LiskHQ/lisk-sdk/blob/e41f107a594699d40bcad6c6e434b496d7794ff4/framework/src/modules/interoperability/sidechain/module.ts#L140-L155

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-beta.5`

### PR DESCRIPTION
**Pull request by ishantiw**
### What was the problem?

This PR resolves #8818 

### How was it solved?

- Move the registration of stores and events to `base_interoperability_module`
- Register `TerminatedStateCreatedEvent` class `base_interoperability_module`
- Add unit tests for register stores and events

### How was it tested?

`npm run test:unit interoperability`

### CODE REVIEW

File: framework/src/modules/interoperability/base_interoperability_module.ts [hunk 1]
```diff
@@ -59,6 +68,22 @@ export abstract class BaseInteroperabilityModule extends BaseInteroperableModule
...
+		this.events.register(
+			InvalidRegistrationSignatureEvent,
+			new InvalidRegistrationSignatureEvent(this.name),
+		);
+		this.events.register(TerminatedStateCreatedEvent, new TerminatedStateCreatedEvent(this.name));
+		this.events.register(TerminatedOutboxCreatedEvent, new TerminatedOutboxCreatedEvent(this.name));
+		this.events.register(
+			InvalidCertificateSignatureEvent,
+			new InvalidCertificateSignatureEvent(this.name),
+		);
```
Comment (shuse2) [inline framework/src/modules/interoperability/base_interoperability_module.ts:86]:
```
this.events.register(InvalidSMTVerification, new InvalidSMTVerification(this.name));
this.events.register(InvalidRMTVerification, new InvalidRMTVerification(this.name));
```
missing these 2 events?

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: framework/src/modules/interoperability/base_interoperability_module.ts (hunk 1 above)
Comment (ishantiw) [reply framework/src/modules/interoperability/base_interoperability_module.ts:90]: Done

**Review by shuse2 — APPROVED** [review]

**Review by mitsuaki-u — APPROVED** [review]
