### PR TITLE
Investigate slow sync on introduce_bft_consensus-dpos branch - Closes #4340

### LINKED ISSUE #4340: Investigate slow sync on introduce_bft_consensus-dpos branch
### Expected behavior
Expect the branch `introduce_bft_consensus-dpos.1` to sync with mainnet in less than 3 days

PS.: `introduce_bft_consensus-dpos.1` branch was branched off `feature/introduce_bft_consensus` after Dpos module implementation and before introducing breaking changes. Because of that, it should still have similar performance when syncing with mainnet (note that due to https://github.com/LiskHQ/lisk-sdk/issues/4194 it's not possible to sync with testnet)

### Actual behavior
It takes more than 5 days to sync up to the height `4 000 000`

### Steps to reproduce
Syncing with mainnet using Lisk Core branch `feature/introduce_bft_consensus` with Lisk SDK branch `introduce_bft_consensus-dpos.1`

### Which version(s) does this affect? (Environment, OS, etc...)
`introduce_bft_consensus-dpos.1`

### PR DESCRIPTION
**Pull request by lsilvs**
### What was the problem?
Syncing process too slow

### How did I solve it?
By fixing `mem_accounts_public_key` index and optimizing some functions heavily used during block processing

### How to manually test it?
Syncing with mainnet using Lisk Core branch introduce_bft_consensus-dpos.3 with Lisk SDK branch introduce_bft_consensus-dpos.3
Full sync should take less than 4 days

### Review checklist

- [ ] The PR resolves #4340
- [ ] All new code is covered with unit tests
- [ ] Relevant integration / functional tests are added
- [ ] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [ ] Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/chain/blocks/transactions/transactions_handlers.js [hunk 1]
```diff
@@ -144,10 +141,7 @@ const applyTransactions = exceptions => async (transactions, stateStore) => {
 	}
 
 	// eslint-disable-next-line no-restricted-syntax
```
Comment (shuse2) [inline framework/src/modules/chain/blocks/transactions/transactions_handlers.js]: We can remove this `eslint-disable` now, as the restriction was removed

File: framework/src/modules/chain/blocks/transactions/votes_weight.js [hunk 2]
```diff
@@ -37,14 +37,21 @@ const updateDelegateVote = (
 	const delegateAccount = stateStore.account.get(delegateAddress);
 	const voteBigNum = new BigNum(delegateAccount.voteWeight || '0');
 	const voteWeight = voteBigNum[method](amount).toString();
-	const updatedDelegateAccount = {
-		...delegateAccount,
-		voteWeight,
-	};
-	stateStore.account.set(delegateAddress, updatedDelegateAccount);
+	delegateAccount.voteWeight = voteWeight;
```
Comment (shuse2) [inline framework/src/modules/chain/blocks/transactions/votes_weight.js]: I think this change didn't actually affect so much

Comment (lsilvs) [reply framework/src/modules/chain/blocks/transactions/votes_weight.js]: Yeah it's just better to read IMO
