### PR TITLE
PoA Improvements #2

### LINKED ISSUE #8964: Code improvements PoA module
### Description

1. **RegisterAuthorityParams fields are ordered differently than in the LIP:**
The generatorKey and proofOfPossession fields are swapped. This could potentially cause schema matching problems if JSON serialization is done in the wrong order. However, we did not find any security problems related to this issue.

2. **Unnecessary calls to validator.validate:**
In the PoA module’s [register authority](https://github.com/LiskHQ/lisk-sdk/blob/ed5649eb954c7c47e11eb2d2ea2b84b9336c4c4b/framework/src/modules/poa/commands/register_authority.ts#L54) and [update generator key](https://github.com/LiskHQ/lisk-sdk/blob/ed5649eb954c7c47e11eb2d2ea2b84b9336c4c4b/framework/src/modules/poa/commands/update_generator_key.ts#L4
5) commands, the code calls validator.validate to validate the commands parameters. Calling validator.validate on a command's verify function is unnecessary because this check is already done in the [state machine logic](https://github.com/LiskHQ/lisk-sdk/blob/ed5649eb954c7c47e11eb2d2ea2b84b9336c4c4b/framework/src/state_machine/state_machine.ts#L119).

3. **Array ordering is checked manually when a helper function could be used:**
In the [PoAModule.initGenesisState](https://github.com/LiskHQ/lisk-sdk/blob/v6.1.0-beta.0/framework/src/modules/poa/module.ts#L209-L219) function, there is a check for whether the validatorAddresses list is sorted, by comparing each of its elements against the corresponding element in [...validatorAddresses].sort(). Instead, the objectUtils.isBufferArrayOrdered helper function should be used. The same applies to the check done later in the function on the activeValidators list: objectUtils.isBufferArrayOrdered(activeValidatorAddresses) should be used.

4: The shuffleValidatorList function is defined both in [PoA](https://github.com/LiskHQ/lisk-sdk/blob/ed5649eb954c7c47e11eb2d2ea2b84b9336c4c4b/framework/src/modules/poa/utils.ts#L20) and [PoS](https://github.com/LiskHQ/lisk-sdk/blob/ed5649eb954c7c47e11eb2d2ea2b84b9336c4c4b/framework/src/modules/pos/utils.ts#L102):
Both do essentially the same thing, but are implemented in slightly different ways. Ideally a common implementation should be used by both.

### Steps to reproduce

N/A

### Which version(s) does this affect? (Environment, OS, etc...)

`6.1.0-beta.1`

### PR DESCRIPTION
**Pull request by Phanco**
### What was the problem?

This PR resolves #8964

### How was it solved?
1. `RegisterAuthorityParams` reordered
2. Skipped as it has been resolved by PR #8967
3. `isBufferArrayOrdered` in initGenesisState
4. `shuffleValidatorList` in PoA is removed and solely using PoS

### How was it tested?
Test Cases Passed

### CODE REVIEW

**Review by mitsuaki-u — APPROVED** [review]

File: framework/src/modules/poa/module.ts [hunk 1]
```diff
@@ -206,23 +212,18 @@ export class PoAModule extends BaseModule {
...
-			if (!validatorAddresses[i].equals(sortedValidatorsByAddress[i])) {
-				throw new Error('`validators` must be ordered lexicographically by address.');
-			}
+		if (!objects.isBufferArrayOrdered(validatorAddresses)) {
+			throw new Error('`validators` must be ordered lexicographically by address.');
+		}
 
-			if (!/^[a-z0-9!@$&_.]+$/g.test(validators[i].name)) {
+		for (const poaValidator of validators) {
+			if (!/^[a-z0-9!@$&_.]+$/g.test(poaValidator.name)) {
```
Comment (ishantiw) [inline framework/src/modules/poa/module.ts:220]: if there is a constant for this regex then use that or else create a new constant and use it here

File: framework/src/modules/poa/module.ts [hunk 2]
```diff
@@ -30,7 +36,7 @@ import {
 	MAX_UINT64,
 	defaultConfig,
 } from './constants';
-import { shuffleValidatorList } from './utils';
+import { shuffleValidatorList } from '../pos/utils';
```
Comment (ishantiw) [inline framework/src/modules/poa/module.ts:39]: poa will be dependent on pos in this case for some functions, probably best would be to extract this out to file under `modules/utils.ts`(create a new one)

**Review by ishantiw — CHANGES_REQUESTED** [review]

File: framework/src/modules/poa/module.ts (hunk 2 above)
Comment (Phanco) [reply framework/src/modules/poa/module.ts]: Created a folder `utils` and moved there

**Review by ishantiw — APPROVED** [review]
