### PR TITLE
Fix cache logging and destruction - Closes #4198, #4206

### LINKED ISSUE #4198: Improve cache logging
### Expected behavior
Either change the log level to `trace` or remove it completely if its not required.
### Actual behavior
For every single block and transaction, an info log is logged which is reduandant and doesn't add any value.
`
Cache - Keys with patterns: '/api/blocks*,/api/transactions*' cleared from cache on 'chain:blocks:change'
`
### Steps to reproduce
- Enable caching before running the node
- Also send multiple requests to `api/node/status` and other endpoints to see the cache related to logs
### Which version(s) does this affect? (Environment, OS, etc...)
2.1.x

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?
Caching was returning undefined or null, but it was not handled properly.
Also, cache logs were in `debug` level, but it should've been `trace`

### How did I solve it?
- Change cache related logs to `trace`
- Properly handle result of `cache`

### How to manually test it?
- Call /node/status endpoint with cache enabled
- Set to debug level and cache enabled. It should not log any cache related things

### Review checklist

- [ ] The PR resolves #4198 #4206 
- [ ] All new code is covered with unit tests
- [ ] Relevant integration / functional tests are added
- [ ] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [ ] Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/http_api/controllers/node.js [hunk 1]
```diff
@@ -124,7 +121,7 @@ async function _getConfirmedTransactionCount() {
 			);
 		} catch (error) {
 			// Ignore error and just put warn
-			library.components.logger.warn("Transaction count wasn't cached", error);
+			library.components.logger.debug(error, "Transaction count wasn't cached");
```
Comment (ManuGowda) [inline framework/src/modules/http_api/controllers/node.js]: this is invalid log message, it should be `Failed to set transaction count` or something like that

Comment (shuse2) [reply framework/src/modules/http_api/controllers/node.js]: I think it is correct as meaning, but since it's the same error message so ill update it
