### PR TITLE
Fix plugin loading in child process and prevent application from crash if child process crashes - Closes #3142

### LINKED ISSUE #3142: Fix plugin loading in child process and prevent application from crash if child process crashes
### Expected behavior

Any plugin should be able to load up in child process. And if a plugin crashes the parent process should keep running.

### Actual behavior

Plugins can't be loaded at the moment and if a plugin crashes It crashed the parent process.

### Steps to reproduce

Run the application and kill httpApi process.

### Which version(s) does this affect? (Environment, OS, etc...)

`feature/child_process_module`

### PR DESCRIPTION
**Pull request by nazarhussain**
### What was the problem?

This PR resolves #3142

### How was it solved?

Fixed loading of child process plugins and prevent application from crashing. 

### How was it tested?

1. Run the test app with `node framework/test/test_app/index.js`
2. Check process tree with `htop` or any other utility 
3. You will notice a process named `devnet` and a child process running under as http-api-plugin
4. Kill that child process for http-api-plugin
5. Check if app shows proper log for plugin to exit
6. Check if app still keep running

### CODE REVIEW

File: framework/src/application/application.ts [hunk 1]
```diff
@@ -176,7 +176,9 @@ export class Application {
 
 	public registerPlugin(
 		pluginKlass: typeof BasePlugin,
-		options = {},
+		options: { [key: string]: any; loadAsChildProcess: boolean } = {
```
Comment (ManuGowda) [inline framework/src/application/application.ts:179]: maybe extract this to type.. in future if we expand it might grow and in general we can reuse if required?
`PluginOptions`?

File: framework/src/application/application.ts [hunk 2]
```diff
@@ -199,7 +201,7 @@ export class Application {
 		this._plugins[pluginAlias] = pluginKlass as InstantiablePlugin<BasePlugin>;
 	}
 
-	public overrideModuleOptions(alias: string, options?: object): void {
+	public overridePluginOptions(alias: string, options?: object): void {
```
Comment (ManuGowda) [inline framework/src/application/application.ts:204]: after defining the above type, u could use the type instead of `object`?

File: framework/src/application/node/node.ts [hunk 3]
```diff
@@ -209,7 +209,7 @@ export class Node {
 				Object.assign(this._applicationState, event.data);
 			});
 
-			this._logger.info('Modules ready and launched');
+			this._logger.info('Node ready and launched');
```
Comment (ManuGowda) [inline framework/src/application/node/node.ts:212]: since process, sync initiated below, is this log line correct? maybe it should below that?

File: framework/src/controller/child_process_loader.ts [hunk 4]
```diff
@@ -19,40 +19,43 @@ import { InstantiablePlugin, BasePlugin } from '../plugins/base_plugin';
...
+];
 
-const _loadModule = async (
+const _loadPlugin = async (
 	config: {
 		[key: string]: unknown;
 		socketsPath: SocketPaths;
 	},
-	moduleOptions: object,
+	pluginOptions: object,
```
Comment (ManuGowda) [inline framework/src/controller/child_process_loader.ts:33]: same here

File: framework/src/application/application.ts (hunk 2 above)
Comment (nazarhussain) [reply framework/src/application/application.ts:204]: We are not sure what configuration we get fro any plugin.

File: framework/src/application/node/node.ts (hunk 3 above)
Comment (nazarhussain) [reply framework/src/application/node/node.ts:212]: I think its correct here, Node is ready and launched. Rest is its internal processing.
