### PR TITLE
P2P peerBook disjoint fix and test improvements - Closes #4609 & #4599

### LINKED ISSUE #4609: P2P PeerBook newPeers and tiredPeers lists should be disjoint
### Expected behavior
- Peers in the PeerBook newPeers / tiredPeers never exist in both list.

### Actual behavior
- When baseList.removePeer() fail it could occur that Peers are remain in the list.

### Steps to reproduce
- With the code sample below it can be reproduced.

```	
if (!peerBook.hasPeer(peerInfo)) {
					peerBook.addPeer(peerInfo);
	}

	peerBook.upgradePeer(peerInfo);
});
```

### Which version(s) does this affect? (Environment, OS, etc...)
3.0

### PR DESCRIPTION
**Pull request by valamidev**
### What was the problem?
- In some scenario the triedPeers and the newPeers could have same Peers and removePeer were unable to remove them neither from the PeerBook. This could happen if the bucketId were equal with 0.

### How did I solve it?
- Correct the bucketId verify statement in the `BaseList.getBucket()`
- Additionally simplified the `PeerBook.removePeer()` and change the `BaseList._initBuckets()` into private function also removed the duplicated call from the triedPeersList Class.

### How to manually test it?
- `npm run test`

### Review checklist

- [x] The PR resolves #4609 & #4599
- [x] All new code is covered with unit tests
- [x] Relevant integration / functional tests are added
- [x] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [x] Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-p2p/src/peer_book/base_list.ts [hunk 1]
```diff
@@ -192,7 +183,7 @@ export class BaseList {
 	protected getBucket(peerId: string): Bucket | undefined {
 		const internalPeerInfo = this.peerIdToPeerInfo.get(peerId);
 
-		if (!internalPeerInfo?.bucketId) {
+		if (typeof internalPeerInfo?.bucketId !== 'number') {
```
Comment (yatki) [inline elements/lisk-p2p/src/peer_book/base_list.ts]: ❤️

File: elements/lisk-p2p/src/peer_book/base_list.ts [hunk 2]
```diff
@@ -204,4 +195,16 @@ export class BaseList {
 
 		return bucket;
 	}
+
+	private _initBuckets(): void {
+		// Init the Map with all the buckets
+		for (const bucketId of [
+			...new Array(this.peerListConfig.numOfBuckets).keys(),
+		]) {
+			this.bucketIdToBucket.set(
```
Comment (yatki) [inline elements/lisk-p2p/src/peer_book/base_list.ts]: ❤️

File: elements/lisk-p2p/test/unit/utils/select.ts [hunk 3]
```diff
@@ -352,6 +353,14 @@ describe('peer selector', () => {
 		});
 
 		describe('when there are less than 100 peers', () => {
+			beforeEach(function() {
+				sinon.stub(Math, 'random').returns(0.499);
```
Comment (yatki) [inline elements/lisk-p2p/test/unit/utils/select.ts]: ❤️ Could you please add a test case where it returns 0.5 and 0.501
