### PR TITLE
Fix incorrect error status check

### LINKED ISSUE #8606: The error method incorrectly checks the status field
### Description

The `error` method of the interoperability module incorrectly verifies the bounds of its status parameter. As specified in the LIP, it attempts to guarantee that the error status is above `MAX_RESERVED_ERROR_STATUS`; however, with the check highlighted in the figure below, it will only errors out on negative numbers and zero.

https://github.com/LiskHQ/lisk-sdk/blob/89e7504ef5eb6183aefe576a93be3d6052e56038/framework/src/modules/interoperability/base_interoperability_method.ts#L150-L166

TODO
- Modify the check to ensure the values below or equal to MAX_RESERVED_ERROR_STATUS error out.
- Add unit tests for `error` method

### Affected version

`6.0.0-beta.2`

### PR DESCRIPTION
**Pull request by sitetester**
### What was the problem?

This PR resolves #8606

### How was it solved?

Check updated per LIP

### How was it tested?

Test cases added

### CODE REVIEW

**Review by ishantiw — APPROVED** [review]

File: framework/src/modules/interoperability/base_interoperability_method.ts [hunk 1]
```diff
@@ -146,11 +146,14 @@ export abstract class BaseInteroperabilityMethod<
...
 
+	// https://github.com/LiskHQ/lips/blob/main/proposals/lip-0045.md#error
 	// eslint-disable-next-line @typescript-eslint/require-await
 	public async error(context: MethodContext, ccm: CCMsg, errorStatus: number): Promise<void> {
 		// Error codes from 0 to MAX_RESERVED_ERROR_STATUS (included) are reserved to the Interoperability module.
-		if (errorStatus <= 0 && errorStatus <= MAX_RESERVED_ERROR_STATUS) {
-			throw new Error('Invalid error status.');
+		if (errorStatus >= 0 && errorStatus <= MAX_RESERVED_ERROR_STATUS) {
+			throw new Error(
+				`Error codes from 0 to ${MAX_RESERVED_ERROR_STATUS} (included) are reserved to the Interoperability module.`,
```
Comment (Phanco) [inline framework/src/modules/interoperability/base_interoperability_method.ts:155]: the word `inclusive` is used elsewhere to describe out-of-range error. Consistency is advised.

**Review by Phanco — APPROVED** [review]
LGTM, suggestions given
