### PR TITLE
P2P update DEFAULT_BAN_TIME in ms

### LINKED ISSUE #4561: P2P: Peer ban expires before 24 hours
### Expected behavior
The peer should be unbanned after 24 hours
### Actual behavior
The peer is banned and unbanned within 24hrs
### Steps to reproduce
Send malicious payload to network http://devnet-seed-01.liskdev.net:6040/
### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0-alpha.2

### PR DESCRIPTION
**Pull request by valamidev**
### What was the problem?
- After executing P2P banPeer request the ban expired earlier than expected. 

### How did I solve it?
- Modify `DEFAULT_BAN_TIME = 86400;` to `DEFAULT_BAN_TIME = 86400000;` which is the correct value of 1 day in milliseconds. Also related default configurations are modified.

### How to manually test it?
- `npm run test`

### Review checklist

- [x] The PR resolves #4561
- [x] All new code is covered with unit tests
- [x] Relevant integration / functional tests are added
- [x] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [x] Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-p2p/src/constants.ts [hunk 1]
```diff
@@ -17,7 +17,7 @@ import { getRandomBytes } from '@liskhq/lisk-cryptography';
 // General P2P constants
 export const DEFAULT_NODE_HOST_IP = '0.0.0.0';
 export const DEFAULT_LOCALHOST_IP = '127.0.0.1';
-export const DEFAULT_BAN_TIME = 86400;
+export const DEFAULT_BAN_TIME = 86400000; // Milliseconds in a day -> hours*minutes*seconds*milliseconds;
```
Comment (diego-G) [inline elements/lisk-p2p/src/constants.ts]: Remove `;`

File: framework/src/modules/network/defaults/config.js [hunk 2]
```diff
@@ -154,7 +154,7 @@ const defaultConfig = {
 		wsPort: 5000,
 		address: '0.0.0.0',
 		discoveryInterval: 30000,
-		peerBanTime: 86400,
+		peerBanTime: 86400000,
```
Comment (diego-G) [inline framework/src/modules/network/defaults/config.js]: I'd import the constants from the P2P library.

File: framework/src/modules/network/defaults/config.js [hunk 3]
```diff
@@ -14,6 +14,8 @@
 
 'use strict';
 
+const LiskP2P = require('@liskhq/lisk-p2p');
```
Comment (shuse2) [inline framework/src/modules/network/defaults/config.js]: I think it shouldn't read the library from this, this is more of a application constants
If it doesn't require default value (as it is already defined in the library), we can remove from the default
