### PR TITLE
Fix functional and unit tests - Closes #3152

### LINKED ISSUE #3152: Change the API response to return an array of errors
### Expected behavior
The API response should return all the errors encountered when processing a request. Therefore, the structure of the API response should be:
```
{
   "code": 404,
   "error": [{
      message: "<ERROR_MESSAGE>"
   },
   {
      ...
   }]
}
```
### Actual behavior
The structure of API response in case of an error is not very extensible. It contains only one property with the name `message` which is of type string. In cases where there are multiple errors, it is impossible to return all the errors in this format. The current structure of the API response in case of an error is as follow:
```
{
   "code": 404,
   "message": "<ERROR_MESSAGE>"
}
```
 
### Which version(s) does this affect? (Environment, OS, etc...)
1.7

### PR DESCRIPTION
**Pull request by mitsujutsu**
### What was the problem?

Functional and unit tests failing after implementation of `improving transactions processing efficiency`.

API endpoints must be updated to return array of errors from `elements`.

### How did I fix it?

- Update `POST` API endpoints for transaction and signature

- Added transaction timestamp validation to `process_transactions` sub-module

- `VoteTransaction` in elements also checks for null `username` value

- Fix related unit tests

- Fix related functional tests

### How to test it?

Run functional tests related to API.

### Review checklist

* The PR resolves #3152 #3297 #3377 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Comment by mitsujutsu** [comment]
@pablitovicente Can you try building and linking elements and then run the functional tests again? I will check the signature issue and the unit tests.

**Comment by pablitovicente** [comment]
> @pablitovicente Can you try building and linking elements and then run the functional tests again? I will check the signature issue and the unit tests.

Elements is already linked in the repository maybe try cleaning and building again in your end?

**Comment by mitsujutsu** [comment]
It seems things broke after the merge from development. `npm run build` fails with `lisk-transaction-pool` on `feature/improve_transactions_processing_efficiency`

File: framework/src/modules/chain/submodules/blocks/process.js [hunk 1]
```diff
@@ -348,6 +354,7 @@ Process.prototype.getCommonBlock = function(peer, height, cb) {
 			if (comparisonFailed && modules.transport.poorConsensus()) {
 				return modules.blocks.chain.recoverChain(cb);
 			}
+			if (err) err = new Error(err);
```
Comment (shuse2) [inline framework/src/modules/chain/submodules/blocks/process.js]: prefer
```
if (err) {
  return setImmediate(cb, new Error(err));
}
```

File: framework/src/modules/http_api/controllers/signatures.js [hunk 2]
```diff
@@ -55,20 +55,31 @@ SignaturesController.postSignature = async function(context, next) {
...
-
-		if (processingError.test(data.message)) {
-			error = new ApiError(data.message, apiCodes.PROCESSING_ERROR);
-		} else if (badRequestBodyError.test(data.message)) {
-			error = new ApiError(data.message, apiCodes.BAD_REQUEST);
+		if (data.code === apiCodes.PROCESSING_ERROR) {
+			error = new ApiError(
+				'Error processing signature',
+				apiCodes.PROCESSING_ERROR,
+				data.error
```
Comment (shuse2) [inline framework/src/modules/http_api/controllers/signatures.js]: isn't this `data.error` a signle Error object?
ApiError should accept array of error as third parameter?

same for below

File: framework/src/modules/http_api/helpers/error_handlers.js [hunk 3]
```diff
@@ -14,30 +14,32 @@
...
+ * @param {array | object} e
  * @see Parent: {@link helpers}
  * @todo Add description for the params
  */
 // TODO: Move this functionality to logger component
-function convertErrorsToString(errors) {
-	if (Array.isArray(errors) && errors.length > 0) {
-		return errors
-			.filter(e => e instanceof Error)
+function convertErrorsToString(e) {
```
Comment (shuse2) [inline framework/src/modules/http_api/helpers/error_handlers.js]: prefer to use `errors`, but any reason changed?

File: framework/src/modules/http_api/schema/swagger.yml [hunk 4]
```diff
@@ -2434,6 +2434,43 @@ definitions:
...
+        description: Expected value
+        type: 
+            - string
+            - number
+      actual: 
+        description: Actual value
+        type: 
+            - string
+            - number
+      jse_shortmsg:
```
Comment (shuse2) [inline framework/src/modules/http_api/schema/swagger.yml]: Let's keep in mind to remove this property

File: framework/src/modules/chain/submodules/blocks/process.js (hunk 1 above)
Comment (pablitovicente) [reply framework/src/modules/chain/submodules/blocks/process.js]: @shuse2 this case is special and needs to stay as it is because err can be null; changing this might require refactoring older methods.

Comment (shuse2) [reply framework/src/modules/chain/submodules/blocks/process.js]: yes, im just saying about the format =)

File: framework/src/modules/http_api/controllers/signatures.js (hunk 2 above)
Comment (mitsujutsu) [reply framework/src/modules/http_api/controllers/signatures.js]: It has been changed to an `array` from a single object, so user can see more detailed errors from `elements`.

File: framework/src/modules/http_api/helpers/error_handlers.js (hunk 3 above)
Comment (mitsujutsu) [reply framework/src/modules/http_api/helpers/error_handlers.js]: this is a temporary file that I think should be moved to `logger`. the reason I changed is because it can also refer to a single error or string.

File: framework/src/modules/http_api/controllers/signatures.js (hunk 2 above)
Comment (shuse2) [reply framework/src/modules/http_api/controllers/signatures.js]: would it be possible to change the property name to `data.errors`?
