### PR TITLE
Use `peerId` instead of constructing it on Block Synchronization Mechanism - Closes #4580

### LINKED ISSUE #4580: bestPeer.id returns `undefined:4000`
### Expected behavior
Expect `BlockSynchronizationMechanism.run` to use `bestPeer.peerId` instead of `bestPeer.id`

### Actual behavior
`_computeBestPeer` adds the property `id` to the object `bestPeer` as `${bestPeer.ip}:${bestPeer.wsPort}` but `bestPeer.ip` is `undefined` because P2P now return `ipAddress` instead of `ip`

### Steps to reproduce
Execute `BlockSynchronizationMechanism._computeBestPeer`
It will return `undefined:4000`

### Which version(s) does this affect? (Environment, OS, etc...)
`3.0.0-alpha.2`

### PR DESCRIPTION
**Pull request by limiaspasdaniel**
### What was the problem?
Refer to #4580 
### How did I solve it?
Use `peerId` property now available on peer objects instead of computing it manually.

I also improved some logs and updated unit tests
### How to manually test it?
Run `block_synchronization_mechanism.spec.js`
### Review checklist

- [ ] The PR resolves #4580 
- [ ] All new code is covered with unit tests
- [ ] Relevant integration / functional tests are added
- [ ] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [ ] Documentation has been added/updated

### CODE REVIEW

File: framework/test/jest/unit/specs/modules/chain/synchronizer/block_synchronization_mechanism/peers.js [hunk 1]
```diff
@@ -26,93 +26,81 @@ module.exports = {
 			blockVersion: 2,
 			maxHeightPrevoted: 1,
 			height: 66,
-			ip: '127.0.0.2',
-			wsPort: '5000',
```
Comment (lsilvs) [inline framework/test/jest/unit/specs/modules/chain/synchronizer/block_synchronization_mechanism/peers.js]: Is this supposed to be a `P2PPeerInfo`?
If so, would be better to just replace `ip` for `ipAddress` and leave `wsPort`

REF.: https://github.com/LiskHQ/lisk-sdk/blob/development/elements/lisk-p2p/src/p2p_types.ts#L73-L80

File: framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js [hunk 2]
```diff
@@ -396,28 +404,32 @@ class BlockSynchronizationMechanism extends BaseSynchronizer {
...
-			const blockIds = (await this.storage.entities.Block.get(
-				{
-					height_in: heightList,
-				},
-				{
-					sort: 'height:asc',
-					limit: heightList.length,
-				},
-			)).map(block => block.id);
+			const blockIds = (
```
Comment (ManuGowda) [inline framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js]: looks like the same formatting issue? if its fixing the formatting please ignore this comment.

Comment (limiaspasdaniel) [reply framework/src/modules/chain/synchronizer/block_synchronization_mechanism.js]: Yeah probably prettier got updated, it's fine.
