### PR TITLE
Node fail to sync when block contains multisignature transaction - Closes #3612

### LINKED ISSUE #3612: Node fail to sync when block contains multisignature transaction
### Expected behavior
The node should be able to sync when a block contains multisignature registration transaction.
### Actual behavior
It fails with following message:
```
14:03:52.617Z  INFO lisk-framework: Block 5753985202868417271 loaded from the network height: 17
14:03:52.625Z DEBUG lisk-framework:
    Block processing failed { id: '1354458273227907673',
      err:
       'Transaction: 4767118963976999553 failed at .multisignature.keysgroup: \'.multisignature.keysgroup\' should NOT have fewer than 1 items',
      module: 'blocks',
      block:
       { id: '1354458273227907673',
         version: 1,
         timestamp: 93719360,
         height: 18,
         previousBlock: '5753985202868417271',
         numberOfTransactions: 10,
         totalAmount: 0,
         totalFee: 15000000000,
         reward: 0,
         payloadLength: 3130,
         payloadHash:
          '7377aae41a8af606f505d18c63ce6994bf04c1844f192a87c822aaf35e6ca526',
         generatorPublicKey:
          '85b07e51ffe528f272b7eb734d0496158f2b0f890155ebe59ba2989a8ccc9a49',
         generatorId: '6214967903930344618L',
         blockSignature:
          'f8670420bd65a232723d6e1b4de4266e9fe05e67ecb1821a7e4d53c5c0cd31a2da048899631b70fff50f2ff1f774a42ec9470f14b30d2861a7acefa55894ee08',
         confirmations: NaN,
         totalForged: '15000000000',
         transactions:
          [ [MultisignatureTransaction],
            [MultisignatureTransaction],
            [MultisignatureTransaction],
            [MultisignatureTransaction],
            [MultisignatureTransaction],
            [MultisignatureTransaction],
            [MultisignatureTransaction],
            [MultisignatureTransaction],
            [MultisignatureTransaction],
            [MultisignatureTransaction] ] } }
14:03:52.628Z DEBUG lisk-framework: Perform chain recovery due to poor consensus
14:03:52.628Z  WARN lisk-framework: Chain comparison failed, starting recovery
```
### Steps to reproduce
Check logs on `fra1-alpha2-001.liskdev.net` machine.
### Which version(s) does this affect? (Environment, OS, etc...)
`2.0.0-alpha.2`

### PR DESCRIPTION
**Pull request by lsilvs**
### What was the problem?
`MultisignatureTransaction.assetFromSync` was assigning empty array to `keysgroup` when `m_keysgroup` was an array

### How did I fix it?
By assigning the passed value for that scenario

### How to test it?
Sync with v1.6 nodes
Run `elements/lisk-transactions/test/4_multisignature_transaction.ts` test

### Review checklist

* The PR resolves #3612
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-transactions/src/4_multisignature_transaction.ts [hunk 1]
```diff
@@ -394,16 +394,18 @@ export class MultisignatureTransaction extends BaseTransaction {
...
+		// When syncing, nodes should receive `m_keysgroup` as csv string and then split the values into an array
+		// Due to the issue https://github.com/LiskHQ/lisk-sdk/issues/3612, v1.6 nodes will send `m_keysgroup` as an array thus skipping the array convertion
 		const multisignature = {
 			min: raw.m_min,
 			lifetime: raw.m_lifetime,
-			keysgroup: [],
+			keysgroup:
+				typeof raw.m_keysgroup === 'string'
+					? raw.m_keysgroup.split(',')
+					: raw.m_keysgroup,
```
Comment (4miners) [inline elements/lisk-transactions/src/4_multisignature_transaction.ts]: Will it be fine when `raw.m_keysgroup` is `null`?

Comment (lsilvs) [reply elements/lisk-transactions/src/4_multisignature_transaction.ts]: Yes, because of line `394`

Comment (lsilvs) [reply elements/lisk-transactions/src/4_multisignature_transaction.ts]: I've just pushed a new test case scenario covering this ;)
