### PR TITLE
Cross chain commands not registered

### LINKED ISSUE #8241: Cross chain commands of interoperability module are not registered
### Expected behavior

Cross chain commands of interoperability module should be registered similar to other modules supporting ccCommands

### Actual behavior

Cross chain commands of interoperability module are not registered

### Steps to reproduce

`Send CCU using chain connector plugin including registration CCM and it doesn't find any ccCommand associated`

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-alpha.15`

### PR DESCRIPTION
**Pull request by ishantiw**
### What was the problem?

This PR resolves #8241 #8234 #8233 #8246 #8245

### How was it solved?
[🐛](https://github.com/LiskHQ/lisk-sdk/commit/ed307e6b033c71c7e14a8ee4af3a56f93d2afeb0) [Add interopMethod dependency to token module ccMethod -](https://github.com/LiskHQ/lisk-sdk/commit/ed307e6b033c71c7e14a8ee4af3a56f93d2afeb0) [Closes](https://github.com/LiskHQ/lisk-sdk/commit/ed307e6b033c71c7e14a8ee4af3a56f93d2afeb0) https://github.com/LiskHQ/lisk-sdk/issues/8233

[🐛](https://github.com/LiskHQ/lisk-sdk/commit/5a4d8ff6a256619afb4dec8c579852e4f99cf05b) [Interop ccCommands are not registered -](https://github.com/LiskHQ/lisk-sdk/commit/5a4d8ff6a256619afb4dec8c579852e4f99cf05b) [Closes](https://github.com/LiskHQ/lisk-sdk/commit/5a4d8ff6a256619afb4dec8c579852e4f99cf05b) https://github.com/LiskHQ/lisk-sdk/issues/8241 https://github.com/LiskHQ/lisk-sdk/issues/8234

[♻️](https://github.com/LiskHQ/lisk-sdk/commit/51e9a4d28168080c1207f87cb6973d83ab28f956) [Save data on newBlock even when receiving client is not working -](https://github.com/LiskHQ/lisk-sdk/commit/51e9a4d28168080c1207f87cb6973d83ab28f956)[ Closes ](https://github.com/LiskHQ/lisk-sdk/commit/51e9a4d28168080c1207f87cb6973d83ab28f956)  #8246 

[🐛](https://github.com/LiskHQ/lisk-sdk/pull/8244/commits/d33bc24bfef8dc6ed5baf88ec756a567873df3a1) [Cross chain transfer command init is not called -](https://github.com/LiskHQ/lisk-sdk/pull/8244/commits/d33bc24bfef8dc6ed5baf88ec756a567873df3a1) [Closes](https://github.com/LiskHQ/lisk-sdk/pull/8244/commits/d33bc24bfef8dc6ed5baf88ec756a567873df3a1) https://github.com/LiskHQ/lisk-sdk/issues/8245

[🐛 Incorrect condition for messageFeeTokenID in transferCrossChain - Closes https://github.com/LiskHQ/lisk-sdk/issues/8246](https://github.com/LiskHQ/lisk-sdk/pull/8244/commits/cdff9b09d053177ef31555d36870ac4c217763bd) 

### How was it tested?

- `Run all the related unit tests`
- Run ChainConnector plugin to observe if the data is being saved when receivingChainClient is not working

### CODE REVIEW

**Review by Phanco — APPROVED** [review]
Cross-checked with all 5 issues and looks good. Thank you.

File: framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts [hunk 1]
```diff
@@ -158,14 +159,9 @@ export class ChainConnectorPlugin extends BasePlugin<ChainConnectorPluginConfig>
...
-		this._receivingChainID = Buffer.from(
-			(
-				await this._receivingChainClient.invoke<OwnChainAccountJSON>(
-					'interoperability_getOwnChainAccount',
-				)
-			).chainID,
-			'hex',
-		);
+		if (this._receivingChainID[0] !== this._ownChainID[0]) {
+			throw new Error('Receiving Chain ID does not match the sending chain network.');
```
Comment (mitsuaki-u) [inline framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:163]:
```suggestion
			throw new Error('Receiving Chain ID network does not match the sending chain network.');
```

File: framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts [hunk 2]
```diff
@@ -203,20 +201,31 @@ export class ChainConnectorPlugin extends BasePlugin<ChainConnectorPluginConfig>
...
+					await this._saveDataOnNewBlock(newBlockHeader);
+
+					return;
+				}
+			} catch (error) {
+				// If receivingChainAPIClient is not ready then still save data on new block
 				await this._saveDataOnNewBlock(newBlockHeader);
+				this.logger.error(
+					error,
+					'Error occured while using accessing receivingChain API Client but all data is saved on newBlock.',
```
Comment (mitsuaki-u) [inline framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:223]:
```suggestion
					'Error occurred while using accessing receivingChain API Client but all data is saved on newBlock.',
```

Comment (mitsuaki-u) [reply framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:223]: Is it guaranteed that the data was saved before the error occurred?

Comment (ishantiw) [reply framework-plugins/lisk-framework-chain-connector-plugin/src/chain_connector_plugin.ts:223]: it will throw error and will not log this if something goes wrong while save data

**Review by mitsuaki-u — APPROVED** [review]
