### PR TITLE
Inconsistent cache behavior - error when cache enabled - Closes #3600

### LINKED ISSUE #3600: Inconsistent cache behavior - error when cache enabled
### Expected behavior
There should be no error when cache is enabled and it should use the cache.
### Actual behavior
There is random error showing when cache is enabled. You can see that for some requests it works and for others error is logged.
```
13:41:27.828Z DEBUG lisk-framework: No delegates enabled
13:41:28.424Z DEBUG lisk-framework: GET /api/node/status from 62.23.239.233
13:41:28.424Z DEBUG lisk-framework: Cache - Get value for key: transactionCount | Status: true
13:41:28.470Z DEBUG lisk-framework: GET /api/blocks?&sort=height:desc&offset=0&limit=1 from 10.127.0.2
13:41:28.472Z DEBUG lisk-framework: Cache - Get value for key: /api/blocks?&sort=height:desc&offset=0&limit=1 | Status: true
13:41:28.474Z DEBUG lisk-framework: GET /api/peers?sort=version:desc&offset=0&limit=100 from 10.127.0.2
13:41:28.479Z DEBUG lisk-framework: Cache - Sending cached response for url: /api/blocks?&sort=height:desc&offset=0&limit=1
13:41:28.482Z DEBUG lisk-framework: GET /api/peers?sort=version:desc&offset=100&limit=100 from 10.127.0.2
13:41:28.830Z DEBUG lisk-framework: No delegates enabled
13:41:29.141Z  INFO lisk-framework: Updated info of peer 178.128.54.218:5000 to {"os":"linux4.15.0-48-generic","version":"2.0.0-alpha.2","wsPort":5000,"httpPort":4000,"minVersion":"1.1.0-rc.0","protocolVersion":"1.0","height":1,"nethash":"198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d","broadhash":"198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d","nonce":"0AEyS6dgi5M7fUGm","state":2,"ipAddress":"178.128.54.218"}
13:41:29.142Z  INFO lisk-framework: Received inbound request for procedure updateMyself
13:41:29.832Z DEBUG lisk-framework: No delegates enabled
13:41:30.810Z  INFO lisk-framework: Starting sync
13:41:30.811Z DEBUG lisk-framework: Establishing broadhash consensus before sync: 100 %
13:41:30.811Z DEBUG lisk-framework: Loading blocks from the network
13:41:30.812Z DEBUG lisk-framework: MONITOR: undefined -> chain:loader:sync { blocks: 0, height: 1 }
13:41:30.826Z DEBUG lisk-framework: GET /api/node/status from 10.127.0.2
13:41:30.827Z DEBUG lisk-framework: Cache - Get value for key: transactionCount | Status: false
13:41:30.829Z DEBUG lisk-framework: GET /api/node/constants from 10.127.0.2
13:41:30.828Z  WARN lisk-framework:
    Transaction count wasn't cached Error: Cache Disabled
        at Cache.getJsonForKey (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/components/cache/cache.js:113:10)
        at Cache.wrappedFunction (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/newrelic/lib/transaction/tracer/index.js:315:51)
        at getConfirmedCountFromCache (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/submodules/transactions.js:604:9)
        at nextTask (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/async/dist/async.js:5324:14)
        at Object.waterfall (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/async/dist/async.js:5334:5)
        at getTransactionsCount (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/submodules/transactions.js:599:9)
        at wrapped (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/newrelic/lib/transaction/tracer/index.js:188:22)
        at wrappedFunction (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/newrelic/lib/transaction/tracer/index.js:319:49)
        at Promise (internal/util.js:275:30)
        at new Promise (<anonymous>)
        at wrappedFunction (internal/util.js:274:12)
        at Object.getNodeStatus (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/chain.js:247:6)
        at Object.handler (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/index.js:117:45)
        at InMemoryChannel.invoke (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/controller/channels/in_memory_channel.js:121:37)
        at Bus.invoke (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/controller/bus.js:188:48)
        at InMemoryChannel.invoke (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/controller/channels/in_memory_channel.js:124:19)
13:41:30.830Z DEBUG lisk-framework: Cache - Get value for key: transactionCount | Status: false
13:41:30.831Z  WARN lisk-framework:
    Transaction count wasn't cached Error: Cache Disabled
        at Cache.getJsonForKey (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/components/cache/cache.js:113:10)
        at Cache.wrappedFunction (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/newrelic/lib/transaction/tracer/index.js:315:51)
        at getConfirmedCountFromCache (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/submodules/transactions.js:604:9)
        at nextTask (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/async/dist/async.js:5324:14)
        at Object.waterfall (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/async/dist/async.js:5334:5)
        at getTransactionsCount (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/submodules/transactions.js:599:9)
        at wrapped (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/newrelic/lib/transaction/tracer/index.js:188:22)
        at wrappedFunction (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/newrelic/lib/transaction/tracer/index.js:319:49)
        at Promise (internal/util.js:275:30)
        at new Promise (<anonymous>)
        at wrappedFunction (internal/util.js:274:12)
        at Object.getNodeStatus (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/chain.js:247:6)
        at Object.handler (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/index.js:117:45)
        at InMemoryChannel.invoke (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/controller/channels/in_memory_channel.js:121:37)
        at Bus.invoke (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/controller/bus.js:188:48)
        at InMemoryChannel.invoke (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/controller/channels/in_memory_channel.js:124:19)
13:41:30.837Z DEBUG lisk-framework: Cache - Set value for key: transactionCount | Status: false
13:41:30.838Z  WARN lisk-framework:
    Transaction count wasn't cached Error: Cache Disabled
        at Cache.setJsonForKey (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/components/cache/cache.js:132:10)
        at Cache.wrappedFunction (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/newrelic/lib/transaction/tracer/index.js:315:51)
        at updateConfirmedCountToCache (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/submodules/transactions.js:635:9)
        at nextTask (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/async/dist/async.js:5324:14)
        at Immediate.next (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/async/dist/async.js:5331:9)
        at Immediate.<anonymous> (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/async/dist/async.js:969:16)
        at Shim.applySegment (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/newrelic/lib/shim/shim.js:1386:20)
        at Immediate.wrapper (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/newrelic/lib/shim/shim.js:2010:17)
        at runCallback (timers.js:706:11)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
        at process.topLevelDomainCallback (domain.js:120:23)
13:41:30.845Z DEBUG lisk-framework: Cache - Set value for key: transactionCount | Status: false
13:41:30.845Z  WARN lisk-framework:
    Transaction count wasn't cached Error: Cache Disabled
        at Cache.setJsonForKey (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/components/cache/cache.js:132:10)
        at Cache.wrappedFunction (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/newrelic/lib/transaction/tracer/index.js:315:51)
        at updateConfirmedCountToCache (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/lisk-framework/src/modules/chain/submodules/transactions.js:635:9)
        at nextTask (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/async/dist/async.js:5324:14)
        at Immediate.next (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/async/dist/async.js:5331:9)
        at Immediate.<anonymous> (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/async/dist/async.js:969:16)
        at Shim.applySegment (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/newrelic/lib/shim/shim.js:1386:20)
        at Immediate.wrapper (/home/lisk/lisk-2.0.0-alpha.2-Linux-x86_64/node_modules/newrelic/lib/shim/shim.js:2010:17)
        at runCallback (timers.js:706:11)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
        at process.topLevelDomainCallback (domain.js:120:23)
13:41:30.902Z DEBUG lisk-framework:
    Application state { os: 'linux4.15.0-48-generic',
      version: '2.0.0-alpha.2',
      wsPort: 5000,
      httpPort: 4000,
      minVersion: '1.1.0-rc.0',
      protocolVersion: '1.0',
      height: 1,
      nethash:
       '198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d',
      broadhash:
       '198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d',
      nonce: '61bDYrppksHTjahu' }
13:41:30.902Z DEBUG lisk-framework:
    MONITOR: undefined -> app:state:updated { os: 'linux4.15.0-48-generic',
      version: '2.0.0-alpha.2',
      wsPort: 5000,
      httpPort: 4000,
      minVersion: '1.1.0-rc.0',
      protocolVersion: '1.0',
      height: 1,
      nethash:
       '198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d',
      broadhash:
       '198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d',
      nonce: '61bDYrppksHTjahu' }
13:41:30.904Z DEBUG lisk-framework: Establishing broadhash consensus after sync: 100 %
13:41:30.904Z  INFO lisk-framework: Finished sync
13:41:30.908Z DEBUG lisk-framework: No delegates enabled
13:41:30.955Z  INFO lisk-framework: Received inbound request for procedure list
13:41:30.963Z  INFO lisk-framework: Updated info of peer 159.203.112.223:5000 to {"os":"linux4.15.0-48-generic","version":"2.0.0-alpha.2","wsPort":5000,"httpPort":4000,"minVersion":"1.1.0-rc.0","protocolVersion":"1.0","height":1,"nethash":"198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d","broadhash":"198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d","nonce":"T5GkLqiYxD3CAxXL","state":2,"ipAddress":"159.203.112.223"}
13:41:30.964Z  INFO lisk-framework: Received inbound request for procedure updateMyself
13:41:31.682Z  INFO lisk-framework: Updated info of peer 134.209.75.228:5000 to {"os":"linux4.15.0-48-generic","version":"2.0.0-alpha.2","wsPort":5000,"httpPort":4000,"minVersion":"1.1.0-rc.0","protocolVersion":"1.0","height":1,"nethash":"198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d","broadhash":"198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d","nonce":"nfCKbV7H4iTCuahy","state":2,"ipAddress":"134.209.75.228"}
13:41:31.682Z  INFO lisk-framework: Received inbound request for procedure updateMyself
13:41:31.910Z DEBUG lisk-framework: No delegates enabled
13:41:32.910Z DEBUG lisk-framework: No delegates enabled
13:41:33.471Z DEBUG lisk-framework: GET /api/blocks?&sort=height:desc&offset=0&limit=1 from 10.127.0.2
13:41:33.472Z DEBUG lisk-framework: Cache - Get value for key: /api/blocks?&sort=height:desc&offset=0&limit=1 | Status: true
```
### Steps to reproduce
Check logs on `alpha2-seed-01.liskdev.net`.
### Which version(s) does this affect? (Environment, OS, etc...)
`2.0.0-alpha.2`

### PR DESCRIPTION
**Pull request by pablitovicente**
### What was the problem?

Incorrect property was being used for checking if cache was enabled

### How did I fix it?

By using the correct properties to check if cache is enabled

### How to test it?

- build should be green
- Disable cache from the config and `GET http://localhost:4000/api/node/status` no messages about cache should be shown.

### Review checklist

* The PR resolves #3600
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Comment by shuse2** [comment]
Probably not related directly, but probably it should check the same usage in `loader.js`

**Comment by pablitovicente** [comment]
> Probably not related directly, but probably it should change the same usage in `loader.js`

Yes I was wondering if to change it there too will run some tests and commit accordingly

File: framework/src/modules/chain/submodules/loader.js [hunk 1]
```diff
@@ -867,7 +867,7 @@ __private.loadBlocksFromNetwork = function(cb) {
  */
 __private.sync = function(cb) {
 	library.logger.info('Starting sync');
-	if (components.cache) {
+	if (components.cache.cacheReady) {
```
Comment (nazarhussain) [inline framework/src/modules/chain/submodules/loader.js]: Why not we rename this attribute to just `ready`, it does not read well `cache.cacheReady`

Comment (pablitovicente) [reply framework/src/modules/chain/submodules/loader.js]: @nazarhussain I will create an issue to do that in the refactor epic (for which we included changes to the cache already)

Comment (pablitovicente) [reply framework/src/modules/chain/submodules/loader.js]: Created https://github.com/LiskHQ/lisk-sdk/issues/3606 . Resolving.
