### PR TITLE
Sign transactions with an undefined schema

### LINKED ISSUE #8007: The function `signTransactionWithPrivateKey` doesn't sign transactions with an `undefined` schema
### Expected behavior
The function `signTransactionWithPrivateKey` should successfully sign a transaction with an `undefined` schema.

### Actual behavior
An error `"Cannot read properties of undefined (reading '$id')"` is thrown when an `undefined` schema is passed to the function.

### Steps to reproduce

- Create a unlock transaction and pass undefined for schema

### PR DESCRIPTION
**Pull request by mosmartin**
### What was the problem?

This PR resolves #8007

### How was it solved?

Updated the signTransaction function to handle empty param objects.

### How was it tested?

Added a unit test that ensures undefined schemas and empty param objects are signed.

### CODE REVIEW

File: elements/lisk-transactions/src/sign.ts [hunk 1]
```diff
@@ -145,6 +145,11 @@ export const signTransaction = (
 		throw new Error('Private key must be 64 bytes');
 	}
 
+	if (transactionObject.params && Object.keys(transactionObject.params).length === 0) {
+		// eslint-disable-next-line no-param-reassign
+		transactionObject.params = null;
```
Comment (shuse2) [inline elements/lisk-transactions/src/sign.ts:150]: i think mutating object from user is not so good.
it would be nicer if we check the paramsSchema in the `getSigningBytes` function

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: elements/lisk-transactions/src/sign.ts (hunk 1 above)
Comment (mosmartin) [reply elements/lisk-transactions/src/sign.ts:150]: Would it be ok to mutate the params object in `getSigningBytes`? A simple check without mutating the value of the empty params object will persist the bug.

Comment (shuse2) [reply elements/lisk-transactions/src/sign.ts]: I think we can simply check the `paramsSchema` in [here](https://github.com/LiskHQ/lisk-sdk/pull/8029/files/03e62301f7dfeaa2606114ef10867aee048e8ed4#diff-2ca6db1bdc8b33bc7e77c47bb4f272240031d265f2a028ad2021790117aa377bR57) additionally like below?
```
(typeof transactionObject.params !== 'object' || transactionObject.params === null || !paramsSchema)
```

Comment (mosmartin) [reply elements/lisk-transactions/src/sign.ts]: Would you kindly check if the link works, seems to be linking to a blank commit.

Comment (shuse2) [reply elements/lisk-transactions/src/sign.ts]: ah sorry, i think link not changed in the PR doesnt work. it's L62 on `elements/lisk-transactions/src/sign.ts`

Comment (mosmartin) [reply elements/lisk-transactions/src/sign.ts]: > `(typeof transactionObject.params !== 'object' || transactionObject.params === null || !paramsSchema)`

...still throws as `paramsSchema` can be undefined and won't cause an issue. The issue is `transactionObject.params` being an empty object.

Comment (shuse2) [reply elements/lisk-transactions/src/sign.ts]: if it goes in the condition,
```
const transactionBytes = codec.encode(baseTransactionSchema, {
			...transactionObject,
			params: Buffer.alloc(0),
			signatures: [],
		});
```
I think params is not used to get the bytes, so why would it be a problem?

Comment (mosmartin) [reply elements/lisk-transactions/src/sign.ts]: Throws a `TypeError: Cannot read properties of undefined (reading '$id')`

File: elements/lisk-transactions/src/sign.ts [hunk 2]
```diff
@@ -50,11 +50,20 @@ export const getSigningBytes = (
 	transactionObject: Record<string, unknown>,
 	paramsSchema?: object,
 ): Buffer => {
+	// if (transactionObject.params && Object.keys(transactionObject.params).length === 0) {
+	// 	// eslint-disable-next-line no-param-reassign
+	// 	transactionObject.params = undefined;
+	// }
```
Comment (shuse2) [inline elements/lisk-transactions/src/sign.ts:56]: this should be removed, but otherwise LGTM

**Review by Incede — APPROVED** [review]
