### PR TITLE
Verify and fix alert from CodeQL

### LINKED ISSUE #7867: Verify and fix alert from CodeQL
Tracking issue for:
- [ ] https://github.com/LiskHQ/lisk-sdk/security/code-scanning/1
- [ ] https://github.com/LiskHQ/lisk-sdk/security/code-scanning/2
- [ ] https://github.com/LiskHQ/lisk-sdk/security/code-scanning/3
- [ ] https://github.com/LiskHQ/lisk-sdk/security/code-scanning/4
- [ ] https://github.com/LiskHQ/lisk-sdk/security/code-scanning/5
- [ ] https://github.com/LiskHQ/lisk-sdk/security/code-scanning/6
- [ ] https://github.com/LiskHQ/lisk-sdk/security/code-scanning/16

### PR DESCRIPTION
**Pull request by mosmartin**
### What was the problem?

This PR resolves #7867

### How was it solved?

- Updated regex
- Refactored the plugin config assignment

### How was it tested?

Existing tests suffice and pass.

### CODE REVIEW

File: elements/lisk-validator/src/formats.ts [hunk 1]
```diff
@@ -38,7 +38,8 @@ export const uint32 = (data: string): boolean => isNumberString(data) && isUInt3
 
 export const int32 = (data: string): boolean => isNumberString(data) && isSInt32(Number(data));
 
-const camelCaseRegex = /^[a-z]+((\d)|([A-Z0-9][a-zA-Z0-9]+))*([a-z0-9A-Z])?$/;
+// const camelCaseRegex = /^[a-z]+((\d)|([A-Z0-9][a-zA-Z0-9]+))*([a-z0-9A-Z])?$/;
```
Comment (shuse2) [inline elements/lisk-validator/src/formats.ts:41]: we can remove this comment

**Review by shuse2 — CHANGES_REQUESTED** [review]
LGTM, just removing the commented code 🚀

File: elements/lisk-validator/src/formats.ts (hunk 1 above)
Comment (mosmartin) [reply elements/lisk-validator/src/formats.ts]: Done

**Review by shuse2 — APPROVED** [review]

**Review by Incede — APPROVED** [review]
