### PR TITLE
SelectInput component selected prop does not reflect the selected value on UI - Closes #6314

### LINKED ISSUE #6314: SelectInput component selected prop does not reflect the selected value on UI
### Expected behavior

If we pass `selected` prop to `SelectInput` it should show that selected value when component is rendered. 

### Actual behavior

Currently what ever value we pass to `selected` prop it always show `Select` label for the input. 

### Steps to reproduce

```
<SelectInput selected={value}
```

### Which version(s) does this affect? (Environment, OS, etc...)
development

### PR DESCRIPTION
**Pull request by nazarhussain**
### What was the problem?

This PR resolves #6314

### How was it solved?

- Spliced single and multi selection options
- Single select will look for single object for `selected` and `onChange` 
- Multi select will look for array objects for `selected` and `onChange` 

### How was it tested?

- Tested manually

### CODE REVIEW

**Review by ManuGowda — APPROVED** [review]

File: framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/widgets/CallActionWidget.tsx [hunk 1]
```diff
@@ -27,11 +27,15 @@ interface WidgetProps {
...
 
 	const handleSubmit = () => {
-		const actionName = selectedActions[0].value;
+		if (!selectedAction) {
+			return;
+		}
+
+		const actionName = selectedAction.value;
 
 		console.info({ actionName });
```
Comment (ishantiw) [inline framework-plugins/lisk-framework-dashboard-plugin/src/ui/components/widgets/CallActionWidget.tsx:40]:
```suggestion
```

**Review by ishantiw — APPROVED** [review]
LGTM, just a console statement remove suggestion
