### PR TITLE
Fix bftweight zero issue

### LINKED ISSUE #8883: ValidatorsHash is taking bftWeight zero into calculation
### Expected behavior

[computeValidatorsHash](https://github.com/LiskHQ/lisk-sdk/blob/93d9291a0d8b8818fd7eb05c53520d988a26cbc3/framework/src/engine/bft/utils.ts#L81)  should not have validators with bftWeight===0 for calculation.

### Actual behavior

[computeValidatorsHash](https://github.com/LiskHQ/lisk-sdk/blob/93d9291a0d8b8818fd7eb05c53520d988a26cbc3/framework/src/engine/bft/utils.ts#L81) takes validators with bftWeight zero and doesn't filter it out and uses it for validatorsHash calculation.

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-beta.6`

### PR DESCRIPTION
**Pull request by ishantiw**
### What was the problem?

This PR resolves #8883 & #8905 & #8849 

### How was it solved?

- Introduce `getBFTParametersActiveValidators` to provide only active validators from BFT params.
- Fix `verifyValidatorsUpdate` bitmap verification to properly handle `bftWeight === 0` in `bftWeightUpdate` 

### How was it tested?

Run multiple chains and enable chain connector plugin, change validator set by staking/unstaking and observe CCUs

### CODE REVIEW

File: framework/src/engine/consensus/certificate_generation/commit_pool.ts [hunk 1]
```diff
@@ -330,26 +342,39 @@ export class CommitPool {
 				...this._nonGossipedCommitsLocal.getByHeight(nextHeight),
 				...this._gossipedCommits.getByHeight(nextHeight),
 			];
-			const nextValidators = singleCommits.map(commit => commit.validatorAddress);
 			let aggregateBFTWeight = BigInt(0);
 
 			// Assume BFT parameters exist for next height
 			const { validators: bftParamValidators, certificateThreshold } =
 				await this._bftMethod.getBFTParameters(methodContext, nextHeight);
```
Comment (gkoumout) [inline framework/src/engine/consensus/certificate_generation/commit_pool.ts:349]: We can replace this by `getBFTParametersActiveValidators`

File: framework/src/engine/consensus/certificate_generation/commit_pool.ts [hunk 2]
```diff
@@ -330,26 +342,39 @@ export class CommitPool {
...
 
+			const filteredSingleCommits = singleCommits.filter(commit => {
+				const foundValidator = bftParamValidators.find(v =>
+					v.address.equals(commit.validatorAddress),
+				);
+				if (foundValidator && foundValidator.bftWeight === BigInt(0)) {
```
Comment (gkoumout) [inline framework/src/engine/consensus/certificate_generation/commit_pool.ts:355]: If we perform the edit of line 349, then this would never be true, so it gets redundant.

File: framework/src/engine/consensus/certificate_generation/commit_pool.ts [hunk 3]
```diff
@@ -330,26 +342,39 @@ export class CommitPool {
...
+			const nextValidators = filteredSingleCommits.map(commit => commit.validatorAddress);
 			for (const matchingAddress of nextValidators) {
 				const bftParamsValidatorInfo = bftParamValidators.find(bftParamValidator =>
 					bftParamValidator.address.equals(matchingAddress),
 				);
 				if (!bftParamsValidatorInfo) {
 					throw new Error('Validator address not found in commit pool');
 				}
+				// Skip validators with BFT Weight zero when someone is running node with standby validators
+				if (bftParamsValidatorInfo.bftWeight === BigInt(0)) {
```
Comment (gkoumout) [inline framework/src/engine/consensus/certificate_generation/commit_pool.ts:369]: This should never happen, since the bft weights are filtered out, right?

**Review by gkoumout — COMMENTED** [review]
Left few comments.

File: framework/src/engine/consensus/certificate_generation/commit_pool.ts [hunk 4]
```diff
@@ -266,10 +267,17 @@ export class CommitPool {
...
 		// assuming this list of validators includes all validators corresponding to each singleCommit.validatorAddress
-		const { validators } = await this._bftMethod.getBFTParameters(methodContext, height);
+		const { validators } = await this._bftMethod.getBFTParametersActiveValidators(
+			methodContext,
+			height,
+		);
 		const addressToBlsKey: dataStructures.BufferMap<Buffer> = new dataStructures.BufferMap();
 		const validatorKeys: Buffer[] = [];
 
+		// Filter out all the standby validators with bftWeight === 0
```
[the remark this answers is not in the document]
Comment (ishantiw) [reply framework/src/engine/consensus/certificate_generation/commit_pool.ts:277]: ah yeah i need to remove this now as its not valid anymore after the endpoint

File: framework/src/engine/consensus/certificate_generation/commit_pool.ts (hunk 1 above)
Comment (ishantiw) [reply framework/src/engine/consensus/certificate_generation/commit_pool.ts:349]: if we replace it with `getBFTParametersActiveValidators` the problem is that it will throw error `Validator address not found in commit pool` bc there are commits from the standby validators which will not be in `getBFTParametersActiveValidators`

File: framework/src/engine/consensus/certificate_generation/commit_pool.ts (hunk 3 above)
Comment (ishantiw) [reply framework/src/engine/consensus/certificate_generation/commit_pool.ts:369]: currently it fails at `Validator address not found in commit pool'` if we use `getBFTParametersActiveValidators` and if we use `getBFTParameters` then we need to make sure to ignore the standby delegates

File: framework/src/engine/consensus/certificate_generation/commit_pool.ts [hunk 5]
```diff
@@ -278,6 +286,10 @@ export class CommitPool {
 		const pubKeySignaturePairs: PkSigPair[] = [];
 
 		for (const commit of singleCommits) {
+			// Skip any standby validator
+			if (objects.bufferArrayIncludes(addressesWithBFTWeightZero, commit.validatorAddress)) {
```
[the remark this answers is not in the document]
Comment (ishantiw) [reply framework/src/engine/consensus/certificate_generation/commit_pool.ts:290]: I'm using `(!objects.bufferArrayIncludes(validatorAddresses, commit.validatorAddress))` to exclude any single commits from standby validators

**Review by shuse2 — APPROVED** [review]

**Review by gkoumout — COMMENTED** [review]
Two small comments, otherwise looks good. Moreover, don't we need to update tests for `verifyValidatorsUpdate`?

File: framework/src/engine/bft/method.ts [hunk 6]
```diff
@@ -217,7 +217,11 @@ export class BFTMethod {
 			throw new Error('Invalid certificateThreshold input.');
 		}
 
-		const validatorsHash = computeValidatorsHash(validators, certificateThreshold);
+		sortValidatorsByAddress(validators);
+		const validatorsHash = computeValidatorsHash(
```
Comment (gkoumout) [inline framework/src/engine/bft/method.ts:221]: I think there is still a discrepancy between LIP and implementation: The LIP assumes that the input of `computeValidatorsHash`  is an array with items of type (bftWeight, blsKey). In the implementation however,  you call computeValidatorsHash with corresponding argument validators (after filtering bft weight 0) , which is an array with items of type (address, bftWeight, generatorKey, blsKey) . 

Not a big deal, it would be good to change it in order to be fully consistent, but since it seems to work correctly now, it's ok to leave it as is..

**Review by gkoumout — COMMENTED** [review]
Looks good, just one optional comment.

File: framework/src/engine/bft/method.ts (hunk 6 above)
Comment (ishantiw) [reply framework/src/engine/bft/method.ts:221]: Updated `computeValidatorsHash ` aligning with LIP

**Review by gkoumout — APPROVED** [review]
