### PR TITLE
Forging fails when genesis block timestamp is in the future - Closes #6356

### LINKED ISSUE #6356: Forging fails when genesis block timestamp is in the future
### Expected behavior

When we migrate Lisk Core from 2.x.x to 3.x.x, the blockchain should be able to start considering genesis block timestamp in future.

More details can be found in LIP: https://github.com/LiskHQ/lips/blob/master/proposals/lip-0035.md#general-block-properties

### Actual behavior

When the genesis block timestamp is in the future(10sec, 1hr, 2hr, 1day, etc..), the application fails to forge blocks.
```
12:14:01 INFO lisk-framework: Node ready and launched (module=lisk:app)
12:14:02 ERROR lisk-framework: Cannot read property 'address' of undefined (module=lisk:app)
Message: Cannot read property 'address' of undefined
 Trace: TypeError: Cannot read property 'address' of undefined
    at Forger.forge (lisk-sdk/framework/src/node/forger/forger.ts:387:57)
    at Node._forgingTask (lisk-sdk/framework/src/node/node.ts:680:4)
    at Timeout._onTimeout (lisk-sdk/elements/lisk-utils/src/job_handlers/scheduler.ts:47:5)
```

### Steps to reproduce

- Create timestamp with(2hrs) in the future
- Update devnet genesis block `timestamp` field with the generated value
- Start the application and observe the error

### Which version(s) does this affect? (Environment, OS, etc...)
5.x.x, development

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?

This PR resolves #6356

### How was it solved?

- Check for validator existence
 
### How was it tested?

- Added unit test
- Tested manually by updating devnet genesis block timestamp to future(100sec)

### CODE REVIEW

File: framework/src/node/forger/forger.ts [hunk 1]
```diff
@@ -384,6 +384,13 @@ export class Forger {
 		}
 
 		const validator = await this._chainModule.getValidator(currentTime);
+		if (!validator) {
+			this._logger.trace(
+				{ currentSlot: this._chainModule.slots.getSlotNumber() },
+				'Waiting for delegate slot',
```
Comment (shuse2) [inline framework/src/node/forger/forger.ts:390]: maybe something like `No validator is set for current time slot`?

File: framework/test/unit/node/forger/forger.spec.ts [hunk 2]
```diff
@@ -928,6 +928,38 @@ describe('forger', () => {
...
+				when(getSlotNumberStub)
+					.calledWith(lastBlock.header.timestamp)
+					.mockReturnValue(changedLastBlockSlot);
+
+				chainModuleStub.slots.getSlotTime.mockReturnValue(futureSlotTime);
+
+				const data = await forgeModule.forge();
+
+				expect(data).toBeUndefined();
+				expect(loggerStub.trace).toHaveBeenCalledTimes(1);
```
Comment (shuse2) [inline framework/test/unit/node/forger/forger.spec.ts:955]: I think it's better not to check the log. It's better to check if the block is not created and no error is thrown?

**Review by shuse2 — APPROVED** [review]

File: framework/src/node/forger/forger.ts [hunk 3]
```diff
@@ -384,6 +384,13 @@ export class Forger {
 		}
 
 		const validator = await this._chainModule.getValidator(currentTime);
+		if (!validator) {
+			this._logger.trace(
```
Comment (nazarhussain) [inline framework/src/node/forger/forger.ts:388]: Is not this information is better at `debug` level?

**Review by nazarhussain — APPROVED** [review]
