### PR TITLE
API returns incorrect error for postTransactions - Closes #3586

### LINKED ISSUE #3586: API returns incorrect error for postTransactions
### Expected behavior
API should return the correct error message.
### Actual behavior
API always returns `Invalid transaction body` error even when the transaction failed from a different reason.
```
10:01:51.954Z  WARN lisk-framework: Balance queue 775
10:01:51.954Z DEBUG lisk-framework: Received transaction 1944531498676575052 from public client
10:01:51.960Z DEBUG lisk-framework: Transaction 1944531498676575052 Error: Transaction pool is full
```
```
{ APIError: Invalid transaction body
       at axios_1.default.request.then.catch (lisk-core/qa/node_modules/@liskhq/lisk-api-client/dist-node/api_resource.js:43:27)
       at process._tickCallback (internal/process/next_tick.js:68:7)
     jse_shortmsg: 'Invalid transaction body',
     jse_info: {},
     message: 'Invalid transaction body',
     name: 'APIError',
     errno: 409,
     errors: {} }
```
### Steps to reproduce
Send transaction when the transaction pool is full.
### Which version(s) does this affect? (Environment, OS, etc...)
`2.0.0-alpha.0`

### PR DESCRIPTION
**Pull request by pablitovicente**
### What was the problem?

The error being used in postTransactions was not generic enough (as the detailed errors are always in the `errors` array )

### How did I fix it?

By changing the previous error to a more generic one

### How to test it?

- Build should be green

### Review checklist

* The PR resolves #3586
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/chain/submodules/transport.js [hunk 1]
```diff
@@ -698,7 +693,7 @@ Transport.prototype.shared = {
 				if (err) {
 					return setImmediate(cb, null, {
 						success: false,
-						message: err.message || 'Invalid transaction body',
+						message: err.message || 'Transaction was rejected with errors',
```
Comment (ManuGowda) [inline framework/src/modules/chain/submodules/transport.js]: if i understand correctly, @4miners found that the `err.message` was undefined as `err` was `type` `string`.
so can you handle the issue?

Comment (pablitovicente) [reply framework/src/modules/chain/submodules/transport.js]: @ManuGowda that assumption was not correct; err is sometimes an error and other times an array. so that part is correct.

Comment (ManuGowda) [reply framework/src/modules/chain/submodules/transport.js]: hmmm ok.. so that case as well.. `err.message` is wrong rite.. if its an array then `err.message` will result in undefined know? am i missing something?
