### PR TITLE
Remove network related config from Chain module - Closes #3484

### LINKED ISSUE #3484: Remove network related config from Chain module
### Expected behavior
Expect Chain module to not use network related config.
It crashes the application when trying to run snapshotting process.

### Actual behavior
It is still used in the following files:
```
framework/src/modules/chain/chain.js#L109
framework/src/modules/chain/submodules/peers.js#L50
```

### Steps to reproduce
`node lisk/src/index.js -n devnet -s 1`

### Which version(s) does this affect? (Environment, OS, etc...)
`development`

### PR DESCRIPTION
**Pull request by lsilvs**
### What was the problem?
Chain module was trying to access a network config during snapshotting making the app to crash

### How did I fix it?
I've removed the unused configuration and added a condition before subscribing to network events in order to prevent receiving block/transactions from network during snapshotting process

### How to test it?
`node lisk/src/index.js -n devnet -s 1`

### Review checklist

* The PR resolves #3484
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/chain/chain.js [hunk 1]
```diff
@@ -174,24 +173,27 @@ module.exports = class Chain {
...
-				({ data: { event, data } }) => {
-					if (event === 'postTransactions') {
-						this.scope.modules.transport.shared.postTransactions(data);
-						return;
+			// Avoid receiving blocks/transactions from the network during snapshotting process
+			if (!this.options.loading.snapshotRound) {
+				this.channel.subscribe(
+					'network:subscribe',
+					({ data: { event, data } }) => {
+						if (event === 'postTransactions') {
```
Comment (michielmulders) [inline framework/src/modules/chain/chain.js]: Is this check correct? 
You are checking twice for the same event name here (line `181` and `185`)

Comment (lsilvs) [reply framework/src/modules/chain/chain.js]: Good catch!

@jondubois line `185` should be `postSignatures`, right?

Comment (shuse2) [reply framework/src/modules/chain/chain.js]: must be merge mistake... =( it should be postSignatures
