### PR TITLE
Fix the peer banning logic

### LINKED ISSUE #8217: Banning when receiving invalid transaction
### Expected behavior
- Honest peer should never be banned

### Actual behavior
If a node receives invalid transaction (ex: lower nonce) which is not included in a block, it will ban the peer. 
However, this can happen if a node included a block, and then receive the replacing transaction (ie: not included in a block, but affecting the same address with same nonce) later affecting the same address.

### Steps to reproduce
- prepare 2 transaction with same nonce and one higher fee. Include higher fee on the block. send both transactions as announcement.
- on receiving side, one of the transaction should be included already, and receive the announcement

### Which version(s) does this affect? (Environment, OS, etc...)
6.0.0-alpha.15

### PR DESCRIPTION
**Pull request by mosmartin**
### What was the problem?

This PR resolves #8217

### How was it solved?

Updated the handleEventPostTransactionsAnnouncement method

### How was it tested?

Updated the unit tests

### CODE REVIEW

File: framework/src/engine/generator/network_endpoint.ts [hunk 1]
```diff
@@ -231,14 +231,7 @@ export class NetworkEndpoint extends BaseNetworkEndpoint {
 					await this._receiveTransaction(transaction);
 				}
 			} catch (err) {
-				// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
 				this._logger.warn({ err, peerId }, 'Received invalid transactions.');
-				if (err instanceof InvalidTransactionError) {
```
Comment (shuse2) [inline framework/src/engine/generator/network_endpoint.ts:236]: I think
```
transaction.validate()
```
is missing, and if it fails on `fromBytes` or `validate`, it should apply penalty to the peer

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: framework/src/engine/generator/network_endpoint.ts [hunk 2]
```diff
@@ -226,19 +226,44 @@ export class NetworkEndpoint extends BaseNetworkEndpoint {
 			);
 
 			try {
-				for (const transactionBytes of transactionsData.transactions) {
-					const transaction = Transaction.fromBytes(transactionBytes);
-					await this._receiveTransaction(transaction);
-				}
+				await Promise.all(
+					transactionsData.transactions.map(async transactionBytes => {
```
Comment (shuse2) [inline framework/src/engine/generator/network_endpoint.ts:230]: why was it changed to `Promise.all`?

File: framework/src/engine/generator/network_endpoint.ts [hunk 3]
```diff
@@ -226,19 +226,44 @@ export class NetworkEndpoint extends BaseNetworkEndpoint {
...
+						const transaction = Transaction.fromBytes(transactionBytes);
```
Comment (shuse2) [inline framework/src/engine/generator/network_endpoint.ts:231]: this will throw instead of returning undefined. Also, try-catch can be bundled.

File: framework/src/engine/generator/network_endpoint.ts (hunk 2 above)
Comment (mosmartin) [reply framework/src/engine/generator/network_endpoint.ts:230]: To run the validation of each transaction concurrently. But I can revert 🙂

Comment (shuse2) [reply framework/src/engine/generator/network_endpoint.ts]: `fromBytes` and `validate` are synchronous function, so probably it doesn't make so much sense. (and if one fails, it's ok to invalidate all the remaining message)

File: framework/test/unit/engine/generator/network_endpoint.spec.ts [hunk 4]
```diff
@@ -203,12 +203,51 @@ describe('generator network endpoint', () => {
 				expect(pool.add).toHaveBeenCalledTimes(2);
 			});
 
-			it('should apply penalty when validateTransactions fails', async () => {
+			it('should not apply penalty when abi verification fails', async () => {
```
Comment (shuse2) [inline framework/test/unit/engine/generator/network_endpoint.spec.ts:206]: test description seems to be ok, but from the source code, i don't understand how it will not call the applyPenalty 🤔

File: framework/src/engine/generator/network_endpoint.ts [hunk 5]
```diff
@@ -228,10 +228,10 @@ export class NetworkEndpoint extends BaseNetworkEndpoint {
 			try {
 				for (const transactionBytes of transactionsData.transactions) {
 					const transaction = Transaction.fromBytes(transactionBytes);
+					transaction.validate();
```
Comment (shuse2) [inline framework/src/engine/generator/network_endpoint.ts:231]: if this fails, the error will not be `InvalidTransactionError`, so i think it will not apply penalty.. on the other hand, it will apply penalty from `_receiveTransaction`?

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: framework/test/unit/engine/generator/network_endpoint.spec.ts (hunk 4 above)
Comment (mosmartin) [reply framework/test/unit/engine/generator/network_endpoint.spec.ts:206]: Updated the tests.

**Review by Incede — APPROVED** [review]
