### PR TITLE
transaction.id should not be used before assignment - Closes #4461

### LINKED ISSUE #4461: transaction.id should not be used before assignment
### Expected behavior
After id has been not required property by #4038, transaction id should not be used before the assignment.
All the usage should be after the assignment.
Also, calculation of the `id` must be done after schema validation, and during the schema validation, `id` should never be used.
Specifically at this point, it should not be used, https://github.com/LiskHQ/lisk-sdk/blob/development/elements/lisk-transactions/src/base_transaction.ts#L235-L239

### Actual behavior
In validation it is used by `toJSON` right before execution.

### Steps to reproduce
Call validate function with minimal properties.

### Which version(s) does this affect? (Environment, OS, etc...)
3.0-

### PR DESCRIPTION
**Pull request by pablitovicente**
### What was the problem?

Transacion.id was throwing error even though not required before signing

### How did I solve it?

By making the getter return empty string if the id doesn't exist

### How to manually test it?

Build should be green

### Review checklist

- [x] The PR resolves #4461
- [x] All new code is covered with unit tests
- [x] Relevant integration / functional tests are added
- [x] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [x] Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-transactions/src/base_transaction.ts [hunk 1]
```diff
@@ -157,11 +157,7 @@ export abstract class BaseTransaction {
 	}
 
 	public get id(): string {
-		if (!this._id) {
-			throw new Error('id is required to be set before use');
-		}
-
-		return this._id;
+		return this._id || 'incalculable-id';
```
Comment (mitsujutsu) [inline elements/lisk-transactions/src/base_transaction.ts]: why not empty string?

Comment (pablitovicente) [reply elements/lisk-transactions/src/base_transaction.ts]: to be more obvious to the user that something is wrong with its JSON
