### PR TITLE
Delegate should not punished by DPoS violation for first rounds - Closes #5110

### LINKED ISSUE #5110: Delegate should not punished by DPoS violation for first rounds
### Expected behavior
Delegate for first rounds are punished for the DPoS violation

### Actual behavior
```
{
 "id": "7620152438571012831"
}
15:47:52 INFO lisk-framework: Punishing delegate for DPoS violation (module=lisk:app)
{
 "id": "17099278745515138981"
}
15:47:52 INFO lisk-framework: Punishing delegate for DPoS violation (module=lisk:app)
{
 "id": "10681471986634929949"
}
15:47:52 INFO lisk-framework: Punishing delegate for DPoS violation (module=lisk:app)
{
 "id": "17861655877572574378"
}
```

### Steps to reproduce
Run a node for several rounds, and try to sync with the node

### Which version(s) does this affect? (Environment, OS, etc...)
4.0-

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?

This PR resolves #5110 

### How was it solved?

- Update hash onion filtering 
- Updated blocks cache to return blocks in `desc` order by default

### How was it tested?

- Updated unit test

### CODE REVIEW

File: elements/lisk-dpos/src/delegates_info.ts [hunk 1]
```diff
@@ -158,11 +158,14 @@ export class DelegatesInfo {
...
 			);
+			const lastBlockHeaders = [
+				...stateStore.consensus.lastBlockHeaders,
+			].reverse();
 
 			const [randomSeed1, randomSeed2] = generateRandomSeeds(
 				round,
 				this.rounds,
-				stateStore.consensus.lastBlockHeaders,
+				lastBlockHeaders,
```
Comment (shuse2) [inline elements/lisk-dpos/src/delegates_info.ts:168]: this doesn't need to be reversed. `generateRandomSeeds` should just use `lastBlockHeaders[0]` for the last block

File: framework/src/application/node/block_processor_v2.js [hunk 2]
```diff
@@ -421,10 +421,9 @@ class BlockProcessorV2 extends BaseBlockProcessor {
 
 		// Set reward to 0 if the block violates DPoS rules
 		if (!isDPoSProtocolCompliant) {
-			this.logger.info(
-				{ id: block.id, generatorPublicKey: block.getAddressFromPublicKey },
-				'Punishing delegate for DPoS violation',
-			);
+			this.logger.info('Punishing delegate for DPoS violation', {
```
Comment (shuse2) [inline framework/src/application/node/block_processor_v2.js:424]: original way is correct order of log
