### PR TITLE
npx mocha doesn't use mocha.opts file - Closes #3413

### LINKED ISSUE #3413: npx mocha doesn't use mocha.opts file
### Expected behavior
It should
### Actual behavior
When running `npx mocha pathToTests` it seems Mocha is not using the mocha.opts file which requires to run `setup.js` in order to load for example global constants used by the tests.
### Steps to reproduce
Try to run `npx mocha framework/test/mocha/integration/blocks/process/process.js`
### Which version(s) does this affect? (Environment, OS, etc...)
`development`

### PR DESCRIPTION
**Pull request by pablitovicente**
### What was the problem?

Running mocha through npx didn't work

### How did I solve it?

- By linking the `mocha.opts` file to the `/test/mocha.opts` folder where mocha is searching for.
- by updating lisk-mocha-runner 

Another options I tested but do not work with `npx`

- to remove mocha.opts (deprecated but still supported by Mocha) and replace with `.mocharc`

### How to manually test it?

in `framework/` run: 
- mocha test/mocha/unit/controller/helpers/validator.js
- npm run mocha:unit test/mocha/unit/controller/helpers/validator.js
- npx mocha test/mocha/unit/controller/helpers/validator.js
and all should be able to run that test or any other test

### Review checklist

- [ ] The PR resolves #3413
- [ ] All new code is covered with unit tests
- [ ] Relevant integration / functional tests are added
- [ ] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [ ] Documentation has been added/updated

### CODE REVIEW

File: framework/test/mocha/common/lisk-mocha-runner/index.js [hunk 1]
```diff
@@ -142,8 +142,6 @@ if (testPathPattern && testPathPattern.indexOf('-') === 0) {
 	testPathPattern = null;
 }
 
-mochaCliOptions.unshift('--', '--opts', 'test/mocha/mocha.opts');
```
Comment (yatki) [inline framework/test/mocha/common/lisk-mocha-runner/index.js]: ❤️

**Comment by pablitovicente** [comment]
> Instead



> Instead of moving the source file, I'd prefer to create a symlink. This way we could know that file is not actually belong there. Because it sort of doesn't fit to current folder structure with having mocha/jest folders.. and having a mocha related file in the top folder?

This was my first approach but was not convinced to have the link instead of the file but this is a good reasoning to have the symlink so I will change it to a symlink.

File: framework/test/mocha/common/lisk-mocha-runner/index.js (hunk 1 above)
Comment (lsilvs) [reply framework/test/mocha/common/lisk-mocha-runner/index.js]: I suspect this is causing https://github.com/LiskHQ/lisk-sdk/issues/4124
