### PR TITLE
Remove signature loading - Closes #4268

### LINKED ISSUE #4268: Remove loading signatures and providing signature endpoint
### Expected behavior
Since we don't manage signature outside of the transaction pool, we don't need to separately provide the signature.
Therefore,

getSignature and getSignature from the network should be removed.

### Actual behavior
It is expecting to have `res[0].transactionId`.
This bug seems to be true since 1.x
https://github.com/LiskHQ/lisk-sdk/blob/1dd941cce6bd7a9cf7fbc3073236f2aa8949d362/framework/src/modules/chain/submodules/loader.js#L227-L231

Also, since signature is provided with transaction object, it always result in error (existing signature)

### Steps to reproduce
Start the node while network having signature

### Which version(s) does this affect? (Environment, OS, etc...)
1.x-

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?
On the startup, signature endpoint was called, but it was never successful.
When signature is received from the network, it will be injected in the transaction.
Therefore, when we start up the node and get the transactions, signatures will be there already if it was propagated.

### How did I solve it?
Remove the signatures fetch on startup.

### How to manually test it?
Observe no error while connecting to the network where it has the multisignature in the pool.

### Review checklist

- [ ] The PR resolves #4268 
- [ ] All new code is covered with unit tests
- [ ] Relevant integration / functional tests are added
- [ ] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [ ] Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/chain/chain.js [hunk 1]
```diff
@@ -564,7 +564,7 @@ module.exports = class Chain {
 	}
 
 	_startLoader() {
-		this.loader.loadTransactionsAndSignatures();
+		this.loader.loadTransactions();
```
Comment (lsilvs) [inline framework/src/modules/chain/chain.js]: Would be nice to take the opportunity and give this function a better name like `loadPendingTransactions` or something like that.

File: framework/src/modules/chain/chain.js [hunk 2]
```diff
@@ -564,7 +564,7 @@ module.exports = class Chain {
 	}
 
 	_startLoader() {
-		this.loader.loadTransactionsAndSignatures();
+		this.loader.loadUnconfirmedTransactions();
```
Comment (lsilvs) [inline framework/src/modules/chain/chain.js]: ❤️
