### PR TITLE
Asset file path in bootstrapping generator is not correct - Closes #6448, #6449

### LINKED ISSUE #6448: Asset file path in bootstrapping generator is not correct
### Expected behavior

When we generate an asset, the generated code should be valid without syntax or linting errors. 

### Actual behavior

Currently the asset file path on the `import ` inside `module` and `spec` is not correct. 

### Steps to reproduce

```
lisk init ~/my-app
cd ~/my-app
lisk generate:module lns 1000
lisk generate:asset lns transfer 1
```
The above code generate a file named `transfer_asset.ts`  but the import path uses `transfer.ts` 

### Which version(s) does this affect? (Environment, OS, etc...)
5.1.0

### PR DESCRIPTION
**Pull request by nazarhussain**
### What was the problem?

This PR resolves #6448, #6449

### How was it solved?

- Fixed asset file path in the bootstrapping
- Fixed the positive value check in the asset oclif command

### How was it tested?

- Tested manually

### CODE REVIEW

File: commander/src/bootstrapping/templates/lisk-template-ts/templates/asset/src/app/modules/assets/asset.ts [hunk 1]
```diff
@@ -13,11 +13,12 @@ export class <%= assetClass %> extends BaseAsset {
 		properties: {},
   };
 
-    public validate({ asset }: ValidateAssetContext<{}>): void {
+  public validate({ asset }: ValidateAssetContext<{}>): void {
     // Validate your asset
   }
 
-  	public async apply({ asset, transaction, stateStore }: ApplyAssetContext<{}>): Promise<void> {
+	// eslint-disable-next-line @typescript-eslint/require-await
```
Comment (ManuGowda) [inline commander/src/bootstrapping/templates/lisk-template-ts/templates/asset/src/app/modules/assets/asset.ts:20]: i don't think we need this?

File: commander/src/bootstrapping/templates/lisk-template-ts/templates/module/src/app/modules/module.ts [hunk 2]
```diff
@@ -46,9 +53,9 @@ export class <%= moduleClass %> extends BaseModule {
     ];
     public id = <%= moduleID %>;
 
-    public constructor(genesisConfig: GenesisConfig) {
-        super(genesisConfig);
-    }
+    // public constructor(genesisConfig: GenesisConfig) {
```
Comment (ManuGowda) [inline commander/src/bootstrapping/templates/lisk-template-ts/templates/module/src/app/modules/module.ts:56]: why commented?

**Review by ManuGowda — APPROVED** [review]

**Review by shuse2 — APPROVED** [review]

File: commander/src/bootstrapping/templates/lisk-template-ts/templates/asset/src/app/modules/assets/asset.ts (hunk 1 above)
Comment (nazarhussain) [reply commander/src/bootstrapping/templates/lisk-template-ts/templates/asset/src/app/modules/assets/asset.ts:20]: In bootstrapped application its cause linting errors.

File: commander/src/bootstrapping/templates/lisk-template-ts/templates/module/src/app/modules/module.ts (hunk 2 above)
Comment (nazarhussain) [reply commander/src/bootstrapping/templates/lisk-template-ts/templates/module/src/app/modules/module.ts:56]: In bootstrapped application its cause linting errors, so why kept it commented as it would be useful for end user.
