### PR TITLE
Fix API Client min fee calculation

### LINKED ISSUE #7010: API Client: transaction minimum fee miscalculation
### Expected behavior

Multisignature transaction with optional members returns the result equal to all optional signatures collected.

The function `apiClient.transaction.computeMinFee(txn)` assumes all signatures having 64 bytes of length while some of them can equal to 0.

Refer to the https://github.com/LiskHQ/lisk-service/issues/971 for more information.

### Actual behavior

Multisignature transaction with optional members returns minimum fees incorrectly.

### Steps to reproduce

Use the `apiClient.transaction.computeMinFee(txn)` on a transaction with a minimum required number of optional signatures.

### Additional Information
Current implementation is here
https://github.com/LiskHQ/lisk-sdk/blob/development/elements/lisk-transactions/src/fee.ts#L28-L50

### Which version(s) does this affect? (Environment, OS, etc...)

latest

### PR DESCRIPTION
**Pull request by bobanm**
### What was the problem?

This PR resolves #7010

### How was it solved?

Implemented solution proposed by @shuse2:

`lisk-api-client` method `Transaction.computeMinFee()` no longer calculates options, but takes them as argument. The options are then passed on to util function with the same name `computeMinFee()` [from `lisk-transactions` package] to correctly calculate min fee.

In order not to have too many potentially conflicting interfaces, `lisk-api-client` no longer defines yet another version of `Options` interface, but imports it from `lisk-transactions`.

### How was it tested?

Nothing really to be tested here. API Client `computeMinFee()` doesn't do anything else but validates input and passes it on to `lisk-transaction` util function `computeMinFee()`, and that one has all the tests.

### CODE REVIEW

**Review by mosmartin — APPROVED** [review]
🚀

File: elements/lisk-api-client/src/transaction.ts [hunk 1]
```diff
@@ -17,6 +17,7 @@ import {
 	signMultiSignatureTransaction,
 	computeMinFee,
 } from '@liskhq/lisk-transactions';
+import { Options } from '@liskhq/lisk-transactions/src/fee';
```
Comment (shuse2) [inline elements/lisk-api-client/src/transaction.ts:20]: Options should be exposed from the package. This will not work in the published package

File: elements/lisk-api-client/src/transaction.ts [hunk 2]
```diff
@@ -137,7 +134,10 @@ export class Transaction {
 				? codec.fromJSON(commandSchema, txInput.params as Record<string, unknown>)
 				: {},
 		};
-		if (authAccount.numberOfSignatures > 0) {
+		if (
+			authAccount.numberOfSignatures > 0 ||
+			(options?.multisignatureKeys && options?.includeSenderSignature)
```
Comment (shuse2) [inline elements/lisk-api-client/src/transaction.ts:139]: Not related to this particular issue, but we can remove `includeSenderSignature` because with the new protocol, sender signature is treated as any other signature

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: elements/lisk-api-client/src/transaction.ts (hunk 2 above)
Comment (bobanm) [reply elements/lisk-api-client/src/transaction.ts:139]: Agree that we should remove the legacy logic, and agree to handle it as a separate issue:

https://github.com/LiskHQ/lisk-sdk/issues/7933

**Review by shuse2 — APPROVED** [review]
