### PR TITLE
Prettier fails to apply format for lisk-sdk - Closes #4614

### LINKED ISSUE #4614: Prettier fails to apply format for lisk-sdk
### Expected behavior
Prettier should be able to apply format at root level and individual packages.
### Actual behavior
The prettier fails apply the format as certain directory and files are not ignored
### Steps to reproduce
- Checkout `development` branch
- Run `npm run format` from root
### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?
The prettier fails apply the format as certain directory and files are not ignored
### How did I solve it?
Fixed the prettierignore and applied outdated prettier changes 
### How to manually test it?
`npm run format`
### Review checklist

- [ ] The PR resolves #4614 
- [ ] All new code is covered with unit tests
- [ ] Relevant integration / functional tests are added
- [ ] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [ ] Documentation has been added/updated

### CODE REVIEW

File: commander/src/utils/core/database.ts [hunk 1]
```diff
@@ -45,7 +45,9 @@ const isDbRunning = async (
 	installDir: string,
 	port: string,
 ): Promise<boolean> => {
-	const { stderr }: ExecResult = await exec(
+	const {
```
Comment (pablitovicente) [inline commander/src/utils/core/database.ts]: I prefer the other way but if the chosen prettier rules are this format I'm ok

Comment (ManuGowda) [reply commander/src/utils/core/database.ts]: before it was like this `const { stderr }: ExecResult = await exec(` I think with new prettier update, it might have changed. so it should be ok, as its gonna apply the same to other parts of the code.

File: elements/lisk-p2p/src/peer_pool.ts [hunk 2]
```diff
@@ -475,9 +475,11 @@ export class PeerPool extends EventEmitter {
 			peerLimit,
 		});
 
-		[...peersToConnect, ...disconnectedFixedPeers].forEach(
-			(peerInfo: P2PPeerInfo) =>
-				this._addOutboundPeer(peerInfo, this._nodeInfo as P2PNodeInfo),
+		[
```
Comment (pablitovicente) [inline elements/lisk-p2p/src/peer_pool.ts]: I prefer the previous version but if the chosen prettier rules are set to this I'm ok with it.
