### PR TITLE
Fix bug in initialize state recovery

### LINKED ISSUE #8722: Fix a bug in state recovery initialization command
### Description

- Fix a bug in state recovery initialization command as it was accepting a chain account with status "registered" which should not be the case.
- emit `EVENT_NAME_INVALID_SMT_VERIFICATION` in execution on failure
- Move SMTVerify from verification to execution

Related LIP PR https://github.com/LiskHQ/lips/pull/399

### Which version(s) does this affect? (Environment, OS, etc...)

`v6.0.0-beta.4`

### PR DESCRIPTION
**Pull request by ishantiw**
### What was the problem?

This PR resolves #8722 #8719 

### How was it solved?

- Added condition to check for ChainStatus.REGISTERED status where it fails if chain is in registered status
- Added condition to check for ChainStatus.ACTIVE for liveness, if the chain violates the liveness then it passes verification
- Moved SMT verify to execute 
- Added Invalid SMT and RMT verification events

### How was it tested?

Under `framework` run `npm run test:unit initialize_state`

### CODE REVIEW

File: framework/src/modules/interoperability/sidechain/commands/initialize_state_recovery.ts [hunk 1]
```diff
@@ -69,78 +70,90 @@ export class InitializeStateRecoveryCommand extends BaseInteroperabilityCommand<
...
-				throw new Error('Sidechain account has missing property: mainchain state root');
-			}
+			const terminatedStateAccount = await terminatedStateSubstore.get(context, chainID);
 			const verified = await smt.verify(
 				terminatedStateAccount.mainchainStateRoot,
 				[queryKey],
 				proofOfInclusion,
 			);
 			if (!verified) {
+				this.events.get(InvalidSMTVerification).error(context);
```
Comment (ricott1) [inline framework/src/modules/interoperability/sidechain/commands/initialize_state_recovery.ts:116]: Personal taste, but I would refactor this a bit to avoid code repetition, for instance by creating a new variable `stateRoot` that can be equal to either `terminatedStateAccount.mainchainStateRoot` or `mainchainAccount.lastCertificate.stateRoot` and then write the verified check only once

File: framework/test/unit/modules/interoperability/sidechain/commands/initialize_state_recovery.spec.ts [hunk 2]
```diff
@@ -314,35 +313,113 @@ describe('Sidechain InitializeStateRecoveryCommand', () => {
 			);
 
 			await expect(stateRecoveryInitCommand.verify(commandVerifyContext)).rejects.toThrow(
-				'Sidechain is not terminated.',
+				'Sidechain is still active and obeys the liveness requirement.',
```
Comment (ricott1) [inline framework/test/unit/modules/interoperability/sidechain/commands/initialize_state_recovery.spec.ts:316]: Isn't this in contradiction with the test description?

**Review by ricott1 — CHANGES_REQUESTED** [review]
A minor stylistic comment and a possible test description error

**Review by ricott1 — APPROVED** [review]

**Review by mitsuaki-u — APPROVED** [review]
