### PR TITLE
Integration tests fail at lisk-p2p lib

### LINKED ISSUE #3549: Integration on lisk-p2p fails randomly
### Expected behavior
It should consistently pass the test

### Actual behavior
```
@liskhq/lisk-p2p:   1 failing
@liskhq/lisk-p2p:   1) Integration tests for P2P library
@liskhq/lisk-p2p:        Partially connected network which becomes fully connected: All nodes launch at the same time. The seedPeers list of each node contains the next node in the sequence. Discovery interval runs multiple times.
@liskhq/lisk-p2p:          Peer discovery
@liskhq/lisk-p2p:            should discover all peers in the network after a few cycles of discovery:
@liskhq/lisk-p2p:       AssertionError: expected [ Array(10) ] to deeply equal [ Array(9) ]
@liskhq/lisk-p2p:       + expected - actual
```

### Steps to reproduce
run lisk-p2p integration test on jenkins

### Which version(s) does this affect? (Environment, OS, etc...)
2.0-

### PR DESCRIPTION
**Pull request by ishantiw**
### What was the problem?

Integration test fails randomly in lisk-p2p lib. 

### How did I fix it?

Increased the `connectTimeout` for a node so that there is enough time for a node to startup and connect with other nodes.

### How to test it?

`npm run test`

### Review checklist

* The PR resolves #3549 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-p2p/test/integration/p2p.ts [hunk 1]
```diff
@@ -442,7 +442,7 @@ describe('Integration tests for P2P library', () => {
 					.sort();
 
 				const expectedPeerPortsAfterPeerCrash = ALL_NODE_PORTS.filter(port => {
-					return port !== 5000 && port != 5001;
+					return port !== NETWORK_START_PORT && port != NETWORK_START_PORT + 1;
```
Comment (jondubois) [inline elements/lisk-p2p/test/integration/p2p.ts]: The first is `!==`, the second is `!=`

File: elements/lisk-p2p/test/integration/p2p.ts [hunk 2]
```diff
@@ -654,7 +654,7 @@ describe('Integration tests for P2P library', () => {
 					.sort();
 
 				expect(initialPeerPorts).to.be.eql(
-					ALL_NODE_PORTS.filter(port => port != 5000),
+					ALL_NODE_PORTS.filter(port => port != NETWORK_START_PORT),
```
Comment (jondubois) [inline elements/lisk-p2p/test/integration/p2p.ts]: Maybe we should use `!==`/`===` everywhere?
