### PR TITLE
estimateSafeStatus no longer returns block heights from the future

### LINKED ISSUE #8220: Generator safe status is estimated far in the future when genesis block is hardcoded
### Expected behavior

Endpoint `generator_estimateSafeStatus` should return block height of an existing block.

### Actual behavior

The endpoint returns block height far in the future.

It tries to estimate number of missing blocks between the last finalized block and a block that was generated a month ago. If blockchain is less than a month old, it will default to block 0.

In the PoS Example app, the genesis block and its timestamp are hardcoded, which means there is a big and growing timestamp gap between block 0 and block 1.

Currently, for a blockchain that is only about 200 blocks high, the endpoint returns:

```
{
  "height": 60620,
  "maxHeightGenerated": 60620,
  "maxHeightPrevoted": 60620
}
```

### Steps to reproduce

1. Start a new pos-example app.
1. Wait until a first block is finalized.
1. Invoke `generator_estimateSafeStatus` with any timestamp before the finalized block, even 0 is OK.
1. The returned value should be a high number as above. If it is 0, then the first block hasn't finalized yet.

### Which version(s) does this affect? (Environment, OS, etc...)

PoS Example app.

### PR DESCRIPTION
**Pull request by bobanm**
### What was the problem?

This PR resolves #8220

### How was it solved?

1. Genesis block height is no longer assumed to be 0 and hardcoded, but passed to the endpoint from engine.
1. If chain is less than 1 month old, `generator_estimateSafeStatus` endpoint will default past block to genesis block + 1, instead of genesis block.
2. Introduced variables `expectedBlocksCount` and `generatedBlocksCount` to make the calculation easier to understand.
3. BONUS: Aligned local variable names in `areDistinctHeadersContradicting()` function to new property names of `BFTHeader` class 😎 

### How was it tested?

1. If used **before** the first block after genesis is finalized, `generator_estimateSafeStatus` returns error 
1. If used **after** the first block after genesis is finalized, `generator_estimateSafeStatus` returns a reasonable block height, which is no longer in the future

### CODE REVIEW

File: framework/src/engine/generator/endpoint.ts [hunk 1]
```diff
@@ -171,19 +171,19 @@ export class Endpoint {
...
-			);
+		if (!lastGeneratedInfo) {
+			if (isZeroValueGeneratedInfo(req)) {
+				await setLastGeneratedInfo(
+					generatorStore,
+					cryptoAddress.getAddressFromLisk32Address(req.address),
+					req,
+				);
+			} else {
+				throw new Error('Last generated information does not exist.');
```
Comment (shuse2) [inline framework/src/engine/generator/endpoint.ts:185]: instead of if/else, original code looks a lot more cleaner to me 🤔

File: framework/src/engine/generator/endpoint.ts [hunk 2]
```diff
@@ -207,25 +207,25 @@ export class Endpoint {
...
-		if (finalizedBlock.timestamp < req.timeShutdown) {
+		if (req.timeShutdown > finalizedBlock.timestamp) {
 			throw new Error(`A block at the time shutdown ${req.timeShutdown} must be finalized.`);
 		}
 
-		// assume there is 30 days per month
+		// assume there are 30 days per month
 		const numberOfBlocksPerMonth = Math.ceil((60 * 60 * 24 * 30) / this._blockTime);
-		const heightOneMonthAgo = Math.max(finalizedHeight - numberOfBlocksPerMonth, 0);
+		const heightOneMonthAgo = Math.max(finalizedHeight - numberOfBlocksPerMonth, 1);
```
Comment (shuse2) [inline framework/src/engine/generator/endpoint.ts:218]: to be precise it should get the genesis block height, but probably + 1 should be fine

File: framework/src/engine/generator/endpoint.ts (hunk 1 above)
Comment (bobanm) [reply framework/src/engine/generator/endpoint.ts]: Ahhh, I see why. I didn't like the overlapping conditionals, but in this case one of them is used for throwing if the case is invalid, before taking the action.

I've reverted the change, and to avoid confusion I moved setting last generated info after setting the keypairs.

File: framework/src/engine/generator/endpoint.ts [hunk 3]
```diff
@@ -207,25 +210,36 @@ export class Endpoint {
 		validator.validate<EstimateSafeStatusRequest>(estimateSafeStatusRequestSchema, ctx.params);
 
 		const req = ctx.params;
-
 		const finalizedHeight = this._consensus.finalizedHeight();
+		// if there hasn't been a finalized block after genesis block yet, then heightOneMonthAgo could be
+		// higher than the current finalizedHeight, resulting in negative safe status estimate
+		if (!(finalizedHeight > this._genesisBlockHeight)) {
```
Comment (shuse2) [inline framework/src/engine/generator/endpoint.ts:216]:
```suggestion
		if (finalizedHeight === this._genesisBlockHeight) {
```

**Review by shuse2 — COMMENTED** [review]
other than minor thing, looks good to me

**Review by shuse2 — APPROVED** [review]

**Review by mosmartin — APPROVED** [review]
