### PR TITLE
Commander sign transaction should take care empty signature space - Closes #5004

### LINKED ISSUE #5004: Commander sign transaction should take care empty signature space
### Expected behavior
When total member of multi-signature account is 5 and numberOfSignatures is 2, 
`signatures` property should have 5 elements, 2 with signature and 3 with empty string

### Actual behavior
It does not create 5 elements, and the spacing is undefined, not empty string, which fails on validation

### Steps to reproduce
```
./bin/run transaction:sign '{"id":"2082398145299954312","type":8,"senderPublicKey":"d9f0569230016a22206dd123900f245a71b479b5463c7ad235e4f4e933e181e2","senderId":"8363255854011484280L","nonce":"3","fee":"10000000","signatures":["e8356b7da0338056c5deb94f5b5e77f8491917f87060008431f941b04d05b938e1ef6a88ca5ed3065340a62c168c37674848c007e5177b6f3b3812ba01d47e07"],"asset":{"amount":"10000000","recipientId":"3077205662092022585L"}}' --optional-key="e072e3987e9aad9ed7e5735b89af817d16835dbc646d2463928912f42ca18176" --optional-key="c39ff325a5329cfe0f1b122302e9e7df9cb0d9d513770fddc79edaf9106abcff" --optional-key="2675782a6b2c90d9d555343d7a0ac6c6a558ba0484f0ca2f6db0c0dd10a72624" --networkIdentifier=11a254dc30db5eb1ce4001acde35fd5a14d62584f886d30df161e4e883220eb7 --passphrase="position slogan mass reflect stumble pluck liar mushroom electric mistake repair add" --passphrase="table grocery kiss hip retreat chief fringe trash egg valve remind cigar"
```

### Which version(s) does this affect? (Environment, OS, etc...)
4.0-

### PR DESCRIPTION
**Pull request by pablitovicente**
### What was the problem?

This PR resolves #5004

### How was it solved?

- Added code to complete missing signatures with empty string `''` for missing signatures
- If signatures are provided and the signature for the passphrase is found the transaction is returned without pushing it again but the signatures array still goes to the previous step

### How was it tested?

Unit tests

### CODE REVIEW

File: elements/lisk-transactions/src/sign_multi_signature_transaction.ts [hunk 1]
```diff
@@ -78,6 +96,12 @@ export const signMultiSignatureTransaction = (options: {
 		passphrase,
 	);
 
+	if (tx.signatures.indexOf(signature) !== -1) {
```
Comment (ManuGowda) [inline elements/lisk-transactions/src/sign_multi_signature_transaction.ts]:
```suggestion
	if (tx.signatures.includes(signature)) {
```
