### PR TITLE
commander core:install command hangs after installation - Closes #3676

### LINKED ISSUE #3676: commander core:install command hangs after installation
### Expected behavior
`lisk core:install` command shouldn't hang, it should successfully install and start node
### Actual behavior
`lisk core:install` command hangs
### Steps to reproduce
`lisk core:install`
### Which version(s) does this affect? (Environment, OS, etc...)
2.2.0

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?
Core commands were hanging due to PM2 exception were not handled
### How did I fix it?
Handled exception in PM2
### How to test it?
Run all core commands `lisk core --help`
### Review checklist

* The PR resolves #3676 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: commander/src/utils/core/pm2.ts [hunk 1]
```diff
@@ -258,10 +258,16 @@ export const listApplication = async (): Promise<
...
+	try {
+		await connectPM2();
+		const application = await describePM2(name);
+		disconnect();
+
+		return extractProcessDetails(application);
+	} catch (error) {
+		disconnect();
+
+		return false;
```
Comment (shuse2) [inline commander/src/utils/core/pm2.ts]: prefer to return consistent type.
maybe
`Promise<PM2ProcessInstance | undefined>` or rethrow error is bit better

Comment (ManuGowda) [reply commander/src/utils/core/pm2.ts]: the problem with throwing would be difficult to handle the case.. here i am returning boolean, that way I can handle the condition, something like this
```
const instance = await describeApplication(name);

		if (!instance) {
			this.log(
				`Lisk Core instance: ${name} doesn't exists, Please install using lisk core:install`,
			);

			return;
		}
		// tslint:disable-next-line await-promise
		await StopCommand.run([name]);
		// tslint:disable-next-line await-promise
		await StartCommand.run([name]);
```

Comment (shuse2) [reply commander/src/utils/core/pm2.ts]: then let's say `undefined` =)
