### PR TITLE
Fix app crash on ipc disabled - Closes #6134 #6151

### LINKED ISSUE #6134: Disabling RPC crashes the application
### Expected behavior

Disabling RPC by `rpc.enable = false` should not effect starting the application. 

### Actual behavior

If we disable rpc the application crashes with following error. 

```
4:44:43 DEBUG lisk-framework: Failed to publish event: httpApi:unloading:started to ipc server. (module=lisk:app)
Message: Cannot read property 'pubSocket' of undefined 
 Trace: TypeError: Cannot read property 'pubSocket' of undefined
    at Bus.publish (/lisk-sdk/framework/src/controller/bus.ts:315:20)
    at InMemoryChannel.publish (/lisk-sdk/framework/src/controller/channels/in_memory_channel.ts:54:12)
    at Controller._unloadInMemoryPlugin (/lisk-sdk/framework/src/controller/controller.ts:280:40)
    at Controller.unloadPlugins (/lisk-sdk/framework/src/controller/controller.ts:132:17)
    at Controller.cleanup (/lisk-sdk/framework/src/controller/controller.ts:160:15)
    at Application.shutdown (/lisk-sdk/framework/src/application.ts:294:27)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at handleShutdown (/lisk-sdk/framework/src/application.ts:71:3) 
```

### Steps to reproduce

```
cd commander
./bin/run init /path/to/app
cd /path/to/app
vi config/mainnet/config.json # change the rpc to false
./bin/run start --overwrite-config
```

### Which version(s) does this affect? (Environment, OS, etc...)
5.0.x

### PR DESCRIPTION
**Pull request by ishantiw**
### What was the problem?

This PR resolves #6134 & #6151

### How was it solved?

♻️ Use IPC server only when IPC is enabled 6f385dc
♻️  consoleLogLevel->info as default value

### How was it tested?

- `/path/to/commander/bin/run init /path/to/app`
- `cd /path/to/app`
-  `vi app/config/mainnet/config.json`  // RPC is disabled `rpc: { enabled: false, ...`
- `./bin/run start --overwrite-config`

### CODE REVIEW

**Review by shuse2 — APPROVED** [review]

File: framework/src/controller/bus.ts [hunk 1]
```diff
@@ -311,13 +311,15 @@ export class Bus {
...
-			);
+		if (this.config.rpc.enable) {
+			try {
+				this._ipcServer.pubSocket.send(notification);
+			} catch (error) {
+				this.logger.debug(
+					{ err: error as Error },
+					`Failed to publish event: ${eventName} to ipc server.`,
+				);
+			}
```
Comment (Incede) [inline framework/src/controller/bus.ts:324]:
```suggestion
		if (this.config.rpc.enable) {
			try {
				this._ipcServer.pubSocket.send(notification);
			} catch (error) {
				this.logger.debug(
					{ err: error as Error },
					`Failed to publish event: ${eventName} to ipc server.`,
				);
			}
			
			if (this.config.rpc.enable && this.config.rpc.mode === 'ws') {
				try {
					this._wsServer.broadcast(JSON.stringify(notification));
				} catch (error) {
					this.logger.debug(
						{ err: error as Error },
						`Failed to publish event: ${eventName} to ws server.`,
					);
				}
			}
```

Comment (Incede) [reply framework/src/controller/bus.ts:324]: I think if we can club the conditional block starting at `L325` here like the suggestion above, it saves one additional `if` comparison. Feel free to ignore though since it's not a significant difference.

**Review by Incede — CHANGES_REQUESTED** [review]

**Review by Incede — APPROVED** [review]
