### PR TITLE
Fix data consistency with list and pool - Closes #4982

### LINKED ISSUE #4982: Account limit should be respected in transaction pool
### Expected behavior
Transaction pool should only maintain certain amount of transaction per account (by default 64)

### Actual behavior
It holds more than 64 transactions

### Steps to reproduce
Send more than 64 transactions from the same account

### Which version(s) does this affect? (Environment, OS, etc...)
4.0-

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #4982 

### How was it solved?

- Update `transactionList.add` and `transactionList.remove` to return what is removed
- Remove from transaction pool when something is removed

### How was it tested?

- Added test to cover this scenario
- Send transactions more than 64 from the same sender, and observe tx-pool size does not go over 64

### CODE REVIEW

File: elements/lisk-transaction-pool/src/transaction_pool.ts [hunk 1]
```diff
@@ -217,6 +215,29 @@ export class TransactionPool {
...
+			incomingTx,
+			txStatus === TransactionStatus.PROCESSABLE,
+		);
+
+		if (removedID) {
+			debug('Removing from transaction pool with id', removedID);
+			delete this._allTransactions[removedID];
+		}
+
+		if (!added) {
```
Comment (ishantiw) [inline elements/lisk-transaction-pool/src/transaction_pool.ts]: Maybe we can move this condition before the above condition and early return error
