### PR TITLE
Fix Commander incorrectly parsing no input at array prompt

### LINKED ISSUE #8517: Validator throws error on multisignature registration
### Expected behavior
It should be possible to register a multi-signature account without any optional keys.

### Actual behavior
Validator throws error, if no optional keys are provided:

### Steps to reproduce
```
$ lisk-core transaction:create auth registerMultisignature 100000000
? Please enter passphrase:  [hidden]
? Please enter: numberOfSignatures:  2
? Please enter: mandatoryKeys(comma separated values (a,b)):
61d320f822fcc163489499200ae6c99a66296513b1ca1066e49a37a026434ac0,dfbe4e3999138d62047c23f61f222a91b24d9d056db055be24f9ab6d95d7aa78
? Please enter: optionalKeys(comma separated values (a,b)):
? Please enter: signatures(comma separated values (a,b)):
85ac61c373218cdf5e0e58a22c9b9ae71cfaf1450062d0302166b60a1cdc3b638eb747ba87c43af20d66b8e9d7513fb1d4cd3800a82debd30f0dc41937cef70e,e17d
67b24c1f0ab207a194bd1a1781b1c8c3110bcb427cd26f84f3034afc567583e021df575881c396e286198f4a36749055e717eaa56cd3f1fd2f3d7835b70d
    Error: Lisk validator found 1 error[s]:
    Property '.optionalKeys.0' minLength not satisfied
```

### Which version(s) does this affect? (Environment, OS, etc...)
Ubuntu 22, beta.1

### PR DESCRIPTION
**Pull request by bobanm**
### What was the problem?

This PR resolves #8517

When an empty string would be received for a param where array is expected, Commander would cast it into an array with an empty string `['']` instead of into an empty array `[]`.

### How was it solved?

- Added logic to `castValue()` to correctly parse empty array input
- Modified `/auth/command/regMultisig` schema to remove `mandatoryKeys` and `optionalKeys` as required properties

### How was it tested?

The scenario from the related issue now successfully creates a transaction.

### CODE REVIEW

File: commander/src/utils/reader.ts [hunk 1]
```diff
@@ -221,6 +221,7 @@ const castValue = (
 		return JSON.parse(val);
 	}
 	if (schemaType === 'array') {
+		if (val === '') return [];
```
Comment (shuse2) [inline commander/src/utils/reader.ts:224]:
```suggestion
		if (val === '') {
			return [];
		}
```

**Review by shuse2 — APPROVED** [review]

**Review by ishantiw — APPROVED** [review]

File: commander/src/utils/reader.ts (hunk 1 above)
Comment (bobanm) [reply commander/src/utils/reader.ts]: Pushed a new implementation which uses the ternary operator.

**Review by mosmartin — APPROVED** [review]

**Review by shuse2 — APPROVED** [review]
