### PR TITLE
Fix NaCL slow/fast module loading

### LINKED ISSUE #4632: NaCl falls back to "slow" making signatures slower
### Expected behavior

Lisk crypto uses "slow" when "process.env.NACL_FAST === 'disable'". In
https://github.com/LiskHQ/lisk-sdk/blob/development/elements/lisk-cryptography/src/nacl/index.ts

### Actual behavior

Using slow when "process.env.NACL_FAST" is undefined.

### Steps to reproduce
Check which version (slow or fast) of the library is used. 

### Proposed solution
Add a check for existence of process.env.NACL_FAST:
```
try {
	if (process.env.NACL_FAST && process.env.NACL_FAST === 'disable') {
		throw new Error('Use tweetnacl');
	}
	// Require used for conditional importing
	// tslint:disable-next-line no-var-requires no-require-imports
	lib = require('./fast');
} catch (err) {
	process.env.NACL_FAST = 'disable';
	// tslint:disable-next-line no-var-requires no-require-imports
	lib = require('./slow');
}
```
Even better: remove the try/catch logic here.

### PR DESCRIPTION
**Pull request by valamidev**
### What was the problem?
- Lisk-cryptography got 2 different implementation for NaCL cryptography library, `fast and slow`, we prefer to use Fast unless it is disabled with `process.env.NACL_FAST=disable`. Due a bug we choose slow when NACL_FAST were undefined which is the default value of a non set environment variable.

### How did I solve it?
- Updated the module import logic statement.

### How to manually test it?
- `npm run test`

### Review checklist

- [x] The PR resolves #4632 
- [x] All new code is covered with unit tests
- [x] Relevant integration / functional tests are added
- [x] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [x] Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-cryptography/test/nacl/index.ts [hunk 1]
```diff
@@ -109,25 +109,11 @@ describe('nacl index.js', () => {
 			return expect(process.env.NACL_FAST).to.eql('disable');
 		});
 
-		it('should load nacl slow if process.env.NACL_FAST is set to enable', () => {
```
Comment (shuse2) [inline elements/lisk-cryptography/test/nacl/index.ts]: this test seems to be wrong, but why it was passing?

Comment (valamidev) [reply elements/lisk-cryptography/test/nacl/index.ts]: The Test check the interface of the loaded module which is equal for slow and fast implementation.
```
{
  box: [Function],
  openBox: [Function],
  signDetached: [Function],
  verifyDetached: [Function],
  getRandomBytes: [Function],
  getKeyPair: [Function],
  getPublicKey: [Function]
}
```

Comment (valamidev) [reply elements/lisk-cryptography/test/nacl/index.ts]: Related issue about tests #4677
