### PR TITLE
Fix generator enable/disable commands

### LINKED ISSUE #7783: generator command not enabling block generation
### Expected behavior
- `generator:enable` should enable the block generation for specified address with parameters
- `generator:enable` should have flag `--use-status-values` to use the status from the node

### Actual behavior
- `generator:enable` should enable the block generator, but it is just setting the generator parameter
- `generator:import` fails with missing parameter

### Steps to reproduce
1. Remove existing data
1. ./bin/run keys:encrypt -f ./config/default/dev-validators.json  
2. ./bin/run generator:import -f ./config/default/dev-validators.json   (add "generatorInfo" in the json file with empty array)
3. ./bin/run generator:enable lske5sqed53fdcs4m9et28f2k7u9fk6hno9bauday 0 0 0
4. ./bin/run generator:enable lske5sqed53fdcs4m9et28f2k7u9fk6hno9bauday --use-status-values

### Which version(s) does this affect? (Environment, OS, etc...)
v6.0.0-alpha.5

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #7783 

### How was it solved?

- Revert generator enable/disable command to have `--use-status-value`
  - Move height/max-height-generated/max-height-prevoted as flag
- Revert temporally lisk-db version to the previous version because it leaves locks value https://github.com/LiskHQ/lisk-db/issues/78
- Fix to pass `keypairs` from `generator` to `endpoint`
- Remove keypair when setting new key

### How was it tested?

1. clean ` rm -rf ~/.lisk/pos-mainchain`
2. encrypt keys `./bin/run keys:encrypt -f ./config/default/dev-validators.json`
3. import new keys `./bin/run keys:import -f config/default/dev-validators.json`
4. enable block generation `./bin/run generator:enable lsk2xxvfxaqpm42wr9reokucegh3quypqg9w9aqfo --height=0 --max-height-prevoted=0 --max-height-generated=0`
5. check block is generated (wait for 1 round)
6. check status `./bin/run generator:status --pretty`

### CODE REVIEW

File: commander/src/bootstrapping/commands/generator/enable.ts [hunk 1]
```diff
@@ -13,43 +13,94 @@
...
+			description: 'Last generated block height.',
+		}),
+		'max-height-generated': Flags.integer({
+			description: 'Validators largest previously generated height.',
+		}),
+		'max-height-prevoted': Flags.integer({
+			description: 'Validators largest prevoted height for a block.',
+		}),
+		'use-status-value': Flags.boolean({
+			description: 'use status value from the connected node',
```
Comment (has5aan) [inline commander/src/bootstrapping/commands/generator/enable.ts:51]: To nitpick, can we please change the message description to 'Use status value from the connected node.', just to have consistent pattern with other command descriptions?

**Review by has5aan — APPROVED** [review]

File: commander/src/bootstrapping/commands/generator/enable.ts [hunk 2]
```diff
@@ -13,43 +13,94 @@
...
+		} = flags;
+
+		if (
+			!useStatusValue &&
+			(isLessThanZero(height) ||
+				isLessThanZero(maxHeightGenerated) ||
+				isLessThanZero(maxHeightPrevoted))
+		) {
+			throw new Error(
+				'The maxHeightGenerated and maxHeightPrevoted parameter value must be greater than or equal to 0',
```
Comment (bobanm) [inline commander/src/bootstrapping/commands/generator/enable.ts:75]: Since flags are provided in kebab-case format, wouldn't it be more consistent [and less confusing for a user] to use the same format in error message and test case names, rather than camelCase:

```
'The max-height-generated and max-height-prevoted parameter value must be greater than or equal to 0'
```

Also, it would be more specific to refer to them as _flag values_, rather than _parameter values_.

File: commander/src/bootstrapping/commands/generator/enable.ts [hunk 3]
```diff
@@ -13,43 +13,94 @@
...
-		...BaseForgingCommand.flags,
+		...BaseGeneratorCommand.flags,
+		height: Flags.integer({
+			description: 'Last generated block height.',
+		}),
+		'max-height-generated': Flags.integer({
+			description: 'Validators largest previously generated height.',
+		}),
+		'max-height-prevoted': Flags.integer({
+			description: 'Validators largest prevoted height for a block.',
```
Comment (bobanm) [inline commander/src/bootstrapping/commands/generator/enable.ts:48]: It looks like these descriptions should use Saxon genitive [validator's] instead of plural [validators].

File: commander/src/bootstrapping/commands/generator/enable.ts [hunk 4]
```diff
@@ -13,43 +13,94 @@
...
  */
 
-import { BaseForgingCommand } from '../base_forging';
+import { Flags } from '@oclif/core';
+import { BaseGeneratorCommand } from '../base_generator';
 
-export abstract class EnableCommand extends BaseForgingCommand {
-	static description = 'Enable forging for given validator address.';
+const isLessThanZero = (value: number | undefined | null): boolean =>
+	value === null || value === undefined || value < 0;
```
Comment (bobanm) [inline commander/src/bootstrapping/commands/generator/enable.ts:20]: I find it semantically incorrect to consider `null` and `undefined` to be less than zero.

Consider renaming the function to `isNonNegativeNumber()` and reversing the conditional. Then don't forget to update the usages of the function by adding negation in front.

https://en.m.wikipedia.org/wiki/Sign_(mathematics)#non-negative_and_non-positive

File: commander/src/bootstrapping/commands/generator/disable.ts [hunk 5]
```diff
@@ -25,13 +25,29 @@ export abstract class DisableCommand extends BaseForgingCommand {
...
+
+		await this._client.invoke('generator_updateStatus', {
+			address,
+			password,
+			enable: false,
+			height: 0,
+			maxHeightGenerated: 0,
+			maxHeightPrevoted: 0,
+		});
+		this.log('Disabled block generation');
```
Comment (bobanm) [inline commander/src/bootstrapping/commands/generator/disable.ts:51]: To make it consistent with `EnableCommand`, the message would be:

```typescript
this.log(`Disabled block generation for ${address}`);
```

File: commander/test/bootstrapping/commands/generator.spec.ts [hunk 6]
```diff
@@ -108,19 +120,53 @@ describe('forging', () => {
 			});
 		});
 
+		describe('when use-status-value is used', () => {
```
Comment (bobanm) [inline commander/test/bootstrapping/commands/generator.spec.ts:123]: It would be nice to add a unit test which will assert that enable command correctly populates all 3 height attributes using status values, when `use-status-value` and 1 or more `*height*` flags are used together.

Or otherwise the command should throw an error if it's not allowed to combine those flags.

File: commander/test/bootstrapping/commands/generator.spec.ts [hunk 7]
```diff
@@ -108,19 +120,53 @@ describe('forging', () => {
...
 		});
 
 		describe('when action fail', () => {
 			it('should log the error returned', async () => {
 				when(invokeMock)
-					.calledWith('generator_setStatus', {
-						address: 'myFailedEnabledAddress',
-						enabled: true,
+					.calledWith('generator_updateStatus', {
+						address: 'myFailedenableAddress',
```
Comment (bobanm) [inline commander/test/bootstrapping/commands/generator.spec.ts:168]: Probably automated replace from `enabled` to `enable` messed up the camelCase here.

This is such an irrelevant test value, but still `myFailedEnableAddress` is more readable 😊

File: commander/src/bootstrapping/commands/generator/enable.ts (hunk 4 above)
Comment (bobanm) [reply commander/src/bootstrapping/commands/generator/enable.ts]: `isPositiveNumber()` is a little bit better, but is still not 100% correct, because 0 is not a positive number 🤓 

There is a reason I suggested `isNonNegativeNumber()` instead of `isPositiveNumber()`

File: commander/test/bootstrapping/commands/generator.spec.ts [hunk 8]
```diff
@@ -36,54 +35,101 @@ describe('forging', () => {
...
-			await expect(EnableCommand.run([], config)).rejects.toThrow('Missing 4 required arg');
+			await expect(EnableCommand.run([], config)).rejects.toThrow('Missing 1 required arg');
 		});
 
 		it('should throw an error when height, maxHeightGenerated and maxHeightPrevoted arg is not provided', async () => {
 			await expect(
 				EnableCommand.run(['myAddress', '--password=my-password'], config),
-			).rejects.toThrow('Missing 3 required arg');
+			).rejects.toThrow(
+				'The height, max-height-generated and max-height-prevoted values must be greater than or equal to 0',
```
Comment (bobanm) [inline commander/test/bootstrapping/commands/generator.spec.ts:55]: Now that we use kebab-case for flags in error message, it would be good to make it consistent also in the name of this test case and the following test case. And also to use plural tense:

```
should throw an error when height, max-height-generated and max-height-prevoted values are not provided
```

File: commander/src/bootstrapping/commands/generator/enable.ts (hunk 4 above)
Comment (shuse2) [reply commander/src/bootstrapping/commands/generator/enable.ts]: yea that's true, but name wise nonNegativeNumber is not so straight forward. I think `isUInt` will probably be more suited

Comment (bobanm) [reply commander/src/bootstrapping/commands/generator/enable.ts]: `isUInt()` is definitely the perfect name for what we need there. Probably haven't thought of it before, because the function never checked that input number was an integer 🙂

**Review by bobanm — APPROVED** [review]
