### PR TITLE
TypeError: Converting circular structure to JSON with Node 12.14.1 - Closes #4667

### LINKED ISSUE #4667: TypeError: Converting circular structure to JSON with Node 12.14.1
### Expected behavior

The application should work well after upgrading to `Node 12.14.1`. 

### Actual behavior

While upgrading and trying with `Node 12.14.1` caused this Type error. It works well with `12.14.0`

```
(base) ➜  lisk-sdk-review git:(release/3.0.0) ✗ node framework/test/test_app/index.js | npx bunyan -o short
15:15:36.116Z  INFO lisk-framework: Booting the application with Lisk Framework(0.1.0) (module=lisk-controller)
15:15:36.118Z  INFO lisk-framework: Starting the app - lisk-devnet-4000 (module=lisk-controller)
15:15:36.131Z  INFO lisk-framework: Initializing controller (module=lisk-controller)
15:15:36.140Z  INFO lisk-framework: Loading controller (module=lisk-controller)
15:15:36.261Z  INFO lisk-framework: Previous Lisk PID (module=lisk-controller)
15:15:36.262Z  INFO lisk-framework: Current Lisk PID (module=lisk-controller)
15:15:36.301Z  INFO lisk-framework-chain: Loading in-memory module (module=lisk-controller, version=0.1.0, moduleAlias=chain)
15:15:36.318Z ERROR lisk-framework: (module=chain)
    Converting circular structure to JSON
        --> starting at object with constructor 'Socket'
        |     property '_writableState' -> object with constructor 'WritableState'
        |     property 'afterWriteTickInfo' -> object with constructor 'Object'
        --- property 'stream' closes the circle
    --
    TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'Socket'
        |     property '_writableState' -> object with constructor 'WritableState'
        |     property 'afterWriteTickInfo' -> object with constructor 'Object'
        --- property 'stream' closes the circle
        at JSON.stringify (<anonymous>)
        at Object.toJson (/Users/nazar/.nvm/versions/node/v12.14.1/lib/node_modules/pg-promise/lib/utils/index.js:221:21)
        at Function.createContextKey (/Users/nazar/.nvm/versions/node/v12.14.1/lib/node_modules/pg-promise/lib/database-pool.js:90:26)
        at Function.register (/Users/.nvm/versions/node/v12.14.1/lib/node_modules/pg-promise/lib/database-pool.js:33:36)
        at new Database (/Users/.nvm/versions/node/v12.14.1/lib/node_modules/pg-promise/lib/database.js:447:18)
        at inst (/Users/.nvm/versions/node/v12.14.1/lib/node_modules/pg-promise/lib/main.js:242:20)
``` 

### Steps to reproduce

Apparently it seems the issue with `Pg-Promise` but I tried it in a new script file 

```js
const pgpLib = require('pg-promise');

const pgpOptions = {
	capSQL: true,
	promiseLib: Promise,
	noLocking: false,
};

const pgp = pgpLib(pgpOptions);

const {
	components: { storage: dbConfig },
} = require('./test/fixtures/config/devnet/config');

const db = pgp(dbConfig);

db.connect()
	.then(() => {
		console.log('connected');
	})
	.catch(error => console.error('error', error));

```

The above script works well with both node versions. Also tests with latest Pg-Promise `10.13.2` as well and same issue. 

### Which version(s) does this affect? (Environment, OS, etc...)
3.0.0, Node 12.14.1

### PR DESCRIPTION
**Pull request by nazarhussain**
### What was the problem?

There were some changes introduced in Node `12.14.1`, which was causing circular dependency for `process.stdout`. Internally `pg-monitor` was using `JSON.stringify` on the options provided to database object. And our options contains logger, which included the `process.stdout` in Bunyan.

### How did I solve it?

Removed the `logger` from adapter options as its already assigned to instance of the adapter. 

### How to manually test it?

Use Node `12.14.1` and start the test application. 

### Review checklist

- [ ] The PR resolves #4667
- [ ] All new code is covered with unit tests
- [ ] Relevant integration / functional tests are added
- [ ] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [ ] Documentation has been added/updated

### CODE REVIEW

File: framework/src/components/storage/adapters/pgp_adapter.js [hunk 1]
```diff
@@ -40,13 +40,15 @@ class PgpAdapter extends BaseAdapter {
 			inTest: options.inTest,
 		});
 
-		this.options = options;
+		this.options = { ...options };
```
Comment (shuse2) [inline framework/src/components/storage/adapters/pgp_adapter.js]: Maybe this is bit more clear?
```
		const { logger, ...optionsWithoutLogger } = options;
		this.options = optionsWithoutLogger;
		this.logger = logger;
```
