### PR TITLE
Investigate slow sync on introduce_bft_consensus-dpos.1 branch - Closes #4340

### LINKED ISSUE #4340: Investigate slow sync on introduce_bft_consensus-dpos branch
### Expected behavior
Expect the branch `introduce_bft_consensus-dpos.1` to sync with mainnet in less than 3 days

PS.: `introduce_bft_consensus-dpos.1` branch was branched off `feature/introduce_bft_consensus` after Dpos module implementation and before introducing breaking changes. Because of that, it should still have similar performance when syncing with mainnet (note that due to https://github.com/LiskHQ/lisk-sdk/issues/4194 it's not possible to sync with testnet)

### Actual behavior
It takes more than 5 days to sync up to the height `4 000 000`

### Steps to reproduce
Syncing with mainnet using Lisk Core branch `feature/introduce_bft_consensus` with Lisk SDK branch `introduce_bft_consensus-dpos.1`

### Which version(s) does this affect? (Environment, OS, etc...)
`introduce_bft_consensus-dpos.1`

### PR DESCRIPTION
**Pull request by lsilvs**
### What was the problem?
When processing the last block of the round Dpos module updates the `voteWeight` of delegates that forging delegates voted for. This update was using `publicKey` as Storage filter but `publicKey` didn't have database index causing the query to take too long.

### How did I solve it?
I've created missing indexes and made some other improvements/fixes that was left out.

### How to manually test it?
Syncing with mainnet using Lisk Core branch `feature/introduce_bft_consensus` with Lisk SDK branch `4340-investigate-slow-sync`
Full sync should take less than 4 days

### Review checklist

- [ ] The PR resolves #4340
- [ ] All new code is covered with unit tests
- [ ] Relevant integration / functional tests are added
- [ ] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [ ] Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/chain/migrations/sql/20191008170600_create_mem_accounts_public_key_index.sql [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+ * Removal or modification of this copyright notice is prohibited.
+ */
+
+
+ /*
+  DESCRIPTION: Create index for mem_accounts.publicKey
+  PARAMETERS: None
+*/
+
+CREATE INDEX IF NOT EXISTS "mem_accounts_public_key" ON "mem_accounts" (ENCODE("publicKey", 'hex'));
```
Comment (shuse2) [inline framework/src/modules/chain/migrations/sql/20191008170600_create_mem_accounts_public_key_index.sql]: I think it will be nice to keep the publicKey out of index since we will use the state store in #4136

File: framework/src/modules/chain/transactions/transactions_handlers.js [hunk 2]
```diff
@@ -151,8 +151,18 @@ const applyTransactions = (storage, exceptions) => async (transactions, tx) => {
...
+	// eslint-disable-next-line no-restricted-syntax
+	for (const transaction of transactions) {
+		// eslint-disable-next-line no-await-in-loop
+		await transaction.prepare(stateStore);
+	}
+
+	// eslint-disable-next-line no-restricted-syntax
+	for (const transaction of transactions) {
+		// eslint-disable-next-line no-await-in-loop
+		await votesWeight.prepare(stateStore, transaction);
```
Comment (shuse2) [inline framework/src/modules/chain/transactions/transactions_handlers.js]: I think this also happens in the `undo` case too.
Not important for this PR, but it would be faster to change to `await votesWeight.prepare(stateStore, transactions);`

File: framework/src/modules/chain/migrations/sql/20191008170600_create_mem_accounts_public_key_index.sql (hunk 1 above)
Comment (yatki) [reply framework/src/modules/chain/migrations/sql/20191008170600_create_mem_accounts_public_key_index.sql]: @shuse2 I agree that maybe creating index for publicKey just for this issue is not necessary but I'd prefer to tackle it after or during working on #4136. Since everything goes to bft branch we can remove this migration file later. But it's up to @lsilvs to decide. This is just my opinion.

File: framework/src/modules/chain/transactions/transactions_handlers.js (hunk 2 above)
Comment (lsilvs) [reply framework/src/modules/chain/transactions/transactions_handlers.js]: Done
