### PR TITLE
Respond status code when client IP not allowed - Closes #6037

### LINKED ISSUE #6037: HTTP status code when client IP is not allowed
### Expected behavior
If the client IP is not allowed to access an API the response HTTP status code should be `401`.

### Actual behavior
The HTTP and monitoring APIs (and possibly more) return `500`.

### Steps to reproduce
```
lisk-core start --enable-http-api-plugin --http-api-plugin-port=5000 --http-api-plugin-whitelist=1.2.3.4
curl --verbose http://127.0.0.1:5000/api/node/info
```

### Which version(s) does this affect? (Environment, OS, etc...)
5.0.0 / 3.0.0-beta.2

### PR DESCRIPTION
**Pull request by Incede**
### What was the problem?

This PR resolves #6037

### How was it solved?

* Handle error status response

### How was it tested?
```
./bin/run sdk:link /path-to-lisk-sdk/lisk-sdk/sdk
./bin/run start --enable-http-api-plugin --http-api-plugin-port=5000 --http-api-plugin-whitelist=1.2.3.4
curl --verbose http://127.0.0.1:5000/api/node/info
```

### CODE REVIEW

File: framework-plugins/lisk-framework-http-api-plugin/src/middlewares/errors.ts [hunk 1]
```diff
@@ -38,5 +46,9 @@ export const errorMiddleware = () => (
 		Object.defineProperty(error, 'message', { enumerable: true });
 	}
 
-	res.status(500).send({ errors });
+	const statusCode = (err as ErrorWithStatus).statusCode
```
Comment (shuse2) [inline framework-plugins/lisk-framework-http-api-plugin/src/middlewares/errors.ts:49]: maybe it's better to check like
```
const statusCode = err instanceof ErrorWithStatus ? err.statusCode : 500;
```

**Review by shuse2 — CHANGES_REQUESTED** [review]
same change should be applied for monitor plugin

File: framework-plugins/lisk-framework-http-api-plugin/src/middlewares/errors.ts [hunk 2]
```diff
@@ -13,6 +13,14 @@
  */
 import { Request, Response, NextFunction } from 'express';
 
+export class ErrorWithStatus extends Error {
```
Comment (nazarhussain) [inline framework-plugins/lisk-framework-http-api-plugin/src/middlewares/errors.ts:16]:
```suggestion
export class HTTPError extends Error {
```

**Review by nazarhussain — CHANGES_REQUESTED** [review]

**Review by nazarhussain — APPROVED** [review]

**Review by shuse2 — APPROVED** [review]
