### PR TITLE
Lisk 2.0.0 protocol rejects with incompatible protocol version for nodes with version <= 1.4.1 - Closes #3799

### LINKED ISSUE #3799: Lisk 2.0.0 protocol rejects with incompatible protocol version for nodes with version <= 1.4.1
### Expected behavior
Lisk Core 2.0.0 protocol should support following versions

## Testnet
```
Version	Count	%
---------| -- | --
1.6.0-rc.4	75	57 %
1.6.0-rc.3	10	8 %
1.6.0	3	2 %
1.5.1-rc.0	8	6 %
1.5.1	1	1 %
1.5.0-rc.2	4	3 %
1.5.0-rc.1	1	1 %
1.4.1-rc.0	8	6 %
1.4.0-rc.0	3	2 %
1.4.0	1	1 %
1.3.1-rc.0	2	2 %
1.3.0-rc.0	3	2 %
1.2.0-rc.2	2	2 %
1.2.0-rc.1	1	1 %
1.1.1-rc.1	8	6 %
```

## mainnet
```

Version | Count | %
----- | -- | --
1.6.0 | 191 | 70 %
1.5.1 | 18 | 7 %
1.5.0 | 18 | 7 %
1.4.1 | 9 | 3 %
1.4.0 | 11 | 4 %
1.3.1 | 7 | 3 %
1.3.0 | 3 | 1 %
1.2.1 | 4 | 1 %
1.1.1 | 4 | 1 %
1.1.0 | 1 | 0 %
1.0.3 | 2 | 1 %
1.0.2 | 5 | 2 %


```
### Actual behavior
```
[ERR] 2019-06-07 11:59:39 | Failed to get random peer from network
[ERR] 2019-06-07 11:59:39 | Failed to get random peer from network
[dbg] 2019-06-07 11:59:39 | System headers - {"os":"linux4.15.0-51-generic","version":"1.4.1","wsPort":5000,"httpPort":4000,"height":1,"nethash":"198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d","broadhash":"198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d","minVersion":"1.0.0","nonce":"W7EbUoW0egEsckFL"}
[dbg] 2019-06-07 11:59:39 | Transport->broadcastHeaders: No peers found
[dbg] 2019-06-07 11:59:39 | Establishing broadhash consensus after sync: 0 %
[inf] 2019-06-07 11:59:39 | Finished sync
[dbg] 2019-06-07 11:59:39 | Listing peers - {"attempt":"matched broadhash","found":1,"matched":0,"picked":0,"accepted":0}
[dbg] 2019-06-07 11:59:39 | Listing peers - {"attempt":"unmatched broadhash","found":1,"matched":1,"picked":1,"accepted":1}
[dbg] 2019-06-07 11:59:39 | [Outbound socket :: close] Peer connection to 165.22.199.48:5000 closed with code 4104 and reason - Peer has incompatible protocol version
[dbg] 2019-06-07 11:59:39 | Removed peer - 165.22.199.48:5000
[dbg] 2019-06-07 11:59:39 | Inserted new peer - 165.22.199.48:5000
[dbg] 2019-06-07 11:59:39 | [Outbound socket :: error] Peer error from 165.22.199.48:5000 - Socket connection closed with status code 4104 and reason: Peer has incompatible protocol version
```
### Steps to reproduce
Deploy Network with nodes `2.0.0-alpha.11`, `1.6.0`, 1.5.0`, `1.4.1`

### Which version(s) does this affect? (Environment, OS, etc...)
2.0.0

### PR DESCRIPTION
**Pull request by jondubois**
### What was the problem?

The P2P library did not account for cases where the peer did not report a `protocolVersion`. This posed a problem when connecting with nodes `v1.4.x` and lower.

### How did I fix it?

Added a backwards compatibility check using the regular `version` field. Took inspiration from https://github.com/LiskHQ/lisk-sdk/blob/v1.5.0/api/ws/workers/middlewares/handshake.js#L117

### How to test it?

Check against testnet.

### Review checklist

* The PR resolves #3799
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-p2p/src/validation.ts [hunk 1]
```diff
@@ -158,11 +160,15 @@ export const checkProtocolVersionCompatibility = (
 	nodeInfo: P2PNodeInfo,
 ): boolean => {
 	if (!peerInfo.protocolVersion) {
-		return false;
+		try {
+			return isVersionGTE(peerInfo.version, nodeInfo.minVersion as string);
+		} catch (error) {
```
Comment (limiaspasdaniel) [inline elements/lisk-p2p/src/validation.ts]: If error is not being used it can be omitted here :)

Comment (shuse2) [reply elements/lisk-p2p/src/validation.ts]: I think error cannot be ommited by the node.js definition =p

Comment (limiaspasdaniel) [reply elements/lisk-p2p/src/validation.ts]: Maybe `_`? hahaha. It's fine then
