### PR TITLE
Fix file log to write bigint and buffer as string - Closes #5707

### LINKED ISSUE #5707: Buffer JSON format is written in file log
### Expected behavior
When logging to a file, `Buffer` must be converted to string

### Actual behavior
It is writing in `{ type: 'Buffer',  data: [] }` format

### Steps to reproduce
Look at logs/lisk.log

### Which version(s) does this affect? (Environment, OS, etc...)
5.0

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #5707 

### How was it solved?

- Add custom file stream to parse the log before writing
- Convert Buffer and bigint to string before calling JSON stringify

### How was it tested?

- Run application with file log and observe the file log (all bigint and Buffer should be string)

### CODE REVIEW

**Review by pablitovicente — APPROVED** [review]

File: framework/src/logger/logger.ts [hunk 1]
```diff
@@ -107,6 +107,66 @@ class ConsoleLog {
...
+			level,
+			name,
+			msg,
+			hostname,
+			pid,
+			module: moduleName ?? 'unknown',
+		};
+		const otherKeys = Object.entries(others);
+		if (otherKeys.length > 0) {
+			const meta = otherKeys.reduce<Record<string, unknown>>((prev, [key, value]) => {
```
Comment (nazarhussain) [inline framework/src/logger/logger.ts:142]: This does not cover all possible cases. 

1. Nested objects with `buffer` or `bigint` values. 
2. Arrays on first level or deep level

I am not sure if such nested objects are not used within SDK. But on a higher perspective we are exposing the logger from the `Application` instance as `app.logger` so SDK user can log anything with. So our logger implementation should be very generic to handle all such cases.

**Review by nazarhussain — CHANGES_REQUESTED** [review]

File: framework/src/logger/logger.ts (hunk 1 above)
Comment (shuse2) [reply framework/src/logger/logger.ts:142]: I think there is a trade off of how nested that logs needs to go vs performance.
For the console log also it only checks the first level. This is focusing on the fixing the bug that it logs the Buffer JSON on our usage.

If we want to support more nested level, we should create new issue as a feature issue

Comment (nazarhussain) [reply framework/src/logger/logger.ts:142]: https://github.com/LiskHQ/lisk-sdk/issues/5778

**Review by nazarhussain — APPROVED** [review]
