### PR TITLE
Fix reward distribution to use # of validators instead of constant

### LINKED ISSUE #9024: Dynamic Block Reward Computation incorrect in case validators number is small
The dynamic block rewards module calculates the block rewards assumming that the number of active validators in each round is *exactly* `NUMBER_ACTIVE_VALIDATORS` (e.g., 101 in the mainchain). 

### Expected behavior

We should take care of the case that in current round the number of eligible validators are less than  `NUMBER_ACTIVE_VALIDATORS` (e.g., 101 in the mainchain). This might very well happen after the next hard-fork since initially old validators will be banned until they register a BLS key. So a given round, might have much fewer validators. 

### Actual behavior

In[ `getStakeRewardActiveValidators` function](https://github.com/LiskHQ/lisk-sdk/blob/2d04e23b5b172a7b84cdad2669b985a51156e671/framework/src/modules/dynamic_rewards/utils.ts#L26), we define 

`	const numberOfActiveValidators = posMethod.getNumberOfActiveValidators(context);`

This always returns `NUMBER_ACTIVE_VALIDATORS` (e.g., 101 in the mainchain), even if the number of validators in current round is smaller, since PoS module state store is agnostic to the number of current active validators. Instead, the number of active validators should be get from the validators module

### Suggested modification

- Make the number of active validators an argument for `getStakeRewardActiveValidators`. The function would look like:

```
export const getStakeRewardActiveValidators = (
	context: ImmutableMethodContext,
	numberOfActiveValidators: bigint,
	defaultReward: bigint,
	minimalRewardActiveValidators: bigint,
) => {
	return (
		BigInt(numberOfActiveValidators) * (defaultReward - minimalRewardActiveValidators)
	);
};
```

(In fact, even the context does not seem to be needed as an argument in this case).

 - Modify the call to `getStakeRewardActiveValidators` from [`getDefaultBlockReward` function](https://github.com/LiskHQ/lisk-sdk/blob/2d04e23b5b172a7b84cdad2669b985a51156e671/framework/src/modules/dynamic_rewards/module.ts#L248) as follows:

Replace [here](https://github.com/LiskHQ/lisk-sdk/blob/2d04e23b5b172a7b84cdad2669b985a51156e671/framework/src/modules/dynamic_rewards/module.ts#L283C39-L283C69)

```
		const stakeRewardActiveValidators = getStakeRewardActiveValidators(
			context,
			this._posMethod,
			defaultReward,
			minimalRewardActiveValidators,
		);
```

by 

```
                numberActiveValidators = len([item for item in validatorParams.validators if item.bftWeight > 0])
		const stakeRewardActiveValidators = getStakeRewardActiveValidators(
			context,
			numberActiveValidators,
			defaultReward,
			minimalRewardActiveValidators,
		);
```

(here I am using pythonic syntax, but hopefully you get the point).

- Add unit tests to check the calculated rewards in case of small set of active validators (e.g., only 8 active) where it is easy to caluclate values at hand and verify results.

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #9024 

### How was it solved?

- Update the logic to use validator method instead of pos method

### How was it tested?

- Fix unit tests

### CODE REVIEW

File: framework/src/modules/dynamic_reward/utils.ts [hunk 1]
```diff
@@ -23,15 +23,16 @@ export const getMinimalRewardActiveValidators = (
 	(defaultReward * BigInt(moduleConfig.factorMinimumRewardActiveValidators)) /
 	DECIMAL_PERCENT_FACTOR;
 
-export const getStakeRewardActiveValidators = (
+export const getStakeRewardActiveValidators = async (
```
Comment (gkoumout) [inline framework/src/modules/dynamic_reward/utils.ts:26]: I think you could avoid using context and validatorMethod (therefor no need to import ValidatorsMethod) and just use `numberActiveValidators` as an argument here. This would also be faster since there is no need to call the validators module here at all. 

Is there any other reason that I am missing to do it like this here?

File: framework/src/modules/dynamic_reward/module.ts [hunk 2]
```diff
@@ -280,9 +280,9 @@ export class DynamicRewardModule extends BaseModule {
 		if (!bftValidator) {
 			throw new Error('Invalid generator. Validator params does not include the validator.');
 		}
-		const stakeRewardActiveValidators = getStakeRewardActiveValidators(
+		const stakeRewardActiveValidators = await getStakeRewardActiveValidators(
 			context,
-			this._posMethod,
+			this._validatorMethod,
```
Comment (gkoumout) [inline framework/src/modules/dynamic_reward/module.ts:285]: Here I would just pass `numberActiveValidators` as an argument, as in the suggestion in the issue description. You can get `numberActiveValidators` from `validatorsParams.validators`, by counting the items with bft weight > 0. 

Is there any reason to do it differently?

**Review by Incede — APPROVED** [review]

File: framework/src/modules/dynamic_reward/endpoint.ts [hunk 3]
```diff
@@ -70,9 +70,9 @@ export class DynamicRewardEndpoint extends RewardEndpoint {
...
 			defaultReward,
 		);
-		const stakeRewardActiveValidators = getStakeRewardActiveValidators(
+		const stakeRewardActiveValidators = await getStakeRewardActiveValidators(
 			context,
-			this._posMethod,
+			this._validatorMethod,
 			defaultReward,
 			minimalRewardActiveValidators,
 		);
```
Comment (gkoumout) [inline framework/src/modules/dynamic_reward/endpoint.ts:78]: Comment about line 88: `roundLength` should be replaced by `numberActiveValidators` (see LIP PR). 

Also, in LIP we use integer division and caclulate the values manually instead of rewardPerSec, not sure if this creates some rounding missmatch, just mentioning so that you can check.

**Review by gkoumout — APPROVED** [review]

File: framework/src/modules/dynamic_reward/endpoint.ts (hunk 3 above)
Comment (shuse2) [reply framework/src/modules/dynamic_reward/endpoint.ts:78]: we keep the roundLength since that's the default behavior, and this needs to count the standby delegate
