### PR TITLE
Serialize the chainID in the peers response

### LINKED ISSUE #8173: chainID not serialized in peers response
### Expected behavior

`chainID` must be a hex string.

### Actual behavior

`chainID` is not properly serialized to hex string.

```
[{"chainID":{"type":"Buffer","data":[4,0,0,0]},"nonce":"65d37a8b8a566772","networkVersion":"1.0","options":{"height":44,"maxHeightPrevoted":0,"blockVersion":2,"lastBlockID":"3f9f41eae0c10cccc5a9cf84431149a226361f93fc7c6a2504f812e6c903d068","legacy":[]},"ipAddress":"127.0.0.1","port":7668,"peerId":"127.0.0.1:7668"}]
```

### Steps to reproduce
- Spin up a local network
  - npm i -g lisk-core@v4.0.0-alpha.14 --registry https://npm.lisk.com
  - lisk-core start -n devnet --api-ipc --api-ws -l info
  - lisk-core start -n devnet --port 7668 --seed-peers 127.0.0.1:7667 -d ~/devnet
- Query the following endpoints:
  - network_getConnectedPeers
  - network_getDisconnectedPeers

### Which version(s) does this affect? (Environment, OS, etc...)
Lisk SDK v6.0.0-alpha.14

### PR DESCRIPTION
**Pull request by mosmartin**
### What was the problem?

This PR resolves #8173

### How was it solved?

Serialize the chainID

### How was it tested?

Existing tests pass ✅

### CODE REVIEW

File: framework/src/engine/network/endpoint.ts [hunk 1]
```diff
@@ -33,10 +33,14 @@ export class Endpoint {
 			const parsedPeer = {
 				...peer,
 			};
+
+			parsedPeer.chainID = parsedPeer.chainID?.toString('hex') as unknown as Buffer;
```
Comment (shuse2) [inline framework/src/engine/network/endpoint.ts:37]: i don't really understand this conversion. It is saying `toString` but type is `Buffer` 🤔 
also, you could do
```
const parsedPeer = {
	...peer,
	chainID: peers.chainID?.toString('hex') ?? '',
};
```

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: framework/src/engine/network/endpoint.ts (hunk 1 above)
Comment (mosmartin) [reply framework/src/engine/network/endpoint.ts:37]: This works too 🙂

**Review by has5aan — APPROVED** [review]

**Review by shuse2 — APPROVED** [review]
