### PR TITLE
Check the error exists or not and then return with proper message

### LINKED ISSUE #3915: Chain comparison is failing when nodes have the same block
### Expected behavior
Chain comparison should pass when nodes have the same block.
### Actual behavior
Chain comparison is failing even when nodes have the same block. Last block is `15910358440661876618` - every node in the netwok have this block.
```
11:41:58.790Z DEBUG lisk-framework: Perform chain recovery due to poor consensus
11:41:58.791Z  WARN lisk-framework: Chain comparison failed, starting recovery
11:41:58.791Z  WARN lisk-framework:
    Deleting last block { id: '15910358440661876618',
      version: 1,
      timestamp: 97979220,
      height: 19,
      previousBlock: '12630086668773113114',
      numberOfTransactions: 0,
      totalAmount: 0,
      totalFee: 0,
      reward: 0,
      payloadLength: 0,
      payloadHash:
       'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      generatorPublicKey:
       '5f6cc5a8aac752d37c676b0d46a798f7625e37dfa1e96091983274e04ab7ffe2',
      generatorId: '2037513790649430470L',
      blockSignature:
       '64fe8a9ffd3375e580804a1de7283857ae6964518cdbefe6bbc9e28ffe0f74cf65fc1ee1c43543e59e86419392718e5c11c5e226f4e621f46b125908f1094c07',
      confirmations: 0,
      totalForged: '0',
      transactions: [] }
11:41:58.816Z DEBUG lisk-framework: Performing backward tick
11:41:58.827Z DEBUG lisk-framework:
    Application state { os: 'linux4.15.0-54-generic',
      version: '2.0.0-rc.0',
      wsPort: 5000,
      httpPort: 4000,
      minVersion: '1.1.0-rc.0',
      protocolVersion: '1.1',
      height: 18,
      nethash:
       '198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d',
      broadhash:
       '2ca25a3d7e2eef75e3b7286e5ce69b462a50a88acbe7f2133aae75f3862413b0',
      nonce: 'D5HpiAdnmVqLJCbS' }
11:41:58.862Z  INFO lisk-framework: Recovery complete, new last block 12630086668773113114
11:41:58.869Z ERROR lisk-framework: Failed chain recovery after failing to load blocks while network consensus was low. null
11:41:58.872Z DEBUG lisk-framework:
    Application state { os: 'linux4.15.0-54-generic',
      version: '2.0.0-rc.0',
      wsPort: 5000,
      httpPort: 4000,
      minVersion: '1.1.0-rc.0',
      protocolVersion: '1.1',
      height: 18,
      nethash:
       '198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d',
      broadhash:
       '2ca25a3d7e2eef75e3b7286e5ce69b462a50a88acbe7f2133aae75f3862413b0',
      nonce: 'D5HpiAdnmVqLJCbS' }
11:41:58.901Z DEBUG lisk-framework: Establishing broadhash consensus after sync: 0 %
11:41:58.902Z  INFO lisk-framework: Finished sync
```
Also this message is weird because chain recovery was succesfull:
```
11:41:58.869Z ERROR lisk-framework: Failed chain recovery after failing to load blocks while network consensus was low. null
```
### Steps to reproduce
Sync with alphanet (`jenkinsnet-19`).
### Which version(s) does this affect? (Environment, OS, etc...)
`release/2.0.0`

### PR DESCRIPTION
**Pull request by ishantiw**
### What was the problem?

Chain comparison is failing even when nodes have the same block.

we get the wierd error,
```
11:41:58.869Z ERROR lisk-framework: Failed chain recovery after failing to load blocks while network consensus was low. null
```

### How did I fix it?

Check if the error exists or not and form a proper error message.

The below error will be resolved in #3612 
```
 Error: Error loading blocks: Transaction: 5608333921440497612 failed at .multisignature.keysgroup: '.multisignature.keysgroup' should NOT have fewer than 1 items
```
### How to test it?

Sync with alphanet `(jenkinsnet-19).`

### Review checklist

* The PR resolves #3915
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: framework/src/modules/chain/submodules/loader.js [hunk 1]
```diff
@@ -813,21 +813,28 @@ __private.loadBlocksFromNetwork = function(cb) {
 						modules.blocks.process.loadBlocksFromNetwork(
 							(loadBlocksFromNetworkErr, lastValidBlock) => {
 								if (loadBlocksFromNetworkErr) {
+									library.logger.error(
+										loadBlocksFromNetworkErr instanceof Error
```
Comment (shuse2) [inline framework/src/modules/chain/submodules/loader.js]: `convertErrorsToString` in the helper can be used for this purpose

Comment (ishantiw) [reply framework/src/modules/chain/submodules/loader.js]: We want to pass an error as a first argument to the logger for Bunyan whereas `convertErrorsToString`  always returns a string. Otherwise, it will simply concatenate stringified error with the message in the second argument.

**Comment by ishantiw** [comment]
@4miners There is no unit test for `loader.js` at all for which I opened an issue during technical debt. https://github.com/LiskHQ/lisk-sdk/issues/3781. Should we handle it separately in that issue?

File: framework/src/modules/chain/submodules/loader.js [hunk 2]
```diff
@@ -813,21 +813,28 @@ __private.loadBlocksFromNetwork = function(cb) {
...
+											? loadBlocksFromNetworkErr
+											: new Error(loadBlocksFromNetworkErr),
+										'Failed chain recovery after failing to load blocks'
```
Comment (nazarhussain) [inline framework/src/modules/chain/submodules/loader.js]:
```suggestion
										'Chain recovery failed after failing to load blocks from network'
```

File: framework/src/modules/chain/submodules/loader.js [hunk 3]
```diff
@@ -813,21 +813,28 @@ __private.loadBlocksFromNetwork = function(cb) {
...
+									);
 									// If comparison failed and current consensus is low - perform chain recovery
 									if (modules.peers.isPoorConsensus()) {
 										library.logger.debug(
 											'Perform chain recovery due to poor consensus'
 										);
 										return modules.blocks.chain.recoverChain(recoveryError => {
+											if (recoveryError) {
+												waterCb(
+													`Failed chain recovery after failing to load blocks while network consensus was low. ${recoveryError}`
```
Comment (nazarhussain) [inline framework/src/modules/chain/submodules/loader.js]:
```suggestion
													`Chain recovery failed after failing to load blocks while network consensus was low. ${recoveryError}`
```

File: framework/src/modules/chain/submodules/loader.js [hunk 4]
```diff
@@ -813,21 +813,28 @@ __private.loadBlocksFromNetwork = function(cb) {
...
+												);
+											}
 											waterCb(
-												`Failed chain recovery after failing to load blocks while network consensus was low. ${recoveryError}`
+												`Failed chain recovery after failing to load blocks. ${loadBlocksFromNetworkErr}`
```
Comment (nazarhussain) [inline framework/src/modules/chain/submodules/loader.js]:
```suggestion
												`Chain recovery failed after failing to load blocks ${loadBlocksFromNetworkErr}`
```

**Comment by nazarhussain** [comment]
Other then just log error messages LGTM

**Comment by ishantiw** [comment]
@4miners Added the unit test for the specific error that has been updated in this PR

**Comment by 4miners** [comment]
Unit tests failed because of deadlock:
```
09:32:32        ✓ should call _getResults with proper param for extended=false (65ms)
09:32:32  { error: deadlock detected
09:32:32      at Connection.parseE (/home/lisk/workspace/lisk-sdk-framework_PR-3924/node_modules/pg/lib/connection.js:554:11)
09:32:32      at Connection.parseMessage (/home/lisk/workspace/lisk-sdk-framework_PR-3924/node_modules/pg/lib/connection.js:379:19)
09:32:32      at Socket.<anonymous> (/home/lisk/workspace/lisk-sdk-framework_PR-3924/node_modules/pg/lib/connection.js:119:22)
09:32:32      at Socket.emit (events.js:189:13)
09:32:32      at Socket.EventEmitter.emit (domain.js:441:20)
09:32:32      at addChunk (_stream_readable.js:284:12)
09:32:32      at readableAddChunk (_stream_readable.js:265:11)
09:32:32      at Socket.Readable.push (_stream_readable.js:220:10)
09:32:32      at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
09:32:32    name: 'error',
09:32:32    length: 337,
09:32:32    severity: 'ERROR',
09:32:32    code: '40P01',
09:32:32    detail:
09:32:32     'Process 28691 waits for AccessExclusiveLock on relation 32898950 of database 32898740; blocked by process 28543.\nProcess 28543 waits for AccessShareLock on relation 32898928 of database 32898740; blocked by process 28691.',
09:32:32    hint: 'See server log for query details.',
09:32:32    position: undefined,
09:32:32    internalPosition: undefined,
09:32:32    internalQuery: undefined,
09:32:32    where: undefined,
09:32:32    schema: undefined,
09:32:32    table: undefined,
09:32:32    column: undefined,
09:32:32    dataType: undefined,
09:32:32    constraint: undefined,
09:32:32    file: 'deadlock.c',
09:32:32    line: '1140',
09:32:32    routine: 'DeadLockReport' }
09:32:32  error error: deadlock detected
09:32:32  error task(db:seed:reset): TRUNCATE TABLE "blocks" CASCADE
09:32:32        - should accept "tx" as last parameter and pass to adapter.executeFile
09:32:32        - should not change any of the provided parameter
09:32:32        filters
09:32:32        ✓ should resolve promise without any error if no data is passed
09:32:33          ✓ should have only specific filters
09:32:33        ✓ should call _getResults with proper param for extended=true
09:32:33        1) "after each" hook for "should call adapter.executeFile with proper param for extended=true"
09:32:33  
09:32:33  
09:32:33    13 passing (18s)
09:32:33    1 failing
09:32:33  
09:32:33    1) Transaction
09:32:33         "after each" hook for "should call adapter.executeFile with proper param for extended=true":
09:32:33       BatchError: deadlock detected
```
It doesn't look like this is related with the changes in the PR, however I add comment for reference.
