### PR TITLE
Align the token support methods to the lip

### LINKED ISSUE #8505: Token support methods are not aligned with LIP
### Expected behavior
Below functions should follow the behavior LIP specify

* [supportAllTokensFromChainID](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0051.md#supportalltokensfromchainid) (SDK implementation [here](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/modules/token/method.ts#L672))
* [removeAllTokensSupportFromChainID](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0051.md#removealltokenssupportfromchainid) (SDK implementation [here](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/modules/token/method.ts#L680))
* [removeSupportTokenID](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0051.md#removesupport) (SDK implementation [here](https://github.com/LiskHQ/lisk-sdk/blob/development/framework/src/modules/token/method.ts#L693))

### Actual behavior
Event is emitted even when it returns or error

### Steps to reproduce
N/A

### Which version(s) does this affect? (Environment, OS, etc...)
6.0.0-beta.1

### PR DESCRIPTION
**Pull request by mosmartin**
### What was the problem?

This PR resolves #8505

### How was it solved?

Aligned the token support methods to the lip

### How was it tested?

Added unit tests

### CODE REVIEW

File: framework/src/modules/token/method.ts [hunk 1]
```diff
@@ -703,8 +750,38 @@ export class TokenMethod extends BaseMethod {
...
+
+		if (allSupportedTokenEntries) {
+			throw new Error('All tokens are supported.');
+		}
+
+		if (tokenID.equals(this.getMainchainTokenID()) || chainID.equals(this._config.ownChainID)) {
+			throw new Error('Cannot remove support for the specified token.');
+		}
+
+		const supportedTokens = await this._supportedTokens(methodContext, chainID);
```
Comment (shuse2) [inline framework/src/modules/token/method.ts:766]: same as above. this will throw if key doesn't exist.

File: framework/src/modules/token/method.ts [hunk 2]
```diff
@@ -703,8 +750,38 @@ export class TokenMethod extends BaseMethod {
...
+
+			const tokenIndex = supportedTokens.supportedTokenIDs.indexOf(tokenID);
+
+			if (tokenIndex === -1) {
+				supportedTokens.supportedTokenIDs.splice(tokenIndex, 1);
+				await this.stores.get(SupportedTokensStore).set(methodContext, chainID, supportedTokens);
+
+				if (supportedTokens.supportedTokenIDs.length === 0) {
+					await this.stores.get(SupportedTokensStore).del(methodContext, chainID);
+				}
```
Comment (shuse2) [inline framework/src/modules/token/method.ts:781]: isn't it better to execute this one of them? ie) when deleting, no point to `set`

File: framework/src/modules/token/method.ts [hunk 3]
```diff
@@ -703,8 +750,38 @@ export class TokenMethod extends BaseMethod {
 		this.events.get(TokenIDSupportedEvent).log(methodContext, tokenID);
 	}
 
-	public async removeSupportTokenID(methodContext: MethodContext, tokenID: Buffer): Promise<void> {
-		await this.stores.get(SupportedTokensStore).removeSupportForToken(methodContext, tokenID);
```
Comment (shuse2) [inline framework/src/modules/token/method.ts:707]: if we don't need store function like `removeSupportForToken` we can remove and move the unit tests to method

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: framework/src/modules/token/method.ts [hunk 4]
```diff
@@ -686,15 +691,57 @@ export class TokenMethod extends BaseMethod {
...
+
+		const supportedTokens = await this._supportedTokens(methodContext, chainID);
+
+		if (supportedTokens) {
+			await this.stores
+				.get(SupportedTokensStore)
+				.set(methodContext, chainID, { supportedTokenIDs: [] });
+		} else {
+			const supportedTokensData: SupportedTokensStoreData = {
+				supportedTokenIDs: [codec.encode(supportedTokensStoreSchema, { supportedTokenIDs: [] })],
```
[the remark this answers is not in the document]
Comment (bobanm) [reply framework/src/modules/token/method.ts:712]: I think the way the `else` branch is defined in [LIP-0051](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0051.md#supportalltokensfromchainid) is either incorrect, or very confusing? 🤔

[the remark this answers is not in the document]
Comment (shuse2) [reply framework/src/modules/token/method.ts:712]: i think the LIP is consistent with other places?

File: framework/src/modules/token/method.ts [hunk 5]
```diff
@@ -686,15 +691,57 @@ export class TokenMethod extends BaseMethod {
...
+			};
+
+			await this.stores.get(SupportedTokensStore).set(methodContext, chainID, supportedTokensData);
+		}
```
[the remark this answers is not in the document]
Comment (mosmartin) [reply framework/src/modules/token/method.ts:716]: According to the LIP (see below)

```py
if supportedTokens(chainID) exists:
        # Set the value of the store entry to the empty array.
        supportedTokens(chainID) = {"supportedTokenIDs": []}

    else:
        create an entry in the supported tokens substore with
            key = chainID
            value = encode(
                schema=supportedTokensSchema,
                object={"supportedTokenIDs": []}
```

the value is encoded?

[the remark this answers is not in the document]
Comment (mosmartin) [reply framework/src/modules/token/method.ts:716]: Should the lip be updated as it's definition will lead to some confusion...esp during reviews?

```py
if supportedTokens(chainID) exists:
        # Set the value of the store entry to the empty array.
        supportedTokens(chainID) = {"supportedTokenIDs": []}

    else:
        create an entry in the supported tokens substore with
            key = chainID
            value = encode(
                schema=supportedTokensSchema,
                object={"supportedTokenIDs": []}

File: framework/src/modules/token/method.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (mosmartin) [reply framework/src/modules/token/method.ts:712]: The LIP definition requires an update in this case.

File: framework/src/modules/token/method.ts [hunk 6]
```diff
@@ -686,15 +691,57 @@ export class TokenMethod extends BaseMethod {
...
+
+		if (chainID.equals(this._config.ownChainID)) {
+			throw new Error(
+				'Invalid operation. All tokens from all the specified chain should be supported.',
+			);
+		}
+
+		const supportedTokens = await this._supportedTokens(methodContext, chainID);
+
+		if (!supportedTokens) {
```
[the remark this answers is not in the document]
Comment (mosmartin) [reply framework/src/modules/token/method.ts:739]: The lip doesn't define an error message 🤔

```py
if supportedTokens(chainID) does not exist:
        return

File: framework/src/modules/token/method.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (shuse2) [reply framework/src/modules/token/method.ts:716]: I think all the LIPs are consistently using this format? When creation, defining key /value with schema, and when updating, just inserting?

File: framework/src/modules/token/method.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (shuse2) [reply framework/src/modules/token/method.ts:712]: I think LIP definition is correct

File: framework/src/modules/token/method.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (shuse2) [reply framework/src/modules/token/method.ts:739]: I mean if the supportedToken for the `chainID` doesn't exist `await this._supportedTokens(methodContext, chainID);` function will throw error, and never reach this condition

[the remark this answers is not in the document]
Comment (mosmartin) [reply framework/src/modules/token/method.ts:739]: In this case then, there is no need for implementing the check as defined in the LIP.

File: framework/src/modules/token/method.ts (hunk 3 above)
Comment (mosmartin) [reply framework/src/modules/token/method.ts:707]: I am not sure if it's needed or not but had to rename it from `removeSupportTokenID` to `removeSupport` as based on our prev discussion, the idea was to align the function names as well.

image
links to
image

File: framework/src/modules/token/method.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (shuse2) [reply framework/src/modules/token/method.ts:739]: i think LIP wants to return without throwing error, so in this case it should check and return without throwing

File: framework/src/modules/token/method.ts (hunk 3 above)
Comment (shuse2) [reply framework/src/modules/token/method.ts:707]: i meant `await this.stores.get(SupportedTokensStore).removeSupportForToken` this function on `Store` which is robably not used anymore

File: framework/src/modules/token/method.ts [hunk 7]
```diff
@@ -689,15 +693,47 @@ export class TokenMethod extends BaseMethod {
 		methodContext: MethodContext,
 		chainID: Buffer,
 	): Promise<void> {
-		await this.stores.get(SupportedTokensStore).supportChain(methodContext, chainID);
+		const allSupportedTokenEntries = await this._isAllTokensSupported(methodContext);
```
Comment (shuse2) [inline framework/src/modules/token/method.ts:696]:
```suggestion
		const allTokensSupported = await this._isAllTokensSupported(methodContext);
```

File: framework/src/modules/token/method.ts [hunk 8]
```diff
@@ -734,4 +799,24 @@ export class TokenMethod extends BaseMethod {
...
+	private async _getSupportedTokens(
+		methodContext: MethodContext,
+		chainID: Buffer,
+	): Promise<SupportedTokensStoreData> {
+		const supportedTokensStore = this.stores.get(SupportedTokensStore);
+		const supportedTokens = await supportedTokensStore.get(methodContext, chainID);
+
+		if (!supportedTokens) {
+			throw new Error('No supported tokens found.');
+		}
```
Comment (shuse2) [inline framework/src/modules/token/method.ts:818]: as mentioned before, `await supportedTokensStore.get` will throw if `chainID` doesn't exist

File: framework/src/modules/token/method.ts [hunk 9]
```diff
@@ -689,15 +693,47 @@ export class TokenMethod extends BaseMethod {
...
+			return;
+		}
+
+		const supportedTokens = await this._getSupportedTokens(methodContext, chainID);
+
+		if (supportedTokens) {
+			await this.stores
+				.get(SupportedTokensStore)
+				.set(methodContext, chainID, { supportedTokenIDs: [] });
+		}
```
Comment (shuse2) [inline framework/src/modules/token/method.ts:712]:
```
await this.stores
				.get(SupportedTokensStore)
				.set(methodContext, chainID, { supportedTokenIDs: [] });
```
Regardless of pre-existing data or not, i think we can always overwrite with this

File: framework/src/modules/token/method.ts [hunk 10]
```diff
@@ -689,15 +693,47 @@ export class TokenMethod extends BaseMethod {
...
+
 		this.events.get(AllTokensFromChainSupportedEvent).log(methodContext, chainID);
 	}
 
 	public async removeAllTokensSupportFromChainID(
 		methodContext: MethodContext,
 		chainID: Buffer,
 	): Promise<void> {
-		await this.stores.get(SupportedTokensStore).removeSupportForChain(methodContext, chainID);
+		const allSupportedTokenEntries = await this._isAllTokensSupported(methodContext);
```
Comment (shuse2) [inline framework/src/modules/token/method.ts:721]:
```suggestion
		const allTokensSupported = await this._isAllTokensSupported(methodContext);
```

File: framework/src/modules/token/method.ts [hunk 11]
```diff
@@ -689,15 +693,47 @@ export class TokenMethod extends BaseMethod {
...
+			throw new Error('Invalid operation. All tokens from all chains are supported.');
+		}
+
+		if (chainID.equals(this._config.ownChainID)) {
+			throw new Error(
+				'Invalid operation. All tokens from all the specified chain should be supported.',
+			);
+		}
+
+		await this._getSupportedTokens(methodContext, chainID);
```
Comment (shuse2) [inline framework/src/modules/token/method.ts:733]: this is not same as below
```
if supportedTokens(chainID) does not exist:
        return
```

File: framework/src/modules/token/method.ts [hunk 12]
```diff
@@ -706,8 +742,37 @@ export class TokenMethod extends BaseMethod {
 		this.events.get(TokenIDSupportedEvent).log(methodContext, tokenID);
 	}
 
-	public async removeSupportTokenID(methodContext: MethodContext, tokenID: Buffer): Promise<void> {
-		await this.stores.get(SupportedTokensStore).removeSupportForToken(methodContext, tokenID);
+	public async removeSupport(methodContext: MethodContext, tokenID: Buffer): Promise<void> {
+		const [chainID] = splitTokenID(tokenID);
+
+		const allSupportedTokenEntries = await this._isAllTokensSupported(methodContext);
```
Comment (shuse2) [inline framework/src/modules/token/method.ts:748]:
```suggestion
		const allTokensSupported = await this._isAllTokensSupported(methodContext);
```

File: framework/src/modules/token/method.ts [hunk 13]
```diff
@@ -706,8 +742,37 @@ export class TokenMethod extends BaseMethod {
...
+
+		if (allSupportedTokenEntries) {
+			throw new Error('All tokens are supported.');
+		}
+
+		if (tokenID.equals(this.getMainchainTokenID()) || chainID.equals(this._config.ownChainID)) {
+			throw new Error('Cannot remove support for the specified token.');
+		}
+
+		const supportedTokens = await this._getSupportedTokens(methodContext, chainID);
```
Comment (shuse2) [inline framework/src/modules/token/method.ts:758]: this return value is not boolean

File: framework/src/modules/token/method.ts [hunk 14]
```diff
@@ -706,8 +742,37 @@ export class TokenMethod extends BaseMethod {
...
+
+		if (supportedTokens) {
+			if (supportedTokens.supportedTokenIDs.length === 0) {
+				throw new Error('All tokens from the specified chain are supported.');
+			}
+
+			const tokenIndex = supportedTokens.supportedTokenIDs.indexOf(tokenID);
+
+			if (tokenIndex === -1) {
```
Comment (shuse2) [inline framework/src/modules/token/method.ts:767]: I think LIP mentions when token exists in `supportedTokenIDs`

File: framework/test/unit/modules/token/method.spec.ts [hunk 15]
```diff
@@ -1225,11 +1230,61 @@ describe('token module', () => {
 	});
 
 	describe('supportAllTokensFromChainID', () => {
-		it('should call support chain', async () => {
-			await expect(
-				method.supportAllTokensFromChainID(methodContext, Buffer.from([1, 2, 3, 4])),
-			).resolves.toBeUndefined();
+		it('should return early if all supported token entries is truthy', async () => {
+			jest.spyOn(method as any, '_isAllTokensSupported').mockResolvedValue(true);
```
Comment (shuse2) [inline framework/test/unit/modules/token/method.spec.ts:1234]: Overall in the test, instead of stubbing the method, it's better to use real function. I think most of the problem on the source code should be identified by that

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: framework/src/modules/token/method.ts (hunk 13 above)
Comment (mosmartin) [reply framework/src/modules/token/method.ts:758]: Is it supposed to be a boolean?

Comment (gkoumout) [reply framework/src/modules/token/method.ts:758]: `supportedTokens(chainID)` is just a notation, not an actual variable. It is used to make the LIP more readable. 

image

File: framework/src/modules/token/method.ts [hunk 16]
```diff
@@ -706,8 +742,37 @@ export class TokenMethod extends BaseMethod {
...
+			throw new Error('All tokens are supported.');
+		}
+
+		if (tokenID.equals(this.getMainchainTokenID()) || chainID.equals(this._config.ownChainID)) {
+			throw new Error('Cannot remove support for the specified token.');
+		}
+
+		const supportedTokens = await this._getSupportedTokens(methodContext, chainID);
+
+		if (supportedTokens) {
```
Comment (gkoumout) [inline framework/src/modules/token/method.ts:760]: Given the comment above, this should be changed. This code would be run unless in line 758 there was not error due to not having a store entry. Again, I guess try-except is the way to go, but you know better than me.

File: framework/src/modules/token/method.ts [hunk 17]
```diff
@@ -734,4 +799,28 @@ export class TokenMethod extends BaseMethod {
...
+		return supportedTokensStore.has(methodContext, ALL_SUPPORTED_TOKENS_KEY);
+	}
+
+	private async _getSupportedTokens(
+		methodContext: MethodContext,
+		chainID: Buffer,
+	): Promise<SupportedTokensStoreData> {
+		if (chainID.length === 0 || !chainID) {
+			throw new Error('Chain ID is required.');
+		}
```
Comment (shuse2) [inline framework/src/modules/token/method.ts:815]: why is this check necessary? by typescript, chainID is never undefined, and if length needs to be checked, shouldnt we check if the chainID has 4bytes?

File: framework/src/modules/token/method.ts (hunk 8 above)
Comment (shuse2) [reply framework/src/modules/token/method.ts:822]: this is still not addressed

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: framework/src/modules/token/method.ts [hunk 18]
```diff
@@ -689,15 +689,55 @@ export class TokenMethod extends BaseMethod {
...
+
+		try {
+			await this.stores.get(SupportedTokensStore).get(methodContext, chainID);
+		} catch (err) {
+			if (err instanceof NotFoundError) {
+				return;
+			}
+
+			throw err;
+		}
```
Comment (shuse2) [inline framework/src/modules/token/method.ts:737]:
```suggestion
		const chainSupported = await this.stores.get(SupportedTokensStore).has(methodContext, chainID);
		if (!chainSupported) {
			return;
		}
```

File: framework/src/modules/token/method.ts [hunk 19]
```diff
@@ -706,8 +746,49 @@ export class TokenMethod extends BaseMethod {
...
+
+		if (allTokensSupported) {
+			throw new Error('All tokens are supported.');
+		}
+
+		if (tokenID.equals(this.getMainchainTokenID()) || chainID.equals(this._config.ownChainID)) {
+			throw new Error('Cannot remove support for the specified token.');
+		}
+
+		try {
```
Comment (shuse2) [inline framework/src/modules/token/method.ts:764]:
```
const chainSupported = await this.stores.get(SupportedTokensStore).has(methodContext, chainID);
if (!chainSupported) {
	this.events.get(TokenIDSupportRemovedEvent).log(methodContext, tokenID);
	return;
}
```
it's better to use `has` function than handling error here as well. Also, from the LIP i think it suppose to log the event in case chain is not supported as well

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: framework/src/modules/token/method.ts (hunk 19 above)
Comment (mosmartin) [reply framework/src/modules/token/method.ts:759]: @shuse2, according to the LIP, an event is `only` emitted on successful removal. An error is thrown instead `if (!chainSupported) `

Comment (shuse2) [reply framework/src/modules/token/method.ts:759]: Looking at https://github.com/LiskHQ/lips/blob/main/proposals/lip-0051.md#removesupport
```
if supportedTokens(chainID) exists:
```
and 
```
emitEvent(
        module=MODULE_NAME_TOKEN,
        name=EVENT_NAME_TOKEN_ID_SUPPORT_REMOVED,
        data={"tokenID": tokenID},
        topics=[tokenID]
    )
```
are in the same indentation. so it looks like if chain is not supported, it will still log the event

File: framework/src/modules/token/method.ts [hunk 20]
```diff
@@ -706,9 +744,57 @@ export class TokenMethod extends BaseMethod {
...
+			this.events.get(TokenIDSupportRemovedEvent).log(methodContext, tokenID);
+			return;
+		}
+
+		try {
+			const supportedTokens = await this.stores
+				.get(SupportedTokensStore)
+				.get(methodContext, chainID);
+
+			if (supportedTokens) {
```
Comment (shuse2) [inline framework/src/modules/token/method.ts:776]: there is no case where supportedTokens return `undefined` or `null` so this `if` is not necessary

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: framework/src/modules/token/method.ts [hunk 21]
```diff
@@ -706,9 +744,45 @@ export class TokenMethod extends BaseMethod {
...
+
+		const tokenIndex = supportedTokens.supportedTokenIDs.indexOf(tokenID);
+
+		if (tokenIndex !== -1) {
+			supportedTokens.supportedTokenIDs.splice(tokenIndex, 1);
+
+			if (supportedTokens.supportedTokenIDs.length === 0) {
+				await this.stores.get(SupportedTokensStore).del(methodContext, chainID);
+			}
+		}
```
Comment (shuse2) [inline framework/src/modules/token/method.ts:785]: it's missing to log the event at the end (and also test for this)

**Review by shuse2 — APPROVED** [review]

**Review by vjaiman — APPROVED** [review]
Looks good to me.
