### PR TITLE
Fix white/fixed/blacklist config and manage it in peer pool for connections- Closes#4197#4213#4214

### LINKED ISSUE #4197: Issue with fixed/white peers config
### Expected behavior

1. Adding fixed peers in config file causes the node to crash.
2. When checking if a fixed peer is in peerMap, we should use the id instead of checking by reference because otherwise it will always be false: https://github.com/LiskHQ/lisk-sdk/blob/e542623b28e88f6a16a85971af212285b133f145/elements/lisk-p2p/src/peer_pool.ts#L383
3. Write a unit/integration test to ensure if the config changes work
### Actual behavior

The new fixed peers config doesn't work.
The crash error is:

```
Network initialization { message: 'Cannot read property \'split\' of undefined',
      stack:
       'TypeError: Cannot read property \'split\' of undefined\n    at Object.exports.getIPGroup (/Users/ishantiwari/Documents/lisk-repos/sdk/test-sdk/lisk-sdk/elements/lisk-p2p/dist-node/utils/misc.js:16:29)\n    at Object.exports.isLocal (/Users/ishantiwari/Documents/lisk-repos/sdk/test-sdk/lisk-sdk/elements/lisk-p2p/dist-node/utils/misc.js:49:40)\n    at Object.exports.getNetwork (/Users/ishantiwari/Documents/lisk-repos/sdk/test-sdk/lisk-sdk/elements/lisk-p2p/dist-node/utils/misc.js:51:17)\n    at Object.exports.getNetgroup (/Users/ishantiwari/Documents/lisk-repos/sdk/test-sdk/lisk-sdk/elements/lisk-p2p/dist-node/utils/misc.js:65:29)\n    at new Peer (/Users/ishantiwari/Documents/lisk-repos/sdk/test-sdk/lisk-sdk/elements/lisk-p2p/dist-node/peer/base.js:33:34)\n    at new OutboundPeer (/Users/ishantiwari/Documents/lisk-repos/sdk/test-sdk/lisk-sdk/elements/lisk-p2p/dist-node/peer/outbound.js:11:9)\n    at PeerPool.addOutboundPeer (/Users/ishantiwari/Documents/lisk-repos/sdk/test-sdk/lisk-sdk/elements/lisk-p2p/dist-node/peer_pool.js:209:22)\n    at forEach (/Users/ishantiwari/Documents/lisk-repos/sdk/test-sdk/lisk-sdk/elements/lisk-p2p/dist-node/peer_pool.js:184:24)\n    at Array.forEach (<anonymous>)\n    at PeerPool.triggerNewConnections (/Users/ishantiwari/Documents/lisk-repos/sdk/test-sdk/lisk-sdk/elements/lisk-p2p/dist-node/peer_pool.js:179:56)\n    at P2P._startPopulator (/Users/ishantiwari/Documents/lisk-repos/sdk/test-sdk/lisk-sdk/elements/lisk-p2p/dist-node/p2p.js:394:24)\n    at P2P.start (/Users/ishantiwari/Documents/lisk-repos/sdk/test-sdk/lisk-sdk/elements/lisk-p2p/dist-node/p2p.js:453:18)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
```

### Steps to reproduce

Run on testnet with fixed peers in config file.

### Which version(s) does this affect? (Environment, OS, etc...)

SDK 2.3

### PR DESCRIPTION
**Pull request by ishantiw**
### What was the problem?

- Adding fixed/blacklist/whitelist peers in config file causes the node to crash
- Whitelisted peers should not be evicted through inbound eviction mechanism.
- We should not disconnect or evict with a fixed peer even during the shuffling.

### How did I solve it?

- Valid schema in config file for different lists
- Pass white/black/fixed list to peerpool to manage connections based on these lists

### How to manually test it?

Run the app and use the list to see if the particular behavior of a peer list works or not

### Review checklist

- [x] The PR resolves #4197 #4213 #4214  
- [ ] All new code is covered with unit tests
- [ ] Relevant integration / functional tests are added
- [x] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [ ] Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-p2p/src/peer_pool.ts [hunk 1]
```diff
@@ -398,17 +402,17 @@ export class PeerPool extends EventEmitter {
 		// Try to connect to disconnected peers without including the fixed ones which are specially treated thereafter
 		const disconnectedNewPeers = newPeers.filter(
 			peer =>
-				!this._peerMap.has(constructPeerIdFromPeerInfo(peer)) ||
+				!this._peerMap.get(constructPeerIdFromPeerInfo(peer)) ||
```
Comment (shuse2) [inline elements/lisk-p2p/src/peer_pool.ts]: why change to `get`? in this case `has` seems more suitable

File: elements/lisk-p2p/src/peer_pool.ts [hunk 2]
```diff
@@ -597,7 +601,13 @@ export class PeerPool extends EventEmitter {
 	}
 
 	private _selectPeersForEviction(): Peer[] {
-		const peers = [...this.getPeers(InboundPeer)];
+		const peers = [...this.getPeers(InboundPeer)].filter(peer => {
+			const found = this._peerLists.whitelisted.find(
```
Comment (shuse2) [inline elements/lisk-p2p/src/peer_pool.ts]:
```
const found = !!this._peerLists.whitelisted.find(
	whitePeer => constructPeerIdFromPeerInfo(whitePeer) === peer.id,
);
return !found;
```
is probably fine? i could be even one line, but not so readable too

File: elements/lisk-p2p/src/peer_pool.ts [hunk 3]
```diff
@@ -655,7 +665,15 @@ export class PeerPool extends EventEmitter {
...
 
 		if (kind === OutboundPeer) {
-			const selectedPeer = shuffle(peers)[0];
+			const selectedPeer = shuffle(
+				peers.filter(peer => {
+					const found = this._peerLists.fixedPeers.find(
+						fixedPeer => constructPeerIdFromPeerInfo(fixedPeer) === peer.id,
+					);
+
+					return found ? false : true;
```
Comment (shuse2) [inline elements/lisk-p2p/src/peer_pool.ts]: sane as avove

File: framework/src/modules/network/defaults/config.js [hunk 4]
```diff
@@ -52,27 +52,63 @@ const defaultConfig = {
...
 		fixedPeers: {
 			type: 'array',
 			items: {
-				type: 'string',
-				format: 'ip',
+				type: 'object',
+				properties: {
+					ip: {
+						type: 'string',
+						format: 'ipOrFQDN',
```
Comment (shuse2) [inline framework/src/modules/network/defaults/config.js]: do we allow FQDN? I think we only check for the seed peers, same for below

File: framework/src/modules/network/defaults/config.js [hunk 5]
```diff
@@ -52,27 +52,63 @@ const defaultConfig = {
 		blacklistedPeers: {
 			type: 'array',
 			items: {
-				type: 'string',
-				format: 'ip',
+				type: 'object',
+				properties: {
+					ip: {
+						type: 'string',
+						format: 'ipOrFQDN',
```
Comment (shuse2) [inline framework/src/modules/network/defaults/config.js]: wasn't blackList suppose to be list of IPs not including port?

File: elements/lisk-p2p/src/peer_pool.ts [hunk 6]
```diff
@@ -398,17 +402,17 @@ export class PeerPool extends EventEmitter {
 		// Try to connect to disconnected peers without including the fixed ones which are specially treated thereafter
 		const disconnectedNewPeers = newPeers.filter(
 			peer =>
-				!this._peerMap.has(constructPeerIdFromPeerInfo(peer)) ||
+				!this._peerMap.get(constructPeerIdFromPeerInfo(peer)) ||
 				!fixedPeers.includes(peer),
```
Comment (jondubois) [inline elements/lisk-p2p/src/peer_pool.ts]: We should check using peer id instead of by peer object reference.

File: framework/src/modules/network/defaults/config.js (hunk 5 above)
Comment (ManuGowda) [reply framework/src/modules/network/defaults/config.js]: think to have a consistent definition of peer makes it clear for usability and configuration.

Comment (shuse2) [reply framework/src/modules/network/defaults/config.js]: FQDN cannot be used for these things.
Seed peers are only used at the beginning, therefore we converted to the ip at the beginning.
However, other ip are the runtime validation, and we should not use the DNS resolver.

Comment (ishantiw) [reply framework/src/modules/network/defaults/config.js]: Yes, I have reverted the changes to use only IP for blacklist. For the seedPeers makes sense to use FQDN because we have seed peers by default in the config when someone starts a node whereas for the fixed and white list are optional lists that will be used by the user for their use-cases.

File: elements/lisk-p2p/src/peer_pool.ts [hunk 7]
```diff
@@ -602,12 +606,13 @@ export class PeerPool extends EventEmitter {
 
 	private _selectPeersForEviction(): Peer[] {
 		const peers = [...this.getPeers(InboundPeer)].filter(peer => {
-			const found = this._peerLists.whitelisted.find(
+			const found = !!this._peerLists.whitelisted.find(
```
Comment (diego-G) [inline elements/lisk-p2p/src/peer_pool.ts]: This is hard to read. Is there any way to improve readability here?

File: elements/lisk-p2p/src/p2p.ts [hunk 8]
```diff
@@ -897,6 +898,10 @@ export class P2P extends EventEmitter {
 			}
 		});
 
+		// According to LIP, add whitelist peers to triedPeer by upgrading them initially.
+		this._sanitizedPeerLists.whitelisted.forEach(whitelistPeer =>
```
Comment (diego-G) [inline elements/lisk-p2p/src/p2p.ts]: Is it possible to cover it by any integration test?

File: elements/lisk-p2p/src/peer_pool.ts [hunk 9]
```diff
@@ -597,7 +605,14 @@ export class PeerPool extends EventEmitter {
 	}
 
 	private _selectPeersForEviction(): Peer[] {
-		const peers = [...this.getPeers(InboundPeer)];
+		const peers = [...this.getPeers(InboundPeer)].filter(peer => {
```
Comment (diego-G) [inline elements/lisk-p2p/src/peer_pool.ts]: I'd expand the test coverage for eviction feature.

File: framework/src/modules/network/network.js [hunk 10]
```diff
@@ -111,19 +111,18 @@ module.exports = class Network {
 		);
 
 		const seedPeers = await lookupPeersIPs(this.options.seedPeers, true);
-		const blacklistedPeers = this.options.blacklistedPeers
-			? this.options.blacklistedPeers.map(peer => ({
-					ipAddress: peer.ip,
-			  }))
-			: [];
+		const blacklistedPeers = this.options.blacklistedPeers || [];
```
Comment (diego-G) [inline framework/src/modules/network/network.js]: I suggest to rename this to `blacklistedIPs`.

File: elements/lisk-p2p/src/peer_pool.ts (hunk 7 above)
Comment (ishantiw) [reply elements/lisk-p2p/src/peer_pool.ts]: The last one was more readable of course, @shuse2 agrees then I can revert the changes. I'm fine with both.

Comment (shuse2) [reply elements/lisk-p2p/src/peer_pool.ts]: find returns `undefined` if not found, and changing it to `boolean`.
I think it's common expression in JS

File: elements/lisk-p2p/src/peer_pool.ts (hunk 9 above)
Comment (ishantiw) [reply elements/lisk-p2p/src/peer_pool.ts]: I've tested it in integration test to see if white list from config is making to the sanitized list but since in the sanitized list we remove ourselves from whitelist, we need not local ip to test it. So we can move it to QA testing instead of testing it locally

File: elements/lisk-p2p/src/p2p.ts (hunk 8 above)
Comment (ishantiw) [reply elements/lisk-p2p/src/p2p.ts]: I get your point but we don't want to test `new/triedPeer` in the integration tests. We already tested that when we do `upgradePeer` then it goes to `triedPeers` in peer_directory unit tests.

File: framework/src/modules/network/network.js (hunk 10 above)
Comment (ishantiw) [reply framework/src/modules/network/network.js]: we will make this change in `3.0`

File: elements/lisk-p2p/src/p2p.ts [hunk 11]
```diff
@@ -477,6 +477,7 @@ export class P2P extends EventEmitter {
 					? config.rateCalculationInterval
 					: DEFAULT_RATE_CALCULATION_INTERVAL,
 			secret: config.secret ? config.secret : DEFAULT_RANDOM_SECRET,
+			peerList: this._sanitizedPeerLists,
```
Comment (jondubois) [inline elements/lisk-p2p/src/p2p.ts]: This should be plural `peerLists` because there are multiple lists.

File: elements/lisk-p2p/src/peer_pool.ts [hunk 12]
```diff
@@ -109,6 +110,7 @@ interface PeerPoolConfig {
 	readonly wsMaxMessageRatePenalty: number;
 	readonly rateCalculationInterval: number;
 	readonly secret: number;
+	readonly peerList: PeerLists;
```
Comment (jondubois) [inline elements/lisk-p2p/src/peer_pool.ts]: Plural `peerLists` if it's multiple lists.

File: elements/lisk-p2p/src/peer_pool.ts (hunk 7 above)
Comment (mitsujutsu) [reply elements/lisk-p2p/src/peer_pool.ts]: can also do something like `.filter(peer => this._peerLists.whitelisted.every(p  => constructPeerIdFromPeerInfo(p) !== peer.id)` to make it shorter

File: elements/lisk-p2p/src/peer_pool.ts [hunk 13]
```diff
@@ -597,7 +605,14 @@ export class PeerPool extends EventEmitter {
 	}
 
 	private _selectPeersForEviction(): Peer[] {
-		const peers = [...this.getPeers(InboundPeer)];
+		const peers = [...this.getPeers(InboundPeer)].filter(peer => {
+			const found = !!this._peerLists.whitelisted.find(
+				whitePeer => constructPeerIdFromPeerInfo(whitePeer) === peer.id,
```
Comment (mitsujutsu) [inline elements/lisk-p2p/src/peer_pool.ts]: prefer `whitelistedPeer`
