### PR TITLE
Fix not to evict the fixed peer - Closes #4352

### LINKED ISSUE #4352: Incoming connections from fixed peers should never be closed similar to whitelist
### Expected behavior

Incoming connections from fixed peers should never be closed similar to whitelist.

### Actual behavior

Fixed peers incoming connections could be dropped when there is an incoming connection through the eviction process

### Steps to reproduce

Assign a `fixedPeer` and then allow it to connect (incoming) to you first. Check if it's getting evicted at any point.

### Which version(s) does this affect? (Environment, OS, etc...)
`3.0`

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?
Fixed peer had possibility to be evicted

### How did I solve it?
From the eviction, remove filter out the fixed peer before evicting

### How to manually test it?
Defined the fixed peer, and observe it's not been disconnected from inbound

### Review checklist

- [ ] The PR resolves #4352 
- [ ] All new code is covered with unit tests
- [ ] Relevant integration / functional tests are added
- [ ] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [ ] Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-p2p/test/unit/peer_pool.ts [hunk 1]
```diff
@@ -1006,7 +1007,49 @@ describe('peerPool', () => {
...
+		];
+
+		beforeEach(async () => {
+			(peerPool as any)._peerLists.whitelisted = whitelistedPeers;
+			(peerPool as any)._peerLists.fixedPeers = fixedPeers;
+			sandbox.stub(peerPool as any, 'getPeers').returns(defaultPeers);
+			sandbox.stub(peerPool, 'removePeer');
+		});
+
+		it('should not evict whitelisted peer', async () => {
```
Comment (diego-G) [inline elements/lisk-p2p/test/unit/peer_pool.ts]: Can we add another case to check a positive eviction?

File: elements/lisk-p2p/test/unit/peer_pool.ts [hunk 2]
```diff
@@ -1006,7 +1007,49 @@ describe('peerPool', () => {
...
+				sinon.match.any,
+				sinon.match.any,
+			);
+		});
+
+		it('should not evict fixed peer', async () => {
+			(peerPool as any)._evictPeer(InboundPeer);
+			expect(peerPool.removePeer).not.to.be.calledWith(
+				fixedPeers[0].ipAddress,
+				sinon.match.any,
```
Comment (diego-G) [inline elements/lisk-p2p/test/unit/peer_pool.ts]: We're not using this anywhere else. Is it necessary?

Comment (shuse2) [reply elements/lisk-p2p/test/unit/peer_pool.ts]: for this test case, the second and third parameter is not important, so that's why it's using any

Comment (diego-G) [reply elements/lisk-p2p/test/unit/peer_pool.ts]: You can also test it without because you're not utilising `calledWithExactly`.

Comment (shuse2) [reply elements/lisk-p2p/test/unit/peer_pool.ts]: Updated to use called with exactly 😉

File: elements/lisk-p2p/test/unit/peer_pool.ts (hunk 1 above)
Comment (shuse2) [reply elements/lisk-p2p/test/unit/peer_pool.ts]: Added positive case too
