### PR TITLE
Remove getFirstBlockIdOfLastRounds and SQL file - Closes #4741

### LINKED ISSUE #4741: Create lisk-blocks data access layer function for `getFirstBlockIdOfLastRounds`
### Expected behavior

There should be a function to replicate `getFirstBlockIdOfLastRounds` function in `lisk-blocks`.

### Actual behavior

Currently it uses a SQL file to execute query. This logic should be duplicated in `storage_access`.

### Steps to reproduce
n/a

### Which version(s) does this affect? (Environment, OS, etc...)
4.0

### PR DESCRIPTION
**Pull request by mitsuaki-u**
### What was the problem?

This PR resolves #4741

Removal of `loader` module removes necessity of `getFirstBlockIdOfLastRounds` functionality.

### How was it solved?

Remove all usages of `getFirstBlockIdOfLastRounds` and SQL files.

### How was it tested?

npm t

### CODE REVIEW

File: elements/lisk-chain/src/data_access/data_access.ts [hunk 1]
```diff
@@ -19,7 +19,6 @@ import {
 	BlockHeaderJSON,
 	BlockInstance,
 	BlockJSON,
-	BlockRound,
```
Comment (shuse2) [inline elements/lisk-chain/src/data_access/data_access.ts]: I think we can also remove this `BlockRound` type
