### PR TITLE
P2P should not connect to itself - Closes #3364

### LINKED ISSUE #3364: P2P should not connect to itself
### Expected behavior
P2P should not have connection to itself

### Actual behavior
It tires to connect to it's self and 

### Steps to reproduce
Set the seed as 127.0.0.1 5000 and see the result
```
[ERR] 2019-04-13 21:42:25 | System error: uncaughtException : - {"message":"Socket closed without status code","stack":"SocketProtocolError: Socket closed without status code\n    at SCClientSocket._onSCClose (/Users/70_lisk/lisk/node_modules/socketcluster-client/lib/scclientsocket.js:654:15)\n    at SCTransport.<anonymous> (/Users/70_lisk/lisk/node_modules/socketcluster-client/lib/scclientsocket.js:299:12)\n    at SCTransport.Emitter.emit (/Users/70_lisk/lisk/node_modules/component-emitter/index.js:133:20)\n    at SCTransport._onClose (/Users/70_lisk/lisk/node_modules/socketcluster-client/lib/sctransport.js:212:28)\n    at SCTransport.send (/Users/70_lisk/lisk/node_modules/socketcluster-client/lib/sctransport.js:389:10)\n    at SCTransport.sendObjectSingle (/Users/70_lisk/lisk/node_modules/socketcluster-client/lib/sctransport.js:432:10)\n    at SCTransport.sendObject (/Users/70_lisk/lisk/node_modules/socketcluster-client/lib/sctransport.js:440:10)\n    at SCTransport.emitObject (/Users/70_lisk/lisk/node_modules/socketcluster-client/lib/sctransport.js:319:8)\n    at SCTransport.emit (/Users/70_lisk/lisk/node_modules/socketcluster-client/lib/sctransport.js:370:16)\n    at SCTransport.close (/Users/70_lisk/lisk/node_modules/socketcluster-client/lib/sctransport.js:297:10)\n    at SCClientSocket.disconnect (/Users/70_lisk/lisk/node_modules/socketcluster-client/lib/scclientsocket.js:326:20)\n    at SCClientSocket.destroy (/Users/70_lisk/lisk/node_modules/socketcluster-client/lib/scclientsocket.js:339:8)\n    at Peer.dropOutboundConnection (/Users/70_lisk/lisk/node_modules/@liskhq/lisk-p2p/dist-node/peer.js:180:34)\n    at Peer.disconnect (/Users/70_lisk/lisk/node_modules/@liskhq/lisk-p2p/dist-node/peer.js:170:14)\n    at PeerPool.removePeer (/Users/70_lisk/lisk/node_modules/@liskhq/lisk-p2p/dist-node/peer_pool.js:254:18)\n    at PeerPool._handlePeerClose (/Users/70_lisk/lisk/node_modules/@liskhq/lisk-p2p/dist-node/peer_pool.js:59:18)"}
```

### Which version(s) does this affect? (Environment, OS, etc...)
2.0-

### PR DESCRIPTION
**Pull request by jondubois**
### What was the problem?

- The peer was allowed to connect to itself. This may be causing issues with current tests.
- Found a gap during which socket errors may not have been handled which could have lead to process crash.

### How did I fix it?

- Use the nonce to prevent the node from connecting to itself at the earliest possible stage (during the inbound handshake).
- Bound error handler on outbound socket as soon as it is created. The handler does not log socket errors, but this is not a problem because we should get any error from the callback which is passed to `outboundSocket.emit(...)` if anything goes wrong.

### How to test it?

In `lisk-p2p`, run `npm test`

### Review checklist

* The PR resolves #3364
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-p2p/src/peer.ts [hunk 1]
```diff
@@ -633,6 +637,10 @@ export const connectAndRequest = async (
 			};
 
 			const outboundSocket = socketClusterClient.create(clientOptions);
+			// Bind an error handler immediately after creating the socket; otherwise errors may crash the process
+			// tslint:disable-next-line no-empty
+			outboundSocket.on('error', () => {});
```
Comment (shuse2) [inline elements/lisk-p2p/src/peer.ts]: shouldn't this emit event to bobble up?
