### PR TITLE
Invalid nodeModulePath when creating a custom plugin

### LINKED ISSUE #7692: Invalid nodeModulePath when creating a custom plugin
### Expected behavior

`lisk generate:plugin customPlugin` should generate a custom plugin without error.

### Actual behavior

When we run `lisk generate:plugin customPlugin` then it creates a file `<plugin_name>_plugin.ts` where nodeModulePath returns a path in invalid string format like below without double or single quotes,
`/lisk-sdk/commander/dist/bootstrapping/templates/lisk-template-ts/templates/plugin/src/app/plugins/plugin.t`
it should be,
`__filename `

Additionally, the following function is generated, but plugins don't emit events anymore afaik:

```
public get events(): string[] {
	return [
		// 'block:created',
		// 'block:missed'
	];
}
```

Also, this is how the load function is generated, I think channel is outdated as well.

```
public async load(_: BaseChannel): Promise<void> {
	// this._channel = channel;
	// this._channel.once('app:ready', () => {});
}
```

Probably the plugin generation needs to be generally aligned to new plugin structure for v6

### Steps to reproduce

Run `lisk generate:plugin customPlugin`

### Which version(s) does this affect? (Environment, OS, etc...)

`6.0.0-alpha.4`

### PR DESCRIPTION
**Pull request by Incede**
### What was the problem?

This PR resolves #7692 

### How was it solved?

Fix template per the requirements

### How was it tested?

Output checked manually

### CODE REVIEW

File: commander/src/bootstrapping/templates/lisk-template-ts/templates/plugin/src/app/plugins/plugin.ts [hunk 1]
```diff
@@ -4,25 +4,14 @@ import type { BaseChannel } from 'lisk-sdk';
...
-			// 'block:created',
-			// 'block:missed'
-		];
-	}
-
-	public async load(_: BaseChannel): Promise<void> {
-		// this._channel = channel;
-		// this._channel.once('app:ready', () => {});
-	}
+	public async load(_: BaseChannel): Promise<void> {}
```
Comment (shuse2) [inline commander/src/bootstrapping/templates/lisk-template-ts/templates/plugin/src/app/plugins/plugin.ts:14]:
```suggestion
	public async load(): Promise<void> {}
```
Looking at `BasePlugin` we should also remove the input and the import

**Review by shuse2 — APPROVED** [review]

**Review by ishantiw — APPROVED** [review]
