### PR TITLE
Fix synchronizer running twice - Closes #5828

### LINKED ISSUE #5828: Synchronizer can run twice at the same time
### Expected behavior
Only 1 syncrhonizer process should run at once

### Actual behavior
```
{"time":"2020-09-21T10:09:39.604Z","level":20,"name":"lisk-framework","msg":"Starting to process block","hostname":"Lisk-MacBook-Pro.local","pid":29298,"module":"lisk:app","meta":{"id":"2ce3e8cec115d6f18b5745c7ebfd1f743eaea3af9d51723d1c412e80f1a70c58","height":548}}
{"time":"2020-09-21T10:09:39.605Z","level":20,"name":"lisk-framework","msg":"Detected different chain to sync","hostname":"Lisk-MacBook-Pro.local","pid":29298,"module":"lisk:app","meta":{"id":"2ce3e8cec115d6f18b5745c7ebfd1f743eaea3af9d51723d1c412e80f1a70c58","height":548}}
{"time":"2020-09-21T10:09:39.606Z","level":30,"name":"lisk-framework","msg":"Starting synchronizer","hostname":"Lisk-MacBook-Pro.local","pid":29298,"module":"lisk:app","meta":{"blockId":"2ce3e8cec115d6f18b5745c7ebfd1f743eaea3af9d51723d1c412e80f1a70c58","height":548}}
{"time":"2020-09-21T10:09:39.606Z","level":20,"name":"lisk-framework","msg":"Validating block","hostname":"Lisk-MacBook-Pro.local","pid":29298,"module":"lisk:app","meta":{"id":"2ce3e8cec115d6f18b5745c7ebfd1f743eaea3af9d51723d1c412e80f1a70c58","height":548}}
{"time":"2020-09-21T10:09:39.613Z","level":20,"name":"lisk-framework","msg":"Starting to process block","hostname":"Lisk-MacBook-Pro.local","pid":29298,"module":"lisk:app","meta":{"id":"2ce3e8cec115d6f18b5745c7ebfd1f743eaea3af9d51723d1c412e80f1a70c58","height":548}}
{"time":"2020-09-21T10:09:39.613Z","level":20,"name":"lisk-framework","msg":"Detected different chain to sync","hostname":"Lisk-MacBook-Pro.local","pid":29298,"module":"lisk:app","meta":{"id":"2ce3e8cec115d6f18b5745c7ebfd1f743eaea3af9d51723d1c412e80f1a70c58","height":548}}
{"time":"2020-09-21T10:09:39.613Z","level":30,"name":"lisk-framework","msg":"Starting synchronizer","hostname":"Lisk-MacBook-Pro.local","pid":29298,"module":"lisk:app","meta":{"blockId":"2ce3e8cec115d6f18b5745c7ebfd1f743eaea3af9d51723d1c412e80f1a70c58","height":548}}
{"time":"2020-09-21T10:09:39.614Z","level":20,"name":"lisk-framework","msg":"Validating block","hostname":"Lisk-MacBook-Pro.local","pid":29298,"module":"lisk:app","meta":{"id":"2ce3e8cec115d6f18b5745c7ebfd1f743eaea3af9d51723d1c412e80f1a70c58","height":548}}
{"time":"2020-09-21T10:09:39.622Z","level":30,"name":"lisk-framework","msg":"Triggering: BlockSynchronizationMechanism","hostname":"Lisk-MacBook-Pro.local","pid":29298,"module":"lisk:app"}
{"time":"2020-09-21T10:09:39.624Z","level":20,"name":"lisk-framework","msg":"Computing the best peer to synchronize from","hostname":"Lisk-MacBook-Pro.local","pid":29298,"module":"lisk:app"}
{"time":"2020-09-21T10:09:39.627Z","level":20,"name":"lisk-framework","msg":"Successfully computed the best peer","hostname":"Lisk-MacBook-Pro.local","pid":29298,"module":"lisk:app","meta":{"peer":{"networkIdentifier":"a03777d28662d44751a2f6b62111ad3c3794027ed1fa472a19a9cd4ff0be7014","networkVersion":"2.0","nonce":"8aa76f701e7823b0","advertiseAddress":true,"options":{"height":547,"maxHeightPrevoted":460,"blockVersion":2,"lastBlockID":"4444aedef603ed4b7fc778b72e0cca4b3fdcaa1d7bf423d87ddd4cbcaf605c99"},"ipAddress":"188.166.83.141","port":5000,"peerId":"188.166.83.141:5000"}}}
{"time":"2020-09-21T10:09:39.627Z","level":20,"name":"lisk-framework","msg":"Requesting tip of the chain from peer","hostname":"Lisk-MacBook-Pro.local","pid":29298,"module":"lisk:app","meta":{"peerId":"188.166.83.141:5000"}}
```

### Steps to reproduce
try to run sync multiple times. It does not happen every time.

### Which version(s) does this affect? (Environment, OS, etc...)
5.0.0-alpha.2

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #5828 

### How was it solved?

- Update `JobQueue` to be `Mutex` referencing two code
  - https://github.com/aws-amplify/amplify-js/blob/e85640a4e18fa1d55411038fee58919ad73121fa/packages/core/src/Util/Mutex.ts
  - https://github.com/DirtyHairy/async-mutex
- Add mutex to synchronizer

### How was it tested?

- Add unit tests to ensure mutex is working
- Run syncing multiple times and observe debug log that syncrhonizer is blocked with `Synchronizer is already running.`

### CODE REVIEW

**Review by pablitovicente — APPROVED** [review]

File: elements/lisk-utils/src/job_handlers/mutex.ts [hunk 1]
```diff
@@ -0,0 +1,55 @@
+/*
+ * Copyright © 2019 Lisk Foundation
```
Comment (ManuGowda) [inline elements/lisk-utils/src/job_handlers/mutex.ts:2]:
```suggestion
 * Copyright © 2020 Lisk Foundation
```

File: elements/lisk-utils/test/job_handlers/mutex.spec.ts [hunk 2]
```diff
@@ -0,0 +1,93 @@
+/*
+ * Copyright © 2019 Lisk Foundation
```
Comment (ManuGowda) [inline elements/lisk-utils/test/job_handlers/mutex.spec.ts:2]:
```suggestion
 * Copyright © 2020 Lisk Foundation
```

File: framework/src/node/synchronizer/synchronizer.ts [hunk 3]
```diff
@@ -91,54 +94,59 @@ export class Synchronizer {
 	}
 
 	public async run(receivedBlock: Block, peerId: string): Promise<void> {
-		if (this.isActive) {
-			throw new Error('Synchronizer is already running');
+		if (this._mutex.isLocked()) {
+			this.logger.debug('Synchronizer is already running.');
```
Comment (ManuGowda) [inline framework/src/node/synchronizer/synchronizer.ts:98]:
```suggestion
			this.logger.info('Synchronizer is already running.');
```

File: framework/src/node/synchronizer/synchronizer.ts [hunk 4]
```diff
@@ -91,54 +94,59 @@ export class Synchronizer {
...
-			},
-			'Synchronization finished',
-		);
+			this.logger.info(
+				{
+					lastBlockHeight: this.chainModule.lastBlock.header.height,
+					lastBlockID: this.chainModule.lastBlock.header.id,
+					mechanism: validMechanism.constructor.name,
+				},
+				'Synchronization finished',
```
Comment (ManuGowda) [inline framework/src/node/synchronizer/synchronizer.ts:135]:
```suggestion
				'Synchronization finished.',
```

**Review by ManuGowda — APPROVED** [review]

File: elements/lisk-utils/test/job_handlers/mutex.spec.ts (hunk 2 above)
Comment (shuse2) [reply elements/lisk-utils/test/job_handlers/mutex.spec.ts:2]: this was update, although it was too much diff so it showed as different file

File: framework/src/node/synchronizer/synchronizer.ts (hunk 3 above)
Comment (shuse2) [reply framework/src/node/synchronizer/synchronizer.ts:98]: this will happen a lot, so i kept it as `debug`

File: elements/lisk-utils/src/job_handlers/mutex.ts (hunk 1 above)
Comment (shuse2) [reply elements/lisk-utils/src/job_handlers/mutex.ts:2]: same as below

File: framework/src/node/synchronizer/synchronizer.ts (hunk 3 above)
Comment (ManuGowda) [reply framework/src/node/synchronizer/synchronizer.ts:98]: Sync is triggered only when chain is out of sync.. so why it happens a lot? i can understand it can happen during initial time before certain height, but after that it shouldn't trigger sync if blocks are propagating? 
Felt the log will be useful, its ok either way.

File: elements/lisk-utils/test/job_handlers/mutex.spec.ts (hunk 2 above)
Comment (ManuGowda) [reply elements/lisk-utils/test/job_handlers/mutex.spec.ts:2]: i thought this was a new implementation, again either way is fine with me 👍
