### PR TITLE
Fix range of single commit generation in init

### LINKED ISSUE #8086: Fail to restart node
### Expected behavior
When application is stopped properly, it should always be able to restart.

### Actual behavior
```
2023-01-26T11:08:36.830Z ERROR MacBook-Pro-2.fritz.box ABIClient 29583 [err=] Fail to start engine
2023-01-26T11:08:36.837Z ERROR MacBook-Pro-2.fritz.box application 29575 [code=1 signal=] Engine exited unexpectedly
2023-01-26T11:08:36.837Z INFO MacBook-Pro-2.fritz.box application 29575 [errorCode=1 message=process.exit] Application shutdown starte
```
application does not start with the above error

### Additional Information
Engine is failing with
```
BFTParameterNotFoundError
    at getBFTParameters (/Users/lisk/Documents/10_lisk/lisk-sdk/framework/dist-node/engine/bft/bft_params.js:18:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Generator._certifySingleCommit (/Users/lisk/Documents/10_lisk/lisk-sdk/framework/dist-node/engine/generator/generator.js:424:24)
    at async Generator._certifySingleCommitForChangedHeight (/Users/lisk/Documents/10_lisk/lisk-sdk/framework/dist-node/engine/generator/generator.js:414:9)
    at async Promise.all (index 70)
    at async Generator.init (/Users/lisk/Documents/10_lisk/lisk-sdk/framework/dist-node/engine/generator/generator.js:100:9)
    at async Engine._init (/Users/lisk/Documents/10_lisk/lisk-sdk/framework/dist-node/engine/engine.js:143:9)
    at async Engine.start (/Users/lisk/Documents/10_lisk/lisk-sdk/framework/dist-node/engine/engine.js:61:9)
    at async /Users/lisk/Documents/10_lisk/lisk-sdk/framework/dist-node/engine_igniter.js:28:5
```

### Steps to reproduce
Try restarting at multiple height

### Which version(s) does this affect? (Environment, OS, etc...)
6.0.0-alpha.12

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #8086 

### How was it solved?

- Fix the range of single commit generation on node initialization.
- Refactor the single commit generation loop, to reduce double check of BFT params on the last height

Problem was `finalizedBlockHeader.aggregateCommit.height` can be removed from the BFT params, and it fails on the initialization.  Because `maxHeightCertified > finalizedBlockHeader.aggregateCommit.height` and up to `maxHeightCertified` there is no need of single commit. Therefore, we can use `maxHeightCertified` for the lower range

### How was it tested?

- Updated unit test

### CODE REVIEW

File: framework/src/engine/generator/generator.ts [hunk 1]
```diff
@@ -622,10 +625,13 @@ export class Generator {
...
 
 	private _handleFinalizedHeightChanged(from: number, to: number): Promise<void>[] {
+		if (from >= to) {
+			return [];
+		}
 		const promises = [];
 		const stateStore = new StateStore(this._blockchainDB);
 		for (const [address, pairs] of this._keypairs.entries()) {
-			for (let height = from + 1; height <= to; height += 1) {
+			for (let height = from + 1; height < to; height += 1) {
```
Comment (ishantiw) [inline framework/src/engine/generator/generator.ts:634]: According to this in the LIP
`h1 = getMaxRemovalHeight() and h2 = getBFTHeights().maxHeightPrecommitted`

here we are starting with `getMaxRemovalHeight()+2` to `h2 - 1 `as we increment it above at Line206. Shouldn't this be?
```suggestion
			for (let height = from; height < to; height += 1) {
```

Comment (shuse2) [reply framework/src/engine/generator/generator.ts:634]: ah that's true. the loop start from +1.
I think the input to this function needs to be changed because when it's called when `maxHeightPrecommited` is changed, we still want to certify from last `maxHeightPrecommited + 1` to current `maxHeightPrecommited`

Comment (shuse2) [reply framework/src/engine/generator/generator.ts:634]: @janhack this needs to be updated in the [LIP](https://github.com/LiskHQ/lips/blob/main/proposals/lip-0061.md#initial-single-commit-creation) as well?

**Review by ishantiw — APPROVED** [review]

File: framework/src/engine/consensus/consensus.ts [hunk 2]
```diff
@@ -366,13 +366,6 @@ export class Consensus {
 		this._commitPool.addCommit(singleCommit, true);
 	}
 
-	public async getMaxRemovalHeight(): Promise<number> {
```
Comment (janhack) [inline framework/src/engine/consensus/consensus.ts:369]: Is the same function still defined somewhere else? It would still be needed to decide when a single commit that is stored locally can be safely removed.

File: framework/src/engine/generator/generator.ts [hunk 3]
```diff
@@ -199,9 +199,12 @@ export class Generator {
 		});
 
 		const stateStore = new StateStore(this._blockchainDB);
-		const maxRemovalHeight = await this._consensus.getMaxRemovalHeight();
-		const { maxHeightPrecommitted } = await this._bft.method.getBFTHeights(stateStore);
-		await Promise.all(this._handleFinalizedHeightChanged(maxRemovalHeight, maxHeightPrecommitted));
+		const { maxHeightPrecommitted, maxHeightCertified } = await this._bft.method.getBFTHeights(
+			stateStore,
+		);
+		await Promise.all(
```
Comment (janhack) [inline framework/src/engine/generator/generator.ts:205]: As this was a point of confusion before, maybe we could add some explanation to the code as a comment, e.g., 
"A certificate for height maxHeightCertified is already generated, hence it is only necessary to create single commits for height maxHeightCertified + 1 onward".

Comment (janhack) [reply framework/src/engine/generator/generator.ts:205]: Or we link to the specific section of the LIP here, i.e., https://github.com/LiskHQ/lips/blob/main/proposals/lip-0061.md#initial-single-commit-creation
(I need to fix it and replace `h1 = getMaxRemovalHeight()` by `h1 = maxHeightCertified`.

File: framework/src/engine/generator/generator.ts (hunk 1 above)
Comment (janhack) [reply framework/src/engine/generator/generator.ts:634]: So there are two cases when this function is called:

Case 1: A block is processed and `maxHeightPrecommitted` changes from `h1` to `h2`, see https://github.com/LiskHQ/lips/blob/main/proposals/lip-0061.md#creation-after-block-processing where `h1 == from` and `h2 == to`. In this case, we want to iterate from `h1 + 1` to `h2` so the current version of the PR is correct (could you point me though where the function is called in this case?).

Case 2: The node restarts and we want to re-create single commits, see https://github.com/LiskHQ/lips/blob/main/proposals/lip-0061.md#initial-single-commit-creation where `maxHeightCertified == from` and `maxHeightPrecommitted == to` (the LIP needs an update here as described above). I also think the PR is correct here and I don't see how you get  `+ 2` @ishantiw .

File: framework/src/engine/generator/generator.ts [hunk 4]
```diff
@@ -622,10 +625,13 @@ export class Generator {
...
 	private _handleFinalizedHeightChanged(from: number, to: number): Promise<void>[] {
+		if (from >= to) {
+			return [];
+		}
 		const promises = [];
 		const stateStore = new StateStore(this._blockchainDB);
 		for (const [address, pairs] of this._keypairs.entries()) {
-			for (let height = from + 1; height <= to; height += 1) {
+			for (let height = from + 1; height < to; height += 1) {
 				promises.push(
```
Comment (janhack) [inline framework/src/engine/generator/generator.ts:635]: In this case, we should first check `existBFTParameters(height + 1) == true` and otherwise not create single commits.

**Review by janhack — CHANGES_REQUESTED** [review]
I added a comment for one issue.

Otherwise, the PR looks good and I just replied to the discussions.

File: framework/src/engine/generator/generator.ts (hunk 1 above)
Comment (ishantiw) [reply framework/src/engine/generator/generator.ts:634]: @janhack the code is updated now in this commit https://github.com/LiskHQ/lisk-sdk/pull/8095/commits/e1ce2650c28431b494f95c0f650ecec59dbd5a0c but earlier we had 
`this._handleFinalizedHeightChanged(maxHeightCertified + 1, maxHeightPrecommitted)`
and the loop is starting `for (let height = from + 1; height < to; height += 1) {` so we were getting `+2`

File: framework/src/engine/consensus/consensus.ts (hunk 2 above)
Comment (shuse2) [reply framework/src/engine/consensus/consensus.ts:369]: yes, the function is defined for the certificate generation. This was a duplicate function

File: framework/src/engine/generator/generator.ts (hunk 4 above)
Comment (shuse2) [reply framework/src/engine/generator/generator.ts:635]: that is checked in the function `_certifySingleCommitForChangedHeight`

Comment (janhack) [reply framework/src/engine/generator/generator.ts:640]: True, I got confused with the functions again. All good.

File: framework/src/engine/generator/generator.ts (hunk 3 above)
Comment (janhack) [reply framework/src/engine/generator/generator.ts:210]: I created an issue for it https://github.com/LiskHQ/lips/issues/245.

**Review by janhack — APPROVED** [review]
