### PR TITLE
transaction:create parameter prompts

### LINKED ISSUE #9105: transaction:create crashes when fetching parameters from prompt
### Expected behavior

`CreateCommand` when fetching properties of type array of objects as CSV crashes if user opts to add no more items. 

Plus, if the user confirms to add a new item in the nested array of objects; the prompt starts from the first property of the object containing the concerned property.

### Actual behavior
`CreateCommand`; when fetching properties of nested arrays having items of type object, should inquire to fetch more items and should use the schema of the nested object.

### Steps to reproduce
Execute `mintNft` command on `testNft` module under `examples/pos-mainchain`.

### Which version(s) does this affect? (Environment, OS, etc...)
`release/6.1.0`

### PR DESCRIPTION
**Pull request by has5aan**
### What was the problem?

This PR resolves #9105

### How was it solved?

- Modified `CreateCommand` to fetch nested object of arrays as CSV from the command-line prompt. 
- Updated the casting logic to cast arrays of type `uint64` and `sint64` to `BigInt[]` also `uint32` and `sint32` types are casted to `Number[]`.   

### How was it tested?

Implemented unit tests.

### Functional test
Calling `transaction:create testNft mintNft 10000000` --send on `pos-mainchain` and providing the required parameters through the prompt.

### CODE REVIEW

File: commander/src/utils/reader.ts [hunk 1]
```diff
@@ -232,107 +189,120 @@ const castValue = (
...
+
+const getNestedParametersFromPrompt = async (property: {
+	name: string;
+	items: { properties: Record<string, unknown> };
+}) => {
+	let addMore = false;
+	const nestedArray: Array<Record<string, unknown>> = [];
+
+	do {
+		const nestedProperties = Object.keys(property.items.properties);
```
Comment (mosmartin) [inline commander/src/utils/reader.ts:212]: Maybe you could move `nestedProperties` and `nestedPropertiesCsv` vars outside the do-while loop as their values don't change in the loop. This can improve performance as these operations are not repeated in each loop iteration.

File: commander/src/utils/reader.ts [hunk 2]
```diff
@@ -232,107 +189,120 @@ const castValue = (
...
+): Promise<NestedAsset | Record<string, unknown>> => {
+	const result: Record<string, unknown> = {};
+	for (const propertyName of Object.keys(assetSchema.properties)) {
+		const property = assetSchema.properties[propertyName] as {
+			dataType?: string;
+			type?: 'array';
+			items?: { dataType?: string; type?: 'object'; properties?: Record<string, unknown> };
+		};
+
+		if (
```
[the remark this answers is not in the document]
Comment (has5aan) [reply commander/src/utils/reader.ts]: [Modified here.](https://github.com/LiskHQ/lisk-sdk/pull/9118/commits/d5dc7f2cd533da80a4b0207d39767a854b6b517b)

File: commander/src/utils/reader.ts (hunk 1 above)
Comment (has5aan) [reply commander/src/utils/reader.ts]: [Modified here.](https://github.com/LiskHQ/lisk-sdk/pull/9118/commits/6de94923dd0092a73315b78d3a86ba4edf4bf092)

**Review by mosmartin — APPROVED** [review]

**Review by shuse2 — APPROVED** [review]
