### PR TITLE
Syncing halted due to block max payload size exceeded - Closes #4083

### LINKED ISSUE #4083: PeerPool removePeer should allow code or reason as parameter
### Expected behavior

`removePeer` should accept `reason` string for disconnect reason so logs are more descriptive.

### Actual behavior

Currently when inbound peer evicted it shows message: `INbound connection of peer 157.230.222.179:5000 was closed with code 1000 and reason: undefined`

### Steps to reproduce

SSH into alphanet 2.3.0 node and view logs. 

### Which version(s) does this affect? (Environment, OS, etc...)
2.3

### PR DESCRIPTION
**Pull request by jondubois**
### What was the problem?

The payload limit was too low.

### How did I solve it?

- Increased the message payload limit.
- Added separate limits for PeerInfo and PeerInfoLists.
- Allow user to configure all these limits from config file.

### How to manually test it?

Run tests

### Review checklist

- [ ] The PR resolves #4083
- [ ] All new code is covered with unit tests
- [ ] Relevant integration / functional tests are added
- [ ] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [ ] Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-p2p/src/validation.ts [hunk 1]
```diff
@@ -117,19 +123,33 @@ export const validatePeerInfo = (rawPeerInfo: unknown): P2PPeerInfo => {
 
 	const { ip, ...peerInfoUpdated } = peerInfo;
 
+	const byteSize = getByteSize(peerInfoUpdated);
```
Comment (ishantiw) [inline elements/lisk-p2p/src/validation.ts]: I think we can move this check right at the beginning of `validatePeerInfo` function before going into all the validations or transformation of `peerInfo`

File: elements/lisk-p2p/src/p2p.ts [hunk 2]
```diff
@@ -779,18 +788,17 @@ export class P2P extends EventEmitter {
 			.minimumPeerDiscoveryThreshold
 			? this._config.minimumPeerDiscoveryThreshold
 			: DEFAULT_MIN_PEER_DISCOVERY_THRESHOLD;
-		const maximumPeerDiscoveryResponseSize = this._config
-			.maximumPeerDiscoveryResponseSize
-			? this._config.maximumPeerDiscoveryResponseSize
-			: DEFAULT_MAX_PEER_DISCOVERY_RESPONSE_SIZE;
+		const peerDiscoveryResponseLength = this._config.peerDiscoveryResponseLength
```
Comment (mitsujutsu) [inline elements/lisk-p2p/src/p2p.ts]: I think we can leave `maximum` in the name here, as it describes the maximum and not the actual response length.

File: elements/lisk-p2p/src/peer_pool.ts [hunk 3]
```diff
@@ -429,6 +431,9 @@ export class PeerPool extends EventEmitter {
 			ackTimeout: this._peerPoolConfig.ackTimeout,
 			wsMaxMessageRate: this._peerPoolConfig.wsMaxMessageRate,
 			wsMaxMessageRatePenalty: this._peerPoolConfig.wsMaxMessageRatePenalty,
+			maxPeerDiscoveryResponseLength: this._peerPoolConfig
```
Comment (mitsujutsu) [inline elements/lisk-p2p/src/peer_pool.ts]: Does peer need to know this?

File: elements/lisk-p2p/src/p2p.ts (hunk 2 above)
Comment (jondubois) [reply elements/lisk-p2p/src/p2p.ts]: @mitsujutsu I separated those two. I renamed the variables. The max length of the peer list that we accept from peers can be different from the length that we provide to peers. I'm worried that if we don't separate those it could make updates more difficult in the future.

File: elements/lisk-p2p/src/peer_pool.ts (hunk 3 above)
Comment (jondubois) [reply elements/lisk-p2p/src/peer_pool.ts]: The validation function which needs it is inside the peer list. It's a pure function so we can't pass it in another way.

File: elements/lisk-p2p/src/validation.ts (hunk 1 above)
Comment (jondubois) [reply elements/lisk-p2p/src/validation.ts]: Ok. I changed it so that it just removes peers that are too large from the list when validating the list instead of rejecting the entire list if just one peer is too big. So then I was able to implement it as you recommend.
