### PR TITLE
Error: Fail to start controller

### LINKED ISSUE #7760: Error: Fail to start controller
### Expected behavior
After registering the plugin and its related code to the project, the controller should start and the plugin's code should be executed as well.

### Actual behavior
On my branch [191-hello-plugin-v6](https://github.com/LiskHQ/lisk-sdk-examples/tree/191-hello-plugin-v6), After registering the plugin and its related code to the project, the controller fails to start and as a result, the plugin's code becomes inaccessible. The Plugin code works individually on a local project which doesn't have any module.

### Steps to reproduce
Pull branch: [191-hello-plugin-v6](https://github.com/LiskHQ/lisk-sdk-examples/tree/191-hello-plugin-v6)

- `rm -r ~/.lisk/hello_client`  (in case already present on system)

- `npm install --registry https://npm.lisk.com/`

- Update line 84 in`node_modules/lisk-framework/dist-node/plugins/base_plugin.js` to

    -  `this._apiClient = await lisk_api_client_1.createIPCClient(this.appConfig.system.dataPath);`

- ` npm run build`

- `./bin/run start --config config/custom_config.json`

**Result: Controller doesn't start**
```
$ application 3965 hello Loading in-memory plugin
$ application 3965 [err=Channel for module hello is already registered.] Fail to start controller
```

### Which version(s) does this affect? (Environment, OS, etc...)
LiskSDK: `lisk-commander/6.0.0-alpha.5 darwin-arm64 node-v16.18.0`
Project-based on: `6.0.0-alpha.5`
macOS Venture 13

### PR DESCRIPTION
**Pull request by Incede**
### What was the problem?

This PR resolves #7760 

### How was it solved?

Check for duplicate names and throw error if found

### How was it tested?

Added unit test

### CODE REVIEW

File: framework/src/application.ts [hunk 1]
```diff
@@ -229,6 +229,11 @@ export class Application {
 		plugin: BasePlugin<any>,
 		options: PluginConfig = { loadAsChildProcess: false },
 	): void {
+		for (const registeredModule of this._registeredModules) {
```
Comment (shuse2) [inline framework/src/application.ts:232]: I think similar check needs to exist on `registerModule` as well?

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: framework/src/application.ts (hunk 1 above)
Comment (Incede) [reply framework/src/application.ts:232]: I am not sure. Is the order of registering modules & plugins not fixed? 
If it is fixed i.e. all modules are always registered before registering a plugin, it may not be necessary.

Comment (shuse2) [reply framework/src/application.ts:232]: the order is not fixed, the function can be called in any order

**Review by shuse2 — CHANGES_REQUESTED** [review]

**Review by shuse2 — APPROVED** [review]

File: framework/test/unit/application.spec.ts [hunk 2]
```diff
@@ -194,6 +232,29 @@ describe('Application', () => {
 		});
 	});
 
+	describe('#registerModule', () => {
+		it('should throw error when module with same name is already registered', () => {
```
Comment (bobanm) [inline framework/test/unit/application.spec.ts:236]: What you probably meant here was:

_should throw error when PLUGIN with same name is already registered_

File: framework/test/unit/application.spec.ts [hunk 3]
```diff
@@ -150,7 +167,28 @@ describe('Application', () => {
...
+			class MyPlugin extends TestPlugin {
+				public get name() {
+					return 'my-plugin';
+				}
+			}
+			class MyModule extends TestModule {
+				public get name() {
+					return 'my-plugin';
+				}
+			}
```
Comment (bobanm) [inline framework/test/unit/application.spec.ts:186]: These 2 classes are always the same and don't need to be copied in all relevant test cases. You can move them to the top of the file, where `TestModule` and `TestPlugin` are declared.

File: framework/test/unit/application.spec.ts [hunk 4]
```diff
@@ -194,6 +232,29 @@ describe('Application', () => {
...
```
Comment (bobanm) [inline framework/test/unit/application.spec.ts:248]: To make the test suite more readable and make it more obvious why it introduces new classes, it is always a good idea to replace generic names `MyModule` and `MyPlugin` with more specific names, such as `DuplicatedNameModule` and `DuplicatedNamePlugin` and set their names to something specific such as `duplicated`.

**Review by bobanm — APPROVED** [review]
