### PR TITLE
Fix flag description - Closes #4962

### LINKED ISSUE #4962: Fix flag description of commander
### Expected behavior
In commander flag description, `flag`, `password`, votes` and `unvotes` are out dated

### Actual behavior
It should reflect the actual usage of the flag.

### Steps to reproduce
`./bin.run transaction:sign --help`

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #4962 

### How was it solved?

- Remove extra types
- Update mocha settings
- Remove NODE_FILES flags from ts-node
- Update flag descriptions

### How was it tested?

- Now commander test should more stable in jenkins
- Check flag description matches the actual flag behavior

### CODE REVIEW

File: commander/src/utils/flags.ts [hunk 1]
```diff
@@ -18,39 +18,27 @@ const messageDescription = `Specifies a source for providing a message to the co
...
 	Examples:
-	- --password=prompt (default behaviour)
 	- --password=pass:password123 (should only be used where security is not important)
-	- --password=env:PASSWORD
-	- --password=file:/path/to/my/password.txt (takes the first line only)
-	- --password=stdin (takes the first line only)
 `;
 
-const votesDescription = `Specifies the public keys for the delegate candidates you want to vote for. Takes either a string of public keys separated by commas, or a path to a file which contains the public keys.
+const votesDescription = `Specifies the public keys for the delegate candidates you want to vote for. Takes either a string of public keys separated by commas.
```
Comment (ishantiw) [inline commander/src/utils/flags.ts]: `Takes a string of public keys separated by commas`

File: commander/src/utils/flags.ts [hunk 2]
```diff
@@ -18,39 +18,27 @@ const messageDescription = `Specifies a source for providing a message to the co
...
 	Examples:
 	- --votes=publickey1,publickey2
-	- --votes=file:/path/to/my/votes.txt (every public key should be on a new line)
 `;
 
-const unvotesDescription = `Specifies the public keys for the delegate candidates you want to remove your vote from. Takes either a string of public keys separated by commas, or a path to a file which contains the public keys.
+const unvotesDescription = `Specifies the public keys for the delegate candidates you want to remove your vote from. Takes either a string of public keys separated by commas.
```
Comment (ishantiw) [inline commander/src/utils/flags.ts]: Takes a string of public keys separated by commas.
