### PR TITLE
signData, signDataWithPassphrase throws invalid error when missing passphrase - Closes #4917

### LINKED ISSUE #4917: signData, signDataWithPassphrase throws invalid error when missing passphrase
### Expected behavior
- When a required parameter(passphrase) is not provided, it should throw `pass missing passphrase parameter`
### Actual behavior
- Sign a message(buffer) without passing passphrase to function `signData`, `signDataWithPassphrase`, results in error as below
```
> sigAcc = cryptography.signData(accHash)
Thrown:
Error: Unsupported data format. Currently only Buffers or `hex` and `utf8` strings are supported.

> sigAcc = cryptography.signDataWithPassphrase(accHash)
Thrown:
Error: Unsupported data format. Currently only Buffers or `hex` and `utf8` strings are supported.
```
### Steps to reproduce
- cryptography.signData(accHash)
- cryptography.signDataWithPassphrase(accHash)
### Which version(s) does this affect? (Environment, OS, etc...)
4.0.0, 3.0.0, 2.x.x

### PR DESCRIPTION
**Pull request by ManuGowda**
### What was the problem?
Sign a message(buffer) without passing passphrase to function signData, signDataWithPassphrase, results in an error which is misleading as below
```
> sigAcc = cryptography.signData(accHash)
Thrown:
Error: Unsupported data format. Currently only Buffers or `hex` and `utf8` strings are supported.
```

### How was it solved?
Check for required parameter and throw correct error message

### How was it tested?
- Added unit test for `signData`, `signDataWithPassphrase`

### CODE REVIEW

File: elements/lisk-cryptography/src/sign.ts [hunk 1]
```diff
@@ -141,11 +141,15 @@ export const signDataWithPassphrase = (
 	data: Buffer,
 	passphrase: string,
 ): string => {
-	const { privateKeyBytes } = getPrivateAndPublicKeyBytesFromPassphrase(
-		passphrase,
-	);
+	if (data && passphrase) {
```
Comment (shuse2) [inline elements/lisk-cryptography/src/sign.ts]: if it requires the check, then the input type is wrong, but i think in this case, the usage of the function is wrong.
Otherwise, to make it extream, u need to check if it's Buffer or string too

Comment (ManuGowda) [reply elements/lisk-cryptography/src/sign.ts]: buffer or string is checked in the hash function.
