### PR TITLE
PeerPool removePeer should allow code or reason as parameter - Closes #4083

### LINKED ISSUE #4083: PeerPool removePeer should allow code or reason as parameter
### Expected behavior

`removePeer` should accept `reason` string for disconnect reason so logs are more descriptive.

### Actual behavior

Currently when inbound peer evicted it shows message: `INbound connection of peer 157.230.222.179:5000 was closed with code 1000 and reason: undefined`

### Steps to reproduce

SSH into alphanet 2.3.0 node and view logs. 

### Which version(s) does this affect? (Environment, OS, etc...)
2.3

### PR DESCRIPTION
**Pull request by jondubois**
### What was the problem?

The logs did not show the disconnect reason most of the time.

### How did I solve it?

If the status reason is not provided by the other side of the socket, then use the default reason for that code from SocketCluster if it exists.

### How to manually test it?

Run tests and check against testnet.

### Review checklist

- [x] The PR resolves #4083
- [x] All new code is covered with unit tests
- [x] Relevant integration / functional tests are added
- [x] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [x] Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-p2p/src/peer/inbound.ts [hunk 1]
```diff
@@ -23,6 +23,10 @@ import {
 import { P2PDiscoveredPeerInfo } from '../p2p_types';
 
 import { SCServerSocket } from 'socketcluster-server';
+const socketErrorStatusCodes = {
+	...(SCServerSocket as any).errorStatuses,
```
Comment (ishantiw) [inline elements/lisk-p2p/src/peer/inbound.ts]: Do you think it might throw an error if `errorStatuses` is `undefined`?

File: elements/lisk-p2p/src/peer/inbound.ts [hunk 2]
```diff
@@ -40,7 +44,7 @@ export class InboundPeer extends Peer {
 	protected readonly _handleInboundSocketError: (error: Error) => void;
 	protected readonly _handleInboundSocketClose: (
 		code: number,
-		reason: string,
+		reason: string | undefined,
```
Comment (ishantiw) [inline elements/lisk-p2p/src/peer/inbound.ts]: Maybe instead of `undefined` we can give a message like `Unknown Reason`?

File: elements/lisk-p2p/src/peer/outbound.ts [hunk 3]
```diff
@@ -47,6 +47,11 @@ export const EVENT_CLOSE_OUTBOUND = 'closeOutbound';
 export const EVENT_OUTBOUND_SOCKET_ERROR = 'outboundSocketError';
 export const RESPONSE_PONG = 'pong';
 
+const socketErrorStatusCodes = {
+	...(socketClusterClient.SCClientSocket as any).errorStatuses,
```
Comment (ishantiw) [inline elements/lisk-p2p/src/peer/outbound.ts]: same here

File: elements/lisk-p2p/src/peer/outbound.ts [hunk 4]
```diff
@@ -151,13 +156,19 @@ export class OutboundPeer extends Peer {
...
-		outboundSocket.on('close', (code: number, reason: string) => {
-			this.emit(EVENT_CLOSE_OUTBOUND, {
-				peerInfo: this._peerInfo,
-				code,
-				reason,
-			});
-		});
+		outboundSocket.on(
+			'close',
+			(code: number, reasonMessage: string | undefined) => {
```
Comment (ishantiw) [inline elements/lisk-p2p/src/peer/outbound.ts]: instead of `undefined` use `Unknown Reason`

File: elements/lisk-p2p/src/peer/inbound.ts (hunk 1 above)
Comment (jondubois) [reply elements/lisk-p2p/src/peer/inbound.ts]: The `errorStatuses` object is always defined; it's part of the SC API.

File: elements/lisk-p2p/src/peer/inbound.ts (hunk 2 above)
Comment (jondubois) [reply elements/lisk-p2p/src/peer/inbound.ts]: This comes from SC so we can't control this input but good point. I made the change below.

File: elements/lisk-p2p/src/peer/outbound.ts (hunk 3 above)
Comment (jondubois) [reply elements/lisk-p2p/src/peer/outbound.ts]: As above, it will always exist. I had to do this casting because the DefinitelyTyped definition is incomplete.

**Comment by jondubois** [comment]
@mitsujutsu Ready to review.
