### PR TITLE
Used hash onion parameters count & 'height' not updated if imported from another node and block height is less than 'height'

### LINKED ISSUE #8369: Used hash onion parameters count & 'height' not updated if imported from another node and block height is less than 'height'
### Expected behavior
When using endpoint `setHashOnionUsage` to import used hash onion parameters from another node, the new node should either :
1. throw if the parameters are not valid for eg. current block height is less than the height of the last used hash onion
2. update the last used hash onion correctly after successfully importing the parameters and then generating a block using the respective next hash onion in the series

### Actual behavior
If the current block height of the new node is less than the height of the last used hash onion set by `setHashOnionUsage` the parameters `height` & `count` returned by endpoint `getHashOnionUsage` remain the same after multiple rounds until the block height reaches or surpasses the height of the last used hash onion even though the validator keeps forging blocks and receiving rewards by using the remaining hash onion in the series.

### Steps to reproduce
1. Run node1 for multiple rounds with valid seed reveal data for atleast 1 validator.
2. Import hash onion data using endpoint `getHashOnionSeeds` and used hash onion data using endpoint `getHashOnionUsage` from node1 for the particular validator
3. Start node2 from scratch.
4. Set seed, count & distance for the same validator from the imported hash onion data using endpoint `setHashOnion`
5. Set height & count (used) for the same validator from the import used hash onion data using endpoint `setHashOnionUsage`
6. Observe the hash onion usage of the particular validator as it forges blocks from beginning and until after the block height of the node surpasses the height of the last used hash onion initially set.

### Which version(s) does this affect? (Environment, OS, etc...)
development

### PR DESCRIPTION
**Pull request by Incede**
### What was the problem?

This PR resolves #8369 

### How was it solved?

Cleanup other entries in used hash onion array if there is new entry with count zero which was not present before

### How was it tested?

- Tested manually following the steps described in the issue
- Added 3 new unit tests for cases when used hash onion height is less, equal and greater to the current block height
- Unrelated: Merged duplicate unit test

### CODE REVIEW

File: framework/src/modules/random/stores/used_hash_onions.ts [hunk 1]
```diff
@@ -100,6 +100,16 @@ export class UsedHashOnionsStore extends BaseOffchainStore<UsedHashOnionStoreObj
...
+			// if newly inserted entry has count 0, then cleanup previous entries
+			if (usedHashOnion.count === 0) {
+				const newUsedHashonions = [usedHashOnion];
+				await this.set(
+					ctx,
+					address,
+					this._filterUsedHashOnions(newUsedHashonions, finalizedHeight),
+				);
+				return;
+			}
```
Comment (bobanm) [inline framework/src/modules/random/stores/used_hash_onions.ts:112]: Here you can slightly improve the code by moving your if statement before `originalUsedHashOnions.push(usedHashOnion)`. If count is 0, then there is no need to modify `originalUsedHashOnions` array.

But even better, what if instead of duplicating the code with the second `this.set()` followed by a `return`, your conditional would simply set value for a variable containing used hash onions? Then the one and only `this.set()` at the end of the method would simply use that variable, which would be common for all the possible paths?

I personally think that's a cleaner approach.

File: framework/test/unit/modules/random/module.spec.ts [hunk 2]
```diff
@@ -304,8 +304,24 @@ describe('RandomModule', () => {
...
+					{
+						count: 6,
+						height: 12,
+					},
+					{
+						count: 7,
+						height: 15,
+					},
+				],
+			};
```
Comment (bobanm) [inline framework/test/unit/modules/random/module.spec.ts:324]: This object is identical to `defaultUsedHashOnionUpdated`.

I assume you didn't re-use that variable for semantic reasons...?

File: framework/src/modules/random/stores/used_hash_onions.ts [hunk 3]
```diff
@@ -100,6 +100,16 @@ export class UsedHashOnionsStore extends BaseOffchainStore<UsedHashOnionStoreObj
 
 		if (index === -1) {
 			originalUsedHashOnions.push(usedHashOnion);
+			// if newly inserted entry has count 0, then cleanup previous entries
+			if (usedHashOnion.count === 0) {
+				const newUsedHashonions = [usedHashOnion];
```
Comment (bobanm) [inline framework/src/modules/random/stores/used_hash_onions.ts:105]: Variable `newUsedHashonions` is not properly camelCased. Should be `newUsedHashOnions`

**Review by bobanm — CHANGES_REQUESTED** [review]

File: framework/test/unit/modules/random/module.spec.ts (hunk 2 above)
Comment (Incede) [reply framework/test/unit/modules/random/module.spec.ts]: I didn't modify this particular test case, `usedHashOnionInput` already existed as a duplicate. git diff is wrongly showing it as modified (picking some content from another modified test case). 

But since you pointed it out, I realized it's another duplicate test case. So, I merge it with the first case like i already did with another duplicate case.

File: framework/src/modules/random/stores/used_hash_onions.ts (hunk 1 above)
Comment (Incede) [reply framework/src/modules/random/stores/used_hash_onions.ts]: 1. moving the if statement before `originalUsedHashOnions.push(usedHashOnion)` made the logic more efficient, yes. Thank you.

2. If we apply the second part of your suggestion the code would look like this :
```
		let newUsedHashOnions: UsedHashOnion[];
		if (index === -1) {
			// if newly inserted entry has count 0, then cleanup previous entries
			if (usedHashOnion.count === 0) {
				newUsedHashOnions = [usedHashOnion];
				await this.set(
					ctx,
					address,
					this._filterUsedHashOnions(newUsedHashOnions, finalizedHeight),
				);
			}
			else {
				originalUsedHashOnions.push(usedHashOnion);
				newUsedHashOnions = originalUsedHashOnions;
			}
		} else {
			// eslint-disable-next-line no-param-reassign
			originalUsedHashOnions[index] = usedHashOnion;
			newUsedHashOnions = originalUsedHashOnions;
		}

		await this.set(
			ctx,
			address,
			this._filterUsedHashOnions(newUsedHashOnions, finalizedHeight),
		);
```

In terms of computation we are getting rid of 1 `return` call at the cost of 1 conditional `else` branch. Not specifically sure about nodejs but with most compilers this modification would be less efficient. However if you know that it's not true I'd then update the PR per your suggestion.

**Review by shuse2 — APPROVED** [review]

**Review by bobanm — APPROVED** [review]
