### PR TITLE
Managing list of peers according to LIP004 - Closes #3339

### LINKED ISSUE #3339: Managing fixed white black lists of peers from configuration
### Description

In Phase 2 of lisk-p2p from [LIP0004](https://github.com/LiskHQ/lips/blob/master/proposals/lip-0004.md), we will have different peers list that user can set in the configuration when a node starts. This will include the following types of peer's lists:
- **Blacklist Peer** : 
  - [X] If a peer is blacklisted, then no incoming or outgoing connection is ever established to that peer
  - [x] preference above all 8267deae671eb69073ba3389f3288ef09c4dc717 65773121f78417cbaa8512d6c1a02f0811b47583

- **Fixedlist Peer** : 
  - [x] a permanent outgoing connection is established to that peer (if an incoming connection does not already exist) e2109230b8dec7ae83912a56e4c531c4b34e0100
  - [x] ~no subject to shuffle~ -> to be addressed by #3347
  - [x] ~triggers reconnect if error (using `exponential backoff` functionality from SocketCluster)~ Not needed
  - [x] ~manually removing from the configuration if connection failures after agreed period~ Not wanted
  - [x] 4 at most 1edabab3db7282b21595d381e699dc3f486f1a99
  - [x] users should be discouraged from declaring fixed peers 97527f4689defc1033ada44ac2c7d99331d6b596
  - [x] ~exclusively connect to fixed peers + `advertiseAddress=false` + no shuffling (**exchanges optional feature**)~ -> to be addressed by #3661
  - [x] preference over _whitelisted_ attribute 65773121f78417cbaa8512d6c1a02f0811b47583

- **Whitelist Peer** : a whitelisted peer is treated the same way as a normal peer with some exceptions
  - [x] add to the triedPeers collection at the beginning a3dfb046778f184843b201fcb184328e3724e0f8
  - [x] never removed from the triedPeers collection 1726f47d293b5f6517cae1f939803ba621c02ab5
  - [x] never banned by the banning mechanism 483074b5fbc35d04f12c38e60bd72b1342df1c03
  - [x] incoming connection from a whitelisted peer is never evicted and has precedence over any other (even over an existing one)
  - [x] users should be warned in the configuration file to only declare trustworthy peers 97527f4689defc1033ada44ac2c7d99331d6b596

### PR DESCRIPTION
**Pull request by diego-G**
### How to test it?
`npm run enableLocalIPs && npm run test:integration` 

### Review checklist

* The PR resolves #3339
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: elements/lisk-p2p/src/peer/outbound.ts [hunk 1]
```diff
@@ -168,7 +146,11 @@ export class OutboundPeer extends Peer {
 
 		outboundSocket.on('connect', async () => {
 			this.emit(EVENT_CONNECT_OUTBOUND, this._peerInfo);
-			await this._updatePeerOnConnect();
+			try {
+				await Promise.all([this.fetchStatus(), this.discoverPeers()]);
```
Comment (ishantiw) [inline elements/lisk-p2p/src/peer/outbound.ts]: Maybe we can make these calls separately and catch and emit specific events? let's say if a peer was able to call `fetchStatus` but failed at `fetchPeers` then it will throw `EVENT_FAILED_TO_COLLECT_PEER_DETAILS_ON_CONNECT ` which is not very clear that which RPC exactly failed.

File: elements/lisk-p2p/src/peer_pool.ts [hunk 2]
```diff
@@ -20,8 +20,7 @@
 
 import { EventEmitter } from 'events';
 // tslint:disable-next-line no-require-imports
-import shuffle = require('lodash.shuffle');
-import { SCClientSocket } from 'socketcluster-client';
+import { shuffle } from 'lodash';
```
Comment (ishantiw) [inline elements/lisk-p2p/src/peer_pool.ts]: maybe still keep `import shuffle = require('lodash.shuffle');` if not using any other function from lodash

File: elements/lisk-p2p/src/peer_pool.ts [hunk 3]
```diff
@@ -40,15 +39,14 @@ import {
...
-	connectAndFetchPeerInfo,
 	constructPeerIdFromPeerInfo,
 	EVENT_BAN_PEER,
 	EVENT_CLOSE_INBOUND,
 	EVENT_CLOSE_OUTBOUND,
 	EVENT_CONNECT_ABORT_OUTBOUND,
 	EVENT_CONNECT_OUTBOUND,
 	EVENT_DISCOVERED_PEER,
-	EVENT_FAILED_PEER_INFO_UPDATE,
+	EVENT_FAILED_TO_COLLECT_PEER_DETAILS_ON_CONNECT,
```
Comment (ishantiw) [inline elements/lisk-p2p/src/peer_pool.ts]: Like mentioned in the above comment, it will look better if we can break it down in two events `EVENT_FAILED_TO_FETCH_STATUS` and `EVENT_FAILED_TO_FETCH_PEERS`, maybe we can use `EVENT_FAILED_TO_FETCH_PEER_INFO ` from below for `EVENT_FAILED_TO_FETCH_STATUS`

File: elements/lisk-p2p/src/peer_pool.ts [hunk 4]
```diff
@@ -213,7 +213,11 @@ export class PeerPool extends EventEmitter {
 		};
 		this._handleFailedPeerInfoUpdate = (error: Error) => {
 			// Re-emit the error to allow it to bubble up the class hierarchy.
-			this.emit(EVENT_FAILED_PEER_INFO_UPDATE, error);
+			this.emit(EVENT_FAILED_TO_FETCH_PEER_INFO, error);
+		};
+		this._handleFailedToCollectPeerDetails = (error: Error) => {
```
Comment (ishantiw) [inline elements/lisk-p2p/src/peer_pool.ts]: same as above, breaking down this handler into two for `fetchStatus` and `fetchPeers`

File: elements/lisk-p2p/src/peer_pool.ts [hunk 5]
```diff
@@ -368,25 +334,39 @@ export class PeerPool extends EventEmitter {
...
 	): void {
-		const disconnectedPeers = peers.filter(
-			peer => !this._peerMap.has(constructPeerIdFromPeerInfo(peer)),
+		// Try to connect to disconnected peers avoiding the fixed ones
+		const disconnectedPeers = knownPeers.filter(
+			peer =>
+				!this._peerMap.has(constructPeerIdFromPeerInfo(peer)) ||
+				!fixedPeers.includes(peer),
 		);
 		const { outbound } = this.getPeersCountPerKind();
```
Comment (ishantiw) [inline elements/lisk-p2p/src/peer_pool.ts]: Maybe it's out of the scope of this PR but its better if `getPeersCountPerKind()` can return `{ outboundCount, inboundCount }`, its more clear as we have other terms revolving around outbound like `outboundSocket`, `outboundShuffleInterval `, etc.

File: elements/lisk-p2p/src/peer_pool.ts [hunk 6]
```diff
@@ -368,25 +334,39 @@ export class PeerPool extends EventEmitter {
...
+		const disconnectedFixedPeers = fixedPeers
+			.filter(peer => !this._peerMap.has(constructPeerIdFromPeerInfo(peer)))
+			.map(peer2Convert => peer2Convert as P2PDiscoveredPeerInfo);
+
 		// Trigger new connections only if the maximum of outbound connections has not been reached
+		// If the node is not yet connected to any of the fixed peers, enough slots should be saved for them
+		const peerLimit =
+			this._maxOutboundConnections - disconnectedFixedPeers.length - outbound;
```
Comment (ishantiw) [inline elements/lisk-p2p/src/peer_pool.ts]: as pointed above, will look better if it will be `outboundCount`

File: elements/lisk-p2p/src/peer_selection.ts [hunk 7]
```diff
@@ -13,7 +13,7 @@
  *
  */
 // tslint:disable-next-line no-require-imports
-import shuffle = require('lodash.shuffle');
+import { shuffle } from 'lodash';
```
Comment (ishantiw) [inline elements/lisk-p2p/src/peer_selection.ts]: same as above

File: elements/lisk-p2p/src/validation.ts [hunk 8]
```diff
@@ -21,6 +21,7 @@ import {
 	InvalidRPCResponseError,
 } from './errors';
 
+import { differenceBy, differenceWith, isEqual } from 'lodash';
```
Comment (ishantiw) [inline elements/lisk-p2p/src/validation.ts]: we can require specific ones? `require('lodash.differenceBy')`. @jondubois @shuse2  I thought we wanted to remove the lodash dependency in future?

File: elements/lisk-p2p/src/validation.ts [hunk 9]
```diff
@@ -195,3 +197,86 @@ export const checkPeerCompatibility = (
 		success: true,
 	};
 };
+
+export interface PeerLists {
```
Comment (ishantiw) [inline elements/lisk-p2p/src/validation.ts]: Maybe we can add this interface in `p2p_types.ts` and reuse it in `P2PConfig` and also import it here?

File: elements/lisk-p2p/package.json [hunk 10]
```diff
@@ -43,10 +43,11 @@
 		"prebuild": "npm run prebuild:node",
 		"build": "npm run build:node",
 		"build:check": "node -e \"require('./dist-node')\"",
-		"prepublishOnly": "npm run lint && npm test && npm run build && npm run build:check"
+		"prepublishOnly": "npm run lint && npm test && npm run build && npm run build:check",
+		"enableLocalIPs": "sudo ./scripts/enableTestLocalIPs.sh 10 19"
 	},
 	"dependencies": {
-		"lodash.shuffle": "4.2.0",
+		"lodash": "4.2.0",
```
[the remark this answers is not in the document]
Comment (diego-G) [reply elements/lisk-p2p/package.json]: I am using several `lodash` features tu clean array of objects and clone objects.

File: elements/lisk-p2p/src/validation.ts (hunk 8 above)
Comment (diego-G) [reply elements/lisk-p2p/src/validation.ts]: 76ff823369a57e4fe0a934c837b8503b27dccf24

File: elements/lisk-p2p/src/p2p.ts [hunk 11]
```diff
@@ -225,7 +242,10 @@ export class P2P extends EventEmitter {
 
 		this._handleOutboundPeerConnectAbort = (peerInfo: P2PPeerInfo) => {
 			const peerId = constructPeerIdFromPeerInfo(peerInfo);
-			if (this._triedPeers.has(peerId)) {
+			const isWhiteListed = this._peerListsWithoutConflicts.whitelisted.find(
+				peer => constructPeerIdFromPeerInfo(peer) === peerId,
+			);
+			if (this._triedPeers.has(peerId) && !isWhiteListed) {
```
Comment (ishantiw) [inline elements/lisk-p2p/src/p2p.ts]: Shouldn't we also keep fixed peers in `triedPeers` list as we keep the connection with them or is it that we never save fixed peer in any of this list because of its importance and not to be advertised?

File: elements/lisk-p2p/src/p2p.ts [hunk 12]
```diff
@@ -178,7 +180,22 @@ export class P2P extends EventEmitter {
...
+				blacklistedPeers:
+					config.blacklistedPeers || ([] as ReadonlyArray<P2PPeerInfo>),
+				fixedPeers: config.fixedPeers || ([] as ReadonlyArray<P2PPeerInfo>),
+				whitelisted:
+					config.whitelistedPeers || ([] as ReadonlyArray<P2PPeerInfo>),
+				previousPeers:
+					config.previousPeers || ([] as ReadonlyArray<P2PDiscoveredPeerInfo>),
+			},
+			{
+				ipAddress: config.hostIp || DEFAULT_NODE_HOST_IP,
```
[the remark this answers is not in the document]
Comment (diego-G) [reply elements/lisk-p2p/src/p2p.ts]: `hostIp` is the key to be able to test the scenario with blacklisted IPs. Besides, w've mocked the SCServerSocket prototype + adding the script `enableLocalIPs`. https://github.com/LiskHQ/lisk-sdk/blob/77e9d628c087f4e2fe40b2ed40688549b8c7b80f/elements/lisk-p2p/test/integration/p2p.ts#L1485
Feel free to propose new ideas but that was the best we were able to do.

File: elements/lisk-p2p/src/p2p.ts (hunk 11 above)
Comment (diego-G) [reply elements/lisk-p2p/src/p2p.ts]: We treat fixed peers separately because of the second reason. We should revisit the topic anyways in #3661
