### PR TITLE
Reject outgoing connection on receiving unexpected messages 

### LINKED ISSUE #5861: Reject outbound connection if it sends unexpected messages
### Expected behaviour

Unexpected messages should not be allowed from any type of connection

### Actual behaviour

On outbound connection its possible to send control messages which is not required by the protocol.

### Which version(s) does this affect? (Environment, OS, etc...)

`5.0.0`

### PR DESCRIPTION
**Pull request by ishantiw**
### What was the problem?

This PR resolves #5861 

### How was it solved?

- Ban the peer on receiving control frames on outgoing connection
- Add tests for outgoing/incoming connections for control frames

### How was it tested?

Connect to or receive connection from a peer and send control frames to see if the peer bans the node

### CODE REVIEW

File: elements/lisk-p2p/src/peer/outbound.ts [hunk 1]
```diff
@@ -194,6 +194,15 @@ export class OutboundPeer extends Peer {
 		// Bind RPC and remote event handlers
 		outboundSocket.on(REMOTE_SC_EVENT_RPC_REQUEST, this._handleRawRPC);
 		outboundSocket.on(REMOTE_SC_EVENT_MESSAGE, this._handleRawMessage);
+		// eslint-disable-next-line @typescript-eslint/no-unsafe-member-access,@typescript-eslint/no-unsafe-assignment
+		const transportSocket = (outboundSocket as any).transport;
+		// eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
+		if (transportSocket?.socket) {
+			// eslint-disable-next-line @typescript-eslint/no-unsafe-member-access,@typescript-eslint/no-unsafe-call
+			transportSocket.socket.on(REMOTE_EVENT_PING, () => this.applyPenalty(100));
```
Comment (shuse2) [inline elements/lisk-p2p/src/peer/outbound.ts:202]: dont we need to unbound them?

**Review by shuse2 — APPROVED** [review]

**Review by mitsuaki-u — APPROVED** [review]

File: elements/lisk-p2p/src/peer/outbound.ts (hunk 1 above)
Comment (ishantiw) [reply elements/lisk-p2p/src/peer/outbound.ts:202]: `transportSocket.socket` is cleaned up by socketcluster internally so we don't need it
