### PR TITLE
Fix DeepScan found issues - Closes #4707

### LINKED ISSUE #4707: Fix DeepScan found issues
### Expected behavior

DeepScan does not report any issues

### Actual behavior

DeepScan found 66 issues 

### Steps to reproduce

https://deepscan.io/dashboard/#view=project&tid=6759&pid=8869&bid=113509&subview=issues&impact=%5B%22High%22%2C%22Medium%22%2C%22Low%22%5D&page=1

### PR DESCRIPTION
**Pull request by pablitovicente**
### What was the problem?

DeepScan found 66 issues of different severity in the code

### How did I solve it?

By refactoring the code to avoid the issues

### How to manually test it?

- DeepScan should show none of the issues displayed in https://deepscan.io/dashboard/#view=project&tid=6759&pid=8869&bid=113509&subview=issues (take into account that DeepScan for some reason is still reporting the issues but you can add the solved issues by using the checkbox `Fixed` in the `status` pane)
- Protocol-specs folder issues are ok as they're not part of a node.

### Review checklist

- [x] The PR resolves #4707
- [x] All new code is covered with unit tests
- [x] Relevant integration / functional tests are added
- [x] Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
- [x] Documentation has been added/updated

### CODE REVIEW

File: commander/test/utils/core/commons.ts [hunk 1]
```diff
@@ -135,7 +135,7 @@ describe('commons core utils', () => {
 				'http://snapshots.lisk.io.s3-eu-west-1.amazonaws.com/lisk/mainnet/blockchain.db.gz';
 			return [NETWORK.ALPHANET, NETWORK.BETANET, NETWORK.DEVNET].map(
 				network => {
-					expect(liskSnapshotUrl(url, network)).to.equal(url);
+					return expect(liskSnapshotUrl(url, network)).to.equal(url);
```
Comment (ishantiw) [inline commander/test/utils/core/commons.ts]: Does it also complain if we do this `network => expect(liskSnapshotUrl(url, network)).to.equal(url);`

File: elements/lisk-p2p/examples/find-city-game/run.ts [hunk 2]
```diff
@@ -28,8 +28,7 @@ const runP2PScenario = async () => {
 		);
 		if (
 			firstP2P.nodeInfo.city === secondP2P.nodeInfo.city &&
-			secondP2P.nodeInfo.city === thirdP2P.nodeInfo.city &&
-			thirdP2P.nodeInfo.city === firstP2P.nodeInfo.city
+			secondP2P.nodeInfo.city === thirdP2P.nodeInfo.city
```
Comment (ishantiw) [inline elements/lisk-p2p/examples/find-city-game/run.ts]: 😅

File: commander/test/utils/core/commons.ts (hunk 1 above)
Comment (pablitovicente) [reply commander/test/utils/core/commons.ts]: Pushed updated version let's see
