### PR TITLE
Fix genesis block aggregate commit

### LINKED ISSUE #9044: When genesis height is not zero, maxRemovalHeight returns 0
### Expected behavior
When genesis height is not zero, maxRemovalHeight should return genesis height.

`aggregateCommint.height` should be set to the genesis height because block at genesis height + 1  will have `aggregateCommint.height == genesis height` .

### Actual behavior
https://github.com/LiskHQ/lisk-sdk/blob/v6.0.0-rc.1-1/framework/src/engine/generator/generator.ts#L217-L219
when genesis height is non zero, and if maxRemovalHeight is `0`, the range of certificate generation will be (0, genesisHeight].
Although there BFTParam doesn't exist so the certificate will not be generated, the loop will be too big that the node won't be able to start

### Steps to reproduce
Start a testnet node which uses 6.0.0-rc.1 with validator enabled

### Which version(s) does this affect? (Environment, OS, etc...)
6.0.0-rc.1

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #9044 

### How was it solved?

- Update `getMaxRemovalHeight` to be at least genesis height
- Update genesis header aggregateCommit.height to be genesis height

### How was it tested?

- Update unit tests

### CODE REVIEW

File: elements/lisk-chain/src/block_header.ts [hunk 1]
```diff
@@ -261,13 +261,13 @@ export class BlockHeader {
 			});
 		}
 
-		if (header.aggregateCommit.height !== 0) {
+		if (header.aggregateCommit.height !== header.height) {
 			errors.push({
-				message: 'Genesis block header aggregateCommit.height must equal 0',
+				message: 'Genesis block header aggregateCommit.height must equal to the height',
```
Comment (ishantiw) [inline elements/lisk-chain/src/block_header.ts:266]: maybe
```suggestion
				message: 'Genesis block header aggregateCommit.height must equal to the genesis height',
```

**Review by ishantiw — APPROVED** [review]

**Review by janhack — APPROVED** [review]
Looks good.
