### PR TITLE
Fix inconsistent account api response - Closes #5141

### LINKED ISSUE #5141: Inconsistent response for delegate information on `/api/accounts` endpoint
### Expected behavior

There should be a consistent response for the information related to delegates for the API endpoint `/api/accounts`

### Actual behavior

For delegate accounts it returns:
```
            "delegate": {
                "approval": 0,
                "fees": "0",
                "missedBlocks": 5,
                "producedBlocks": 64,
                "productivity": 92.75,
                "rewards": "0"
            },
```
for non-delegate accounts it return:
```
            "delegate": {
                "consecutiveMissedBlocks": 0,
                "isBanned": false,
                "lastForgedHeight": 0,
                "pomHeights": []
            },
```

### Steps to reproduce

```
curl -XGET http://localhost:4000/api/accounts
```

### Which version(s) does this affect? (Environment, OS, etc...)
4.0.0

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?

This PR resolves #5141 

### How was it solved?
- Fix not to have partial formatting
- Keep approval calculation under delegate property

### How was it tested?

- Call `/api/accounts` endpoint
- Add unit test

### CODE REVIEW

File: framework/src/modules/http_api/controllers/accounts.js [hunk 1]
```diff
@@ -27,42 +27,13 @@ function AccountsController(scope) {
...
-		);
-	}
-
-	// If an account is not multi signature, then do not include keys for response
-	if (formattedAccount.keys.numberOfSignatures === 0) {
-		delete formattedAccount.keys;
-	}
+	const formattedAccount = {
+		...account,
+		delegate: {
```
Comment (pablitovicente) [inline framework/src/modules/http_api/controllers/accounts.js:32]: Why not just add the approval to the original `delegate` property as the object is no longer used so mutating it does not affect anything else?
